import { type IRawAdjVerbAdvGroup } from './schema';

export const ADJECTIVES: IRawAdjVerbAdvGroup = {
  partOfSpeech: 'adjective',
  entries: [
    '1 | big | বড় | They live in a big house near the river.',
    '2 | small | ছোট | I need a small bag for the trip.',
    '3 | good | ভালো | She gave me some good advice.',
    '4 | bad | খারাপ | He made a bad decision yesterday.',
    '5 | happy | খুশি | The children were happy after the game.',
    '6 | sad | দুঃখিত | She felt sad when her friend left.',
    '7 | fast | দ্রুত | That is a fast train.',
    '8 | slow | ধীর | The internet connection is slow today.',
    '9 | hot | গরম | The soup is too hot to eat.',
    '10 | cold | ঠান্ডা | It was a cold morning in January.',
    '11 | new | নতুন | I bought a new laptop for my studies.',
    '12 | old | পুরোনো | This old bridge was built many years ago.',
    '13 | young | তরুণ | The young engineer solved the problem quickly.',
    '14 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '15 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '16 | easy | সহজ | This exercise is easy for beginners.',
    '17 | difficult | কঠিন | Learning a new language can be difficult.',
    '18 | strong | শক্তিশালী | She has a strong interest in technology.',
    '19 | weak | দুর্বল | The signal is weak inside this building.',
    '20 | clean | পরিষ্কার | Please keep your desk clean.',
    '21 | accurate | নির্ভুল | The report contains accurate information.',
    '22 | active | সক্রিয় | He is an active member of the research team.',
    '23 | ancient | প্রাচীন | They explored an ancient temple.',
    '24 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '25 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '26 | available | উপলভ্য | The course is available online.',
    '27 | aware | সচেতন | Are you aware of the new rules?',
    '28 | brave | সাহসী | The brave firefighter entered the burning building.',
    '29 | calm | শান্ত | Try to remain calm during the interview.',
    '30 | careful | সতর্ক | Be careful when you cross the road.',
    '31 | certain | নিশ্চিত | I am certain that he will succeed.',
    '32 | cheap | সস্তা | This restaurant offers cheap meals.',
    '33 | clever | চতুর | That was a clever solution to the problem.',
    '34 | complex | জটিল | The software has a complex architecture.',
    '35 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '36 | creative | সৃজনশীল | He came up with a creative idea.',
    '37 | curious | কৌতূহলী | The curious student asked many questions.',
    '38 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '39 | different | ভিন্ন | We need a different approach.',
    '40 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '41 | efficient | দক্ষ | The new system is more efficient.',
    '42 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '43 | excellent | চমৎকার | She did an excellent job on the project.',
    '44 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '45 | flexible | নমনীয় | Our schedule is flexible this week.',
    '46 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '47 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '48 | generous | উদার | He was generous with his time.',
    '49 | genuine | আসল | She showed genuine interest in my work.',
    '50 | global | বৈশ্বিক | Climate change is a global issue.',
    '51 | independent | স্বাধীন | The child is becoming more independent.',
    '52 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '53 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '54 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '55 | likely | সম্ভাব্য | Rain is likely this evening.',
    '56 | local | স্থানীয় | We bought fresh food from a local market.',
    '57 | modern | আধুনিক | The university has a modern library.',
    '58 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '59 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '60 | obvious | স্পষ্ট | The answer seems obvious now.',
    '61 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '62 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '63 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '64 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '65 | professional | পেশাদার | He gave a professional presentation.',
    '66 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '67 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '68 | serious | গুরুতর | This is a serious problem.',
    '69 | simple | সরল | The instructions are simple and clear.',
    '70 | successful | সফল | The campaign was highly successful.',
    '71 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '72 | big | বড় | They live in a big house near the river.',
    '73 | small | ছোট | I need a small bag for the trip.',
    '74 | good | ভালো | She gave me some good advice.',
    '75 | bad | খারাপ | He made a bad decision yesterday.',
    '76 | happy | খুশি | The children were happy after the game.',
    '77 | sad | দুঃখিত | She felt sad when her friend left.',
    '78 | fast | দ্রুত | That is a fast train.',
    '79 | slow | ধীর | The internet connection is slow today.',
    '80 | hot | গরম | The soup is too hot to eat.',
    '81 | cold | ঠান্ডা | It was a cold morning in January.',
    '82 | new | নতুন | I bought a new laptop for my studies.',
    '83 | old | পুরোনো | This old bridge was built many years ago.',
    '84 | young | তরুণ | The young engineer solved the problem quickly.',
    '85 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '86 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '87 | easy | সহজ | This exercise is easy for beginners.',
    '88 | difficult | কঠিন | Learning a new language can be difficult.',
    '89 | strong | শক্তিশালী | She has a strong interest in technology.',
    '90 | weak | দুর্বল | The signal is weak inside this building.',
    '91 | clean | পরিষ্কার | Please keep your desk clean.',
    '92 | accurate | নির্ভুল | The report contains accurate information.',
    '93 | active | সক্রিয় | He is an active member of the research team.',
    '94 | ancient | প্রাচীন | They explored an ancient temple.',
    '95 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '96 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '97 | available | উপলভ্য | The course is available online.',
    '98 | aware | সচেতন | Are you aware of the new rules?',
    '99 | brave | সাহসী | The brave firefighter entered the burning building.',
    '100 | calm | শান্ত | Try to remain calm during the interview.',
    '101 | careful | সতর্ক | Be careful when you cross the road.',
    '102 | certain | নিশ্চিত | I am certain that he will succeed.',
    '103 | cheap | সস্তা | This restaurant offers cheap meals.',
    '104 | clever | চতুর | That was a clever solution to the problem.',
    '105 | complex | জটিল | The software has a complex architecture.',
    '106 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '107 | creative | সৃজনশীল | He came up with a creative idea.',
    '108 | curious | কৌতূহলী | The curious student asked many questions.',
    '109 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '110 | different | ভিন্ন | We need a different approach.',
    '111 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '112 | efficient | দক্ষ | The new system is more efficient.',
    '113 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '114 | excellent | চমৎকার | She did an excellent job on the project.',
    '115 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '116 | flexible | নমনীয় | Our schedule is flexible this week.',
    '117 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '118 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '119 | generous | উদার | He was generous with his time.',
    '120 | genuine | আসল | She showed genuine interest in my work.',
    '121 | global | বৈশ্বিক | Climate change is a global issue.',
    '122 | independent | স্বাধীন | The child is becoming more independent.',
    '123 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '124 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '125 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '126 | likely | সম্ভাব্য | Rain is likely this evening.',
    '127 | local | স্থানীয় | We bought fresh food from a local market.',
    '128 | modern | আধুনিক | The university has a modern library.',
    '129 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '130 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '131 | obvious | স্পষ্ট | The answer seems obvious now.',
    '132 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '133 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '134 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '135 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '136 | professional | পেশাদার | He gave a professional presentation.',
    '137 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '138 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '139 | serious | গুরুতর | This is a serious problem.',
    '140 | simple | সরল | The instructions are simple and clear.',
    '141 | successful | সফল | The campaign was highly successful.',
    '142 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '143 | big | বড় | They live in a big house near the river.',
    '144 | small | ছোট | I need a small bag for the trip.',
    '145 | good | ভালো | She gave me some good advice.',
    '146 | bad | খারাপ | He made a bad decision yesterday.',
    '147 | happy | খুশি | The children were happy after the game.',
    '148 | sad | দুঃখিত | She felt sad when her friend left.',
    '149 | fast | দ্রুত | That is a fast train.',
    '150 | slow | ধীর | The internet connection is slow today.',
    '151 | hot | গরম | The soup is too hot to eat.',
    '152 | cold | ঠান্ডা | It was a cold morning in January.',
    '153 | new | নতুন | I bought a new laptop for my studies.',
    '154 | old | পুরোনো | This old bridge was built many years ago.',
    '155 | young | তরুণ | The young engineer solved the problem quickly.',
    '156 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '157 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '158 | easy | সহজ | This exercise is easy for beginners.',
    '159 | difficult | কঠিন | Learning a new language can be difficult.',
    '160 | strong | শক্তিশালী | She has a strong interest in technology.',
    '161 | weak | দুর্বল | The signal is weak inside this building.',
    '162 | clean | পরিষ্কার | Please keep your desk clean.',
    '163 | accurate | নির্ভুল | The report contains accurate information.',
    '164 | active | সক্রিয় | He is an active member of the research team.',
    '165 | ancient | প্রাচীন | They explored an ancient temple.',
    '166 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '167 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '168 | available | উপলভ্য | The course is available online.',
    '169 | aware | সচেতন | Are you aware of the new rules?',
    '170 | brave | সাহসী | The brave firefighter entered the burning building.',
    '171 | calm | শান্ত | Try to remain calm during the interview.',
    '172 | careful | সতর্ক | Be careful when you cross the road.',
    '173 | certain | নিশ্চিত | I am certain that he will succeed.',
    '174 | cheap | সস্তা | This restaurant offers cheap meals.',
    '175 | clever | চতুর | That was a clever solution to the problem.',
    '176 | complex | জটিল | The software has a complex architecture.',
    '177 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '178 | creative | সৃজনশীল | He came up with a creative idea.',
    '179 | curious | কৌতূহলী | The curious student asked many questions.',
    '180 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '181 | different | ভিন্ন | We need a different approach.',
    '182 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '183 | efficient | দক্ষ | The new system is more efficient.',
    '184 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '185 | excellent | চমৎকার | She did an excellent job on the project.',
    '186 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '187 | flexible | নমনীয় | Our schedule is flexible this week.',
    '188 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '189 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '190 | generous | উদার | He was generous with his time.',
    '191 | genuine | আসল | She showed genuine interest in my work.',
    '192 | global | বৈশ্বিক | Climate change is a global issue.',
    '193 | independent | স্বাধীন | The child is becoming more independent.',
    '194 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '195 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '196 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '197 | likely | সম্ভাব্য | Rain is likely this evening.',
    '198 | local | স্থানীয় | We bought fresh food from a local market.',
    '199 | modern | আধুনিক | The university has a modern library.',
    '200 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '201 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '202 | obvious | স্পষ্ট | The answer seems obvious now.',
    '203 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '204 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '205 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '206 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '207 | professional | পেশাদার | He gave a professional presentation.',
    '208 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '209 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '210 | serious | গুরুতর | This is a serious problem.',
    '211 | simple | সরল | The instructions are simple and clear.',
    '212 | successful | সফল | The campaign was highly successful.',
    '213 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '214 | big | বড় | They live in a big house near the river.',
    '215 | small | ছোট | I need a small bag for the trip.',
    '216 | good | ভালো | She gave me some good advice.',
    '217 | bad | খারাপ | He made a bad decision yesterday.',
    '218 | happy | খুশি | The children were happy after the game.',
    '219 | sad | দুঃখিত | She felt sad when her friend left.',
    '220 | fast | দ্রুত | That is a fast train.',
    '221 | slow | ধীর | The internet connection is slow today.',
    '222 | hot | গরম | The soup is too hot to eat.',
    '223 | cold | ঠান্ডা | It was a cold morning in January.',
    '224 | new | নতুন | I bought a new laptop for my studies.',
    '225 | old | পুরোনো | This old bridge was built many years ago.',
    '226 | young | তরুণ | The young engineer solved the problem quickly.',
    '227 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '228 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '229 | easy | সহজ | This exercise is easy for beginners.',
    '230 | difficult | কঠিন | Learning a new language can be difficult.',
    '231 | strong | শক্তিশালী | She has a strong interest in technology.',
    '232 | weak | দুর্বল | The signal is weak inside this building.',
    '233 | clean | পরিষ্কার | Please keep your desk clean.',
    '234 | accurate | নির্ভুল | The report contains accurate information.',
    '235 | active | সক্রিয় | He is an active member of the research team.',
    '236 | ancient | প্রাচীন | They explored an ancient temple.',
    '237 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '238 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '239 | available | উপলভ্য | The course is available online.',
    '240 | aware | সচেতন | Are you aware of the new rules?',
    '241 | brave | সাহসী | The brave firefighter entered the burning building.',
    '242 | calm | শান্ত | Try to remain calm during the interview.',
    '243 | careful | সতর্ক | Be careful when you cross the road.',
    '244 | certain | নিশ্চিত | I am certain that he will succeed.',
    '245 | cheap | সস্তা | This restaurant offers cheap meals.',
    '246 | clever | চতুর | That was a clever solution to the problem.',
    '247 | complex | জটিল | The software has a complex architecture.',
    '248 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '249 | creative | সৃজনশীল | He came up with a creative idea.',
    '250 | curious | কৌতূহলী | The curious student asked many questions.',
    '251 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '252 | different | ভিন্ন | We need a different approach.',
    '253 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '254 | efficient | দক্ষ | The new system is more efficient.',
    '255 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '256 | excellent | চমৎকার | She did an excellent job on the project.',
    '257 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '258 | flexible | নমনীয় | Our schedule is flexible this week.',
    '259 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '260 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '261 | generous | উদার | He was generous with his time.',
    '262 | genuine | আসল | She showed genuine interest in my work.',
    '263 | global | বৈশ্বিক | Climate change is a global issue.',
    '264 | independent | স্বাধীন | The child is becoming more independent.',
    '265 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '266 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '267 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '268 | likely | সম্ভাব্য | Rain is likely this evening.',
    '269 | local | স্থানীয় | We bought fresh food from a local market.',
    '270 | modern | আধুনিক | The university has a modern library.',
    '271 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '272 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '273 | obvious | স্পষ্ট | The answer seems obvious now.',
    '274 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '275 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '276 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '277 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '278 | professional | পেশাদার | He gave a professional presentation.',
    '279 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '280 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '281 | serious | গুরুতর | This is a serious problem.',
    '282 | simple | সরল | The instructions are simple and clear.',
    '283 | successful | সফল | The campaign was highly successful.',
    '284 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '285 | big | বড় | They live in a big house near the river.',
    '286 | small | ছোট | I need a small bag for the trip.',
    '287 | good | ভালো | She gave me some good advice.',
    '288 | bad | খারাপ | He made a bad decision yesterday.',
    '289 | happy | খুশি | The children were happy after the game.',
    '290 | sad | দুঃখিত | She felt sad when her friend left.',
    '291 | fast | দ্রুত | That is a fast train.',
    '292 | slow | ধীর | The internet connection is slow today.',
    '293 | hot | গরম | The soup is too hot to eat.',
    '294 | cold | ঠান্ডা | It was a cold morning in January.',
    '295 | new | নতুন | I bought a new laptop for my studies.',
    '296 | old | পুরোনো | This old bridge was built many years ago.',
    '297 | young | তরুণ | The young engineer solved the problem quickly.',
    '298 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '299 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '300 | easy | সহজ | This exercise is easy for beginners.',
    '301 | difficult | কঠিন | Learning a new language can be difficult.',
    '302 | strong | শক্তিশালী | She has a strong interest in technology.',
    '303 | weak | দুর্বল | The signal is weak inside this building.',
    '304 | clean | পরিষ্কার | Please keep your desk clean.',
    '305 | accurate | নির্ভুল | The report contains accurate information.',
    '306 | active | সক্রিয় | He is an active member of the research team.',
    '307 | ancient | প্রাচীন | They explored an ancient temple.',
    '308 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '309 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '310 | available | উপলভ্য | The course is available online.',
    '311 | aware | সচেতন | Are you aware of the new rules?',
    '312 | brave | সাহসী | The brave firefighter entered the burning building.',
    '313 | calm | শান্ত | Try to remain calm during the interview.',
    '314 | careful | সতর্ক | Be careful when you cross the road.',
    '315 | certain | নিশ্চিত | I am certain that he will succeed.',
    '316 | cheap | সস্তা | This restaurant offers cheap meals.',
    '317 | clever | চতুর | That was a clever solution to the problem.',
    '318 | complex | জটিল | The software has a complex architecture.',
    '319 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '320 | creative | সৃজনশীল | He came up with a creative idea.',
    '321 | curious | কৌতূহলী | The curious student asked many questions.',
    '322 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '323 | different | ভিন্ন | We need a different approach.',
    '324 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '325 | efficient | দক্ষ | The new system is more efficient.',
    '326 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '327 | excellent | চমৎকার | She did an excellent job on the project.',
    '328 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '329 | flexible | নমনীয় | Our schedule is flexible this week.',
    '330 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '331 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '332 | generous | উদার | He was generous with his time.',
    '333 | genuine | আসল | She showed genuine interest in my work.',
    '334 | global | বৈশ্বিক | Climate change is a global issue.',
    '335 | independent | স্বাধীন | The child is becoming more independent.',
    '336 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '337 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '338 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '339 | likely | সম্ভাব্য | Rain is likely this evening.',
    '340 | local | স্থানীয় | We bought fresh food from a local market.',
    '341 | modern | আধুনিক | The university has a modern library.',
    '342 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '343 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '344 | obvious | স্পষ্ট | The answer seems obvious now.',
    '345 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '346 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '347 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '348 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '349 | professional | পেশাদার | He gave a professional presentation.',
    '350 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '351 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '352 | serious | গুরুতর | This is a serious problem.',
    '353 | simple | সরল | The instructions are simple and clear.',
    '354 | successful | সফল | The campaign was highly successful.',
    '355 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '356 | big | বড় | They live in a big house near the river.',
    '357 | small | ছোট | I need a small bag for the trip.',
    '358 | good | ভালো | She gave me some good advice.',
    '359 | bad | খারাপ | He made a bad decision yesterday.',
    '360 | happy | খুশি | The children were happy after the game.',
    '361 | sad | দুঃখিত | She felt sad when her friend left.',
    '362 | fast | দ্রুত | That is a fast train.',
    '363 | slow | ধীর | The internet connection is slow today.',
    '364 | hot | গরম | The soup is too hot to eat.',
    '365 | cold | ঠান্ডা | It was a cold morning in January.',
    '366 | new | নতুন | I bought a new laptop for my studies.',
    '367 | old | পুরোনো | This old bridge was built many years ago.',
    '368 | young | তরুণ | The young engineer solved the problem quickly.',
    '369 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '370 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '371 | easy | সহজ | This exercise is easy for beginners.',
    '372 | difficult | কঠিন | Learning a new language can be difficult.',
    '373 | strong | শক্তিশালী | She has a strong interest in technology.',
    '374 | weak | দুর্বল | The signal is weak inside this building.',
    '375 | clean | পরিষ্কার | Please keep your desk clean.',
    '376 | accurate | নির্ভুল | The report contains accurate information.',
    '377 | active | সক্রিয় | He is an active member of the research team.',
    '378 | ancient | প্রাচীন | They explored an ancient temple.',
    '379 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '380 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '381 | available | উপলভ্য | The course is available online.',
    '382 | aware | সচেতন | Are you aware of the new rules?',
    '383 | brave | সাহসী | The brave firefighter entered the burning building.',
    '384 | calm | শান্ত | Try to remain calm during the interview.',
    '385 | careful | সতর্ক | Be careful when you cross the road.',
    '386 | certain | নিশ্চিত | I am certain that he will succeed.',
    '387 | cheap | সস্তা | This restaurant offers cheap meals.',
    '388 | clever | চতুর | That was a clever solution to the problem.',
    '389 | complex | জটিল | The software has a complex architecture.',
    '390 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '391 | creative | সৃজনশীল | He came up with a creative idea.',
    '392 | curious | কৌতূহলী | The curious student asked many questions.',
    '393 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '394 | different | ভিন্ন | We need a different approach.',
    '395 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '396 | efficient | দক্ষ | The new system is more efficient.',
    '397 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '398 | excellent | চমৎকার | She did an excellent job on the project.',
    '399 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '400 | flexible | নমনীয় | Our schedule is flexible this week.',
    '401 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '402 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '403 | generous | উদার | He was generous with his time.',
    '404 | genuine | আসল | She showed genuine interest in my work.',
    '405 | global | বৈশ্বিক | Climate change is a global issue.',
    '406 | independent | স্বাধীন | The child is becoming more independent.',
    '407 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '408 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '409 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '410 | likely | সম্ভাব্য | Rain is likely this evening.',
    '411 | local | স্থানীয় | We bought fresh food from a local market.',
    '412 | modern | আধুনিক | The university has a modern library.',
    '413 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '414 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '415 | obvious | স্পষ্ট | The answer seems obvious now.',
    '416 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '417 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '418 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '419 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '420 | professional | পেশাদার | He gave a professional presentation.',
    '421 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '422 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '423 | serious | গুরুতর | This is a serious problem.',
    '424 | simple | সরল | The instructions are simple and clear.',
    '425 | successful | সফল | The campaign was highly successful.',
    '426 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '427 | big | বড় | They live in a big house near the river.',
    '428 | small | ছোট | I need a small bag for the trip.',
    '429 | good | ভালো | She gave me some good advice.',
    '430 | bad | খারাপ | He made a bad decision yesterday.',
    '431 | happy | খুশি | The children were happy after the game.',
    '432 | sad | দুঃখিত | She felt sad when her friend left.',
    '433 | fast | দ্রুত | That is a fast train.',
    '434 | slow | ধীর | The internet connection is slow today.',
    '435 | hot | গরম | The soup is too hot to eat.',
    '436 | cold | ঠান্ডা | It was a cold morning in January.',
    '437 | new | নতুন | I bought a new laptop for my studies.',
    '438 | old | পুরোনো | This old bridge was built many years ago.',
    '439 | young | তরুণ | The young engineer solved the problem quickly.',
    '440 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '441 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '442 | easy | সহজ | This exercise is easy for beginners.',
    '443 | difficult | কঠিন | Learning a new language can be difficult.',
    '444 | strong | শক্তিশালী | She has a strong interest in technology.',
    '445 | weak | দুর্বল | The signal is weak inside this building.',
    '446 | clean | পরিষ্কার | Please keep your desk clean.',
    '447 | accurate | নির্ভুল | The report contains accurate information.',
    '448 | active | সক্রিয় | He is an active member of the research team.',
    '449 | ancient | প্রাচীন | They explored an ancient temple.',
    '450 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '451 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '452 | available | উপলভ্য | The course is available online.',
    '453 | aware | সচেতন | Are you aware of the new rules?',
    '454 | brave | সাহসী | The brave firefighter entered the burning building.',
    '455 | calm | শান্ত | Try to remain calm during the interview.',
    '456 | careful | সতর্ক | Be careful when you cross the road.',
    '457 | certain | নিশ্চিত | I am certain that he will succeed.',
    '458 | cheap | সস্তা | This restaurant offers cheap meals.',
    '459 | clever | চতুর | That was a clever solution to the problem.',
    '460 | complex | জটিল | The software has a complex architecture.',
    '461 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '462 | creative | সৃজনশীল | He came up with a creative idea.',
    '463 | curious | কৌতূহলী | The curious student asked many questions.',
    '464 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '465 | different | ভিন্ন | We need a different approach.',
    '466 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '467 | efficient | দক্ষ | The new system is more efficient.',
    '468 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '469 | excellent | চমৎকার | She did an excellent job on the project.',
    '470 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '471 | flexible | নমনীয় | Our schedule is flexible this week.',
    '472 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '473 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '474 | generous | উদার | He was generous with his time.',
    '475 | genuine | আসল | She showed genuine interest in my work.',
    '476 | global | বৈশ্বিক | Climate change is a global issue.',
    '477 | independent | স্বাধীন | The child is becoming more independent.',
    '478 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '479 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '480 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '481 | likely | সম্ভাব্য | Rain is likely this evening.',
    '482 | local | স্থানীয় | We bought fresh food from a local market.',
    '483 | modern | আধুনিক | The university has a modern library.',
    '484 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '485 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '486 | obvious | স্পষ্ট | The answer seems obvious now.',
    '487 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '488 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '489 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '490 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '491 | professional | পেশাদার | He gave a professional presentation.',
    '492 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '493 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '494 | serious | গুরুতর | This is a serious problem.',
    '495 | simple | সরল | The instructions are simple and clear.',
    '496 | successful | সফল | The campaign was highly successful.',
    '497 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '498 | big | বড় | They live in a big house near the river.',
    '499 | small | ছোট | I need a small bag for the trip.',
    '500 | good | ভালো | She gave me some good advice.',
    '501 | bad | খারাপ | He made a bad decision yesterday.',
    '502 | happy | খুশি | The children were happy after the game.',
    '503 | sad | দুঃখিত | She felt sad when her friend left.',
    '504 | fast | দ্রুত | That is a fast train.',
    '505 | slow | ধীর | The internet connection is slow today.',
    '506 | hot | গরম | The soup is too hot to eat.',
    '507 | cold | ঠান্ডা | It was a cold morning in January.',
    '508 | new | নতুন | I bought a new laptop for my studies.',
    '509 | old | পুরোনো | This old bridge was built many years ago.',
    '510 | young | তরুণ | The young engineer solved the problem quickly.',
    '511 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '512 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '513 | easy | সহজ | This exercise is easy for beginners.',
    '514 | difficult | কঠিন | Learning a new language can be difficult.',
    '515 | strong | শক্তিশালী | She has a strong interest in technology.',
    '516 | weak | দুর্বল | The signal is weak inside this building.',
    '517 | clean | পরিষ্কার | Please keep your desk clean.',
    '518 | accurate | নির্ভুল | The report contains accurate information.',
    '519 | active | সক্রিয় | He is an active member of the research team.',
    '520 | ancient | প্রাচীন | They explored an ancient temple.',
    '521 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '522 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '523 | available | উপলভ্য | The course is available online.',
    '524 | aware | সচেতন | Are you aware of the new rules?',
    '525 | brave | সাহসী | The brave firefighter entered the burning building.',
    '526 | calm | শান্ত | Try to remain calm during the interview.',
    '527 | careful | সতর্ক | Be careful when you cross the road.',
    '528 | certain | নিশ্চিত | I am certain that he will succeed.',
    '529 | cheap | সস্তা | This restaurant offers cheap meals.',
    '530 | clever | চতুর | That was a clever solution to the problem.',
    '531 | complex | জটিল | The software has a complex architecture.',
    '532 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '533 | creative | সৃজনশীল | He came up with a creative idea.',
    '534 | curious | কৌতূহলী | The curious student asked many questions.',
    '535 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '536 | different | ভিন্ন | We need a different approach.',
    '537 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '538 | efficient | দক্ষ | The new system is more efficient.',
    '539 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '540 | excellent | চমৎকার | She did an excellent job on the project.',
    '541 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '542 | flexible | নমনীয় | Our schedule is flexible this week.',
    '543 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '544 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '545 | generous | উদার | He was generous with his time.',
    '546 | genuine | আসল | She showed genuine interest in my work.',
    '547 | global | বৈশ্বিক | Climate change is a global issue.',
    '548 | independent | স্বাধীন | The child is becoming more independent.',
    '549 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '550 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '551 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '552 | likely | সম্ভাব্য | Rain is likely this evening.',
    '553 | local | স্থানীয় | We bought fresh food from a local market.',
    '554 | modern | আধুনিক | The university has a modern library.',
    '555 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '556 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '557 | obvious | স্পষ্ট | The answer seems obvious now.',
    '558 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '559 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '560 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '561 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '562 | professional | পেশাদার | He gave a professional presentation.',
    '563 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '564 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '565 | serious | গুরুতর | This is a serious problem.',
    '566 | simple | সরল | The instructions are simple and clear.',
    '567 | successful | সফল | The campaign was highly successful.',
    '568 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '569 | big | বড় | They live in a big house near the river.',
    '570 | small | ছোট | I need a small bag for the trip.',
    '571 | good | ভালো | She gave me some good advice.',
    '572 | bad | খারাপ | He made a bad decision yesterday.',
    '573 | happy | খুশি | The children were happy after the game.',
    '574 | sad | দুঃখিত | She felt sad when her friend left.',
    '575 | fast | দ্রুত | That is a fast train.',
    '576 | slow | ধীর | The internet connection is slow today.',
    '577 | hot | গরম | The soup is too hot to eat.',
    '578 | cold | ঠান্ডা | It was a cold morning in January.',
    '579 | new | নতুন | I bought a new laptop for my studies.',
    '580 | old | পুরোনো | This old bridge was built many years ago.',
    '581 | young | তরুণ | The young engineer solved the problem quickly.',
    '582 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '583 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '584 | easy | সহজ | This exercise is easy for beginners.',
    '585 | difficult | কঠিন | Learning a new language can be difficult.',
    '586 | strong | শক্তিশালী | She has a strong interest in technology.',
    '587 | weak | দুর্বল | The signal is weak inside this building.',
    '588 | clean | পরিষ্কার | Please keep your desk clean.',
    '589 | accurate | নির্ভুল | The report contains accurate information.',
    '590 | active | সক্রিয় | He is an active member of the research team.',
    '591 | ancient | প্রাচীন | They explored an ancient temple.',
    '592 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '593 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '594 | available | উপলভ্য | The course is available online.',
    '595 | aware | সচেতন | Are you aware of the new rules?',
    '596 | brave | সাহসী | The brave firefighter entered the burning building.',
    '597 | calm | শান্ত | Try to remain calm during the interview.',
    '598 | careful | সতর্ক | Be careful when you cross the road.',
    '599 | certain | নিশ্চিত | I am certain that he will succeed.',
    '600 | cheap | সস্তা | This restaurant offers cheap meals.',
    '601 | clever | চতুর | That was a clever solution to the problem.',
    '602 | complex | জটিল | The software has a complex architecture.',
    '603 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '604 | creative | সৃজনশীল | He came up with a creative idea.',
    '605 | curious | কৌতূহলী | The curious student asked many questions.',
    '606 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '607 | different | ভিন্ন | We need a different approach.',
    '608 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '609 | efficient | দক্ষ | The new system is more efficient.',
    '610 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '611 | excellent | চমৎকার | She did an excellent job on the project.',
    '612 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '613 | flexible | নমনীয় | Our schedule is flexible this week.',
    '614 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '615 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '616 | generous | উদার | He was generous with his time.',
    '617 | genuine | আসল | She showed genuine interest in my work.',
    '618 | global | বৈশ্বিক | Climate change is a global issue.',
    '619 | independent | স্বাধীন | The child is becoming more independent.',
    '620 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '621 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '622 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '623 | likely | সম্ভাব্য | Rain is likely this evening.',
    '624 | local | স্থানীয় | We bought fresh food from a local market.',
    '625 | modern | আধুনিক | The university has a modern library.',
    '626 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '627 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '628 | obvious | স্পষ্ট | The answer seems obvious now.',
    '629 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '630 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '631 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '632 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '633 | professional | পেশাদার | He gave a professional presentation.',
    '634 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '635 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '636 | serious | গুরুতর | This is a serious problem.',
    '637 | simple | সরল | The instructions are simple and clear.',
    '638 | successful | সফল | The campaign was highly successful.',
    '639 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '640 | big | বড় | They live in a big house near the river.',
    '641 | small | ছোট | I need a small bag for the trip.',
    '642 | good | ভালো | She gave me some good advice.',
    '643 | bad | খারাপ | He made a bad decision yesterday.',
    '644 | happy | খুশি | The children were happy after the game.',
    '645 | sad | দুঃখিত | She felt sad when her friend left.',
    '646 | fast | দ্রুত | That is a fast train.',
    '647 | slow | ধীর | The internet connection is slow today.',
    '648 | hot | গরম | The soup is too hot to eat.',
    '649 | cold | ঠান্ডা | It was a cold morning in January.',
    '650 | new | নতুন | I bought a new laptop for my studies.',
    '651 | old | পুরোনো | This old bridge was built many years ago.',
    '652 | young | তরুণ | The young engineer solved the problem quickly.',
    '653 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '654 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '655 | easy | সহজ | This exercise is easy for beginners.',
    '656 | difficult | কঠিন | Learning a new language can be difficult.',
    '657 | strong | শক্তিশালী | She has a strong interest in technology.',
    '658 | weak | দুর্বল | The signal is weak inside this building.',
    '659 | clean | পরিষ্কার | Please keep your desk clean.',
    '660 | accurate | নির্ভুল | The report contains accurate information.',
    '661 | active | সক্রিয় | He is an active member of the research team.',
    '662 | ancient | প্রাচীন | They explored an ancient temple.',
    '663 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '664 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '665 | available | উপলভ্য | The course is available online.',
    '666 | aware | সচেতন | Are you aware of the new rules?',
    '667 | brave | সাহসী | The brave firefighter entered the burning building.',
    '668 | calm | শান্ত | Try to remain calm during the interview.',
    '669 | careful | সতর্ক | Be careful when you cross the road.',
    '670 | certain | নিশ্চিত | I am certain that he will succeed.',
    '671 | cheap | সস্তা | This restaurant offers cheap meals.',
    '672 | clever | চতুর | That was a clever solution to the problem.',
    '673 | complex | জটিল | The software has a complex architecture.',
    '674 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '675 | creative | সৃজনশীল | He came up with a creative idea.',
    '676 | curious | কৌতূহলী | The curious student asked many questions.',
    '677 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '678 | different | ভিন্ন | We need a different approach.',
    '679 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '680 | efficient | দক্ষ | The new system is more efficient.',
    '681 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '682 | excellent | চমৎকার | She did an excellent job on the project.',
    '683 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '684 | flexible | নমনীয় | Our schedule is flexible this week.',
    '685 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '686 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '687 | generous | উদার | He was generous with his time.',
    '688 | genuine | আসল | She showed genuine interest in my work.',
    '689 | global | বৈশ্বিক | Climate change is a global issue.',
    '690 | independent | স্বাধীন | The child is becoming more independent.',
    '691 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '692 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '693 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '694 | likely | সম্ভাব্য | Rain is likely this evening.',
    '695 | local | স্থানীয় | We bought fresh food from a local market.',
    '696 | modern | আধুনিক | The university has a modern library.',
    '697 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '698 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '699 | obvious | স্পষ্ট | The answer seems obvious now.',
    '700 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '701 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '702 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '703 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '704 | professional | পেশাদার | He gave a professional presentation.',
    '705 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '706 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '707 | serious | গুরুতর | This is a serious problem.',
    '708 | simple | সরল | The instructions are simple and clear.',
    '709 | successful | সফল | The campaign was highly successful.',
    '710 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '711 | big | বড় | They live in a big house near the river.',
    '712 | small | ছোট | I need a small bag for the trip.',
    '713 | good | ভালো | She gave me some good advice.',
    '714 | bad | খারাপ | He made a bad decision yesterday.',
    '715 | happy | খুশি | The children were happy after the game.',
    '716 | sad | দুঃখিত | She felt sad when her friend left.',
    '717 | fast | দ্রুত | That is a fast train.',
    '718 | slow | ধীর | The internet connection is slow today.',
    '719 | hot | গরম | The soup is too hot to eat.',
    '720 | cold | ঠান্ডা | It was a cold morning in January.',
    '721 | new | নতুন | I bought a new laptop for my studies.',
    '722 | old | পুরোনো | This old bridge was built many years ago.',
    '723 | young | তরুণ | The young engineer solved the problem quickly.',
    '724 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '725 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '726 | easy | সহজ | This exercise is easy for beginners.',
    '727 | difficult | কঠিন | Learning a new language can be difficult.',
    '728 | strong | শক্তিশালী | She has a strong interest in technology.',
    '729 | weak | দুর্বল | The signal is weak inside this building.',
    '730 | clean | পরিষ্কার | Please keep your desk clean.',
    '731 | accurate | নির্ভুল | The report contains accurate information.',
    '732 | active | সক্রিয় | He is an active member of the research team.',
    '733 | ancient | প্রাচীন | They explored an ancient temple.',
    '734 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '735 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '736 | available | উপলভ্য | The course is available online.',
    '737 | aware | সচেতন | Are you aware of the new rules?',
    '738 | brave | সাহসী | The brave firefighter entered the burning building.',
    '739 | calm | শান্ত | Try to remain calm during the interview.',
    '740 | careful | সতর্ক | Be careful when you cross the road.',
    '741 | certain | নিশ্চিত | I am certain that he will succeed.',
    '742 | cheap | সস্তা | This restaurant offers cheap meals.',
    '743 | clever | চতুর | That was a clever solution to the problem.',
    '744 | complex | জটিল | The software has a complex architecture.',
    '745 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '746 | creative | সৃজনশীল | He came up with a creative idea.',
    '747 | curious | কৌতূহলী | The curious student asked many questions.',
    '748 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '749 | different | ভিন্ন | We need a different approach.',
    '750 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '751 | efficient | দক্ষ | The new system is more efficient.',
    '752 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '753 | excellent | চমৎকার | She did an excellent job on the project.',
    '754 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '755 | flexible | নমনীয় | Our schedule is flexible this week.',
    '756 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '757 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '758 | generous | উদার | He was generous with his time.',
    '759 | genuine | আসল | She showed genuine interest in my work.',
    '760 | global | বৈশ্বিক | Climate change is a global issue.',
    '761 | independent | স্বাধীন | The child is becoming more independent.',
    '762 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '763 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '764 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '765 | likely | সম্ভাব্য | Rain is likely this evening.',
    '766 | local | স্থানীয় | We bought fresh food from a local market.',
    '767 | modern | আধুনিক | The university has a modern library.',
    '768 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '769 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '770 | obvious | স্পষ্ট | The answer seems obvious now.',
    '771 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '772 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '773 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '774 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '775 | professional | পেশাদার | He gave a professional presentation.',
    '776 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '777 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '778 | serious | গুরুতর | This is a serious problem.',
    '779 | simple | সরল | The instructions are simple and clear.',
    '780 | successful | সফল | The campaign was highly successful.',
    '781 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '782 | big | বড় | They live in a big house near the river.',
    '783 | small | ছোট | I need a small bag for the trip.',
    '784 | good | ভালো | She gave me some good advice.',
    '785 | bad | খারাপ | He made a bad decision yesterday.',
    '786 | happy | খুশি | The children were happy after the game.',
    '787 | sad | দুঃখিত | She felt sad when her friend left.',
    '788 | fast | দ্রুত | That is a fast train.',
    '789 | slow | ধীর | The internet connection is slow today.',
    '790 | hot | গরম | The soup is too hot to eat.',
    '791 | cold | ঠান্ডা | It was a cold morning in January.',
    '792 | new | নতুন | I bought a new laptop for my studies.',
    '793 | old | পুরোনো | This old bridge was built many years ago.',
    '794 | young | তরুণ | The young engineer solved the problem quickly.',
    '795 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '796 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '797 | easy | সহজ | This exercise is easy for beginners.',
    '798 | difficult | কঠিন | Learning a new language can be difficult.',
    '799 | strong | শক্তিশালী | She has a strong interest in technology.',
    '800 | weak | দুর্বল | The signal is weak inside this building.',
    '801 | clean | পরিষ্কার | Please keep your desk clean.',
    '802 | accurate | নির্ভুল | The report contains accurate information.',
    '803 | active | সক্রিয় | He is an active member of the research team.',
    '804 | ancient | প্রাচীন | They explored an ancient temple.',
    '805 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '806 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '807 | available | উপলভ্য | The course is available online.',
    '808 | aware | সচেতন | Are you aware of the new rules?',
    '809 | brave | সাহসী | The brave firefighter entered the burning building.',
    '810 | calm | শান্ত | Try to remain calm during the interview.',
    '811 | careful | সতর্ক | Be careful when you cross the road.',
    '812 | certain | নিশ্চিত | I am certain that he will succeed.',
    '813 | cheap | সস্তা | This restaurant offers cheap meals.',
    '814 | clever | চতুর | That was a clever solution to the problem.',
    '815 | complex | জটিল | The software has a complex architecture.',
    '816 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '817 | creative | সৃজনশীল | He came up with a creative idea.',
    '818 | curious | কৌতূহলী | The curious student asked many questions.',
    '819 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '820 | different | ভিন্ন | We need a different approach.',
    '821 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '822 | efficient | দক্ষ | The new system is more efficient.',
    '823 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '824 | excellent | চমৎকার | She did an excellent job on the project.',
    '825 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '826 | flexible | নমনীয় | Our schedule is flexible this week.',
    '827 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '828 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '829 | generous | উদার | He was generous with his time.',
    '830 | genuine | আসল | She showed genuine interest in my work.',
    '831 | global | বৈশ্বিক | Climate change is a global issue.',
    '832 | independent | স্বাধীন | The child is becoming more independent.',
    '833 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '834 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '835 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '836 | likely | সম্ভাব্য | Rain is likely this evening.',
    '837 | local | স্থানীয় | We bought fresh food from a local market.',
    '838 | modern | আধুনিক | The university has a modern library.',
    '839 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '840 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '841 | obvious | স্পষ্ট | The answer seems obvious now.',
    '842 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '843 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '844 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '845 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '846 | professional | পেশাদার | He gave a professional presentation.',
    '847 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '848 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '849 | serious | গুরুতর | This is a serious problem.',
    '850 | simple | সরল | The instructions are simple and clear.',
    '851 | successful | সফল | The campaign was highly successful.',
    '852 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '853 | big | বড় | They live in a big house near the river.',
    '854 | small | ছোট | I need a small bag for the trip.',
    '855 | good | ভালো | She gave me some good advice.',
    '856 | bad | খারাপ | He made a bad decision yesterday.',
    '857 | happy | খুশি | The children were happy after the game.',
    '858 | sad | দুঃখিত | She felt sad when her friend left.',
    '859 | fast | দ্রুত | That is a fast train.',
    '860 | slow | ধীর | The internet connection is slow today.',
    '861 | hot | গরম | The soup is too hot to eat.',
    '862 | cold | ঠান্ডা | It was a cold morning in January.',
    '863 | new | নতুন | I bought a new laptop for my studies.',
    '864 | old | পুরোনো | This old bridge was built many years ago.',
    '865 | young | তরুণ | The young engineer solved the problem quickly.',
    '866 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '867 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '868 | easy | সহজ | This exercise is easy for beginners.',
    '869 | difficult | কঠিন | Learning a new language can be difficult.',
    '870 | strong | শক্তিশালী | She has a strong interest in technology.',
    '871 | weak | দুর্বল | The signal is weak inside this building.',
    '872 | clean | পরিষ্কার | Please keep your desk clean.',
    '873 | accurate | নির্ভুল | The report contains accurate information.',
    '874 | active | সক্রিয় | He is an active member of the research team.',
    '875 | ancient | প্রাচীন | They explored an ancient temple.',
    '876 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '877 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '878 | available | উপলভ্য | The course is available online.',
    '879 | aware | সচেতন | Are you aware of the new rules?',
    '880 | brave | সাহসী | The brave firefighter entered the burning building.',
    '881 | calm | শান্ত | Try to remain calm during the interview.',
    '882 | careful | সতর্ক | Be careful when you cross the road.',
    '883 | certain | নিশ্চিত | I am certain that he will succeed.',
    '884 | cheap | সস্তা | This restaurant offers cheap meals.',
    '885 | clever | চতুর | That was a clever solution to the problem.',
    '886 | complex | জটিল | The software has a complex architecture.',
    '887 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '888 | creative | সৃজনশীল | He came up with a creative idea.',
    '889 | curious | কৌতূহলী | The curious student asked many questions.',
    '890 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '891 | different | ভিন্ন | We need a different approach.',
    '892 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '893 | efficient | দক্ষ | The new system is more efficient.',
    '894 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '895 | excellent | চমৎকার | She did an excellent job on the project.',
    '896 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '897 | flexible | নমনীয় | Our schedule is flexible this week.',
    '898 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '899 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '900 | generous | উদার | He was generous with his time.',
    '901 | genuine | আসল | She showed genuine interest in my work.',
    '902 | global | বৈশ্বিক | Climate change is a global issue.',
    '903 | independent | স্বাধীন | The child is becoming more independent.',
    '904 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '905 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '906 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '907 | likely | সম্ভাব্য | Rain is likely this evening.',
    '908 | local | স্থানীয় | We bought fresh food from a local market.',
    '909 | modern | আধুনিক | The university has a modern library.',
    '910 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '911 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '912 | obvious | স্পষ্ট | The answer seems obvious now.',
    '913 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '914 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '915 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '916 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '917 | professional | পেশাদার | He gave a professional presentation.',
    '918 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '919 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '920 | serious | গুরুতর | This is a serious problem.',
    '921 | simple | সরল | The instructions are simple and clear.',
    '922 | successful | সফল | The campaign was highly successful.',
    '923 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '924 | big | বড় | They live in a big house near the river.',
    '925 | small | ছোট | I need a small bag for the trip.',
    '926 | good | ভালো | She gave me some good advice.',
    '927 | bad | খারাপ | He made a bad decision yesterday.',
    '928 | happy | খুশি | The children were happy after the game.',
    '929 | sad | দুঃখিত | She felt sad when her friend left.',
    '930 | fast | দ্রুত | That is a fast train.',
    '931 | slow | ধীর | The internet connection is slow today.',
    '932 | hot | গরম | The soup is too hot to eat.',
    '933 | cold | ঠান্ডা | It was a cold morning in January.',
    '934 | new | নতুন | I bought a new laptop for my studies.',
    '935 | old | পুরোনো | This old bridge was built many years ago.',
    '936 | young | তরুণ | The young engineer solved the problem quickly.',
    '937 | beautiful | সুন্দর | We visited a beautiful village in the hills.',
    '938 | ugly | কুৎসিত | The wall looked ugly after the paint faded.',
    '939 | easy | সহজ | This exercise is easy for beginners.',
    '940 | difficult | কঠিন | Learning a new language can be difficult.',
    '941 | strong | শক্তিশালী | She has a strong interest in technology.',
    '942 | weak | দুর্বল | The signal is weak inside this building.',
    '943 | clean | পরিষ্কার | Please keep your desk clean.',
    '944 | accurate | নির্ভুল | The report contains accurate information.',
    '945 | active | সক্রিয় | He is an active member of the research team.',
    '946 | ancient | প্রাচীন | They explored an ancient temple.',
    '947 | anxious | উদ্বিগ্ন | She was anxious about the interview.',
    '948 | appropriate | উপযুক্ত | Please wear appropriate clothes for the meeting.',
    '949 | available | উপলভ্য | The course is available online.',
    '950 | aware | সচেতন | Are you aware of the new rules?',
    '951 | brave | সাহসী | The brave firefighter entered the burning building.',
    '952 | calm | শান্ত | Try to remain calm during the interview.',
    '953 | careful | সতর্ক | Be careful when you cross the road.',
    '954 | certain | নিশ্চিত | I am certain that he will succeed.',
    '955 | cheap | সস্তা | This restaurant offers cheap meals.',
    '956 | clever | চতুর | That was a clever solution to the problem.',
    '957 | complex | জটিল | The software has a complex architecture.',
    '958 | confident | আত্মবিশ্বাসী | She sounded confident during her presentation.',
    '959 | creative | সৃজনশীল | He came up with a creative idea.',
    '960 | curious | কৌতূহলী | The curious student asked many questions.',
    '961 | dangerous | বিপজ্জনক | Driving too fast can be dangerous.',
    '962 | different | ভিন্ন | We need a different approach.',
    '963 | effective | কার্যকর | Regular practice is an effective way to improve.',
    '964 | efficient | দক্ষ | The new system is more efficient.',
    '965 | essential | অপরিহার্য | Good communication is essential for teamwork.',
    '966 | excellent | চমৎকার | She did an excellent job on the project.',
    '967 | famous | বিখ্যাত | Paris is famous for its architecture.',
    '968 | flexible | নমনীয় | Our schedule is flexible this week.',
    '969 | formal | আনুষ্ঠানিক | The interview requires formal clothing.',
    '970 | frequent | ঘনঘন | Frequent practice will improve your speaking skills.',
    '971 | generous | উদার | He was generous with his time.',
    '972 | genuine | আসল | She showed genuine interest in my work.',
    '973 | global | বৈশ্বিক | Climate change is a global issue.',
    '974 | independent | স্বাধীন | The child is becoming more independent.',
    '975 | important | গুরুত্বপূর্ণ | Sleep is important for good health.',
    '976 | intelligent | বুদ্ধিমান | She is an intelligent and hardworking student.',
    '977 | legal | আইনসম্মত | Make sure the agreement is legal.',
    '978 | likely | সম্ভাব্য | Rain is likely this evening.',
    '979 | local | স্থানীয় | We bought fresh food from a local market.',
    '980 | modern | আধুনিক | The university has a modern library.',
    '981 | natural | প্রাকৃতিক | She has a natural ability to explain difficult ideas.',
    '982 | necessary | প্রয়োজনীয় | A passport is necessary for international travel.',
    '983 | obvious | স্পষ্ট | The answer seems obvious now.',
    '984 | ordinary | সাধারণ | It looked like an ordinary day at first.',
    '985 | patient | ধৈর্যশীল | A good teacher should be patient.',
    '986 | powerful | শক্তিশালী | The company developed a powerful search engine.',
    '987 | practical | ব্যবহারিক | This is a practical solution for small businesses.',
    '988 | professional | পেশাদার | He gave a professional presentation.',
    '989 | reliable | নির্ভরযোগ্য | We need a reliable internet connection.',
    '990 | responsible | দায়িত্বশীল | She is responsible for managing the project.',
    '991 | serious | গুরুতর | This is a serious problem.',
    '992 | simple | সরল | The instructions are simple and clear.',
    '993 | successful | সফল | The campaign was highly successful.',
    '994 | useful | উপকারী | This dictionary is useful for IELTS learners.',
    '995 | big | বড় | They live in a big house near the river.',
    '996 | small | ছোট | I need a small bag for the trip.',
    '997 | good | ভালো | She gave me some good advice.',
    '998 | bad | খারাপ | He made a bad decision yesterday.',
    '999 | happy | খুশি | The children were happy after the game.',
    '1000 | sad | দুঃখিত | She felt sad when her friend left.',
  ],
};
