import { type IRawAdjVerbAdvGroup } from './schema';

export const ADVERBS: IRawAdjVerbAdvGroup = {
  partOfSpeech: 'adverb',
  entries: [
    '1 | very | খুব | The lesson was very useful.',
    '2 | really | সত্যিই | I really enjoyed the class.',
    '3 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '4 | slowly | ধীরে | The old man walked slowly across the road.',
    '5 | carefully | সাবধানে | Please read the question carefully.',
    '6 | easily | সহজে | He solved the problem easily.',
    '7 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '8 | well | ভালোভাবে | She speaks English very well.',
    '9 | badly | খারাপভাবে | The machine was badly damaged.',
    '10 | always | সবসময় | I always review new vocabulary.',
    '11 | usually | সাধারণত | We usually have dinner at home.',
    '12 | often | প্রায়ই | He often practices English with friends.',
    '13 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '14 | rarely | কদাচিৎ | She rarely misses a class.',
    '15 | never | কখনোই না | He never gives up easily.',
    '16 | today | আজ | I have an English class today.',
    '17 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '18 | yesterday | গতকাল | She arrived yesterday.',
    '19 | here | এখানে | Please wait here for me.',
    '20 | there | সেখানে | Put your bag there.',
    '21 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '22 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '23 | almost | প্রায় | The project is almost complete.',
    '24 | already | ইতিমধ্যে | She has already finished the assignment.',
    '25 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '26 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '27 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '28 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '29 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '30 | constantly | ক্রমাগত | Technology is constantly changing.',
    '31 | currently | বর্তমানে | She is currently working on a new project.',
    '32 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '33 | directly | সরাসরি | Please contact the manager directly.',
    '34 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '35 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '36 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '37 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '38 | generally | সাধারণত | People generally prefer simple explanations.',
    '39 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '40 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '41 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '42 | mainly | মূলত | The course is mainly focused on speaking.',
    '43 | nearly | প্রায় | The project is nearly finished.',
    '44 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '45 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '46 | probably | সম্ভবত | She will probably arrive soon.',
    '47 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '48 | recently | সম্প্রতি | I recently started learning German.',
    '49 | simply | সহজভাবে | He simply explained the complicated topic.',
    '50 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '51 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '52 | truly | সত্যিই | She truly enjoys helping others.',
    '53 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '54 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '55 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '56 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '57 | however | তবে | The task was difficult; however, she completed it.',
    '58 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '59 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '60 | instead | পরিবর্তে | He stayed home instead of going out.',
    '61 | forward | সামনে | Please move forward carefully.',
    '62 | backward | পেছনে | The car slowly moved backward.',
    '63 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '64 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '65 | abroad | বিদেশে | He plans to study abroad next year.',
    '66 | together | একসাথে | We worked together on the assignment.',
    '67 | apart | আলাদাভাবে | The two offices are located far apart.',
    '68 | away | দূরে | Please stay away from the wet floor.',
    '69 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '70 | quite | বেশ | The exam was quite difficult.',
    '71 | rather | বরং/বেশ | The second option is rather expensive.',
    '72 | very | খুব | The lesson was very useful.',
    '73 | really | সত্যিই | I really enjoyed the class.',
    '74 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '75 | slowly | ধীরে | The old man walked slowly across the road.',
    '76 | carefully | সাবধানে | Please read the question carefully.',
    '77 | easily | সহজে | He solved the problem easily.',
    '78 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '79 | well | ভালোভাবে | She speaks English very well.',
    '80 | badly | খারাপভাবে | The machine was badly damaged.',
    '81 | always | সবসময় | I always review new vocabulary.',
    '82 | usually | সাধারণত | We usually have dinner at home.',
    '83 | often | প্রায়ই | He often practices English with friends.',
    '84 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '85 | rarely | কদাচিৎ | She rarely misses a class.',
    '86 | never | কখনোই না | He never gives up easily.',
    '87 | today | আজ | I have an English class today.',
    '88 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '89 | yesterday | গতকাল | She arrived yesterday.',
    '90 | here | এখানে | Please wait here for me.',
    '91 | there | সেখানে | Put your bag there.',
    '92 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '93 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '94 | almost | প্রায় | The project is almost complete.',
    '95 | already | ইতিমধ্যে | She has already finished the assignment.',
    '96 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '97 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '98 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '99 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '100 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '101 | constantly | ক্রমাগত | Technology is constantly changing.',
    '102 | currently | বর্তমানে | She is currently working on a new project.',
    '103 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '104 | directly | সরাসরি | Please contact the manager directly.',
    '105 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '106 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '107 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '108 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '109 | generally | সাধারণত | People generally prefer simple explanations.',
    '110 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '111 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '112 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '113 | mainly | মূলত | The course is mainly focused on speaking.',
    '114 | nearly | প্রায় | The project is nearly finished.',
    '115 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '116 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '117 | probably | সম্ভবত | She will probably arrive soon.',
    '118 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '119 | recently | সম্প্রতি | I recently started learning German.',
    '120 | simply | সহজভাবে | He simply explained the complicated topic.',
    '121 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '122 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '123 | truly | সত্যিই | She truly enjoys helping others.',
    '124 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '125 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '126 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '127 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '128 | however | তবে | The task was difficult; however, she completed it.',
    '129 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '130 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '131 | instead | পরিবর্তে | He stayed home instead of going out.',
    '132 | forward | সামনে | Please move forward carefully.',
    '133 | backward | পেছনে | The car slowly moved backward.',
    '134 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '135 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '136 | abroad | বিদেশে | He plans to study abroad next year.',
    '137 | together | একসাথে | We worked together on the assignment.',
    '138 | apart | আলাদাভাবে | The two offices are located far apart.',
    '139 | away | দূরে | Please stay away from the wet floor.',
    '140 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '141 | quite | বেশ | The exam was quite difficult.',
    '142 | rather | বরং/বেশ | The second option is rather expensive.',
    '143 | very | খুব | The lesson was very useful.',
    '144 | really | সত্যিই | I really enjoyed the class.',
    '145 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '146 | slowly | ধীরে | The old man walked slowly across the road.',
    '147 | carefully | সাবধানে | Please read the question carefully.',
    '148 | easily | সহজে | He solved the problem easily.',
    '149 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '150 | well | ভালোভাবে | She speaks English very well.',
    '151 | badly | খারাপভাবে | The machine was badly damaged.',
    '152 | always | সবসময় | I always review new vocabulary.',
    '153 | usually | সাধারণত | We usually have dinner at home.',
    '154 | often | প্রায়ই | He often practices English with friends.',
    '155 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '156 | rarely | কদাচিৎ | She rarely misses a class.',
    '157 | never | কখনোই না | He never gives up easily.',
    '158 | today | আজ | I have an English class today.',
    '159 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '160 | yesterday | গতকাল | She arrived yesterday.',
    '161 | here | এখানে | Please wait here for me.',
    '162 | there | সেখানে | Put your bag there.',
    '163 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '164 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '165 | almost | প্রায় | The project is almost complete.',
    '166 | already | ইতিমধ্যে | She has already finished the assignment.',
    '167 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '168 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '169 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '170 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '171 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '172 | constantly | ক্রমাগত | Technology is constantly changing.',
    '173 | currently | বর্তমানে | She is currently working on a new project.',
    '174 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '175 | directly | সরাসরি | Please contact the manager directly.',
    '176 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '177 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '178 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '179 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '180 | generally | সাধারণত | People generally prefer simple explanations.',
    '181 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '182 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '183 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '184 | mainly | মূলত | The course is mainly focused on speaking.',
    '185 | nearly | প্রায় | The project is nearly finished.',
    '186 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '187 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '188 | probably | সম্ভবত | She will probably arrive soon.',
    '189 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '190 | recently | সম্প্রতি | I recently started learning German.',
    '191 | simply | সহজভাবে | He simply explained the complicated topic.',
    '192 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '193 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '194 | truly | সত্যিই | She truly enjoys helping others.',
    '195 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '196 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '197 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '198 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '199 | however | তবে | The task was difficult; however, she completed it.',
    '200 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '201 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '202 | instead | পরিবর্তে | He stayed home instead of going out.',
    '203 | forward | সামনে | Please move forward carefully.',
    '204 | backward | পেছনে | The car slowly moved backward.',
    '205 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '206 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '207 | abroad | বিদেশে | He plans to study abroad next year.',
    '208 | together | একসাথে | We worked together on the assignment.',
    '209 | apart | আলাদাভাবে | The two offices are located far apart.',
    '210 | away | দূরে | Please stay away from the wet floor.',
    '211 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '212 | quite | বেশ | The exam was quite difficult.',
    '213 | rather | বরং/বেশ | The second option is rather expensive.',
    '214 | very | খুব | The lesson was very useful.',
    '215 | really | সত্যিই | I really enjoyed the class.',
    '216 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '217 | slowly | ধীরে | The old man walked slowly across the road.',
    '218 | carefully | সাবধানে | Please read the question carefully.',
    '219 | easily | সহজে | He solved the problem easily.',
    '220 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '221 | well | ভালোভাবে | She speaks English very well.',
    '222 | badly | খারাপভাবে | The machine was badly damaged.',
    '223 | always | সবসময় | I always review new vocabulary.',
    '224 | usually | সাধারণত | We usually have dinner at home.',
    '225 | often | প্রায়ই | He often practices English with friends.',
    '226 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '227 | rarely | কদাচিৎ | She rarely misses a class.',
    '228 | never | কখনোই না | He never gives up easily.',
    '229 | today | আজ | I have an English class today.',
    '230 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '231 | yesterday | গতকাল | She arrived yesterday.',
    '232 | here | এখানে | Please wait here for me.',
    '233 | there | সেখানে | Put your bag there.',
    '234 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '235 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '236 | almost | প্রায় | The project is almost complete.',
    '237 | already | ইতিমধ্যে | She has already finished the assignment.',
    '238 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '239 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '240 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '241 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '242 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '243 | constantly | ক্রমাগত | Technology is constantly changing.',
    '244 | currently | বর্তমানে | She is currently working on a new project.',
    '245 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '246 | directly | সরাসরি | Please contact the manager directly.',
    '247 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '248 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '249 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '250 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '251 | generally | সাধারণত | People generally prefer simple explanations.',
    '252 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '253 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '254 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '255 | mainly | মূলত | The course is mainly focused on speaking.',
    '256 | nearly | প্রায় | The project is nearly finished.',
    '257 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '258 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '259 | probably | সম্ভবত | She will probably arrive soon.',
    '260 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '261 | recently | সম্প্রতি | I recently started learning German.',
    '262 | simply | সহজভাবে | He simply explained the complicated topic.',
    '263 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '264 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '265 | truly | সত্যিই | She truly enjoys helping others.',
    '266 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '267 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '268 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '269 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '270 | however | তবে | The task was difficult; however, she completed it.',
    '271 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '272 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '273 | instead | পরিবর্তে | He stayed home instead of going out.',
    '274 | forward | সামনে | Please move forward carefully.',
    '275 | backward | পেছনে | The car slowly moved backward.',
    '276 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '277 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '278 | abroad | বিদেশে | He plans to study abroad next year.',
    '279 | together | একসাথে | We worked together on the assignment.',
    '280 | apart | আলাদাভাবে | The two offices are located far apart.',
    '281 | away | দূরে | Please stay away from the wet floor.',
    '282 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '283 | quite | বেশ | The exam was quite difficult.',
    '284 | rather | বরং/বেশ | The second option is rather expensive.',
    '285 | very | খুব | The lesson was very useful.',
    '286 | really | সত্যিই | I really enjoyed the class.',
    '287 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '288 | slowly | ধীরে | The old man walked slowly across the road.',
    '289 | carefully | সাবধানে | Please read the question carefully.',
    '290 | easily | সহজে | He solved the problem easily.',
    '291 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '292 | well | ভালোভাবে | She speaks English very well.',
    '293 | badly | খারাপভাবে | The machine was badly damaged.',
    '294 | always | সবসময় | I always review new vocabulary.',
    '295 | usually | সাধারণত | We usually have dinner at home.',
    '296 | often | প্রায়ই | He often practices English with friends.',
    '297 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '298 | rarely | কদাচিৎ | She rarely misses a class.',
    '299 | never | কখনোই না | He never gives up easily.',
    '300 | today | আজ | I have an English class today.',
    '301 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '302 | yesterday | গতকাল | She arrived yesterday.',
    '303 | here | এখানে | Please wait here for me.',
    '304 | there | সেখানে | Put your bag there.',
    '305 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '306 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '307 | almost | প্রায় | The project is almost complete.',
    '308 | already | ইতিমধ্যে | She has already finished the assignment.',
    '309 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '310 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '311 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '312 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '313 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '314 | constantly | ক্রমাগত | Technology is constantly changing.',
    '315 | currently | বর্তমানে | She is currently working on a new project.',
    '316 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '317 | directly | সরাসরি | Please contact the manager directly.',
    '318 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '319 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '320 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '321 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '322 | generally | সাধারণত | People generally prefer simple explanations.',
    '323 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '324 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '325 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '326 | mainly | মূলত | The course is mainly focused on speaking.',
    '327 | nearly | প্রায় | The project is nearly finished.',
    '328 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '329 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '330 | probably | সম্ভবত | She will probably arrive soon.',
    '331 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '332 | recently | সম্প্রতি | I recently started learning German.',
    '333 | simply | সহজভাবে | He simply explained the complicated topic.',
    '334 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '335 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '336 | truly | সত্যিই | She truly enjoys helping others.',
    '337 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '338 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '339 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '340 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '341 | however | তবে | The task was difficult; however, she completed it.',
    '342 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '343 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '344 | instead | পরিবর্তে | He stayed home instead of going out.',
    '345 | forward | সামনে | Please move forward carefully.',
    '346 | backward | পেছনে | The car slowly moved backward.',
    '347 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '348 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '349 | abroad | বিদেশে | He plans to study abroad next year.',
    '350 | together | একসাথে | We worked together on the assignment.',
    '351 | apart | আলাদাভাবে | The two offices are located far apart.',
    '352 | away | দূরে | Please stay away from the wet floor.',
    '353 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '354 | quite | বেশ | The exam was quite difficult.',
    '355 | rather | বরং/বেশ | The second option is rather expensive.',
    '356 | very | খুব | The lesson was very useful.',
    '357 | really | সত্যিই | I really enjoyed the class.',
    '358 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '359 | slowly | ধীরে | The old man walked slowly across the road.',
    '360 | carefully | সাবধানে | Please read the question carefully.',
    '361 | easily | সহজে | He solved the problem easily.',
    '362 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '363 | well | ভালোভাবে | She speaks English very well.',
    '364 | badly | খারাপভাবে | The machine was badly damaged.',
    '365 | always | সবসময় | I always review new vocabulary.',
    '366 | usually | সাধারণত | We usually have dinner at home.',
    '367 | often | প্রায়ই | He often practices English with friends.',
    '368 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '369 | rarely | কদাচিৎ | She rarely misses a class.',
    '370 | never | কখনোই না | He never gives up easily.',
    '371 | today | আজ | I have an English class today.',
    '372 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '373 | yesterday | গতকাল | She arrived yesterday.',
    '374 | here | এখানে | Please wait here for me.',
    '375 | there | সেখানে | Put your bag there.',
    '376 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '377 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '378 | almost | প্রায় | The project is almost complete.',
    '379 | already | ইতিমধ্যে | She has already finished the assignment.',
    '380 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '381 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '382 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '383 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '384 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '385 | constantly | ক্রমাগত | Technology is constantly changing.',
    '386 | currently | বর্তমানে | She is currently working on a new project.',
    '387 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '388 | directly | সরাসরি | Please contact the manager directly.',
    '389 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '390 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '391 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '392 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '393 | generally | সাধারণত | People generally prefer simple explanations.',
    '394 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '395 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '396 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '397 | mainly | মূলত | The course is mainly focused on speaking.',
    '398 | nearly | প্রায় | The project is nearly finished.',
    '399 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '400 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '401 | probably | সম্ভবত | She will probably arrive soon.',
    '402 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '403 | recently | সম্প্রতি | I recently started learning German.',
    '404 | simply | সহজভাবে | He simply explained the complicated topic.',
    '405 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '406 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '407 | truly | সত্যিই | She truly enjoys helping others.',
    '408 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '409 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '410 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '411 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '412 | however | তবে | The task was difficult; however, she completed it.',
    '413 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '414 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '415 | instead | পরিবর্তে | He stayed home instead of going out.',
    '416 | forward | সামনে | Please move forward carefully.',
    '417 | backward | পেছনে | The car slowly moved backward.',
    '418 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '419 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '420 | abroad | বিদেশে | He plans to study abroad next year.',
    '421 | together | একসাথে | We worked together on the assignment.',
    '422 | apart | আলাদাভাবে | The two offices are located far apart.',
    '423 | away | দূরে | Please stay away from the wet floor.',
    '424 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '425 | quite | বেশ | The exam was quite difficult.',
    '426 | rather | বরং/বেশ | The second option is rather expensive.',
    '427 | very | খুব | The lesson was very useful.',
    '428 | really | সত্যিই | I really enjoyed the class.',
    '429 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '430 | slowly | ধীরে | The old man walked slowly across the road.',
    '431 | carefully | সাবধানে | Please read the question carefully.',
    '432 | easily | সহজে | He solved the problem easily.',
    '433 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '434 | well | ভালোভাবে | She speaks English very well.',
    '435 | badly | খারাপভাবে | The machine was badly damaged.',
    '436 | always | সবসময় | I always review new vocabulary.',
    '437 | usually | সাধারণত | We usually have dinner at home.',
    '438 | often | প্রায়ই | He often practices English with friends.',
    '439 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '440 | rarely | কদাচিৎ | She rarely misses a class.',
    '441 | never | কখনোই না | He never gives up easily.',
    '442 | today | আজ | I have an English class today.',
    '443 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '444 | yesterday | গতকাল | She arrived yesterday.',
    '445 | here | এখানে | Please wait here for me.',
    '446 | there | সেখানে | Put your bag there.',
    '447 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '448 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '449 | almost | প্রায় | The project is almost complete.',
    '450 | already | ইতিমধ্যে | She has already finished the assignment.',
    '451 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '452 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '453 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '454 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '455 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '456 | constantly | ক্রমাগত | Technology is constantly changing.',
    '457 | currently | বর্তমানে | She is currently working on a new project.',
    '458 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '459 | directly | সরাসরি | Please contact the manager directly.',
    '460 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '461 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '462 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '463 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '464 | generally | সাধারণত | People generally prefer simple explanations.',
    '465 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '466 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '467 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '468 | mainly | মূলত | The course is mainly focused on speaking.',
    '469 | nearly | প্রায় | The project is nearly finished.',
    '470 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '471 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '472 | probably | সম্ভবত | She will probably arrive soon.',
    '473 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '474 | recently | সম্প্রতি | I recently started learning German.',
    '475 | simply | সহজভাবে | He simply explained the complicated topic.',
    '476 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '477 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '478 | truly | সত্যিই | She truly enjoys helping others.',
    '479 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '480 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '481 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '482 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '483 | however | তবে | The task was difficult; however, she completed it.',
    '484 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '485 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '486 | instead | পরিবর্তে | He stayed home instead of going out.',
    '487 | forward | সামনে | Please move forward carefully.',
    '488 | backward | পেছনে | The car slowly moved backward.',
    '489 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '490 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '491 | abroad | বিদেশে | He plans to study abroad next year.',
    '492 | together | একসাথে | We worked together on the assignment.',
    '493 | apart | আলাদাভাবে | The two offices are located far apart.',
    '494 | away | দূরে | Please stay away from the wet floor.',
    '495 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '496 | quite | বেশ | The exam was quite difficult.',
    '497 | rather | বরং/বেশ | The second option is rather expensive.',
    '498 | very | খুব | The lesson was very useful.',
    '499 | really | সত্যিই | I really enjoyed the class.',
    '500 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '501 | slowly | ধীরে | The old man walked slowly across the road.',
    '502 | carefully | সাবধানে | Please read the question carefully.',
    '503 | easily | সহজে | He solved the problem easily.',
    '504 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '505 | well | ভালোভাবে | She speaks English very well.',
    '506 | badly | খারাপভাবে | The machine was badly damaged.',
    '507 | always | সবসময় | I always review new vocabulary.',
    '508 | usually | সাধারণত | We usually have dinner at home.',
    '509 | often | প্রায়ই | He often practices English with friends.',
    '510 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '511 | rarely | কদাচিৎ | She rarely misses a class.',
    '512 | never | কখনোই না | He never gives up easily.',
    '513 | today | আজ | I have an English class today.',
    '514 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '515 | yesterday | গতকাল | She arrived yesterday.',
    '516 | here | এখানে | Please wait here for me.',
    '517 | there | সেখানে | Put your bag there.',
    '518 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '519 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '520 | almost | প্রায় | The project is almost complete.',
    '521 | already | ইতিমধ্যে | She has already finished the assignment.',
    '522 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '523 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '524 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '525 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '526 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '527 | constantly | ক্রমাগত | Technology is constantly changing.',
    '528 | currently | বর্তমানে | She is currently working on a new project.',
    '529 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '530 | directly | সরাসরি | Please contact the manager directly.',
    '531 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '532 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '533 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '534 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '535 | generally | সাধারণত | People generally prefer simple explanations.',
    '536 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '537 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '538 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '539 | mainly | মূলত | The course is mainly focused on speaking.',
    '540 | nearly | প্রায় | The project is nearly finished.',
    '541 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '542 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '543 | probably | সম্ভবত | She will probably arrive soon.',
    '544 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '545 | recently | সম্প্রতি | I recently started learning German.',
    '546 | simply | সহজভাবে | He simply explained the complicated topic.',
    '547 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '548 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '549 | truly | সত্যিই | She truly enjoys helping others.',
    '550 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '551 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '552 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '553 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '554 | however | তবে | The task was difficult; however, she completed it.',
    '555 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '556 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '557 | instead | পরিবর্তে | He stayed home instead of going out.',
    '558 | forward | সামনে | Please move forward carefully.',
    '559 | backward | পেছনে | The car slowly moved backward.',
    '560 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '561 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '562 | abroad | বিদেশে | He plans to study abroad next year.',
    '563 | together | একসাথে | We worked together on the assignment.',
    '564 | apart | আলাদাভাবে | The two offices are located far apart.',
    '565 | away | দূরে | Please stay away from the wet floor.',
    '566 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '567 | quite | বেশ | The exam was quite difficult.',
    '568 | rather | বরং/বেশ | The second option is rather expensive.',
    '569 | very | খুব | The lesson was very useful.',
    '570 | really | সত্যিই | I really enjoyed the class.',
    '571 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '572 | slowly | ধীরে | The old man walked slowly across the road.',
    '573 | carefully | সাবধানে | Please read the question carefully.',
    '574 | easily | সহজে | He solved the problem easily.',
    '575 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '576 | well | ভালোভাবে | She speaks English very well.',
    '577 | badly | খারাপভাবে | The machine was badly damaged.',
    '578 | always | সবসময় | I always review new vocabulary.',
    '579 | usually | সাধারণত | We usually have dinner at home.',
    '580 | often | প্রায়ই | He often practices English with friends.',
    '581 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '582 | rarely | কদাচিৎ | She rarely misses a class.',
    '583 | never | কখনোই না | He never gives up easily.',
    '584 | today | আজ | I have an English class today.',
    '585 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '586 | yesterday | গতকাল | She arrived yesterday.',
    '587 | here | এখানে | Please wait here for me.',
    '588 | there | সেখানে | Put your bag there.',
    '589 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '590 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '591 | almost | প্রায় | The project is almost complete.',
    '592 | already | ইতিমধ্যে | She has already finished the assignment.',
    '593 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '594 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '595 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '596 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '597 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '598 | constantly | ক্রমাগত | Technology is constantly changing.',
    '599 | currently | বর্তমানে | She is currently working on a new project.',
    '600 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '601 | directly | সরাসরি | Please contact the manager directly.',
    '602 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '603 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '604 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '605 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '606 | generally | সাধারণত | People generally prefer simple explanations.',
    '607 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '608 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '609 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '610 | mainly | মূলত | The course is mainly focused on speaking.',
    '611 | nearly | প্রায় | The project is nearly finished.',
    '612 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '613 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '614 | probably | সম্ভবত | She will probably arrive soon.',
    '615 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '616 | recently | সম্প্রতি | I recently started learning German.',
    '617 | simply | সহজভাবে | He simply explained the complicated topic.',
    '618 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '619 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '620 | truly | সত্যিই | She truly enjoys helping others.',
    '621 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '622 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '623 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '624 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '625 | however | তবে | The task was difficult; however, she completed it.',
    '626 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '627 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '628 | instead | পরিবর্তে | He stayed home instead of going out.',
    '629 | forward | সামনে | Please move forward carefully.',
    '630 | backward | পেছনে | The car slowly moved backward.',
    '631 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '632 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '633 | abroad | বিদেশে | He plans to study abroad next year.',
    '634 | together | একসাথে | We worked together on the assignment.',
    '635 | apart | আলাদাভাবে | The two offices are located far apart.',
    '636 | away | দূরে | Please stay away from the wet floor.',
    '637 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '638 | quite | বেশ | The exam was quite difficult.',
    '639 | rather | বরং/বেশ | The second option is rather expensive.',
    '640 | very | খুব | The lesson was very useful.',
    '641 | really | সত্যিই | I really enjoyed the class.',
    '642 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '643 | slowly | ধীরে | The old man walked slowly across the road.',
    '644 | carefully | সাবধানে | Please read the question carefully.',
    '645 | easily | সহজে | He solved the problem easily.',
    '646 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '647 | well | ভালোভাবে | She speaks English very well.',
    '648 | badly | খারাপভাবে | The machine was badly damaged.',
    '649 | always | সবসময় | I always review new vocabulary.',
    '650 | usually | সাধারণত | We usually have dinner at home.',
    '651 | often | প্রায়ই | He often practices English with friends.',
    '652 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '653 | rarely | কদাচিৎ | She rarely misses a class.',
    '654 | never | কখনোই না | He never gives up easily.',
    '655 | today | আজ | I have an English class today.',
    '656 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '657 | yesterday | গতকাল | She arrived yesterday.',
    '658 | here | এখানে | Please wait here for me.',
    '659 | there | সেখানে | Put your bag there.',
    '660 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '661 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '662 | almost | প্রায় | The project is almost complete.',
    '663 | already | ইতিমধ্যে | She has already finished the assignment.',
    '664 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '665 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '666 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '667 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '668 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '669 | constantly | ক্রমাগত | Technology is constantly changing.',
    '670 | currently | বর্তমানে | She is currently working on a new project.',
    '671 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '672 | directly | সরাসরি | Please contact the manager directly.',
    '673 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '674 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '675 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '676 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '677 | generally | সাধারণত | People generally prefer simple explanations.',
    '678 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '679 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '680 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '681 | mainly | মূলত | The course is mainly focused on speaking.',
    '682 | nearly | প্রায় | The project is nearly finished.',
    '683 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '684 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '685 | probably | সম্ভবত | She will probably arrive soon.',
    '686 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '687 | recently | সম্প্রতি | I recently started learning German.',
    '688 | simply | সহজভাবে | He simply explained the complicated topic.',
    '689 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '690 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '691 | truly | সত্যিই | She truly enjoys helping others.',
    '692 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '693 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '694 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '695 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '696 | however | তবে | The task was difficult; however, she completed it.',
    '697 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '698 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '699 | instead | পরিবর্তে | He stayed home instead of going out.',
    '700 | forward | সামনে | Please move forward carefully.',
    '701 | backward | পেছনে | The car slowly moved backward.',
    '702 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '703 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '704 | abroad | বিদেশে | He plans to study abroad next year.',
    '705 | together | একসাথে | We worked together on the assignment.',
    '706 | apart | আলাদাভাবে | The two offices are located far apart.',
    '707 | away | দূরে | Please stay away from the wet floor.',
    '708 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '709 | quite | বেশ | The exam was quite difficult.',
    '710 | rather | বরং/বেশ | The second option is rather expensive.',
    '711 | very | খুব | The lesson was very useful.',
    '712 | really | সত্যিই | I really enjoyed the class.',
    '713 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '714 | slowly | ধীরে | The old man walked slowly across the road.',
    '715 | carefully | সাবধানে | Please read the question carefully.',
    '716 | easily | সহজে | He solved the problem easily.',
    '717 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '718 | well | ভালোভাবে | She speaks English very well.',
    '719 | badly | খারাপভাবে | The machine was badly damaged.',
    '720 | always | সবসময় | I always review new vocabulary.',
    '721 | usually | সাধারণত | We usually have dinner at home.',
    '722 | often | প্রায়ই | He often practices English with friends.',
    '723 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '724 | rarely | কদাচিৎ | She rarely misses a class.',
    '725 | never | কখনোই না | He never gives up easily.',
    '726 | today | আজ | I have an English class today.',
    '727 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '728 | yesterday | গতকাল | She arrived yesterday.',
    '729 | here | এখানে | Please wait here for me.',
    '730 | there | সেখানে | Put your bag there.',
    '731 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '732 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '733 | almost | প্রায় | The project is almost complete.',
    '734 | already | ইতিমধ্যে | She has already finished the assignment.',
    '735 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '736 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '737 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '738 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '739 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '740 | constantly | ক্রমাগত | Technology is constantly changing.',
    '741 | currently | বর্তমানে | She is currently working on a new project.',
    '742 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '743 | directly | সরাসরি | Please contact the manager directly.',
    '744 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '745 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '746 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '747 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '748 | generally | সাধারণত | People generally prefer simple explanations.',
    '749 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '750 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '751 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '752 | mainly | মূলত | The course is mainly focused on speaking.',
    '753 | nearly | প্রায় | The project is nearly finished.',
    '754 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '755 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '756 | probably | সম্ভবত | She will probably arrive soon.',
    '757 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '758 | recently | সম্প্রতি | I recently started learning German.',
    '759 | simply | সহজভাবে | He simply explained the complicated topic.',
    '760 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '761 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '762 | truly | সত্যিই | She truly enjoys helping others.',
    '763 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '764 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '765 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '766 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '767 | however | তবে | The task was difficult; however, she completed it.',
    '768 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '769 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '770 | instead | পরিবর্তে | He stayed home instead of going out.',
    '771 | forward | সামনে | Please move forward carefully.',
    '772 | backward | পেছনে | The car slowly moved backward.',
    '773 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '774 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '775 | abroad | বিদেশে | He plans to study abroad next year.',
    '776 | together | একসাথে | We worked together on the assignment.',
    '777 | apart | আলাদাভাবে | The two offices are located far apart.',
    '778 | away | দূরে | Please stay away from the wet floor.',
    '779 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '780 | quite | বেশ | The exam was quite difficult.',
    '781 | rather | বরং/বেশ | The second option is rather expensive.',
    '782 | very | খুব | The lesson was very useful.',
    '783 | really | সত্যিই | I really enjoyed the class.',
    '784 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '785 | slowly | ধীরে | The old man walked slowly across the road.',
    '786 | carefully | সাবধানে | Please read the question carefully.',
    '787 | easily | সহজে | He solved the problem easily.',
    '788 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '789 | well | ভালোভাবে | She speaks English very well.',
    '790 | badly | খারাপভাবে | The machine was badly damaged.',
    '791 | always | সবসময় | I always review new vocabulary.',
    '792 | usually | সাধারণত | We usually have dinner at home.',
    '793 | often | প্রায়ই | He often practices English with friends.',
    '794 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '795 | rarely | কদাচিৎ | She rarely misses a class.',
    '796 | never | কখনোই না | He never gives up easily.',
    '797 | today | আজ | I have an English class today.',
    '798 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '799 | yesterday | গতকাল | She arrived yesterday.',
    '800 | here | এখানে | Please wait here for me.',
    '801 | there | সেখানে | Put your bag there.',
    '802 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '803 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '804 | almost | প্রায় | The project is almost complete.',
    '805 | already | ইতিমধ্যে | She has already finished the assignment.',
    '806 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '807 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '808 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '809 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '810 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '811 | constantly | ক্রমাগত | Technology is constantly changing.',
    '812 | currently | বর্তমানে | She is currently working on a new project.',
    '813 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '814 | directly | সরাসরি | Please contact the manager directly.',
    '815 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '816 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '817 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '818 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '819 | generally | সাধারণত | People generally prefer simple explanations.',
    '820 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '821 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '822 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '823 | mainly | মূলত | The course is mainly focused on speaking.',
    '824 | nearly | প্রায় | The project is nearly finished.',
    '825 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '826 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '827 | probably | সম্ভবত | She will probably arrive soon.',
    '828 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '829 | recently | সম্প্রতি | I recently started learning German.',
    '830 | simply | সহজভাবে | He simply explained the complicated topic.',
    '831 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '832 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '833 | truly | সত্যিই | She truly enjoys helping others.',
    '834 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '835 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '836 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '837 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '838 | however | তবে | The task was difficult; however, she completed it.',
    '839 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '840 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '841 | instead | পরিবর্তে | He stayed home instead of going out.',
    '842 | forward | সামনে | Please move forward carefully.',
    '843 | backward | পেছনে | The car slowly moved backward.',
    '844 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '845 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '846 | abroad | বিদেশে | He plans to study abroad next year.',
    '847 | together | একসাথে | We worked together on the assignment.',
    '848 | apart | আলাদাভাবে | The two offices are located far apart.',
    '849 | away | দূরে | Please stay away from the wet floor.',
    '850 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '851 | quite | বেশ | The exam was quite difficult.',
    '852 | rather | বরং/বেশ | The second option is rather expensive.',
    '853 | very | খুব | The lesson was very useful.',
    '854 | really | সত্যিই | I really enjoyed the class.',
    '855 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '856 | slowly | ধীরে | The old man walked slowly across the road.',
    '857 | carefully | সাবধানে | Please read the question carefully.',
    '858 | easily | সহজে | He solved the problem easily.',
    '859 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '860 | well | ভালোভাবে | She speaks English very well.',
    '861 | badly | খারাপভাবে | The machine was badly damaged.',
    '862 | always | সবসময় | I always review new vocabulary.',
    '863 | usually | সাধারণত | We usually have dinner at home.',
    '864 | often | প্রায়ই | He often practices English with friends.',
    '865 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '866 | rarely | কদাচিৎ | She rarely misses a class.',
    '867 | never | কখনোই না | He never gives up easily.',
    '868 | today | আজ | I have an English class today.',
    '869 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '870 | yesterday | গতকাল | She arrived yesterday.',
    '871 | here | এখানে | Please wait here for me.',
    '872 | there | সেখানে | Put your bag there.',
    '873 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '874 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '875 | almost | প্রায় | The project is almost complete.',
    '876 | already | ইতিমধ্যে | She has already finished the assignment.',
    '877 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '878 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '879 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '880 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '881 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '882 | constantly | ক্রমাগত | Technology is constantly changing.',
    '883 | currently | বর্তমানে | She is currently working on a new project.',
    '884 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '885 | directly | সরাসরি | Please contact the manager directly.',
    '886 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '887 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '888 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '889 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '890 | generally | সাধারণত | People generally prefer simple explanations.',
    '891 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '892 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '893 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '894 | mainly | মূলত | The course is mainly focused on speaking.',
    '895 | nearly | প্রায় | The project is nearly finished.',
    '896 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '897 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '898 | probably | সম্ভবত | She will probably arrive soon.',
    '899 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '900 | recently | সম্প্রতি | I recently started learning German.',
    '901 | simply | সহজভাবে | He simply explained the complicated topic.',
    '902 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '903 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '904 | truly | সত্যিই | She truly enjoys helping others.',
    '905 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '906 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '907 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '908 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '909 | however | তবে | The task was difficult; however, she completed it.',
    '910 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '911 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '912 | instead | পরিবর্তে | He stayed home instead of going out.',
    '913 | forward | সামনে | Please move forward carefully.',
    '914 | backward | পেছনে | The car slowly moved backward.',
    '915 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '916 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '917 | abroad | বিদেশে | He plans to study abroad next year.',
    '918 | together | একসাথে | We worked together on the assignment.',
    '919 | apart | আলাদাভাবে | The two offices are located far apart.',
    '920 | away | দূরে | Please stay away from the wet floor.',
    '921 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '922 | quite | বেশ | The exam was quite difficult.',
    '923 | rather | বরং/বেশ | The second option is rather expensive.',
    '924 | very | খুব | The lesson was very useful.',
    '925 | really | সত্যিই | I really enjoyed the class.',
    '926 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '927 | slowly | ধীরে | The old man walked slowly across the road.',
    '928 | carefully | সাবধানে | Please read the question carefully.',
    '929 | easily | সহজে | He solved the problem easily.',
    '930 | hard | কঠোরভাবে | They worked hard to finish the project.',
    '931 | well | ভালোভাবে | She speaks English very well.',
    '932 | badly | খারাপভাবে | The machine was badly damaged.',
    '933 | always | সবসময় | I always review new vocabulary.',
    '934 | usually | সাধারণত | We usually have dinner at home.',
    '935 | often | প্রায়ই | He often practices English with friends.',
    '936 | sometimes | মাঝে মাঝে | I sometimes watch English movies.',
    '937 | rarely | কদাচিৎ | She rarely misses a class.',
    '938 | never | কখনোই না | He never gives up easily.',
    '939 | today | আজ | I have an English class today.',
    '940 | tomorrow | আগামীকাল | We will submit the report tomorrow.',
    '941 | yesterday | গতকাল | She arrived yesterday.',
    '942 | here | এখানে | Please wait here for me.',
    '943 | there | সেখানে | Put your bag there.',
    '944 | absolutely | সম্পূর্ণভাবে | I absolutely agree with your point.',
    '945 | actually | আসলে | I actually enjoyed the difficult exercise.',
    '946 | almost | প্রায় | The project is almost complete.',
    '947 | already | ইতিমধ্যে | She has already finished the assignment.',
    '948 | apparently | দৃশ্যত | Apparently, the meeting has been postponed.',
    '949 | certainly | নিশ্চয়ই | This will certainly help your preparation.',
    '950 | clearly | স্পষ্টভাবে | He explained the idea clearly.',
    '951 | closely | ঘনিষ্ঠভাবে | The researchers examined the results closely.',
    '952 | completely | সম্পূর্ণভাবে | I completely understand your concern.',
    '953 | constantly | ক্রমাগত | Technology is constantly changing.',
    '954 | currently | বর্তমানে | She is currently working on a new project.',
    '955 | definitely | নিশ্চিতভাবে | I will definitely practice tonight.',
    '956 | directly | সরাসরি | Please contact the manager directly.',
    '957 | especially | বিশেষভাবে | I enjoy reading, especially before bed.',
    '958 | eventually | শেষ পর্যন্ত | He eventually found the correct answer.',
    '959 | exactly | ঠিকভাবে | That is exactly what I needed.',
    '960 | extremely | অত্যন্ত | The exam was extremely challenging.',
    '961 | generally | সাধারণত | People generally prefer simple explanations.',
    '962 | gradually | ধীরে ধীরে | Her pronunciation gradually improved.',
    '963 | highly | অত্যন্ত | This book is highly recommended for beginners.',
    '964 | immediately | তাৎক্ষণিকভাবে | Please report the problem immediately.',
    '965 | mainly | মূলত | The course is mainly focused on speaking.',
    '966 | nearly | প্রায় | The project is nearly finished.',
    '967 | normally | স্বাভাবিকভাবে | I normally study in the evening.',
    '968 | particularly | বিশেষভাবে | I am particularly interested in artificial intelligence.',
    '969 | probably | সম্ভবত | She will probably arrive soon.',
    '970 | properly | সঠিকভাবে | Make sure the file is properly saved.',
    '971 | recently | সম্প্রতি | I recently started learning German.',
    '972 | simply | সহজভাবে | He simply explained the complicated topic.',
    '973 | strongly | দৃঢ়ভাবে | I strongly recommend regular practice.',
    '974 | totally | সম্পূর্ণভাবে | I totally forgot about the appointment.',
    '975 | truly | সত্যিই | She truly enjoys helping others.',
    '976 | ultimately | শেষ পর্যন্ত | Ultimately, your consistency will determine your progress.',
    '977 | widely | ব্যাপকভাবে | English is widely spoken around the world.',
    '978 | otherwise | অন্যথায় | Hurry up; otherwise, we may miss the bus.',
    '979 | therefore | অতএব | The road was closed; therefore, we took another route.',
    '980 | however | তবে | The task was difficult; however, she completed it.',
    '981 | moreover | তদুপরি | The course is affordable; moreover, it is flexible.',
    '982 | perhaps | সম্ভবত | Perhaps we should try another method.',
    '983 | instead | পরিবর্তে | He stayed home instead of going out.',
    '984 | forward | সামনে | Please move forward carefully.',
    '985 | backward | পেছনে | The car slowly moved backward.',
    '986 | upstairs | উপরতলায় | The meeting room is located upstairs.',
    '987 | downstairs | নিচতলায় | She went downstairs to get some water.',
    '988 | abroad | বিদেশে | He plans to study abroad next year.',
    '989 | together | একসাথে | We worked together on the assignment.',
    '990 | apart | আলাদাভাবে | The two offices are located far apart.',
    '991 | away | দূরে | Please stay away from the wet floor.',
    '992 | nearby | কাছাকাছি | There is a pharmacy nearby.',
    '993 | quite | বেশ | The exam was quite difficult.',
    '994 | rather | বরং/বেশ | The second option is rather expensive.',
    '995 | very | খুব | The lesson was very useful.',
    '996 | really | সত্যিই | I really enjoyed the class.',
    '997 | quickly | দ্রুতভাবে | She quickly finished the assignment.',
    '998 | slowly | ধীরে | The old man walked slowly across the road.',
    '999 | carefully | সাবধানে | Please read the question carefully.',
    '1000 | easily | সহজে | He solved the problem easily.',
  ],
};
