import { type IRawSaifursGroup } from './schema';

export const WORDS_I: IRawSaifursGroup = {
  letter: 'I',
  entries: [
    'iconoclast | n | aɪˈkɒnəklæst | aɪˈkɑːnəˌklæst | প্রথার বিরোধী | rebel, critic | conformist, follower | An iconoclast challenged the rule. | এক প্রথার বিরোধী নিয়মকে চ্যালেঞ্জ করেন।',
    'ideal | adj | aɪˈdiːəl | aɪˈdiːəl | আদর্শ | perfect, model | flawed, real | An ideal answer is short and clear. | একটি আদর্শ উত্তর ছোট ও স্পষ্ট।',
    'identical | adj | aɪˈdentɪkl | aɪˈdentɪkl | অভিন্ন | same, matching | different, unlike | The twins wore identical shirts. | যমজরা অভিন্ন শার্ট পরে।',
    'ideology | n | ˌaɪdiˈɒlədʒi | ˌaɪdiˈɑːlədʒi | মতাদর্শ | belief, doctrine | - | The party has a clear ideology. | দলের একটি স্পষ্ট মতাদর্শ আছে।',
    'idiom | n | ˈɪdiəm | ˈɪdiəm | বাগধারা | phrase, expression | - | Learn one idiom a day. | দিনে একটি বাগধারা শিখুন।',
    'idle | adj | ˈaɪdl | ˈaɪdl | অলস | inactive, lazy | busy, active | Do not sit idle all morning. | সারা সকাল অলস বসে থাকবেন না।',
    'ignite | v | ɪɡˈnaɪt | ɪɡˈnaɪt | জ্বালানো | light, kindle | extinguish, quench | A spark can ignite the dry grass. | একটি স্ফুলিঙ্গ শুকনো ঘাস জ্বালাতে পারে।',
    'ignoble | adj | ɪɡˈnəʊbl | ɪɡˈnoʊbl | নীচ | base, shameful | noble, honourable | An ignoble trick won nothing. | একটি নীচ কৌশল কিছু জেতেনি।',
    'ignominy | n | ˈɪɡnəmɪni | ˈɪɡnəmɪni | অপমান | shame, disgrace | honour, glory | Defeat brought ignominy. | হার অপমান আনে।',
    'ignorant | adj | ˈɪɡnərənt | ˈɪɡnərənt | অজ্ঞ | uninformed, unaware | knowledgeable, aware | An ignorant remark hurt the class. | একটি অজ্ঞ মন্তব্য ক্লাসকে কষ্ট দেয়।',
    'illegible | adj | ɪˈledʒəbl | ɪˈledʒəbl | পড়া যায় না এমন | unreadable, unclear | legible, clear | The note was illegible. | নোটটি পড়া যায় না এমন ছিল।',
    'illicit | adj | ɪˈlɪsɪt | ɪˈlɪsɪt | অবৈধ | illegal, forbidden | legal, lawful | Police seized illicit goods. | পুলিশ অবৈধ মাল জব্দ করে।',
    'illuminate | v | ɪˈluːmɪneɪt | ɪˈluːməˌneɪt | আলোকিত করা | light, clarify | darken, obscure | Lamps illuminate the yard. | বাতি উঠান আলোকিত করে।',
    'illusion | n | ɪˈluːʒn | ɪˈluːʒn | মায়া | delusion, mirage | reality, fact | The oasis was an illusion. | মরুদ্যানটি একটি মায়া ছিল।',
    'illustrate | v | ˈɪləstreɪt | ˈɪləˌstreɪt | উদাহরণ দিয়ে বোঝানো | show, demonstrate | obscure, hide | Please illustrate the rule. | নিয়মটি উদাহরণ দিয়ে বোঝান।',
    'illustrious | adj | ɪˈlʌstriəs | ɪˈlʌstriəs | বিখ্যাত | famous, distinguished | obscure, unknown | An illustrious guest opened the fair. | এক বিখ্যাত অতিথি মেলা খোলেন।',
    'imbibe | v | ɪmˈbaɪb | ɪmˈbaɪb | শোষণ করা | absorb, drink | emit, refuse | Children imbibe language at home. | শিশুরা ঘরে ভাষা শোষণ করে।',
    'imbue | v | ɪmˈbjuː | ɪmˈbjuː | ভরে দেওয়া | fill, infuse | drain, empty | Stories imbue children with courage. | গল্প শিশুদের সাহসে ভরে দেয়।',
    'immaculate | adj | ɪˈmækjələt | ɪˈmækjələt | নিখুঁত পরিষ্কার | spotless, pure | stained, dirty | An immaculate page lay on the desk. | ডেস্কে একটি নিখুঁত পরিষ্কার পাতা পড়ে ছিল।',
    'imminent | adj | ˈɪmɪnənt | ˈɪmɪnənt | আসন্ন | impending, near | distant, remote | Rain is imminent. | বৃষ্টি আসন্ন।',
    'immobile | adj | ɪˈməʊbaɪl | ɪˈmoʊbl | স্থির | still, fixed | mobile, moving | The injured bird lay immobile. | আহত পাখি স্থির পড়ে ছিল।',
    'immortal | adj | ɪˈmɔːtl | ɪˈmɔːrtl | অমর | deathless, lasting | mortal, fleeting | The poet hoped for immortal fame. | কবি অমর খ্যাতি আশা করেন।',
    'immune | adj | ɪˈmjuːn | ɪˈmjuːn | রোগপ্রতিরোধী | resistant, exempt | susceptible, liable | Few are immune to the fever. | কয়েকজন জ্বরে রোগপ্রতিরোধী।',
    'immutable | adj | ɪˈmjuːtəbl | ɪˈmjuːtəbl | অপরিবর্তনীয় | unchangeable, fixed | changeable, fluid | The law is not immutable. | আইন অপরিবর্তনীয় নয়।',
    'impair | v | ɪmˈpeə | ɪmˈper | ক্ষতি করা | damage, weaken | improve, aid | Noise can impair hearing. | শব্দ শ্রবণ ক্ষতি করতে পারে।',
    'impartial | adj | ɪmˈpɑːʃl | ɪmˈpɑːrʃl | নিরপেক্ষ | fair, unbiased | biased, partial | A judge must be impartial. | বিচারককে নিরপেক্ষ থাকতে হয়।',
    'impasse | n | ˈæmpɑːs | ˈɪmpæs | অচলাবস্থা | deadlock, stalemate | breakthrough, progress | Talks reached an impasse. | আলোচনা অচলাবস্থায় পৌঁছায়।',
    'impeach | v | ɪmˈpiːtʃ | ɪmˈpiːtʃ | অভিযোগ আনা | accuse, charge | exonerate, clear | Parliament may impeach the minister. | সংসদ মন্ত্রীর বিরুদ্ধে অভিযোগ আনতে পারে।',
    'impeccable | adj | ɪmˈpekəbl | ɪmˈpekəbl | নির্দোষ | flawless, perfect | faulty, flawed | Her English is impeccable. | তার ইংরেজি নির্দোষ।',
    'impede | v | ɪmˈpiːd | ɪmˈpiːd | বাধা দেওয়া | hinder, obstruct | help, aid | Mud will impede the cart. | কাদা গাড়িতে বাধা দেবে।',
    'impel | v | ɪmˈpel | ɪmˈpel | তাড়িত করা | drive, force | deter, restrain | Duty will impel him to speak. | কর্তব্য তাকে কথা বলতে তাড়িত করবে।',
    'impending | adj | ɪmˈpendɪŋ | ɪmˈpendɪŋ | আসন্ন | approaching, imminent | distant, past | An impending storm closed the port. | একটি আসন্ন ঝড় বন্দর বন্ধ করে।',
    'imperative | adj | ɪmˈperətɪv | ɪmˈperətɪv | অত্যাবশ্যক | urgent, essential | optional, minor | Sleep is imperative before the exam. | পরীক্ষার আগে ঘুম অত্যাবশ্যক।',
    'imperceptible | adj | ˌɪmpəˈseptəbl | ˌɪmpərˈseptəbl | অদৃশ্যপ্রায় | tiny, faint | obvious, clear | The change was almost imperceptible. | পরিবর্তন প্রায় অদৃশ্যপ্রায় ছিল।',
    'imperial | adj | ɪmˈpɪəriəl | ɪmˈpɪriəl | সাম্রাজ্যিক | royal, majestic | humble, modest | An imperial order closed the gates. | একটি সাম্রাজ্যিক আদেশ ফটক বন্ধ করে।',
    'imperious | adj | ɪmˈpɪəriəs | ɪmˈpɪriəs | দাম্ভিক | arrogant, commanding | humble, meek | An imperious tone ended the talk. | একটি দাম্ভিক সুর আলোচনা শেষ করে।',
    'impertinent | adj | ɪmˈpɜːtɪnənt | ɪmˈpɜːrtnənt | অশিষ্ট | rude, insolent | polite, respectful | An impertinent reply angered the teacher. | একটি অশিষ্ট উত্তর শিক্ষককে রাগায়।',
    'impetuous | adj | ɪmˈpetʃuəs | ɪmˈpetʃuəs | আবেগপ্রবণ | rash, hasty | cautious, careful | An impetuous dash cost the point. | একটি আবেগপ্রবণ দৌড় পয়েন্ট কাড়ে।',
    'implausible | adj | ɪmˈplɔːzəbl | ɪmˈplɔːzəbl | অবিশ্বাস্য | unlikely, doubtful | plausible, likely | The excuse sounded implausible. | অজুহাত অবিশ্বাস্য শোনাত।',
    'implement | v | ˈɪmplɪment | ˈɪmplɪˌment | বাস্তবায়ন করা | apply, execute | abandon, delay | Schools implement the new rule. | স্কুলগুলো নতুন নিয়ম বাস্তবায়ন করে।',
    'implicate | v | ˈɪmplɪkeɪt | ˈɪmplɪˌkeɪt | জড়ানো | involve, incriminate | exonerate, clear | Do not implicate the innocent. | নির্দোষকে জড়াবেন না।',
    'implicit | adj | ɪmˈplɪsɪt | ɪmˈplɪsɪt | অন্তর্নিহিত | implied, unspoken | explicit, stated | There is an implicit warning in the letter. | চিঠিতে একটি অন্তর্নিহিত সতর্কতা আছে।',
    'implore | v | ɪmˈplɔː | ɪmˈplɔːr | অনুনয় করা | beg, entreat | demand, command | I implore you to wait. | আমি আপনাকে অপেক্ষা করার অনুনয় করি।',
    'imply | v | ɪmˈplaɪ | ɪmˈplaɪ | ইঙ্গিত করা | suggest, hint | state, declare | Silence may imply consent. | নীরবতা সম্মতির ইঙ্গিত করতে পারে।',
    'importunate | adj | ɪmˈpɔːtʃənət | ɪmˈpɔːrtʃənət | নাছোড় | insistent, persistent | modest, shy | An importunate beggar followed us. | এক নাছোড় ভিক্ষুক আমাদের অনুসরণ করেন।',
    'impose | v | ɪmˈpəʊz | ɪmˈpoʊz | চাপিয়ে দেওয়া | force, levy | lift, remove | Do not impose extra work. | অতিরিক্ত কাজ চাপিয়ে দেবেন না।',
    'impoverish | v | ɪmˈpɒvərɪʃ | ɪmˈpɑːvərɪʃ | দরিদ্র করা | ruin, deplete | enrich, fund | War can impoverish a land. | যুদ্ধ দেশকে দরিদ্র করতে পারে।',
    'impregnable | adj | ɪmˈpreɡnəbl | ɪmˈpreɡnəbl | অজেয় | invincible, unassailable | weak, open | The fort looked impregnable. | দুর্গ অজেয় মনে হয়।',
    'impress | v | ɪmˈpres | ɪmˈpres | মুগ্ধ করা | strike, move | bore, disappoint | The talk will impress the judges. | আলোচনা বিচারকদের মুগ্ধ করবে।',
    'impromptu | adj | ɪmˈprɒmptjuː | ɪmˈprɑːmptuː | তাৎক্ষণিক | unplanned, offhand | rehearsed, planned | An impromptu speech won the prize. | একটি তাৎক্ষণিক বক্তৃতা পুরস্কার জেতে।',
    'imprudent | adj | ɪmˈpruːdnt | ɪmˈpruːdnt | অবিবেচক | rash, unwise | prudent, wise | An imprudent loan ruined the shop. | একটি অবিবেচক ঋণ দোকান ধ্বংস করে।',
    'impudent | adj | ˈɪmpjədənt | ˈɪmpjədənt | নির্লজ্জ | insolent, rude | polite, modest | An impudent laugh filled the hall. | একটি নির্লজ্জ হাসি হল ভরে দেয়।',
    'impulse | n | ˈɪmpʌls | ˈɪmpʌls | আবেগ | urge, drive | plan, hesitation | Do not buy on impulse. | আবেগে কিনবেন না।',
    'impunity | n | ɪmˈpjuːnəti | ɪmˈpjuːnəti | দণ্ডহীনতা | exemption, immunity | punishment, penalty | Crime cannot go with impunity. | অপরাধ দণ্ডহীনতায় চলতে পারে না।',
    'impute | v | ɪmˈpjuːt | ɪmˈpjuːt | আরোপ করা | ascribe, attribute | exonerate, clear | Do not impute blame without proof. | প্রমাণ ছাড়া দোষ আরোপ করবেন না।',
    'inadvertent | adj | ˌɪnədˈvɜːtnt | ˌɪnədˈvɜːrtnt | অনবধান | accidental, unintentional | deliberate, planned | An inadvertent error slipped in. | একটি অনবধান ভুল ঢুকে পড়ে।',
    'inane | adj | ɪˈneɪn | ɪˈneɪn | অর্থহীন | silly, empty | sensible, wise | An inane joke wasted time. | একটি অর্থহীন রসিকতা সময় নষ্ট করে।',
    'inanimate | adj | ɪnˈænɪmət | ɪnˈænɪmət | জড় | lifeless, dead | living, animate | A stone is inanimate. | পাথর জড়।',
    'inaugurate | v | ɪˈnɔːɡjəreɪt | ɪˈnɔːɡjəˌreɪt | উদ্বোধন করা | open, launch | close, end | They inaugurate the hall in May. | তারা মে মাসে হল উদ্বোধন করে।',
    'incandescent | adj | ˌɪnkænˈdesnt | ˌɪnkænˈdesnt | উজ্জ্বল উত্তপ্ত | glowing, radiant | dull, cold | An incandescent lamp lit the room. | একটি উজ্জ্বল উত্তপ্ত বাতি ঘর আলো করে।',
    'incapacitate | v | ˌɪnkəˈpæsɪteɪt | ˌɪnkəˈpæsəˌteɪt | অক্ষম করা | disable, cripple | enable, restore | Injury can incapacitate a player. | চোট খেলোয়াড়কে অক্ষম করতে পারে।',
    'incarcerate | v | ɪnˈkɑːsəreɪt | ɪnˈkɑːrsəˌreɪt | কারাবদ্ধ করা | imprison, jail | free, release | The court may incarcerate the thief. | আদালত চোরকে কারাবদ্ধ করতে পারে।',
    'incense | v | ɪnˈsens | ɪnˈsens | ক্রুদ্ধ করা | enrage, infuriate | soothe, please | Delay will incense the crowd. | দেরি ভিড়কে ক্রুদ্ধ করবে।',
    'incentive | n | ɪnˈsentɪv | ɪnˈsentɪv | প্রণোদনা | motive, spur | deterrent, barrier | A prize is an incentive to study. | পুরস্কার পড়ার প্রণোদনা।',
    'inception | n | ɪnˈsepʃn | ɪnˈsepʃn | সূচনা | beginning, start | end, close | The club grew from its inception. | ক্লাব সূচনা থেকে বেড়েছে।',
    'incessant | adj | ɪnˈsesnt | ɪnˈsesnt | অবিরাম | constant, endless | occasional, brief | Incessant rain flooded the yard. | অবিরাম বৃষ্টি উঠান ভাসিয়ে দেয়।',
    'incidental | adj | ˌɪnsɪˈdentl | ˌɪnsɪˈdentl | আনুষঙ্গিক | minor, secondary | central, main | The cost was only incidental. | খরচ কেবল আনুষঙ্গিক ছিল।',
    'incisive | adj | ɪnˈsaɪsɪv | ɪnˈsaɪsɪv | তীক্ষ্ণ | sharp, penetrating | dull, vague | An incisive question ended the debate. | একটি তীক্ষ্ণ প্রশ্ন বিতর্ক শেষ করে।',
    'incite | v | ɪnˈsaɪt | ɪnˈsaɪt | উস্কানি দেওয়া | provoke, stir | calm, deter | Do not incite the crowd. | ভিড়কে উস্কানি দেবেন না।',
    'inclination | n | ˌɪnklɪˈneɪʃn | ˌɪnklɪˈneɪʃn | ঝোঁক | tendency, leaning | aversion, dislike | She has an inclination to write. | তার লেখার ঝোঁক আছে।',
    'inclusive | adj | ɪnˈkluːsɪv | ɪnˈkluːsɪv | অন্তর্ভুক্তিমূলক | comprehensive, embracing | exclusive, narrow | Keep the club inclusive. | ক্লাব অন্তর্ভুক্তিমূলক রাখুন।',
    'incoherent | adj | ˌɪnkəʊˈhɪərənt | ˌɪnkoʊˈhɪrənt | অসংলগ্ন | rambling, confused | coherent, clear | An incoherent answer failed. | একটি অসংলগ্ন উত্তর ফেল করে।',
    'incompatible | adj | ˌɪnkəmˈpætəbl | ˌɪnkəmˈpætəbl | অসামঞ্জস্যপূর্ণ | conflicting, clashing | compatible, matching | The two plans are incompatible. | দুই পরিকল্পনা অসামঞ্জস্যপূর্ণ।',
    'incompetent | adj | ɪnˈkɒmpɪtənt | ɪnˈkɑːmpɪtənt | অযোগ্য | inept, unfit | competent, able | An incompetent clerk lost the file. | এক অযোগ্য কেরানি ফাইল হারান।',
    'incongruous | adj | ɪnˈkɒŋɡruəs | ɪnˈkɑːŋɡruəs | বেখাপ্পা | odd, unsuitable | fitting, apt | A joke felt incongruous at the funeral. | শেষকৃত্যে রসিকতা বেখাপ্পা লাগে।',
    'inconsistent | adj | ˌɪnkənˈsɪstənt | ˌɪnkənˈsɪstənt | অসামঞ্জস্যপূর্ণ | uneven, contradictory | consistent, steady | Inconsistent marks puzzled her. | অসামঞ্জস্যপূর্ণ নম্বর তাকে হতবুদ্ধি করে।',
    'incorporate | v | ɪnˈkɔːpəreɪt | ɪnˈkɔːrpəˌreɪt | অন্তর্ভুক্ত করা | include, merge | exclude, omit | Please incorporate the new rule. | নতুন নিয়ম অন্তর্ভুক্ত করুন।',
    'incorrigible | adj | ɪnˈkɒrɪdʒəbl | ɪnˈkɔːrɪdʒəbl | অসংশোধনীয় | hopeless, incurable | reformable, teachable | An incorrigible liar fooled nobody. | এক অসংশোধনীয় মিথ্যাবাদী কাউকে বোকা করেনি।',
    'increase | v | ɪnˈkriːs | ɪnˈkriːs | বাড়ানো | raise, grow | decrease, reduce | Practice will increase your score. | অনুশীলন আপনার স্কোর বাড়াবে।',
    'incredulous | adj | ɪnˈkredjələs | ɪnˈkredʒələs | অবিশ্বাসী | sceptical, doubtful | credulous, believing | An incredulous look met the claim. | দাবির মুখে একটি অবিশ্বাসী চাহনি ওঠে।',
    'increment | n | ˈɪŋkrəmənt | ˈɪŋkrəmənt | বৃদ্ধি | increase, rise | decrease, cut | A small increment raised the pay. | একটি ছোট বৃদ্ধি বেতন বাড়ায়।',
    'incriminate | v | ɪnˈkrɪmɪneɪt | ɪnˈkrɪməˌneɪt | অপরাধী সাব্যস্ত করা | implicate, accuse | exonerate, clear | Do not incriminate a friend. | বন্ধুকে অপরাধী সাব্যস্ত করবেন না।',
    'inculcate | v | ˈɪnkʌlkeɪt | ɪnˈkʌlkeɪt | গেঁথে দেওয়া | instil, teach | erase, neglect | Schools inculcate honesty. | স্কুল সততা গেঁথে দেয়।',
    'incumbent | adj | ɪnˈkʌmbənt | ɪnˈkʌmbənt | কর্তব্যরত | sitting, obligatory | former, optional | It is incumbent on us to wait. | অপেক্ষা করা আমাদের কর্তব্যরত।',
    'incur | v | ɪnˈkɜː | ɪnˈkɜːr | বহন করা | suffer, bring on | avoid, escape | Late fees incur extra cost. | দেরির ফি অতিরিক্ত খরচ বহন করে।',
    'incursion | n | ɪnˈkɜːʃn | ɪnˈkɜːrʒn | অনধিকার প্রবেশ | raid, invasion | withdrawal, retreat | An incursion crossed the border. | একটি অনধিকার প্রবেশ সীমানা পার হয়।',
    'indefatigable | adj | ˌɪndɪˈfætɪɡəbl | ˌɪndɪˈfætɪɡəbl | অক্লান্ত | tireless, persistent | lazy, weary | An indefatigable runner finished first. | এক অক্লান্ত দৌড়বিদ প্রথমে শেষ করেন।',
    'indefinite | adj | ɪnˈdefɪnət | ɪnˈdefɪnət | অনির্দিষ্ট | unclear, vague | definite, fixed | The delay is indefinite. | দেরি অনির্দিষ্ট।',
    'indelible | adj | ɪnˈdeləbl | ɪnˈdeləbl | মুছতে না পারা | permanent, lasting | erasable, faint | The day left an indelible mark. | দিনটি একটি মুছতে না পারা ছাপ রাখে।',
    'indemnify | v | ɪnˈdemnɪfaɪ | ɪnˈdemnəˌfaɪ | ক্ষতিপূরণ দেওয়া | compensate, repay | penalise, fine | The firm will indemnify the loss. | প্রতিষ্ঠান ক্ষতিপূরণ দেবে।',
    'indicate | v | ˈɪndɪkeɪt | ˈɪndɪˌkeɪt | নির্দেশ করা | show, point | hide, conceal | Arrows indicate the exit. | তীর বেরোনোর পথ নির্দেশ করে।',
    'indict | v | ɪnˈdaɪt | ɪnˈdaɪt | অভিযোগপত্র দেওয়া | charge, accuse | acquit, clear | The court may indict the clerk. | আদালত কেরানিকে অভিযোগপত্র দিতে পারে।',
    'indifferent | adj | ɪnˈdɪfrənt | ɪnˈdɪfrənt | উদাসীন | unconcerned, apathetic | eager, keen | Do not stay indifferent to pain. | কষ্টে উদাসীন থাকবেন না।',
    'indigenous | adj | ɪnˈdɪdʒənəs | ɪnˈdɪdʒənəs | দেশজ | native, local | foreign, imported | Rice is indigenous to this valley. | ধান এই উপত্যকার দেশজ।',
    'indignant | adj | ɪnˈdɪɡnənt | ɪnˈdɪɡnənt | ক্ষুব্ধ | angry, outraged | pleased, calm | An indignant letter reached the board. | একটি ক্ষুব্ধ চিঠি বোর্ডে পৌঁছায়।',
    'indispensable | adj | ˌɪndɪˈspensəbl | ˌɪndɪˈspensəbl | অপরিহার্য | essential, vital | optional, needless | Water is indispensable in summer. | গ্রীষ্মে পানি অপরিহার্য।',
    'indolent | adj | ˈɪndələnt | ˈɪndələnt | অলস | lazy, idle | industrious, busy | An indolent student missed the class. | এক অলস শিক্ষার্থী ক্লাস মিস করেন।',
    'induce | v | ɪnˈdjuːs | ɪnˈduːs | প্ররোচিত করা | persuade, cause | deter, prevent | Nothing will induce him to lie. | কিছুই তাকে মিথ্যা বলতে প্ররোচিত করবে না।',
    'indulge | v | ɪnˈdʌldʒ | ɪnˈdʌldʒ | প্রশ্রয় দেওয়া | gratify, pamper | deny, restrain | Do not indulge every whim. | প্রতিটি খেয়ালে প্রশ্রয় দেবেন না।',
    'industrious | adj | ɪnˈdʌstriəs | ɪnˈdʌstriəs | পরিশ্রমী | hardworking, diligent | lazy, idle | An industrious farmer rose at dawn. | এক পরিশ্রমী কৃষক ভোরে ওঠেন।',
    'ineffable | adj | ɪnˈefəbl | ɪnˈefəbl | অবর্ণনীয় | inexpressible, unspeakable | ordinary, plain | An ineffable joy filled the hall. | একটি অবর্ণনীয় আনন্দ হল ভরে দেয়।',
    'inept | adj | ɪˈnept | ɪˈnept | অদক্ষ | clumsy, unfit | adept, skilled | An inept repair made it worse. | একটি অদক্ষ মেরামত আরও খারাপ করে।',
    'inert | adj | ɪˈnɜːt | ɪˈnɜːrt | নিষ্ক্রিয় | inactive, sluggish | active, lively | The gas is chemically inert. | গ্যাস রাসায়নিকভাবে নিষ্ক্রিয়।',
    'inevitable | adj | ɪnˈevɪtəbl | ɪnˈevɪtəbl | অনিবার্য | unavoidable, certain | avoidable, uncertain | Change is inevitable. | পরিবর্তন অনিবার্য।',
    'inexorable | adj | ɪnˈeksərəbl | ɪnˈeksərəbl | অনমনীয় | relentless, unyielding | flexible, merciful | Time is an inexorable judge. | সময় একটি অনমনীয় বিচারক।',
    'infamous | adj | ˈɪnfəməs | ˈɪnfəməs | কুখ্যাত | notorious, disgraceful | famous, honourable | An infamous cheat was caught. | এক কুখ্যাত প্রতারক ধরা পড়ে।',
    'infant | n | ˈɪnfənt | ˈɪnfənt | শিশু | baby, toddler | adult, elder | An infant slept in the basket. | একটি শিশু ঝুড়িতে ঘুমায়।',
    'infer | v | ɪnˈfɜː | ɪnˈfɜːr | অনুমান করা | deduce, conclude | guess blindly | From the mud we infer rain. | কাদা থেকে আমরা বৃষ্টি অনুমান করি।',
    'infest | v | ɪnˈfest | ɪnˈfest | উপদ্রব করা | overrun, plague | clear, cleanse | Rats infest the old mill. | ইঁদুর পুরনো কল উপদ্রব করে।',
    'infiltrate | v | ˈɪnfɪltreɪt | ˈɪnfɪlˌtreɪt | অনুপ্রবেশ করা | penetrate, sneak | withdraw, leave | Spies try to infiltrate the camp. | গুপ্তচররা শিবিরে অনুপ্রবেশ করার চেষ্টা করে।',
    'infinite | adj | ˈɪnfɪnət | ˈɪnfɪnət | অসীম | boundless, endless | finite, limited | The sky looked infinite. | আকাশ অসীম মনে হয়।',
    'infirm | adj | ɪnˈfɜːm | ɪnˈfɜːrm | দুর্বল | weak, frail | strong, healthy | An infirm elder sat by the fire. | এক দুর্বল বয়স্ক ব্যক্তি আগুনের পাশে বসেন।',
    'inflame | v | ɪnˈfleɪm | ɪnˈfleɪm | উত্তেজিত করা | provoke, incite | soothe, calm | Harsh words inflame the crowd. | কঠোর কথা ভিড়কে উত্তেজিত করে।',
    'inflate | v | ɪnˈfleɪt | ɪnˈfleɪt | ফোলানো | swell, expand | deflate, shrink | Do not inflate the claim. | দাবি ফোলাবেন না।',
    'inflexible | adj | ɪnˈfleksəbl | ɪnˈfleksəbl | অনমনীয় | rigid, stubborn | flexible, yielding | An inflexible rule angered staff. | একটি অনমনীয় নিয়ম কর্মীদের রাগায়।',
    'inflict | v | ɪnˈflɪkt | ɪnˈflɪkt | চাপিয়ে দেওয়া | impose, deal | spare, withhold | Do not inflict extra work. | অতিরিক্ত কাজ চাপিয়ে দেবেন না।',
    'influence | n | ˈɪnfluəns | ˈɪnfluəns | প্রভাব | sway, impact | impotence, weakness | Teachers have great influence. | শিক্ষকদের বড় প্রভাব আছে।',
    'inform | v | ɪnˈfɔːm | ɪnˈfɔːrm | জানানো | tell, notify | hide, conceal | Please inform the class. | ক্লাসকে জানান।',
    'infuriate | v | ɪnˈfjʊərieɪt | ɪnˈfjʊriˌeɪt | ক্ষিপ্ত করা | enrage, incense | soothe, please | Delay will infuriate the crowd. | দেরি ভিড়কে ক্ষিপ্ত করবে।',
    'ingenious | adj | ɪnˈdʒiːniəs | ɪnˈdʒiːniəs | চতুর উদ্ভাবনী | clever, inventive | clumsy, dull | An ingenious plan saved water. | একটি চতুর উদ্ভাবনী পরিকল্পনা পানি বাঁচায়।',
    'ingenuous | adj | ɪnˈdʒenjuəs | ɪnˈdʒenjuəs | সরল | naive, frank | cunning, sly | An ingenuous child told the truth. | এক সরল শিশু সত্য বলে।',
    'ingrained | adj | ɪnˈɡreɪnd | ɪnˈɡreɪnd | গেঁথে যাওয়া | deep-rooted, fixed | superficial, new | An ingrained habit is hard to break. | একটি গেঁথে যাওয়া অভ্যাস ভাঙা কঠিন।',
    'ingredient | n | ɪnˈɡriːdiənt | ɪnˈɡriːdiənt | উপাদান | component, element | whole, mixture | Salt is an ingredient of the curry. | লবণ তরকারির একটি উপাদান।',
    'inhabit | v | ɪnˈhæbɪt | ɪnˈhæbɪt | বাস করা | live, dwell | vacate, leave | Birds inhabit the old tree. | পাখি পুরনো গাছে বাস করে।',
    'inherent | adj | ɪnˈherənt | ɪnˈherənt | সহজাত | innate, natural | acquired, added | Risk is inherent in the climb. | আরোহণে ঝুঁকি সহজাত।',
    'inherit | v | ɪnˈherɪt | ɪnˈherɪt | উত্তরাধিকার পাওয়া | receive, succeed | forfeit, lose | She will inherit the land. | তিনি জমি উত্তরাধিকার পাবেন।',
    'inhibit | v | ɪnˈhɪbɪt | ɪnˈhɪbɪt | বাধা দেওয়া | restrain, hinder | encourage, free | Fear can inhibit speech. | ভয় কথা বলায় বাধা দিতে পারে।',
    'inimical | adj | ɪˈnɪmɪkl | ɪˈnɪmɪkl | শত্রুভাবাপন্ন | hostile, harmful | friendly, helpful | Drought is inimical to rice. | খরা ধানের জন্য শত্রুভাবাপন্ন।',
    'initiate | v | ɪˈnɪʃieɪt | ɪˈnɪʃiˌeɪt | শুরু করা | begin, start | end, finish | They initiate the project in June. | তারা জুনে প্রকল্প শুরু করে।',
    'inject | v | ɪnˈdʒekt | ɪnˈdʒekt | সূচি দেওয়া | insert, introduce | extract, remove | Nurses inject the vaccine. | নার্সরা টিকা সূচি দেন।',
    'injunction | n | ɪnˈdʒʌŋkʃn | ɪnˈdʒʌŋkʃn | নিষেধাজ্ঞা | order, ban | permission, leave | The court issued an injunction. | আদালত একটি নিষেধাজ্ঞা জারি করে।',
    'injure | v | ˈɪndʒə | ˈɪndʒər | আহত করা | hurt, harm | heal, help | Do not injure the bird. | পাখি আহত করবেন না।',
    'innate | adj | ɪˈneɪt | ɪˈneɪt | সহজাত | inborn, natural | learned, acquired | She has an innate gift for song. | তার গানে সহজাত দান আছে।',
    'innocuous | adj | ɪˈnɒkjuəs | ɪˈnɑːkjuəs | নিরীহ | harmless, safe | harmful, toxic | The remark was innocuous. | মন্তব্যটি নিরীহ ছিল।',
    'innovate | v | ˈɪnəveɪt | ˈɪnəˌveɪt | নতুন কিছু করা | invent, pioneer | copy, stagnate | Firms must innovate to survive. | টিকে থাকতে প্রতিষ্ঠানগুলোকে নতুন কিছু করতে হয়।',
    'innumerable | adj | ɪˈnjuːmərəbl | ɪˈnuːmərəbl | অসংখ্য | countless, myriad | few, scarce | Innumerable stars filled the sky. | অসংখ্য তারা আকাশ ভরে দেয়।',
    'inoculate | v | ɪˈnɒkjuleɪt | ɪˈnɑːkjəˌleɪt | টিকা দেওয়া | vaccinate, immunize | infect, expose | Clinics inoculate the children. | ক্লিনিকগুলো শিশুদের টিকা দেয়।',
    'inordinate | adj | ɪˈnɔːdɪnət | ɪˈnɔːrdɪnət | অতিরিক্ত | excessive, undue | moderate, reasonable | An inordinate delay closed the shop. | একটি অতিরিক্ত দেরি দোকান বন্ধ করে।',
    'inquire | v | ɪnˈkwaɪə | ɪnˈkwaɪər | অনুসন্ধান করা | ask, investigate | ignore, assume | Please inquire at the desk. | ডেস্কে অনুসন্ধান করুন।',
    'inscribe | v | ɪnˈskraɪb | ɪnˈskraɪb | খোদাই করা | engrave, write | erase, omit | They inscribe the names on stone. | তারা পাথরে নাম খোদাই করে।',
    'inscrutable | adj | ɪnˈskruːtəbl | ɪnˈskruːtəbl | দুর্বোধ্য | mysterious, opaque | clear, open | An inscrutable look hid the plan. | একটি দুর্বোধ্য চাহনি পরিকল্পনা ঢাকে।',
    'insidious | adj | ɪnˈsɪdiəs | ɪnˈsɪdiəs | কুটিল | stealthy, treacherous | overt, honest | An insidious rumour spread. | একটি কুটিল গুজব ছড়ায়।',
    'insight | n | ˈɪnsaɪt | ˈɪnsaɪt | অন্তর্দৃষ্টি | understanding, perception | ignorance, blindness | The essay showed real insight. | রচনায় আসল অন্তর্দৃষ্টি ফুটে ওঠে।',
    'insinuate | v | ɪnˈsɪnjueɪt | ɪnˈsɪnjuˌeɪt | ইঙ্গিতে বলা | hint, imply | state, declare | Do not insinuate without proof. | প্রমাণ ছাড়া ইঙ্গিতে বলবেন না।',
    'insipid | adj | ɪnˈsɪpɪd | ɪnˈsɪpɪd | স্বাদহীন | bland, dull | tasty, lively | The soup tasted insipid. | স্যুপ স্বাদহীন লাগে।',
    'insolent | adj | ˈɪnsələnt | ˈɪnsələnt | উদ্ধত | rude, cheeky | polite, respectful | An insolent reply ended the talk. | একটি উদ্ধত উত্তর আলোচনা শেষ করে।',
    'inspect | v | ɪnˈspekt | ɪnˈspekt | পরিদর্শন করা | examine, check | ignore, neglect | Officers inspect the school. | কর্মকর্তারা স্কুল পরিদর্শন করেন।',
    'inspire | v | ɪnˈspaɪə | ɪnˈspaɪər | অনুপ্রাণিত করা | motivate, stir | discourage, dull | Good teachers inspire the class. | ভালো শিক্ষক ক্লাসকে অনুপ্রাণিত করেন।',
    'install | v | ɪnˈstɔːl | ɪnˈstɔːl | স্থাপন করা | fit, set up | remove, uninstall | Please install the new lamp. | নতুন বাতি স্থাপন করুন।',
    'instigate | v | ˈɪnstɪɡeɪt | ˈɪnstɪˌɡeɪt | উস্কানি দেওয়া | provoke, incite | deter, prevent | Do not instigate a fight. | মারামারিতে উস্কানি দেবেন না।',
    'instil | v | ɪnˈstɪl | ɪnˈstɪl | গেঁথে দেওয়া | implant, infuse | extract, erase | Parents instil good manners. | অভিভাবকরা ভালো আচরণ গেঁথে দেন।',
    'institute | v | ˈɪnstɪtjuːt | ˈɪnstɪˌtuːt | চালু করা | establish, start | abolish, end | They institute a new rule. | তারা একটি নতুন নিয়ম চালু করে।',
    'instruct | v | ɪnˈstrʌkt | ɪnˈstrʌkt | নির্দেশ দেওয়া | teach, order | confuse, mislead | Please instruct the class. | ক্লাসকে নির্দেশ দিন।',
    'insulate | v | ˈɪnsjuleɪt | ˈɪnsəˌleɪt | বিচ্ছিন্ন রাখা | isolate, protect | expose, connect | Foam will insulate the roof. | ফোম ছাদ বিচ্ছিন্ন রাখবে।',
    'insult | v | ɪnˈsʌlt | ɪnˈsʌlt | অপমান করা | offend, slight | compliment, praise | Do not insult a guest. | অতিথিকে অপমান করবেন না।',
    'insurgent | n | ɪnˈsɜːdʒənt | ɪnˈsɜːrdʒənt | বিদ্রোহী | rebel, revolutionary | loyalist, supporter | An insurgent crossed the river. | এক বিদ্রোহী নদী পার হয়।',
    'intact | adj | ɪnˈtækt | ɪnˈtækt | অক্ষত | whole, unbroken | damaged, broken | The seal remained intact. | সিল অক্ষত থাকে।',
    'intangible | adj | ɪnˈtændʒəbl | ɪnˈtændʒəbl | অস্পর্শনীয় | abstract, immaterial | tangible, solid | Trust is an intangible asset. | বিশ্বাস একটি অস্পর্শনীয় সম্পদ।',
    'integral | adj | ˈɪntɪɡrəl | ˈɪntɪɡrəl | অপরিহার্য অংশ | essential, central | extra, optional | Grammar is integral to writing. | ব্যাকরণ লেখার অপরিহার্য অংশ।',
    'integrate | v | ˈɪntɪɡreɪt | ˈɪntɪˌɡreɪt | একীভূত করা | combine, merge | separate, split | Schools integrate the two courses. | স্কুল দুই কোর্স একীভূত করে।',
    'integrity | n | ɪnˈteɡrəti | ɪnˈteɡrəti | সততা | honesty, honour | corruption, deceit | Integrity matters more than marks. | সততা নম্বরের চেয়ে বেশি দরকার।',
    'intellect | n | ˈɪntəlekt | ˈɪntəlekt | বুদ্ধি | mind, reason | instinct, emotion | The puzzle tested her intellect. | ধাঁধা তার বুদ্ধি পরীক্ষা করে।',
    'intend | v | ɪnˈtend | ɪnˈtend | ইচ্ছা করা | mean, plan | forget, neglect | I intend to finish today. | আমি আজ শেষ করতে ইচ্ছা করি।',
    'intensify | v | ɪnˈtensɪfaɪ | ɪnˈtensəˌfaɪ | তীব্র করা | heighten, increase | ease, lessen | Rain will intensify at night. | রাতে বৃষ্টি তীব্র হবে।',
    'intent | n | ɪnˈtent | ɪnˈtent | উদ্দেশ্য | purpose, aim | accident, chance | The intent of the law is clear. | আইনের উদ্দেশ্য স্পষ্ট।',
    'interact | v | ˌɪntərˈækt | ˌɪntərˈækt | মেলামেশা করা | communicate, engage | isolate, withdraw | Students interact after class. | শিক্ষার্থীরা ক্লাসের পর মেলামেশা করে।',
    'intercept | v | ˌɪntəˈsept | ˌɪntərˈsept | বাধা দিয়ে ধরা | stop, seize | miss, allow | Police intercept the van. | পুলিশ ভ্যান বাধা দিয়ে ধরে।',
    'interdict | v | ˌɪntəˈdɪkt | ˌɪntərˈdɪkt | নিষেধ করা | ban, prohibit | permit, allow | The court will interdict the sale. | আদালত বিক্রি নিষেধ করবে।',
    'interfere | v | ˌɪntəˈfɪə | ˌɪntərˈfɪr | হস্তক্ষেপ করা | meddle, intrude | assist, help | Do not interfere in the match. | ম্যাচে হস্তক্ষেপ করবেন না।',
    'interim | adj | ˈɪntərɪm | ˈɪntərɪm | অন্তর্বর্তী | temporary, provisional | permanent, final | An interim head ran the school. | এক অন্তর্বর্তী প্রধান স্কুল চালান।',
    'intermittent | adj | ˌɪntəˈmɪtənt | ˌɪntərˈmɪtənt | বিরতিযুক্ত | occasional, sporadic | constant, steady | Intermittent rain fell all day. | সারাদিন বিরতিযুক্ত বৃষ্টি পড়ে।',
    'internal | adj | ɪnˈtɜːnl | ɪnˈtɜːrnl | অভ্যন্তরীণ | inner, inside | external, outer | The injury is internal. | চোট অভ্যন্তরীণ।',
    'interpret | v | ɪnˈtɜːprɪt | ɪnˈtɜːrprɪt | ব্যাখ্যা করা | explain, construe | misread, distort | Please interpret the poem. | কবিতা ব্যাখ্যা করুন।',
    'interrogate | v | ɪnˈterəɡeɪt | ɪnˈterəˌɡeɪt | জেরা করা | question, grill | answer, ignore | Police interrogate the suspect. | পুলিশ সন্দেহভাজনকে জেরা করে।',
    'interrupt | v | ˌɪntəˈrʌpt | ˌɪntəˈrʌpt | বাধা দেওয়া | break, cut in | continue, allow | Do not interrupt the speaker. | বক্তাকে বাধা দেবেন না।',
    'intervene | v | ˌɪntəˈviːn | ˌɪntərˈviːn | হস্তক্ষেপ করা | step in, mediate | withdraw, ignore | Teachers intervene in the quarrel. | শিক্ষকরা ঝগড়ায় হস্তক্ষেপ করেন।',
    'intimate | adj | ˈɪntɪmət | ˈɪntɪmət | ঘনিষ্ঠ | close, familiar | distant, formal | They share an intimate friendship. | তাদের ঘনিষ্ঠ বন্ধুত্ব আছে।',
    'intimidate | v | ɪnˈtɪmɪdeɪt | ɪnˈtɪməˌdeɪt | ভয় দেখানো | frighten, bully | reassure, encourage | Do not intimidate the witness. | সাক্ষীকে ভয় দেখাবেন না।',
    'intolerable | adj | ɪnˈtɒlərəbl | ɪnˈtɑːlərəbl | অসহ্য | unbearable, unendurable | tolerable, mild | The heat was intolerable. | গরম অসহ্য ছিল।',
    'intoxicate | v | ɪnˈtɒksɪkeɪt | ɪnˈtɑːksɪˌkeɪt | মাতাল করা | inebriate, excite | sober, calm | Victory can intoxicate a crowd. | জয় ভিড়কে মাতাল করতে পারে।',
    'intractable | adj | ɪnˈtræktəbl | ɪnˈtræktəbl | দুর্দমনীয় | stubborn, unmanageable | tractable, easy | An intractable fever worried them. | একটি দুর্দমনীয় জ্বর তাদের চিন্তায় ফেলে।',
    'intransigent | adj | ɪnˈtrænsɪdʒənt | ɪnˈtrænzədʒənt | অনমনীয় | unyielding, stubborn | flexible, yielding | An intransigent stance ended the talk. | একটি অনমনীয় অবস্থান আলোচনা শেষ করে।',
    'intrepid | adj | ɪnˈtrepɪd | ɪnˈtrepɪd | নির্ভীক | brave, fearless | timid, cowardly | An intrepid climber reached the peak. | এক নির্ভীক আরোহী চূড়ায় পৌঁছান।',
    'intricate | adj | ˈɪntrɪkət | ˈɪntrɪkət | জটিল | complex, elaborate | simple, plain | An intricate pattern filled the cloth. | একটি জটিল নকশা কাপড় ভরে দেয়।',
    'intrigue | n | ˈɪntriːɡ | ɪnˈtriːɡ | ষড়যন্ত্র | plot, scheme | honesty, openness | Court intrigue filled the novel. | উপন্যাস দরবারি ষড়যন্ত্রে ভরে।',
    'intrinsic | adj | ɪnˈtrɪnsɪk | ɪnˈtrɪnsɪk | অন্তর্নিহিত | inherent, essential | extrinsic, added | Honesty has intrinsic worth. | সততার অন্তর্নিহিত মূল্য আছে।',
    'introduce | v | ˌɪntrəˈdjuːs | ˌɪntrəˈduːs | পরিচয় করানো | present, launch | withdraw, omit | Please introduce the guest. | অতিথির পরিচয় করান।',
    'intrude | v | ɪnˈtruːd | ɪnˈtruːd | অনধিকার প্রবেশ করা | encroach, trespass | withdraw, respect | Do not intrude on the class. | ক্লাসে অনধিকার প্রবেশ করবেন না।',
    'intuition | n | ˌɪntjuˈɪʃn | ˌɪntuˈɪʃn | অন্তর্জ্ঞান | instinct, hunch | reason, proof | Trust your intuition here. | এখানে আপনার অন্তর্জ্ঞানকে বিশ্বাস করুন।',
    'inundate | v | ˈɪnʌndeɪt | ˈɪnʌnˌdeɪt | প্লাবিত করা | flood, overwhelm | drain, dry | Rain will inundate the field. | বৃষ্টি মাঠ প্লাবিত করবে।',
    'inure | v | ɪˈnjʊə | ɪˈnʊr | অভ্যস্ত করা | harden, accustom | soften, shock | Hard work will inure you to heat. | কঠোর পরিশ্রম আপনাকে গরমে অভ্যস্ত করবে।',
    'invade | v | ɪnˈveɪd | ɪnˈveɪd | আক্রমণ করা | attack, occupy | withdraw, defend | Armies invade at dawn. | সেনা ভোরে আক্রমণ করে।',
    'invalid | adj | ɪnˈvælɪd | ɪnˈvælɪd | অবৈধ | void, null | valid, legal | The ticket is invalid now. | টিকিট এখন অবৈধ।',
    'invaluable | adj | ɪnˈvæljuəbl | ɪnˈvæljuəbl | অমূল্য | priceless, precious | worthless, cheap | Her advice was invaluable. | তার পরামর্শ অমূল্য ছিল।',
    'invariable | adj | ɪnˈveəriəbl | ɪnˈveriəbl | অপরিবর্তনীয় | constant, fixed | variable, changing | His route is invariable. | তার পথ অপরিবর্তনীয়।',
    'invasion | n | ɪnˈveɪʒn | ɪnˈveɪʒn | আক্রমণ | assault, occupation | withdrawal, retreat | An invasion crossed the river. | একটি আক্রমণ নদী পার হয়।',
    'invective | n | ɪnˈvektɪv | ɪnˈvektɪv | গালিগালাজ | abuse, vituperation | praise, compliment | Cut the invective from the letter. | চিঠি থেকে গালিগালাজ কাটুন।',
    'inveigh | v | ɪnˈveɪ | ɪnˈveɪ | তীব্র নিন্দা করা | rail, denounce | praise, defend | Editors inveigh against delay. | সম্পাদকরা দেরির তীব্র নিন্দা করেন।',
    'invent | v | ɪnˈvent | ɪnˈvent | উদ্ভাবন করা | create, devise | copy, imitate | She will invent a new game. | তিনি একটি নতুন খেলা উদ্ভাবন করবেন।',
    'inventory | n | ˈɪnvəntri | ˈɪnvəntɔːri | মালতালিকা | stock, list | - | Check the inventory tonight. | আজ রাতে মালতালিকা দেখুন।',
    'inverse | adj | ˌɪnˈvɜːs | ˌɪnˈvɜːrs | বিপরীত | opposite, reverse | same, identical | The inverse order confused them. | বিপরীত ক্রম তাদের বিভ্রান্ত করে।',
    'invert | v | ɪnˈvɜːt | ɪnˈvɜːrt | উল্টানো | reverse, flip | restore, right | Do not invert the bottle. | বোতল উল্টাবেন না।',
    'invest | v | ɪnˈvest | ɪnˈvest | বিনিয়োগ করা | put in, fund | withdraw, spend | They invest in the school. | তারা স্কুলে বিনিয়োগ করে।',
    'investigate | v | ɪnˈvestɪɡeɪt | ɪnˈvestɪˌɡeɪt | তদন্ত করা | examine, probe | ignore, neglect | Police investigate the theft. | পুলিশ চুরির তদন্ত করে।',
    'inveterate | adj | ɪnˈvetərət | ɪnˈvetərət | পুরনো অভ্যাসী | chronic, confirmed | occasional, new | An inveterate smoker quit at last. | এক পুরনো অভ্যাসী ধূমপায়ী শেষে ছাড়েন।',
    'invidious | adj | ɪnˈvɪdiəs | ɪnˈvɪdiəs | ঈর্ষা জাগানো | resentful, unfair | fair, kind | An invidious comparison hurt the class. | একটি ঈর্ষা জাগানো তুলনা ক্লাসকে কষ্ট দেয়।',
    'invigorate | v | ɪnˈvɪɡəreɪt | ɪnˈvɪɡəˌreɪt | সতেজ করা | refresh, energize | weaken, drain | A walk will invigorate you. | হাঁটা আপনাকে সতেজ করবে।',
    'invincible | adj | ɪnˈvɪnsəbl | ɪnˈvɪnsəbl | অপরাজেয় | unbeatable, unconquerable | weak, beatable | The side looked invincible. | দল অপরাজেয় মনে হয়।',
    'inviolable | adj | ɪnˈvaɪələbl | ɪnˈvaɪələbl | অলঙ্ঘনীয় | sacred, unbreakable | violable, weak | The oath is inviolable. | শপথ অলঙ্ঘনীয়।',
    'invisible | adj | ɪnˈvɪzəbl | ɪnˈvɪzəbl | অদৃশ্য | unseen, hidden | visible, apparent | The wire was almost invisible. | তার প্রায় অদৃশ্য ছিল।',
    'invite | v | ɪnˈvaɪt | ɪnˈvaɪt | আমন্ত্রণ করা | ask, bid | exclude, bar | Please invite the neighbours. | প্রতিবেশীদের আমন্ত্রণ করুন।',
    'invoke | v | ɪnˈvəʊk | ɪnˈvoʊk | আহ্বান করা | call, appeal | waive, ignore | Lawyers invoke the old rule. | আইনজীবীরা পুরনো নিয়ম আহ্বান করেন।',
    'involve | v | ɪnˈvɒlv | ɪnˈvɑːlv | জড়ানো | include, entail | exclude, omit | The job will involve travel. | কাজ ভ্রমণ জড়াবে।',
    'irate | adj | aɪˈreɪt | aɪˈreɪt | ক্রুদ্ধ | angry, furious | calm, pleased | An irate parent waited outside. | এক ক্রুদ্ধ অভিভাবক বাইরে অপেক্ষা করেন।',
    'iridescent | adj | ˌɪrɪˈdesnt | ˌɪrɪˈdesnt | বহুবর্ণ চকচকে | shimmering, rainbow | dull, matte | An iridescent wing caught the light. | একটি বহুবর্ণ চকচকে ডানা আলো কাড়ে।',
    'irk | v | ɜːk | ɜːrk | বিরক্ত করা | annoy, irritate | please, soothe | Delays irk the passengers. | দেরি যাত্রীদের বিরক্ত করে।',
    'ironic | adj | aɪˈrɒnɪk | aɪˈrɑːnɪk | বিদ্রূপাত্মক | sarcastic, wry | sincere, literal | An ironic smile hid the hurt. | একটি বিদ্রূপাত্মক হাসি কষ্ট ঢাকে।',
    'irrational | adj | ɪˈræʃənl | ɪˈræʃənl | অযৌক্তিক | unreasonable, illogical | rational, sensible | Fear made the choice irrational. | ভয় পছন্দকে অযৌক্তিক করে।',
    'irreconcilable | adj | ɪˌrekənˈsaɪləbl | ɪˌrekənˈsaɪləbl | অমিলনীয় | incompatible, implacable | reconcilable, friendly | The two claims are irreconcilable. | দুই দাবি অমিলনীয়।',
    'irrefutable | adj | ˌɪrɪˈfjuːtəbl | ˌɪrɪˈfjuːtəbl | অকাট্য | undeniable, conclusive | doubtful, weak | The proof is irrefutable. | প্রমাণ অকাট্য।',
    'irrelevant | adj | ɪˈreləvənt | ɪˈreləvənt | অপ্রাসঙ্গিক | unrelated, beside the point | relevant, germane | Cut the irrelevant detail. | অপ্রাসঙ্গিক বিস্তারিত কাটুন।',
    'irreparable | adj | ɪˈrepərəbl | ɪˈrepərəbl | অপূরণীয় | irreversible, hopeless | repairable, slight | The damage looks irreparable. | ক্ষতি অপূরণীয় মনে হয়।',
    'irreproachable | adj | ˌɪrɪˈprəʊtʃəbl | ˌɪrɪˈproʊtʃəbl | নিন্দার অযোগ্য | blameless, faultless | blameworthy, faulty | Her conduct was irreproachable. | তার আচরণ নিন্দার অযোগ্য ছিল।',
    'irresolute | adj | ɪˈrezəluːt | ɪˈrezəˌluːt | দ্বিধাগ্রস্ত | hesitant, indecisive | resolute, firm | An irresolute vote delayed the plan. | একটি দ্বিধাগ্রস্ত ভোট পরিকল্পনা দেরি করায়।',
    'irreverent | adj | ɪˈrevərənt | ɪˈrevərənt | অশ্রদ্ধাপূর্ণ | disrespectful, cheeky | respectful, pious | An irreverent joke shocked the hall. | একটি অশ্রদ্ধাপূর্ণ রসিকতা হল নাড়ায়।',
    'irrigate | v | ˈɪrɪɡeɪt | ˈɪrɪˌɡeɪt | সেচ দেওয়া | water, flood | drain, dry | Canals irrigate the fields. | খাল মাঠে সেচ দেয়।',
    'irritate | v | ˈɪrɪteɪt | ˈɪrɪˌteɪt | বিরক্ত করা | annoy, provoke | soothe, please | Noise can irritate the class. | শব্দ ক্লাসকে বিরক্ত করতে পারে।',
    'isolate | v | ˈaɪsəleɪt | ˈaɪsəˌleɪt | বিচ্ছিন্ন করা | separate, sequester | include, join | Doctors isolate the patient. | চিকিৎসকরা রোগীকে বিচ্ছিন্ন করেন।',
    'issue | n | ˈɪʃuː | ˈɪʃuː | বিষয় | matter, problem | solution, answer | Land is the main issue. | জমি প্রধান বিষয়।',
    'itemize | v | ˈaɪtəmaɪz | ˈaɪtəˌmaɪz | তালিকা করা | list, detail | summarize, lump | Please itemize the costs. | খরচ তালিকা করুন।',
    'itinerant | adj | aɪˈtɪnərənt | aɪˈtɪnərənt | ভ্রাম্যমাণ | wandering, travelling | settled, fixed | An itinerant trader visited the fair. | এক ভ্রাম্যমাণ ব্যবসায়ী মেলায় আসেন।',
  ],
};
