import { type IRawSaifursGroup } from './schema';

export const WORDS_D: IRawSaifursGroup = {
  letter: 'D',
  entries: [
    'daunt | v | dɔːnt | dɔːnt | ভয় দেখানো | discourage, intimidate | encourage, hearten | The climb did not daunt them. | আরোহণ তাদের ভয় দেখায়নি।',
    'dawdle | v | ˈdɔːdl | ˈdɔːdl | গড়িমসি করা | linger, loiter | hurry, rush | Do not dawdle on the way. | পথে গড়িমসি করবেন না।',
    'dearth | n | dɜːθ | dɜːrθ | অভাব | shortage, scarcity | surplus, plenty | There is a dearth of rain. | বৃষ্টির অভাব আছে।',
    'debacle | n | deɪˈbɑːkl | dɪˈbɑːkl | চরম ব্যর্থতা | fiasco, disaster | success, triumph | The match ended in a debacle. | ম্যাচ চরম ব্যর্থতায় শেষ হয়।',
    'debase | v | dɪˈbeɪs | dɪˈbeɪs | অবনমিত করা | degrade, cheapen | elevate, honour | Lies debase public life. | মিথ্যা জনজীবন অবনমিত করে।',
    'debilitate | v | dɪˈbɪlɪteɪt | dɪˈbɪləˌteɪt | দুর্বল করা | weaken, sap | strengthen, fortify | Fever will debilitate the patient. | জ্বর রোগীকে দুর্বল করবে।',
    'debris | n | ˈdebriː | dəˈbriː | ধ্বংসাবশেষ | wreckage, rubble | - | Storm debris blocked the road. | ঝড়ের ধ্বংসাবশেষ রাস্তা আটকায়।',
    'decade | n | ˈdekeɪd | ˈdekeɪd | দশক | ten years | - | A decade of work paid off. | এক দশকের কাজ ফল দেয়।',
    'decimate | v | ˈdesɪmeɪt | ˈdesəˌmeɪt | ব্যাপক ধ্বংস করা | destroy, ravage | spare, protect | Disease can decimate a flock. | রোগ পাল ব্যাপক ধ্বংস করতে পারে।',
    'decipher | v | dɪˈsaɪfə | dɪˈsaɪfər | পাঠোদ্ধার করা | decode, interpret | encode, confuse | Can you decipher this note? | আপনি কি এই নোট পাঠোদ্ধার করতে পারেন?',
    'decisive | adj | dɪˈsaɪsɪv | dɪˈsaɪsɪv | নির্ণায়ক | conclusive, firm | hesitant, weak | A decisive goal won the cup. | একটি নির্ণায়ক গোল কাপ জেতে।',
    'declaim | v | dɪˈkleɪm | dɪˈkleɪm | জোরালোভাবে বলা | orate, proclaim | mutter, whisper | Poets declaim their lines on stage. | কবিরা মঞ্চে পঙ্ক্তি জোরালোভাবে বলেন।',
    'decline | v | dɪˈklaɪn | dɪˈklaɪn | প্রত্যাখ্যান করা | refuse, reject | accept, agree | She will decline the invitation. | তিনি নিমন্ত্রণ প্রত্যাখ্যান করবেন।',
    'decorum | n | dɪˈkɔːrəm | dɪˈkɔːrəm | শিষ্টাচার | propriety, etiquette | rudeness, disorder | Keep decorum in the hall. | হলে শিষ্টাচার রাখুন।',
    'decree | n | dɪˈkriː | dɪˈkriː | ডিক্রি | order, edict | request, plea | A royal decree closed the gates. | একটি রাজকীয় ডিক্রি ফটক বন্ধ করে।',
    'decry | v | dɪˈkraɪ | dɪˈkraɪ | নিন্দা করা | condemn, denounce | praise, applaud | Editors decry the delay. | সম্পাদকরা দেরির নিন্দা করেন।',
    'deduce | v | dɪˈdjuːs | dɪˈduːs | অনুমান করে বের করা | infer, conclude | guess blindly | From the mud we deduce rain. | কাদা থেকে আমরা বৃষ্টি অনুমান করে বের করি।',
    'defame | v | dɪˈfeɪm | dɪˈfeɪm | মানহানি করা | slander, smear | praise, honour | Do not defame a rival. | প্রতিদ্বন্দ্বীর মানহানি করবেন না।',
    'defer | v | dɪˈfɜː | dɪˈfɜːr | স্থগিত করা | postpone, delay | advance, hasten | They defer the vote until May. | তারা মে পর্যন্ত ভোট স্থগিত করে।',
    'defiant | adj | dɪˈfaɪənt | dɪˈfaɪənt | অবাধ্য | rebellious, bold | obedient, meek | A defiant look met the order. | আদেশের মুখে একটি অবাধ্য চাহনি ওঠে।',
    'deficient | adj | dɪˈfɪʃnt | dɪˈfɪʃnt | অভাবযুক্ত | lacking, inadequate | sufficient, ample | The soil is deficient in iron. | মাটিতে লোহার অভাবযুক্ত।',
    'defile | v | dɪˈfaɪl | dɪˈfaɪl | অপবিত্র করা | pollute, taint | purify, cleanse | Do not defile the river. | নদী অপবিত্র করবেন না।',
    'definitive | adj | dɪˈfɪnətɪv | dɪˈfɪnətɪv | চূড়ান্ত | conclusive, final | tentative, vague | This is the definitive edition. | এটি চূড়ান্ত সংস্করণ।',
    'deflect | v | dɪˈflekt | dɪˈflekt | সরিয়ে দেওয়া | divert, turn | attract, receive | A shield can deflect the blow. | ঢাল আঘাত সরিয়ে দিতে পারে।',
    'deft | adj | deft | deft | নিপুণ | skilful, adroit | clumsy, awkward | A deft pass opened the defence. | একটি নিপুণ পাস প্রতিরক্ষা খুলে দেয়।',
    'defunct | adj | dɪˈfʌŋkt | dɪˈfʌŋkt | বিলুপ্ত | extinct, dead | active, living | The mill is now defunct. | কলটি এখন বিলুপ্ত।',
    'degrade | v | dɪˈɡreɪd | dɪˈɡreɪd | অবনমিত করা | demean, lower | elevate, honour | Poverty can degrade a life. | দারিদ্র্য জীবন অবনমিত করতে পারে।',
    'dehydrate | v | ˌdiːhaɪˈdreɪt | diːˈhaɪˌdreɪt | শুকিয়ে ফেলা | dry, parch | hydrate, moisten | Heat will dehydrate the soil. | গরম মাটি শুকিয়ে ফেলবে।',
    'deign | v | deɪn | deɪn | অনুগ্রহ করে করা | condescend, stoop | refuse, snub | He did not deign to reply. | তিনি উত্তর দিতে অনুগ্রহ করেননি।',
    'dejected | adj | dɪˈdʒektɪd | dɪˈdʒektɪd | বিষণ্ণ | downcast, sad | cheerful, elated | The team looked dejected. | দল বিষণ্ণ দেখায়।',
    'deleterious | adj | ˌdeləˈtɪəriəs | ˌdeləˈtɪriəs | ক্ষতিকর | harmful, injurious | beneficial, helpful | Smoke is deleterious to lungs. | ধোঁয়া ফুসফুসের জন্য ক্ষতিকর।',
    'deliberate | adj | dɪˈlɪbərət | dɪˈlɪbərət | ইচ্ছাকৃত | intentional, planned | accidental, hasty | It was a deliberate foul. | এটি একটি ইচ্ছাকৃত ফাউল ছিল।',
    'delineate | v | dɪˈlɪnieɪt | dɪˈlɪniˌeɪt | স্পষ্ট করে আঁকা | outline, depict | blur, obscure | Maps delineate the border. | মানচিত্র সীমানা স্পষ্ট করে আঁকে।',
    'delude | v | dɪˈluːd | dɪˈluːd | বিভ্রান্ত করা | deceive, mislead | enlighten, inform | Do not delude yourself. | নিজেকে বিভ্রান্ত করবেন না।',
    'deluge | n | ˈdeljuːdʒ | ˈdeljuːdʒ | মহাপ্লাবন | flood, torrent | drought, trickle | A deluge washed the road. | একটি মহাপ্লাবন রাস্তা ভাসিয়ে দেয়।',
    'demean | v | dɪˈmiːn | dɪˈmiːn | ছোট করা | degrade, humble | honour, exalt | Do not demean honest labour. | সৎ শ্রম ছোট করবেন না।',
    'demise | n | dɪˈmaɪz | dɪˈmaɪz | মৃত্যু | death, end | birth, start | The factory’s demise cost jobs. | কারখানার মৃত্যু চাকরি কাড়ে।',
    'demolish | v | dɪˈmɒlɪʃ | dɪˈmɑːlɪʃ | ভেঙে ফেলা | destroy, raze | build, erect | Crews will demolish the shed. | কর্মীরা শেড ভেঙে ফেলবে।',
    'demure | adj | dɪˈmjʊə | dɪˈmjʊr | লাজুক শান্ত | modest, reserved | bold, brash | A demure smile greeted the guest. | একটি লাজুক শান্ত হাসি অতিথিকে স্বাগত জানায়।',
    'denounce | v | dɪˈnaʊns | dɪˈnaʊns | প্রকাশ্যে নিন্দা করা | condemn, accuse | praise, defend | Leaders denounce the crime. | নেতারা অপরাধ প্রকাশ্যে নিন্দা করেন।',
    'depict | v | dɪˈpɪkt | dɪˈpɪkt | চিত্রিত করা | portray, show | hide, conceal | The mural will depict the river. | ম্যুরাল নদী চিত্রিত করবে।',
    'deplete | v | dɪˈpliːt | dɪˈpliːt | নিঃশেষ করা | exhaust, drain | replenish, fill | Overuse will deplete the well. | অতিরিক্ত ব্যবহার কূপ নিঃশেষ করবে।',
    'deplore | v | dɪˈplɔː | dɪˈplɔːr | গভীর দুঃখ প্রকাশ করা | lament, regret | applaud, welcome | We deplore the delay. | আমরা দেরিতে গভীর দুঃখ প্রকাশ করি।',
    'deploy | v | dɪˈplɔɪ | dɪˈplɔɪ | মোতায়েন করা | station, position | withdraw, recall | The army will deploy at dawn. | সেনা ভোরে মোতায়েন করবে।',
    'deprecate | v | ˈdeprəkeɪt | ˈdeprəˌkeɪt | আপত্তি জানানো | disapprove, criticise | praise, endorse | Elders deprecate rude speech. | বয়োজ্যেষ্ঠরা রূঢ় কথায় আপত্তি জানান।',
    'deride | v | dɪˈraɪd | dɪˈraɪd | উপহাস করা | mock, ridicule | praise, respect | Do not deride a beginner. | নবীনকে উপহাস করবেন না।',
    'derive | v | dɪˈraɪv | dɪˈraɪv | উদ্ভূত হওয়া | obtain, stem | lose, forfeit | Many words derive from Latin. | অনেক শব্দ লাতিন থেকে উদ্ভূত হয়।',
    'derogatory | adj | dɪˈrɒɡətri | dɪˈrɑːɡətɔːri | অবমাননাকর | insulting, disparaging | complimentary, kind | Avoid derogatory remarks. | অবমাননাকর মন্তব্য এড়ান।',
    'desolate | adj | ˈdesələt | ˈdesələt | নির্জন | barren, deserted | crowded, lively | The beach looked desolate at dusk. | সন্ধ্যায় সমুদ্রতীর নির্জন দেখায়।',
    'despicable | adj | dɪˈspɪkəbl | dɪˈspɪkəbl | ঘৃণ্য | vile, contemptible | admirable, noble | Cheating is a despicable act. | নকল একটি ঘৃণ্য কাজ।',
    'despise | v | dɪˈspaɪz | dɪˈspaɪz | ঘৃণা করা | hate, scorn | admire, love | They despise cruelty. | তারা নিষ্ঠুরতা ঘৃণা করে।',
    'despondent | adj | dɪˈspɒndənt | dɪˈspɑːndənt | হতাশ | hopeless, dejected | hopeful, cheerful | She felt despondent after the fail. | ফেলের পর তিনি হতাশ বোধ করেন।',
    'destitute | adj | ˈdestɪtjuːt | ˈdestɪˌtuːt | নিঃস্ব | penniless, poor | wealthy, affluent | The flood left families destitute. | বন্যা পরিবারগুলোকে নিঃস্ব করে।',
    'deter | v | dɪˈtɜː | dɪˈtɜːr | নিরুৎসাহিত করা | discourage, prevent | encourage, invite | Fines deter late payment. | জরিমানা দেরিতে পরিশোধ নিরুৎসাহিত করে।',
    'detest | v | dɪˈtest | dɪˈtest | তীব্র ঘৃণা করা | hate, loathe | love, adore | I detest wasted food. | আমি নষ্ট খাবার তীব্র ঘৃণা করি।',
    'detract | v | dɪˈtrækt | dɪˈtrækt | কমিয়ে দেখানো | diminish, lessen | enhance, add | Noise can detract from the talk. | শব্দ আলোচনাকে কমিয়ে দেখাতে পারে।',
    'detrimental | adj | ˌdetrɪˈmentl | ˌdetrɪˈmentl | ক্ষতিকর | harmful, damaging | beneficial, helpful | Smoke is detrimental to health. | ধোঁয়া স্বাস্থ্যের জন্য ক্ষতিকর।',
    'deviate | v | ˈdiːvieɪt | ˈdiːviˌeɪt | সরে যাওয়া | diverge, stray | follow, stick | Do not deviate from the path. | পথ থেকে সরে যাবেন না।',
    'devoid | adj | dɪˈvɔɪd | dɪˈvɔɪd | শূন্য | empty, lacking | full, filled | The room was devoid of chairs. | ঘর চেয়ারশূন্য ছিল।',
    'devote | v | dɪˈvəʊt | dɪˈvoʊt | উৎসর্গ করা | dedicate, commit | withhold, spare | She will devote an hour to reading. | তিনি পড়ায় এক ঘণ্টা উৎসর্গ করবেন।',
    'devour | v | dɪˈvaʊə | dɪˈvaʊər | গোগ্রাসে খাওয়া | consume, gobble | nibble, save | Wolves devour the leftover meat. | নেকড়ে অবশিষ্ট মাংস গোগ্রাসে খায়।',
    'dexterous | adj | ˈdekstrəs | ˈdekstrəs | দক্ষহস্ত | skilful, adroit | clumsy, awkward | A dexterous cook chopped fast. | এক দক্ষহস্ত রাঁধুনি দ্রুত কাটেন।',
    'diabolic | adj | ˌdaɪəˈbɒlɪk | ˌdaɪəˈbɑːlɪk | শয়তানি | evil, wicked | angelic, kind | A diabolic plot was uncovered. | একটি শয়তানি ষড়যন্ত্র উন্মোচিত হয়।',
    'dictate | v | dɪkˈteɪt | ˈdɪkteɪt | নির্দেশ দেওয়া | command, order | request, ask | Do not dictate every step. | প্রতিটি ধাপ নির্দেশ দেবেন না।',
    'didactic | adj | daɪˈdæktɪk | daɪˈdæktɪk | শিক্ষামূলক | instructive, preachy | entertaining, amusing | The tale is too didactic. | গল্পটি খুব শিক্ষামূলক।',
    'diffident | adj | ˈdɪfɪdənt | ˈdɪfɪdənt | আত্মবিশ্বাসহীন | shy, timid | confident, bold | A diffident speaker whispered. | এক আত্মবিশ্বাসহীন বক্তা ফিসফিস করেন।',
    'diffuse | adj | dɪˈfjuːs | dɪˈfjuːs | ছড়ানো | scattered, wordy | concise, focused | The essay was too diffuse. | রচনা খুব ছড়ানো ছিল।',
    'digress | v | daɪˈɡres | daɪˈɡres | প্রসঙ্গচ্যুত হওয়া | wander, stray | focus, stick | Do not digress in the exam. | পরীক্ষায় প্রসঙ্গচ্যুত হবেন না।',
    'dilapidated | adj | dɪˈlæpɪdeɪtɪd | dɪˈlæpɪˌdeɪtɪd | জীর্ণ | ruined, ramshackle | new, sound | A dilapidated hut stood by the field. | মাঠের পাশে একটি জীর্ণ কুঁড়ে দাঁড়িয়ে ছিল।',
    'dilate | v | daɪˈleɪt | daɪˈleɪt | প্রসারিত হওয়া | expand, widen | contract, shrink | Pupils dilate in the dark. | অন্ধকারে মণি প্রসারিত হয়।',
    'diligent | adj | ˈdɪlɪdʒənt | ˈdɪlɪdʒənt | পরিশ্রমী | hardworking, assiduous | lazy, idle | A diligent pupil finished first. | এক পরিশ্রমী ছাত্র প্রথমে শেষ করেন।',
    'dilute | v | daɪˈluːt | daɪˈluːt | পাতলা করা | thin, weaken | concentrate, strengthen | Water will dilute the juice. | পানি রস পাতলা করবে।',
    'diminish | v | dɪˈmɪnɪʃ | dɪˈmɪnɪʃ | কমে যাওয়া | lessen, reduce | increase, grow | Savings diminish each month. | সঞ্চয় প্রতি মাসে কমে যায়।',
    'din | n | dɪn | dɪn | গোলমাল | noise, clamour | silence, hush | A din rose from the market. | বাজার থেকে গোলমাল ওঠে।',
    'dire | adj | ˈdaɪə | daɪr | ভয়াবহ | terrible, urgent | mild, slight | The village faced dire need. | গ্রাম ভয়াবহ অভাবে পড়ে।',
    'discern | v | dɪˈsɜːn | dɪˈsɜːrn | বুঝতে পারা | perceive, detect | miss, overlook | Can you discern the difference? | আপনি কি পার্থক্য বুঝতে পারেন?',
    'disclose | v | dɪsˈkləʊz | dɪsˈkloʊz | প্রকাশ করা | reveal, unveil | hide, conceal | Do not disclose the password. | পাসওয়ার্ড প্রকাশ করবেন না।',
    'discord | n | ˈdɪskɔːd | ˈdɪskɔːrd | মতবিরোধ | conflict, strife | harmony, accord | Discord split the committee. | মতবিরোধ কমিটিকে ভাগ করে।',
    'discreet | adj | dɪˈskriːt | dɪˈskriːt | বিচক্ষণ | tactful, prudent | indiscreet, rash | Be discreet with the news. | খবর নিয়ে বিচক্ষণ থাকুন।',
    'discrepancy | n | dɪˈskrepənsi | dɪˈskrepənsi | অমিল | difference, mismatch | agreement, match | A discrepancy in the totals appeared. | মোটের মধ্যে একটি অমিল দেখা যায়।',
    'discrete | adj | dɪˈskriːt | dɪˈskriːt | পৃথক | separate, distinct | continuous, joined | Treat each case as discrete. | প্রতিটি মামলা পৃথক হিসেবে ধরুন।',
    'disdain | n | dɪsˈdeɪn | dɪsˈdeɪn | অবজ্ঞা | scorn, contempt | respect, regard | She looked at the lie with disdain. | তিনি মিথ্যার দিকে অবজ্ঞায় তাকান।',
    'disgruntled | adj | dɪsˈɡrʌntld | dɪsˈɡrʌntld | অসন্তুষ্ট | dissatisfied, annoyed | content, pleased | Disgruntled fans left early. | অসন্তুষ্ট ভক্তরা তাড়াতাড়ি চলে যায়।',
    'dismal | adj | ˈdɪzməl | ˈdɪzməl | বিষণ্ণ | gloomy, dreary | bright, cheerful | A dismal sky hung over the town. | একটি বিষণ্ণ আকাশ শহরের উপর ঝুলে ছিল।',
    'dismay | n | dɪsˈmeɪ | dɪsˈmeɪ | হতাশা | alarm, distress | delight, joy | The news filled them with dismay. | খবর তাদের হতাশায় ভরে দেয়।',
    'disparage | v | dɪˈspærɪdʒ | dɪˈspærɪdʒ | ছোট করে বলা | belittle, denigrate | praise, commend | Do not disparage honest work. | সৎ কাজ ছোট করে বলবেন না।',
    'disparate | adj | ˈdɪspərət | ˈdɪspərət | ভিন্নধর্মী | different, unlike | similar, alike | Two disparate ideas met in the essay. | দুই ভিন্নধর্মী ধারণা রচনায় মেশে।',
    'dispel | v | dɪˈspel | dɪˈspel | দূর করা | banish, scatter | gather, invite | Facts dispel the rumour. | তথ্য গুজব দূর করে।',
    'dispense | v | dɪˈspens | dɪˈspens | বিতরণ করা | distribute, give | withhold, keep | Nurses dispense the medicine. | নার্সরা ওষুধ বিতরণ করেন।',
    'disperse | v | dɪˈspɜːs | dɪˈspɜːrs | ছড়িয়ে দেওয়া | scatter, spread | gather, collect | Police asked the crowd to disperse. | পুলিশ ভিড়কে ছড়িয়ে যেতে বলে।',
    'dispose | v | dɪˈspəʊz | dɪˈspoʊz | সরিয়ে ফেলা | discard, arrange | keep, retain | Please dispose of the waste. | বর্জ্য সরিয়ে ফেলুন।',
    'dispute | n | dɪˈspjuːt | dɪˈspjuːt | বিবাদ | argument, quarrel | agreement, peace | A land dispute reached the court. | একটি জমি বিবাদ আদালতে পৌঁছায়।',
    'disrupt | v | dɪsˈrʌpt | dɪsˈrʌpt | ব্যাহত করা | interrupt, upset | assist, aid | Noise can disrupt the exam. | শব্দ পরীক্ষা ব্যাহত করতে পারে।',
    'disseminate | v | dɪˈsemɪneɪt | dɪˈseməˌneɪt | ছড়িয়ে দেওয়া | spread, circulate | withhold, hide | Schools disseminate the notice. | স্কুলগুলো নোটিশ ছড়িয়ে দেয়।',
    'dissent | n | dɪˈsent | dɪˈsent | ভিন্নমত | disagreement, protest | consent, accord | One vote of dissent was recorded. | একটি ভিন্নমতের ভোট নথিভুক্ত হয়।',
    'dissolve | v | dɪˈzɒlv | dɪˈzɑːlv | গলে যাওয়া | melt, disband | solidify, form | Salt will dissolve in water. | লবণ পানিতে গলে যাবে।',
    'dissuade | v | dɪˈsweɪd | dɪˈsweɪd | নিবৃত্ত করা | deter, discourage | persuade, urge | Friends dissuade him from leaving. | বন্ধুরা তাকে যাওয়া থেকে নিবৃত্ত করে।',
    'distinct | adj | dɪˈstɪŋkt | dɪˈstɪŋkt | স্পষ্ট পৃথক | clear, separate | vague, similar | Each voice was distinct. | প্রতিটি কণ্ঠ স্পষ্ট পৃথক ছিল।',
    'distort | v | dɪˈstɔːt | dɪˈstɔːrt | বিকৃত করা | twist, warp | straighten, clarify | Heat can distort the plastic. | গরম প্লাস্টিক বিকৃত করতে পারে।',
    'distract | v | dɪˈstrækt | dɪˈstrækt | মনোযোগ কাড়ানো | divert, sidetrack | focus, concentrate | Phones distract the class. | ফোন ক্লাসের মনোযোগ কাড়ে।',
    'distraught | adj | dɪˈstrɔːt | dɪˈstrɔːt | উদ্বিগ্ন | frantic, upset | calm, composed | A distraught parent waited outside. | এক উদ্বিগ্ন অভিভাবক বাইরে অপেক্ষা করেন।',
    'diurnal | adj | daɪˈɜːnl | daɪˈɜːrnl | দিনের | daytime, daily | nocturnal, nightly | Many birds are diurnal. | অনেক পাখি দিনের।',
    'diverge | v | daɪˈvɜːdʒ | daɪˈvɜːrdʒ | আলাদা হয়ে যাওয়া | separate, split | converge, meet | The paths diverge at the oak. | পথগুলো ওকগাছে আলাদা হয়ে যায়।',
    'diverse | adj | daɪˈvɜːs | daɪˈvɜːrs | বৈচিত্র্যময় | varied, mixed | uniform, same | A diverse crowd filled the hall. | একটি বৈচিত্র্যময় ভিড় হল ভরে দেয়।',
    'divulge | v | daɪˈvʌldʒ | daɪˈvʌldʒ | ফাঁস করা | reveal, disclose | hide, conceal | Do not divulge the secret. | গোপন কথা ফাঁস করবেন না।',
    'docile | adj | ˈdəʊsaɪl | ˈdɑːsl | বাধ্য | obedient, meek | stubborn, wild | A docile horse stood still. | একটি বাধ্য ঘোড়া স্থির দাঁড়ায়।',
    'doctrine | n | ˈdɒktrɪn | ˈdɑːktrɪn | মতবাদ | teaching, creed | heresy, dissent | The school taught one doctrine. | স্কুল একটি মতবাদ শেখায়।',
    'document | v | ˈdɒkjument | ˈdɑːkjəˌment | নথিভুক্ত করা | record, evidence | erase, hide | Please document every step. | প্রতিটি ধাপ নথিভুক্ত করুন।',
    'dogged | adj | ˈdɒɡɪd | ˈdɔːɡɪd | জেদি | persistent, stubborn | yielding, weak | Dogged practice won the prize. | জেদি অনুশীলন পুরস্কার জেতে।',
    'dogma | n | ˈdɒɡmə | ˈdɔːɡmə | মতবাদ | creed, doctrine | doubt, heresy | Question every old dogma. | প্রতিটি পুরনো মতবাদ প্রশ্ন করুন।',
    'doleful | adj | ˈdəʊlfl | ˈdoʊlfl | দুঃখপূর্ণ | mournful, sad | cheerful, glad | A doleful song filled the room. | একটি দুঃখপূর্ণ গান ঘর ভরে দেয়।',
    'domain | n | dəˈmeɪn | doʊˈmeɪn | ক্ষেত্র | field, realm | - | Maths is her main domain. | গণিত তার প্রধান ক্ষেত্র।',
    'domestic | adj | dəˈmestɪk | dəˈmestɪk | ঘরোয়া | household, home | foreign, wild | Domestic chores filled the morning. | ঘরোয়া কাজ সকাল ভরে দেয়।',
    'dominant | adj | ˈdɒmɪnənt | ˈdɑːmɪnənt | প্রধান | ruling, chief | minor, weak | English is the dominant language here. | ইংরেজি এখানে প্রধান ভাষা।',
    'donate | v | dəʊˈneɪt | ˈdoʊneɪt | দান করা | give, contribute | withhold, keep | Please donate books to the library. | গ্রন্থাগারে বই দান করুন।',
    'dormant | adj | ˈdɔːmənt | ˈdɔːrmənt | সুপ্ত | inactive, sleeping | active, awake | The volcano has long been dormant. | আগ্নেয়গিরি দীর্ঘদিন সুপ্ত।',
    'dreary | adj | ˈdrɪəri | ˈdrɪri | নিরস | dull, gloomy | bright, lively | A dreary afternoon dragged on. | একটি নিরস দুপুর টেনে চলে।',
    'drench | v | drentʃ | drentʃ | ভিজিয়ে দেওয়া | soak, saturate | dry, parch | Rain will drench the field. | বৃষ্টি মাঠ ভিজিয়ে দেবে।',
    'dubious | adj | ˈdjuːbiəs | ˈduːbiəs | সন্দেহজনক | doubtful, uncertain | certain, sure | The claim looks dubious. | দাবিটি সন্দেহজনক মনে হয়।',
    'durable | adj | ˈdjʊərəbl | ˈdʊrəbl | স্থায়ী | lasting, sturdy | fragile, weak | Buy a durable bag. | একটি স্থায়ী ব্যাগ কিনুন।',
    'dwell | v | dwel | dwel | বাস করা | live, reside | leave, depart | Many families dwell by the river. | অনেক পরিবার নদীর ধারে বাস করে।',
    'dwindle | v | ˈdwɪndl | ˈdwɪndl | কমে যাওয়া | shrink, decline | grow, increase | Savings dwindle each week. | সঞ্চয় প্রতি সপ্তাহে কমে যায়।',
  ],
};
