import { type IRawSaifursGroup } from './schema';

export const WORDS_F: IRawSaifursGroup = {
  letter: 'F',
  entries: [
    'fabricate | v | ˈfæbrɪkeɪt | ˈfæbrɪˌkeɪt | জালিয়াতি করে বানানো | invent, forge | verify, prove | Do not fabricate an excuse. | অজুহাত জালিয়াতি করে বানাবেন না।',
    'facetious | adj | fəˈsiːʃəs | fəˈsiːʃəs | রসিক | flippant, witty | serious, solemn | A facetious remark spoiled the mood. | একটি রসিক মন্তব্য মেজাজ নষ্ট করে।',
    'facile | adj | ˈfæsaɪl | ˈfæsl | সহজসাধ্য | easy, glib | difficult, laboured | A facile answer ignored the facts. | একটি সহজসাধ্য উত্তর তথ্য উপেক্ষা করে।',
    'facilitate | v | fəˈsɪlɪteɪt | fəˈsɪləˌteɪt | সহজ করা | ease, help | hinder, obstruct | Maps facilitate the journey. | মানচিত্র যাত্রা সহজ করে।',
    'faction | n | ˈfækʃn | ˈfækʃn | উপদল | clique, camp | unity, whole | A faction split the party. | একটি উপদল দল ভাগ করে।',
    'fallacy | n | ˈfæləsi | ˈfæləsi | ভ্রান্তি | error, myth | truth, fact | That claim is a fallacy. | সেই দাবি একটি ভ্রান্তি।',
    'fallible | adj | ˈfæləbl | ˈfæləbl | ভুল করতে পারে এমন | imperfect, erring | infallible, perfect | Every judge is fallible. | প্রতিটি বিচারক ভুল করতে পারেন।',
    'falter | v | ˈfɔːltə | ˈfɔːltər | হোঁচট খাওয়া | stumble, hesitate | proceed, continue | Do not falter at the last step. | শেষ ধাপে হোঁচট খাবেন না।',
    'famine | n | ˈfæmɪn | ˈfæmɪn | দুর্ভিক্ষ | starvation, scarcity | plenty, surplus | Drought brought famine. | খরা দুর্ভিক্ষ আনে।',
    'fanatic | n | fəˈnætɪk | fəˈnætɪk | উন্মাদ অনুরাগী | zealot, extremist | moderate, sceptic | A fanatic ignored every fact. | এক উন্মাদ অনুরাগী সব তথ্য উপেক্ষা করেন।',
    'fastidious | adj | fæˈstɪdiəs | fæˈstɪdiəs | খুঁতখুঁতে | fussy, particular | sloppy, easy | A fastidious editor checked twice. | এক খুঁতখুঁতে সম্পাদক দুবার দেখেন।',
    'feasible | adj | ˈfiːzəbl | ˈfiːzəbl | সম্ভব | possible, practicable | impossible, unworkable | The plan looks feasible. | পরিকল্পনা সম্ভব মনে হয়।',
    'feign | v | feɪn | feɪn | ভান করা | pretend, fake | reveal, show | Do not feign illness. | অসুখের ভান করবেন না।',
    'felicity | n | fəˈlɪsəti | fəˈlɪsəti | সুখ | happiness, bliss | misery, sorrow | Marriage brought them felicity. | বিয়ে তাদের সুখ আনে।',
    'ferocious | adj | fəˈrəʊʃəs | fəˈroʊʃəs | ভয়ংকর | fierce, savage | gentle, mild | A ferocious storm hit the coast. | একটি ভয়ংকর ঝড় উপকূলে আঘাত করে।',
    'fervent | adj | ˈfɜːvnt | ˈfɜːrvnt | উত্তপ্ত উৎসাহী | ardent, passionate | cool, indifferent | A fervent crowd filled the square. | একটি উত্তপ্ত উৎসাহী ভিড় চত্বর ভরে দেয়।',
    'fickle | adj | ˈfɪkl | ˈfɪkl | চঞ্চল | changeable, inconstant | loyal, steady | Fickle weather spoiled the picnic. | চঞ্চল আবহাওয়া পিকনিক নষ্ট করে।',
    'fidelity | n | fɪˈdeləti | fɪˈdeləti | বিশ্বস্ততা | loyalty, faithfulness | betrayal, treachery | Soldiers swore fidelity to the flag. | সৈন্যরা পতাকার প্রতি বিশ্বস্ততার শপথ নেয়।',
    'figurative | adj | ˈfɪɡərətɪv | ˈfɪɡjərətɪv | রূপক | metaphorical, symbolic | literal, plain | The poet used figurative language. | কবি রূপক ভাষা ব্যবহার করেন।',
    'filial | adj | ˈfɪliəl | ˈfɪliəl | সন্তানের যোগ্য | dutiful, devoted | undutiful, rebellious | Filial care kept her home. | সন্তানের যোগ্য সেবা তাকে ঘরে রাখে।',
    'finale | n | fɪˈnɑːli | fɪˈnæli | সমাপ্তি | ending, close | opening, start | The finale drew a huge crowd. | সমাপ্তি বিশাল ভিড় টানে।',
    'finesse | n | fɪˈnes | fɪˈnes | নিপুণতা | skill, tact | clumsiness, bluntness | She handled the quarrel with finesse. | তিনি ঝগড়া নিপুণতায় সামলান।',
    'flagrant | adj | ˈfleɪɡrənt | ˈfleɪɡrənt | প্রকাশ্য জঘন্য | blatant, glaring | subtle, hidden | A flagrant foul ended the match. | একটি প্রকাশ্য জঘন্য ফাউল ম্যাচ শেষ করে।',
    'flamboyant | adj | flæmˈbɔɪənt | flæmˈbɔɪənt | চমকপ্রদ | showy, colourful | modest, plain | A flamboyant hat caught every eye. | একটি চমকপ্রদ টুপি সব চোখ কাড়ে।',
    'fledgling | n | ˈfledʒlɪŋ | ˈfledʒlɪŋ | নবীন | beginner, novice | veteran, expert | A fledgling writer joined the club. | এক নবীন লেখক ক্লাবে যোগ দেন।',
    'flourish | v | ˈflʌrɪʃ | ˈflɜːrɪʃ | সমৃদ্ধ হওয়া | thrive, prosper | wither, fail | Trade will flourish after the rain. | বৃষ্টির পর বাণিজ্য সমৃদ্ধ হবে।',
    'fluctuate | v | ˈflʌktʃueɪt | ˈflʌktʃuˌeɪt | ওঠানামা করা | vary, oscillate | steady, settle | Prices fluctuate each week. | দাম প্রতি সপ্তাহে ওঠানামা করে।',
    'fluent | adj | ˈfluːənt | ˈfluːənt | সাবলীল | flowing, articulate | hesitant, broken | She is fluent in Bangla. | তিনি বাংলায় সাবলীল।',
    'foible | n | ˈfɔɪbl | ˈfɔɪbl | ছোট দোষ | weakness, quirk | virtue, strength | We all have a foible. | আমাদের সবার একটি ছোট দোষ আছে।',
    'forage | v | ˈfɒrɪdʒ | ˈfɔːrɪdʒ | খাবার খোঁজা | search, scavenge | ignore, rest | Goats forage along the bank. | ছাগল তীর ধরে খাবার খোঁজে।',
    'forbear | v | fɔːˈbeə | fɔːrˈber | ধৈর্য ধরা | refrain, restrain | lash out, yield | Please forbear from shouting. | চিৎকার থেকে ধৈর্য ধরুন।',
    'foreboding | n | fɔːˈbəʊdɪŋ | fɔːrˈboʊdɪŋ | অশুভ আশঙ্কা | omen, dread | hope, cheer | A dark sky filled them with foreboding. | কালো আকাশ তাদের অশুভ আশঙ্কায় ভরে দেয়।',
    'forfeit | v | ˈfɔːfɪt | ˈfɔːrfət | হারানো | lose, surrender | keep, retain | Late teams forfeit the match. | দেরি করা দল ম্যাচ হারায়।',
    'forlorn | adj | fəˈlɔːn | fərˈlɔːrn | নিরাশ একাকী | abandoned, desolate | cheerful, hopeful | A forlorn hut stood in the field. | মাঠে একটি নিরাশ একাকী কুঁড়ে দাঁড়িয়ে ছিল।',
    'formidable | adj | fəˈmɪdəbl | ˈfɔːrmɪdəbl | ভয়ংকর শক্তিশালী | daunting, impressive | weak, slight | A formidable rival waited. | এক ভয়ংকর শক্তিশালী প্রতিদ্বন্দ্বী অপেক্ষা করে।',
    'forsake | v | fəˈseɪk | fərˈseɪk | পরিত্যাগ করা | abandon, desert | keep, stay | Do not forsake a friend. | বন্ধু পরিত্যাগ করবেন না।',
    'fortify | v | ˈfɔːtɪfaɪ | ˈfɔːrtɪˌfaɪ | শক্তিশালী করা | strengthen, reinforce | weaken, undermine | Walls fortify the town. | দেয়াল শহর শক্তিশালী করে।',
    'fortuitous | adj | fɔːˈtjuːɪtəs | fɔːrˈtuːɪtəs | দৈবক্রমে | accidental, lucky | planned, intended | A fortuitous meeting saved the day. | একটি দৈবক্রমে দেখা দিন বাঁচায়।',
    'foster | v | ˈfɒstə | ˈfɑːstər | লালন করা | encourage, nurture | hinder, neglect | Schools foster reading. | স্কুল পড়া লালন করে।',
    'fractious | adj | ˈfrækʃəs | ˈfrækʃəs | খিটখিটে | irritable, quarrelsome | calm, agreeable | A fractious child spoiled the ride. | এক খিটখিটে শিশু যাত্রা নষ্ট করে।',
    'fragile | adj | ˈfrædʒaɪl | ˈfrædʒl | ভঙ্গুর | delicate, breakable | sturdy, tough | Handle the glass; it is fragile. | কাচ সামলান; এটি ভঙ্গুর।',
    'fragment | n | ˈfræɡmənt | ˈfræɡmənt | খণ্ড | piece, shard | whole, entirety | A fragment of pottery lay in the dust. | ধুলোয় মৃতপাত্রের একটি খণ্ড পড়ে ছিল।',
    'frantic | adj | ˈfræntɪk | ˈfræntɪk | উন্মত্ত | wild, desperate | calm, composed | A frantic search filled the yard. | একটি উন্মত্ত খোঁজ উঠান ভরে দেয়।',
    'fraudulent | adj | ˈfrɔːdjələnt | ˈfrɔːdʒələnt | প্রতারণামূলক | dishonest, fake | honest, genuine | A fraudulent claim was rejected. | একটি প্রতারণামূলক দাবি খারিজ হয়।',
    'frivolous | adj | ˈfrɪvələs | ˈfrɪvələs | তুচ্ছ | trivial, silly | serious, solemn | Do not waste time on frivolous talk. | তুচ্ছ কথায় সময় নষ্ট করবেন না।',
    'frugal | adj | ˈfruːɡl | ˈfruːɡl | মিতব্যয়ী | thrifty, sparing | wasteful, lavish | A frugal meal fed the family. | একটি মিতব্যয়ী খাবার পরিবারকে খাওয়ায়।',
    'frustrate | v | frʌˈstreɪt | ˈfrʌstreɪt | ব্যর্থ করা | thwart, foil | help, aid | Rain can frustrate the plan. | বৃষ্টি পরিকল্পনা ব্যর্থ করতে পারে।',
    'fugitive | n | ˈfjuːdʒətɪv | ˈfjuːdʒətɪv | পলাতক | runaway, escapee | captive, resident | Police sought the fugitive. | পুলিশ পলাতককে খোঁজে।',
    'fulsome | adj | ˈfʊlsəm | ˈfʊlsəm | অতিরিক্ত তোষামোদপূর্ণ | excessive, insincere | sincere, modest | Fulsome praise embarrassed her. | অতিরিক্ত তোষামোদপূর্ণ প্রশংসা তাকে লজ্জায় ফেলে।',
    'furtive | adj | ˈfɜːtɪv | ˈfɜːrtɪv | চুপিসারে | secret, stealthy | open, overt | A furtive glance crossed the room. | একটি চুপিসারে চাহনি ঘর পার হয়।',
    'futile | adj | ˈfjuːtaɪl | ˈfjuːtl | বৃথা | useless, vain | useful, effective | Further argument was futile. | আরও তর্ক বৃথা ছিল।',
  ],
};

export const WORDS_G: IRawSaifursGroup = {
  letter: 'G',
  entries: [
    'gainsay | v | ˌɡeɪnˈseɪ | ˌɡeɪnˈseɪ | অস্বীকার করা | deny, contradict | admit, confirm | None could gainsay the record. | কেউ নথি অস্বীকার করতে পারেনি।',
    'gallant | adj | ˈɡælənt | ˈɡælənt | বীর | brave, chivalrous | cowardly, rude | A gallant rescue saved the child. | একটি বীর উদ্ধার শিশুকে বাঁচায়।',
    'galvanize | v | ˈɡælvənaɪz | ˈɡælvəˌnaɪz | উদ্বুদ্ধ করা | spur, stir | dull, lull | The speech will galvanize the crowd. | বক্তৃতা ভিড়কে উদ্বুদ্ধ করবে।',
    'garbled | adj | ˈɡɑːbld | ˈɡɑːrbld | বিকৃত | confused, distorted | clear, accurate | A garbled message reached us. | একটি বিকৃত বার্তা আমাদের কাছে পৌঁছায়।',
    'garish | adj | ˈɡeərɪʃ | ˈɡerɪʃ | চেঁচামেচি রঙিন | gaudy, loud | tasteful, muted | A garish sign spoiled the street. | একটি চেঁচামেচি রঙিন সাইন রাস্তা নষ্ট করে।',
    'garnish | v | ˈɡɑːnɪʃ | ˈɡɑːrnɪʃ | সাজানো | decorate, adorn | strip, bare | Coriander will garnish the curry. | ধনেপাতা তরকারি সাজাবে।',
    'garrulous | adj | ˈɡærələs | ˈɡærələs | বাচাল | talkative, loquacious | taciturn, quiet | A garrulous neighbour stopped us. | এক বাচাল প্রতিবেশী আমাদের আটকান।',
    'gaunt | adj | ɡɔːnt | ɡɔːnt | শীর্ণ | lean, haggard | plump, healthy | A gaunt face showed the fever. | একটি শীর্ণ মুখ জ্বর দেখায়।',
    'genial | adj | ˈdʒiːniəl | ˈdʒiːniəl | হাসিখুশি | friendly, cheerful | cold, hostile | A genial host opened the door. | এক হাসিখুশি আয়োজক দরজা খোলেন।',
    'genre | n | ˈʒɒnrə | ˈʒɑːnrə | ধরন | type, category | - | Mystery is her favourite genre. | রহস্য তার প্রিয় ধরন।',
    'germane | adj | dʒɜːˈmeɪn | dʒɜːrˈmeɪn | প্রাসঙ্গিক | relevant, pertinent | irrelevant, odd | Keep the remark germane. | মন্তব্য প্রাসঙ্গিক রাখুন।',
    'ghastly | adj | ˈɡɑːstli | ˈɡæstli | ভয়ংকর | horrible, grim | pleasant, lovely | A ghastly accident closed the road. | একটি ভয়ংকর দুর্ঘটনা রাস্তা বন্ধ করে।',
    'gist | n | dʒɪst | dʒɪst | সারকথা | essence, point | detail, padding | Give me the gist of the talk. | আলোচনার সারকথা বলুন।',
    'glacial | adj | ˈɡleɪʃl | ˈɡleɪʃl | বরফশীতল | icy, freezing | warm, mild | A glacial wind crossed the field. | একটি বরফশীতল হাওয়া মাঠ পার হয়।',
    'glaring | adj | ˈɡleərɪŋ | ˈɡlerɪŋ | চোখে পড়ে এমন | obvious, blatant | subtle, hidden | A glaring error spoiled the page. | একটি চোখে পড়ে এমন ভুল পাতা নষ্ট করে।',
    'glib | adj | ɡlɪb | ɡlɪb | তড়বড়ে | slick, fluent | hesitant, thoughtful | A glib answer hid the truth. | একটি তড়বড়ে উত্তর সত্য ঢাকে।',
    'glutton | n | ˈɡlʌtn | ˈɡlʌtn | পেটুক | overeater, gourmand | ascetic, abstainer | A glutton finished the feast. | এক পেটুক ভোজ শেষ করেন।',
    'goad | v | ɡəʊd | ɡoʊd | খোঁচা দেওয়া | prod, provoke | soothe, deter | Do not goad the crowd. | ভিড়কে খোঁচা দেবেন না।',
    'gratuitous | adj | ɡrəˈtjuːɪtəs | ɡrəˈtuːɪtəs | অনাবশ্যক | needless, uncalled | necessary, earned | Cut the gratuitous insult. | অনাবশ্যক অপমান কাটুন।',
    'gravity | n | ˈɡrævəti | ˈɡrævəti | গুরুত্ব | seriousness, weight | levity, lightness | The news had real gravity. | খবরের আসল গুরুত্ব ছিল।',
    'gregarious | adj | ɡrɪˈɡeəriəs | ɡrɪˈɡeriəs | দলবদ্ধ | sociable, outgoing | solitary, shy | A gregarious child joined every game. | এক দলবদ্ধ শিশু প্রতিটি খেলায় যোগ দেয়।',
    'grievance | n | ˈɡriːvns | ˈɡriːvns | অভিযোগ | complaint, grudge | satisfaction, praise | Staff filed a grievance. | কর্মীরা একটি অভিযোগ দাখিল করেন।',
    'gruesome | adj | ˈɡruːsəm | ˈɡruːsəm | বীভৎস | ghastly, horrific | pleasant, mild | A gruesome tale scared the class. | একটি বীভৎস গল্প ক্লাসকে ভয় দেখায়।',
    'guile | n | ɡaɪl | ɡaɪl | চাতুরি | cunning, deceit | honesty, candour | He won by guile, not strength. | তিনি শক্তিতে নয়, চাতুরিতে জেতেন।',
    'gullible | adj | ˈɡʌləbl | ˈɡʌləbl | সহজে ঠকে | naive, credulous | sceptical, wary | A gullible buyer paid too much. | এক সহজে ঠকে ক্রেতা বেশি দেন।',
  ],
};

export const WORDS_H: IRawSaifursGroup = {
  letter: 'H',
  entries: [
    'habituate | v | həˈbɪtʃueɪt | həˈbɪtʃuˌeɪt | অভ্যস্ত করা | accustom, inure | unsettle, shock | Travel will habituate you to change. | ভ্রমণ আপনাকে পরিবর্তনে অভ্যস্ত করবে।',
    'hackneyed | adj | ˈhæknid | ˈhæknid | গতানুগতিক | stale, trite | fresh, original | Avoid a hackneyed phrase. | গতানুগতিক বাক্যাংশ এড়ান।',
    'haggard | adj | ˈhæɡəd | ˈhæɡərd | ক্লান্ত শীর্ণ | worn, gaunt | fresh, healthy | A haggard face met the dawn. | একটি ক্লান্ত শীর্ণ মুখ ভোর দেখে।',
    'halcyon | adj | ˈhælsiən | ˈhælsiən | শান্ত সুখের | peaceful, golden | stormy, harsh | She recalled halcyon days of school. | তিনি স্কুলের শান্ত সুখের দিন মনে করেন।',
    'hamper | v | ˈhæmpə | ˈhæmpər | বাধা দেওয়া | hinder, impede | help, aid | Rain will hamper the match. | বৃষ্টি ম্যাচে বাধা দেবে।',
    'haphazard | adj | hæpˈhæzəd | hæpˈhæzərd | এলোমেলো | random, chaotic | orderly, planned | A haphazard pile filled the desk. | একটি এলোমেলো স্তূপ ডেস্ক ভরে দেয়।',
    'harangue | n | həˈræŋ | həˈræŋ | দীর্ঘ ধমক | tirade, lecture | praise, whisper | A long harangue bored the hall. | একটি দীর্ঘ ধমক হলকে বিরক্ত করে।',
    'harbinger | n | ˈhɑːbɪndʒə | ˈhɑːrbɪndʒər | পূর্বাভাস | omen, forerunner | aftermath, result | Clouds are a harbinger of rain. | মেঘ বৃষ্টির পূর্বাভাস।',
    'harmonious | adj | hɑːˈməʊniəs | hɑːrˈmoʊniəs | সুসংগত | agreeable, tuneful | discordant, harsh | A harmonious choir filled the hall. | একটি সুসংগত গায়কদল হল ভরে দেয়।',
    'haughty | adj | ˈhɔːti | ˈhɔːti | অহংকারী | arrogant, proud | humble, modest | A haughty look spoiled the talk. | একটি অহংকারী চাহনি আলোচনা নষ্ট করে।',
    'haven | n | ˈheɪvn | ˈheɪvn | আশ্রয় | refuge, shelter | danger, trap | The library is a quiet haven. | গ্রন্থাগার একটি শান্ত আশ্রয়।',
    'hazardous | adj | ˈhæzədəs | ˈhæzərdəs | বিপজ্জনক | dangerous, risky | safe, harmless | The road is hazardous at night. | রাতে রাস্তা বিপজ্জনক।',
    'hectic | adj | ˈhektɪk | ˈhektɪk | ব্যস্ত | frantic, busy | calm, leisurely | A hectic morning filled the station. | একটি ব্যস্ত সকাল স্টেশন ভরে দেয়।',
    'heed | v | hiːd | hiːd | মনোযোগ দেওয়া | regard, mind | ignore, neglect | Please heed the warning. | সতর্কবাণীতে মনোযোগ দিন।',
    'heinous | adj | ˈheɪnəs | ˈheɪnəs | জঘন্য | atrocious, odious | admirable, kind | A heinous crime shocked the town. | একটি জঘন্য অপরাধ শহর নাড়ায়।',
    'heresy | n | ˈherəsi | ˈherəsi | ধর্মদ্রোহ | dissent, unorthodoxy | orthodoxy, dogma | The claim was called heresy. | দাবিটিকে ধর্মদ্রোহ বলা হয়।',
    'hiatus | n | haɪˈeɪtəs | haɪˈeɪtəs | বিরতি | gap, pause | continuity, flow | A short hiatus followed the storm. | ঝড়ের পর একটি ছোট বিরতি আসে।',
    'hierarchy | n | ˈhaɪərɑːki | ˈhaɪəˌrɑːrki | ক্রমবিন্যাস | ranking, order | equality, chaos | A clear hierarchy ran the office. | একটি স্পষ্ট ক্রমবিন্যাস অফিস চালায়।',
    'hinder | v | ˈhɪndə | ˈhɪndər | বাধা দেওয়া | obstruct, impede | help, aid | Fog will hinder the flight. | কুয়াশা ফ্লাইটে বাধা দেবে।',
    'hoard | v | hɔːd | hɔːrd | জমিয়ে রাখা | store, stockpile | spend, share | Do not hoard the rice. | চাল জমিয়ে রাখবেন না।',
    'homogeneous | adj | ˌhɒməˈdʒiːniəs | ˌhoʊməˈdʒiːniəs | সমজাতীয় | uniform, similar | mixed, diverse | A homogeneous group is easier to teach. | একটি সমজাতীয় দলকে পড়ানো সহজ।',
    'hone | v | həʊn | hoʊn | ধারালো করা | sharpen, refine | dull, blunt | Practice will hone your skill. | অনুশীলন আপনার দক্ষতা ধারালো করবে।',
    'hostile | adj | ˈhɒstaɪl | ˈhɑːstl | শত্রুভাবাপন্ন | unfriendly, adverse | friendly, kind | A hostile crowd blocked the gate. | একটি শত্রুভাবাপন্ন ভিড় গেট আটকায়।',
    'hubris | n | ˈhjuːbrɪs | ˈhjuːbrɪs | অহংকার | arrogance, pride | humility, modesty | Hubris cost him the match. | অহংকার তাকে ম্যাচ হারায়।',
    'humiliate | v | hjuːˈmɪlieɪt | hjuːˈmɪliˌeɪt | অপমান করা | shame, degrade | honour, praise | Do not humiliate a student. | শিক্ষার্থীকে অপমান করবেন না।',
    'hybrid | n | ˈhaɪbrɪd | ˈhaɪbrɪd | সংকর | mix, cross | purebred, original | The crop is a new hybrid. | ফসলটি একটি নতুন সংকর।',
    'hyperbole | n | haɪˈpɜːbəli | haɪˈpɜːrbəli | অতিরঞ্জন | exaggeration, overstatement | understatement, fact | Avoid hyperbole in the report. | প্রতিবেদনে অতিরঞ্জন এড়ান।',
    'hypocrisy | n | hɪˈpɒkrəsi | hɪˈpɑːkrəsi | কপটতা | pretence, duplicity | sincerity, honesty | Voters hate hypocrisy. | ভোটাররা কপটতা ঘৃণা করে।',
    'hypothesis | n | haɪˈpɒθəsɪs | haɪˈpɑːθəsɪs | অনুকল্প | theory, conjecture | fact, proof | Test the hypothesis in the lab. | ল্যাবে অনুকল্প পরীক্ষা করুন।',
  ],
};
