import { type IRawSaifursGroup } from './schema';

export const WORDS_B: IRawSaifursGroup = {
  letter: 'B',
  entries: [
    'baffle | v | ˈbæfl | ˈbæfl | হতবুদ্ধি করা | bewilder, puzzle | enlighten, explain | The riddle will baffle the class. | ধাঁধাটি ক্লাসকে হতবুদ্ধি করবে।',
    'baleful | adj | ˈbeɪlfl | ˈbeɪlfl | অশুভ | menacing, harmful | kindly, benign | A baleful look silenced the room. | একটি অশুভ চাহনি ঘর নীরব করে।',
    'balk | v | bɔːk | bɔːk | পিছিয়ে যাওয়া | hesitate, refuse | proceed, accept | Horses balk at the high fence. | ঘোড়া উঁচু বেড়ায় পিছিয়ে যায়।',
    'banal | adj | bəˈnɑːl | bəˈnæl | মামুলি | trite, dull | original, fresh | The speech was banal and empty. | বক্তৃতা মামুলি ও ফাঁকা ছিল।',
    'bane | n | beɪn | beɪn | অভিশাপ | curse, ruin | blessing, boon | Debt was the bane of the farm. | ঋণ খামারের অভিশাপ ছিল।',
    'banish | v | ˈbænɪʃ | ˈbænɪʃ | নির্বাসিত করা | exile, expel | welcome, admit | The king will banish the traitor. | রাজা বিশ্বাসঘাতককে নির্বাসিত করবেন।',
    'banter | n | ˈbæntə | ˈbæntər | হাসিঠাট্টা | teasing, raillery | insult, abuse | Friendly banter filled the bus. | বন্ধুত্বপূর্ণ হাসিঠাট্টা বাস ভরে দেয়।',
    'barbaric | adj | bɑːˈbærɪk | bɑːrˈbærɪk | বর্বর | savage, cruel | civilised, humane | The punishment was barbaric. | শাস্তিটি বর্বর ছিল।',
    'bare | adj | beə | ber | উন্মুক্ত | naked, empty | covered, clothed | The trees stood bare in winter. | শীতে গাছগুলো উন্মুক্ত দাঁড়িয়ে ছিল।',
    'barricade | n | ˈbærɪkeɪd | ˈbærɪˌkeɪd | ব্যারিকেড | barrier, blockade | opening, passage | Students built a barricade of desks. | শিক্ষার্থীরা ডেস্ক দিয়ে ব্যারিকেড গড়ে।',
    'barren | adj | ˈbærən | ˈbærən | অনুর্বর | infertile, sterile | fertile, lush | Crops fail on barren soil. | অনুর্বর মাটিতে ফসল হয় না।',
    'bashful | adj | ˈbæʃfl | ˈbæʃfl | লাজুক | shy, timid | bold, confident | A bashful child hid behind her. | একটি লাজুক শিশু তার পেছনে লুকোয়।',
    'beacon | n | ˈbiːkən | ˈbiːkən | আলোকস্তম্ভ | signal, guide | - | The lighthouse was a beacon in the fog. | বাতিঘর কুয়াশায় একটি আলোকস্তম্ভ ছিল।',
    'beckon | v | ˈbekən | ˈbekən | ইশারা করা | signal, gesture | dismiss, ignore | She will beckon you to the door. | তিনি আপনাকে দরজার দিকে ইশারা করবেন।',
    'bedlam | n | ˈbedləm | ˈbedləm | হৈচৈ | chaos, uproar | order, calm | The market was bedlam at noon. | দুপুরে বাজার হৈচৈয়ে ভরে ছিল।',
    'befuddle | v | bɪˈfʌdl | bɪˈfʌdl | বিভ্রান্ত করা | confuse, muddle | clarify, enlighten | Too many rules befuddle beginners. | অতিরিক্ত নিয়ম নতুনদের বিভ্রান্ত করে।',
    'begrudge | v | bɪˈɡrʌdʒ | bɪˈɡrʌdʒ | অনিচ্ছায় দেওয়া | resent, envy | grant freely | Do not begrudge them their rest. | তাদের বিশ্রাম অনিচ্ছায় দেবেন না।',
    'beguile | v | bɪˈɡaɪl | bɪˈɡaɪl | মুগ্ধ করা | charm, deceive | bore, repel | Stories beguile the long evening. | গল্প দীর্ঘ সন্ধ্যা মুগ্ধ করে।',
    'behold | v | bɪˈhəʊld | bɪˈhoʊld | দেখা | see, view | ignore, overlook | Behold the river at sunrise. | সূর্যোদয়ে নদীটি দেখুন।',
    'belie | v | bɪˈlaɪ | bɪˈlaɪ | মিথ্যা প্রমাণ করা | contradict, disguise | confirm, reveal | His smile did belie the worry. | তার হাসি দুশ্চিন্তাকে মিথ্যা প্রমাণ করে।',
    'belittle | v | bɪˈlɪtl | bɪˈlɪtl | ছোট করা | disparage, dismiss | praise, honour | Do not belittle honest effort. | সৎ চেষ্টাকে ছোট করবেন না।',
    'belligerent | adj | bəˈlɪdʒərənt | bəˈlɪdʒərənt | যুদ্ধংদেহী | hostile, aggressive | peaceful, calm | A belligerent tone ended the talk. | একটি যুদ্ধংদেহী সুর আলোচনা শেষ করে।',
    'bellow | v | ˈbeləʊ | ˈbeloʊ | গর্জন করা | roar, shout | whisper, murmur | The ox will bellow in the yard. | বলদ উঠানে গর্জন করবে।',
    'benefactor | n | ˈbenɪfæktə | ˈbenəˌfæktər | উপকারী দাতা | patron, donor | opponent, foe | A silent benefactor paid the fees. | এক নীরব উপকারী দাতা ফি দেন।',
    'benevolent | adj | bəˈnevələnt | bəˈnevələnt | পরোপকারী | kind, generous | cruel, mean | A benevolent neighbour shared rice. | এক পরোপকারী প্রতিবেশী চাল ভাগ করেন।',
    'benign | adj | bɪˈnaɪn | bɪˈnaɪn | নিরীহ | harmless, kindly | malignant, harsh | The growth was benign. | বৃদ্ধিটি নিরীহ ছিল।',
    'bequeath | v | bɪˈkwiːð | bɪˈkwiːð | উইল করে দেওয়া | leave, will | withhold, seize | She will bequeath the land to her son. | তিনি ছেলের নামে জমি উইল করে দেবেন।',
    'berate | v | bɪˈreɪt | bɪˈreɪt | তিরস্কার করা | scold, rebuke | praise, compliment | Do not berate the child in public. | জনসমক্ষে শিশুকে তিরস্কার করবেন না।',
    'bereft | adj | bɪˈreft | bɪˈreft | বঞ্চিত | deprived, stripped | endowed, filled | He felt bereft after they left. | তারা চলে যাওয়ার পর তিনি বঞ্চিত বোধ করেন।',
    'beseech | v | bɪˈsiːtʃ | bɪˈsiːtʃ | অনুনয় করা | implore, beg | demand, command | I beseech you to wait. | আমি আপনাকে অপেক্ষা করার অনুনয় করি।',
    'besiege | v | bɪˈsiːdʒ | bɪˈsiːdʒ | অবরোধ করা | surround, blockade | free, relieve | Armies besiege the fort for months. | সেনাবাহিনী মাসব্যাপী দুর্গ অবরোধ করে।',
    'betray | v | bɪˈtreɪ | bɪˈtreɪ | বিশ্বাসঘাতকতা করা | deceive, desert | protect, support | Do not betray a friend. | বন্ধুর সঙ্গে বিশ্বাসঘাতকতা করবেন না।',
    'bewilder | v | bɪˈwɪldə | bɪˈwɪldər | হতবুদ্ধি করা | confuse, puzzle | clarify, enlighten | New maps bewilder first-year students. | নতুন মানচিত্র প্রথম বর্ষকে হতবুদ্ধি করে।',
    'bias | n | ˈbaɪəs | ˈbaɪəs | পক্ষপাত | prejudice, slant | fairness, balance | Check the article for bias. | নিবন্ধে পক্ষপাত আছে কিনা দেখুন।',
    'bicker | v | ˈbɪkə | ˈbɪkər | তুচ্ছ তর্ক করা | quarrel, squabble | agree, concur | Siblings bicker over the remote. | ভাইবোন রিমোট নিয়ে তুচ্ছ তর্ক করে।',
    'bizarre | adj | bɪˈzɑː | bɪˈzɑːr | অদ্ভুত | strange, odd | ordinary, normal | A bizarre noise woke the street. | একটি অদ্ভুত শব্দ রাস্তা জাগায়।',
    'bland | adj | blænd | blænd | স্বাদহীন | mild, dull | spicy, sharp | The soup tasted bland. | স্যুপের স্বাদহীন লাগে।',
    'blatant | adj | ˈbleɪtnt | ˈbleɪtnt | প্রকাশ্য | obvious, flagrant | subtle, hidden | A blatant lie angered the judge. | একটি প্রকাশ্য মিথ্যা বিচারককে রাগায়।',
    'bleak | adj | bliːk | bliːk | নিরাশ | grim, hopeless | bright, hopeful | The forecast looks bleak. | পূর্বাভাস নিরাশ মনে হয়।',
    'blemish | n | ˈblemɪʃ | ˈblemɪʃ | কলঙ্ক | flaw, stain | perfection, virtue | One blemish marked the fruit. | একটি কলঙ্ক ফলে দাগ ফেলে।',
    'blight | n | blaɪt | blaɪt | ক্ষতি | plague, curse | blessing, boon | Drought was a blight on the harvest. | খরা ফসলের ক্ষতি ছিল।',
    'blithe | adj | blaɪð | blaɪð | উদাসীন আনন্দিত | cheerful, carefree | gloomy, anxious | A blithe remark ignored the risk. | একটি উদাসীন আনন্দিত মন্তব্য ঝুঁকি এড়ায়।',
    'bloom | v | bluːm | bluːm | ফুটে ওঠা | flower, flourish | wither, fade | Roses bloom in March here. | এখানে মার্চে গোলাপ ফুটে ওঠে।',
    'blunder | n | ˈblʌndə | ˈblʌndər | ভুল | mistake, error | success, coup | A simple blunder cost the point. | একটি সাধারণ ভুল পয়েন্ট কাড়ে।',
    'blunt | adj | blʌnt | blʌnt | ভোঁতা | dull, frank | sharp, tactful | Use a blunt knife for butter. | মাখনের জন্য ভোঁতা ছুরি ব্যবহার করুন।',
    'boast | v | bəʊst | boʊst | দম্ভ করা | brag, crow | hide, understate | Do not boast about the prize. | পুরস্কার নিয়ে দম্ভ করবেন না।',
    'bolster | v | ˈbəʊlstə | ˈboʊlstər | শক্তিশালী করা | support, strengthen | weaken, undermine | Extra staff will bolster the ward. | অতিরিক্ত কর্মী ওয়ার্ড শক্তিশালী করবে।',
    'bombastic | adj | bɒmˈbæstɪk | bɑːmˈbæstɪk | শব্দাড়ম্বরপূর্ণ | pompous, inflated | plain, modest | A bombastic speech bored the hall. | একটি শব্দাড়ম্বরপূর্ণ বক্তৃতা হলকে বিরক্ত করে।',
    'boon | n | buːn | buːn | আশীর্বাদ | blessing, benefit | curse, bane | Rain was a boon to the fields. | বৃষ্টি মাঠের আশীর্বাদ ছিল।',
    'boorish | adj | ˈbʊərɪʃ | ˈbʊrɪʃ | অসভ্য | rude, crude | polite, refined | Boorish jokes spoiled the dinner. | অসভ্য রসিকতা রাতের খাবার নষ্ট করে।',
    'bounty | n | ˈbaʊnti | ˈbaʊnti | প্রাচুর্য | abundance, generosity | scarcity, stinginess | Autumn brings a bounty of fruit. | শরৎ ফলের প্রাচুর্য আনে।',
    'brash | adj | bræʃ | bræʃ | বেপরোয়া | rash, bold | cautious, shy | A brash driver ignored the sign. | এক বেপরোয়া চালক সাইন উপেক্ষা করেন।',
    'bravado | n | brəˈvɑːdəʊ | brəˈvɑːdoʊ | ভান করা সাহস | swagger, bluster | humility, fear | His bravado hid real fear. | তার ভান করা সাহস আসল ভয় ঢাকে।',
    'brawl | n | brɔːl | brɔːl | মারামারি | fight, scuffle | peace, truce | A street brawl woke the block. | রাস্তার মারামারি ব্লক জাগায়।',
    'brazen | adj | ˈbreɪzn | ˈbreɪzn | নির্লজ্জ | shameless, bold | modest, shy | A brazen lie fooled nobody. | একটি নির্লজ্জ মিথ্যা কাউকে বোকা করেনি।',
    'breach | n | briːtʃ | briːtʃ | লঙ্ঘন | violation, gap | observance, seal | A breach of the rule ends the match. | নিয়মের লঙ্ঘন ম্যাচ শেষ করে।',
    'brevity | n | ˈbrevəti | ˈbrevəti | সংক্ষিপ্ততা | conciseness, shortness | length, verbosity | Brevity made the letter strong. | সংক্ষিপ্ততা চিঠি শক্তিশালী করে।',
    'brisk | adj | brɪsk | brɪsk | চটপটে | lively, quick | slow, sluggish | A brisk walk clears the mind. | চটপটে হাঁটা মন পরিষ্কার করে।',
    'brittle | adj | ˈbrɪtl | ˈbrɪtl | ভঙ্গুর | fragile, breakable | tough, flexible | Dry clay is brittle. | শুকনো মাটি ভঙ্গুর।',
    'broach | v | brəʊtʃ | broʊtʃ | প্রসঙ্গ তোলা | raise, introduce | avoid, drop | Wait to broach the subject. | প্রসঙ্গ তুলতে অপেক্ষা করুন।',
    'brood | v | bruːd | bruːd | চিন্তায় ডুবে থাকা | dwell, mope | forget, cheer | Do not brood over the loss. | ক্ষতি নিয়ে চিন্তায় ডুবে থাকবেন না।',
    'browbeat | v | ˈbraʊbiːt | ˈbraʊˌbiːt | ভয় দেখিয়ে চাপ দেওয়া | intimidate, bully | encourage, soothe | Do not browbeat the witness. | সাক্ষীকে ভয় দেখিয়ে চাপ দেবেন না।',
    'brusque | adj | brʊsk | brʌsk | রূঢ় সংক্ষিপ্ত | abrupt, curt | polite, gentle | A brusque reply ended the call. | একটি রূঢ় সংক্ষিপ্ত উত্তর কল শেষ করে।',
    'bucolic | adj | bjuːˈkɒlɪk | bjuːˈkɑːlɪk | গ্রাম্য | rural, pastoral | urban, civic | A bucolic scene calmed the painter. | একটি গ্রাম্য দৃশ্য চিত্রকরকে শান্ত করে।',
    'buoyant | adj | ˈbɔɪənt | ˈbɔɪənt | ভাসমান | floating, cheerful | sinking, gloomy | Cork is buoyant in water. | কর্ক পানিতে ভাসমান।',
    'burgeon | v | ˈbɜːdʒən | ˈbɜːrdʒən | দ্রুত বাড়া | flourish, grow | shrink, fade | New shops burgeon along the road. | নতুন দোকান সড়কে দ্রুত বাড়ে।',
    'burnish | v | ˈbɜːnɪʃ | ˈbɜːrnɪʃ | মসৃণ করে চকচকে করা | polish, shine | tarnish, dull | Craftsmen burnish the brass. | কারিগর পিতল মসৃণ করে চকচকে করেন।',
    'bustle | n | ˈbʌsl | ˈbʌsl | ব্যস্ততা | activity, hurry | calm, stillness | Morning bustle filled the station. | সকালের ব্যস্ততা স্টেশন ভরে দেয়।',
    'buttress | v | ˈbʌtrəs | ˈbʌtrəs | মজবুত করা | support, reinforce | weaken, undermine | Facts will buttress the claim. | তথ্য দাবি মজবুত করবে।',
    'bygone | adj | ˈbaɪɡɒn | ˈbaɪˌɡɔːn | অতীত | past, former | present, current | Let bygone quarrels rest. | অতীত ঝগড়া থাকুক।',
  ],
};
