import { type IRawSaifursGroup } from './schema';

export const WORDS_C: IRawSaifursGroup = {
  letter: 'C',
  entries: [
    'cacophony | n | kəˈkɒfəni | kəˈkɑːfəni | কর্কশ শব্দ | din, discord | harmony, melody | A cacophony of horns filled the street. | হর্নের কর্কশ শব্দ রাস্তা ভরে দেয়।',
    'cajole | v | kəˈdʒəʊl | kəˈdʒoʊl | তোষামোদ করে রাজি করানো | coax, wheedle | bully, force | She tried to cajole him into coming. | তিনি তোষামোদ করে তাকে আসতে রাজি করানোর চেষ্টা করেন।',
    'calamity | n | kəˈlæməti | kəˈlæməti | বিপর্যয় | disaster, catastrophe | blessing, boon | The flood was a national calamity. | বন্যা একটি জাতীয় বিপর্যয় ছিল।',
    'callous | adj | ˈkæləs | ˈkæləs | নিষ্ঠুর | heartless, unfeeling | kind, tender | A callous remark hurt the family. | একটি নিষ্ঠুর মন্তব্য পরিবারকে কষ্ট দেয়।',
    'candid | adj | ˈkændɪd | ˈkændɪd | অকপট | frank, honest | secretive, false | Be candid about the mistake. | ভুল নিয়ে অকপট থাকুন।',
    'candour | n | ˈkændə | ˈkændər | অকপটতা | frankness, honesty | deceit, pretence | Her candour won their trust. | তার অকপটতা তাদের বিশ্বাস জেতে।',
    'canvass | v | ˈkænvəs | ˈkænvəs | ভোট চাওয়া | solicit, campaign | ignore, neglect | Volunteers canvass every street. | স্বেচ্ছাসেবক প্রতি রাস্তায় ভোট চায়।',
    'capacious | adj | kəˈpeɪʃəs | kəˈpeɪʃəs | প্রশস্ত | roomy, spacious | cramped, tiny | A capacious bag held the books. | একটি প্রশস্ত ব্যাগ বই ধরে।',
    'capitulate | v | kəˈpɪtʃuleɪt | kəˈpɪtʃəˌleɪt | আত্মসমর্পণ করা | surrender, yield | resist, fight | The fort will not capitulate. | দুর্গ আত্মসমর্পণ করবে না।',
    'capricious | adj | kəˈprɪʃəs | kəˈprɪʃəs | খেয়ালী | fickle, unpredictable | steady, constant | A capricious wind shifted the boat. | একটি খেয়ালী হাওয়া নৌকা সরায়।',
    'captivate | v | ˈkæptɪveɪt | ˈkæptɪˌveɪt | মুগ্ধ করা | charm, fascinate | bore, repel | The story will captivate children. | গল্পটি শিশুদের মুগ্ধ করবে।',
    'cardinal | adj | ˈkɑːdɪnl | ˈkɑːrdɪnl | প্রধান | chief, principal | minor, slight | Honesty is a cardinal rule here. | সততা এখানে একটি প্রধান নিয়ম।',
    'careen | v | kəˈriːn | kəˈriːn | দুলতে দুলতে ছুটে যাওয়া | lurch, swerve | steady, halt | The bus will careen around the bend. | বাস বাঁকে দুলতে দুলতে ছুটে যাবে।',
    'caricature | n | ˈkærɪkətʃʊə | ˈkærɪkətʃər | ব্যঙ্গচিত্র | parody, cartoon | portrait, likeness | The paper printed a caricature of the mayor. | পত্রিকা মেয়রের ব্যঙ্গচিত্র ছাপায়।',
    'castigate | v | ˈkæstɪɡeɪt | ˈkæstɪˌɡeɪt | কঠোর তিরস্কার করা | scold, rebuke | praise, commend | Editors castigate careless writing. | সম্পাদকরা অসতর্ক লেখাকে কঠোর তিরস্কার করেন।',
    'catalyst | n | ˈkætəlɪst | ˈkætəlɪst | অনুঘটক | spur, trigger | obstacle, brake | The speech was a catalyst for change. | বক্তৃতা পরিবর্তনের অনুঘটক ছিল।',
    'catastrophe | n | kəˈtæstrəfi | kəˈtæstrəfi | মহাবিপর্যয় | disaster, calamity | success, blessing | A fire would be a catastrophe here. | এখানে আগুন মহাবিপর্যয় হবে।',
    'categorical | adj | ˌkætəˈɡɒrɪkl | ˌkætəˈɡɔːrɪkl | নিঃশর্ত | absolute, definite | qualified, vague | He gave a categorical refusal. | তিনি একটি নিঃশর্ত প্রত্যাখ্যান দেন।',
    'caustic | adj | ˈkɔːstɪk | ˈkɑːstɪk | তীব্র কটাক্ষপূর্ণ | biting, sarcastic | mild, kind | A caustic joke silenced the table. | একটি তীব্র কটাক্ষপূর্ণ রসিকতা টেবিল নীরব করে।',
    'cautious | adj | ˈkɔːʃəs | ˈkɔːʃəs | সতর্ক | careful, wary | reckless, rash | Be cautious on the wet road. | ভেজা রাস্তায় সতর্ক থাকুন।',
    'cavity | n | ˈkævəti | ˈkævəti | গহ্বর | hole, hollow | bulge, mound | The dentist filled the cavity. | দন্তচিকিৎসক গহ্বর ভরে দেন।',
    'cease | v | siːs | siːs | থেমে যাওয়া | stop, halt | continue, persist | The rain will cease by noon. | দুপুরের মধ্যে বৃষ্টি থেমে যাবে।',
    'cede | v | siːd | siːd | ছেড়ে দেওয়া | yield, surrender | keep, retain | The club will cede the ground. | ক্লাব মাঠ ছেড়ে দেবে।',
    'censure | v | ˈsenʃə | ˈsenʃər | নিন্দা করা | criticize, blame | praise, approve | Members may censure the delay. | সদস্যরা দেরির নিন্দা করতে পারেন।',
    'cerebral | adj | ˈserəbrəl | səˈriːbrəl | বুদ্ধিবৃত্তিক | intellectual, mental | physical, instinctive | The puzzle is a cerebral game. | ধাঁধাটি একটি বুদ্ধিবৃত্তিক খেলা।',
    'chagrin | n | ˈʃæɡrɪn | ʃəˈɡrɪn | ক্ষোভ | annoyance, dismay | delight, pride | He hid his chagrin with a smile. | তিনি হাসি দিয়ে ক্ষোভ লুকান।',
    'champion | v | ˈtʃæmpiən | ˈtʃæmpiən | পক্ষে দাঁড়ানো | support, defend | oppose, attack | She will champion the workers. | তিনি শ্রমিকদের পক্ষে দাঁড়াবেন।',
    'chaos | n | ˈkeɪɒs | ˈkeɪɑːs | বিশৃঙ্খলা | disorder, turmoil | order, calm | The strike created chaos at the port. | ধর্মঘট বন্দরে বিশৃঙ্খলা তৈরি করে।',
    'charisma | n | kəˈrɪzmə | kəˈrɪzmə | আকর্ষণীয় ব্যক্তিত্ব | charm, allure | dullness, blandness | The leader had rare charisma. | নেতার দুর্লভ আকর্ষণীয় ব্যক্তিত্ব ছিল।',
    'chastise | v | tʃæˈstaɪz | tʃæˈstaɪz | শাস্তি দেওয়া | punish, scold | praise, reward | Do not chastise a child for asking. | জিজ্ঞাসার জন্য শিশুকে শাস্তি দেবেন না।',
    'chide | v | tʃaɪd | tʃaɪd | ভর্ৎসনা করা | scold, rebuke | praise, commend | Teachers chide late homework. | শিক্ষকরা দেরিতে বাড়ির কাজ ভর্ৎসনা করেন।',
    'chronic | adj | ˈkrɒnɪk | ˈkrɑːnɪk | দীর্ঘস্থায়ী | persistent, lasting | brief, acute | He has a chronic cough. | তার দীর্ঘস্থায়ী কাশি আছে।',
    'chronicle | n | ˈkrɒnɪkl | ˈkrɑːnɪkl | ধারাবিবরণী | record, history | fiction, myth | The book is a chronicle of the war. | বইটি যুদ্ধের ধারাবিবরণী।',
    'circumspect | adj | ˈsɜːkəmspekt | ˈsɜːrkəmˌspekt | সতর্ক | cautious, wary | rash, reckless | Be circumspect with strangers. | অপরিচিতদের সঙ্গে সতর্ক থাকুন।',
    'circumvent | v | ˌsɜːkəmˈvent | ˌsɜːrkəmˈvent | ফাঁকি দেওয়া | bypass, evade | face, follow | Do not circumvent the rule. | নিয়ম ফাঁকি দেবেন না।',
    'cite | v | saɪt | saɪt | উদ্ধৃত করা | quote, mention | ignore, omit | Please cite your sources. | অনুগ্রহ করে উৎস উদ্ধৃত করুন।',
    'civil | adj | ˈsɪvl | ˈsɪvl | ভদ্র | polite, courteous | rude, uncivil | Keep a civil tone in class. | ক্লাসে ভদ্র সুর রাখুন।',
    'clamour | n | ˈklæmə | ˈklæmər | হৈচৈ | uproar, din | silence, hush | A clamour rose from the yard. | উঠান থেকে হৈচৈ ওঠে।',
    'clandestine | adj | klænˈdestɪn | klænˈdestɪn | গোপন | secret, covert | open, public | They held a clandestine meeting. | তারা একটি গোপন বৈঠক করে।',
    'clarify | v | ˈklærɪfaɪ | ˈklærəˌfaɪ | পরিষ্কার করা | explain, clear | confuse, obscure | Please clarify the last point. | শেষ পয়েন্টটি পরিষ্কার করুন।',
    'clemency | n | ˈklemənsi | ˈklemənsi | ক্ষমা | mercy, leniency | severity, harshness | The prisoner asked for clemency. | বন্দি ক্ষমা চান।',
    'cliche | n | ˈkliːʃeɪ | kliːˈʃeɪ | গতানুগতিক উক্তি | platitude, truism | originality, novelty | Avoid every tired cliche in the essay. | রচনায় প্রতিটি ক্লান্ত গতানুগতিক উক্তি এড়ান।',
    'coalesce | v | ˌkəʊəˈles | ˌkoʊəˈles | একত্র হওয়া | merge, unite | split, separate | Small groups coalesce into one. | ছোট দল একত্র হয়ে একটি হয়।',
    'coerce | v | kəʊˈɜːs | koʊˈɜːrs | জোর করা | force, compel | persuade, invite | Do not coerce a confession. | স্বীকারোক্তি জোর করে আনবেন না।',
    'cogent | adj | ˈkəʊdʒənt | ˈkoʊdʒənt | যুক্তিপূর্ণ | convincing, sound | weak, feeble | She made a cogent argument. | তিনি একটি যুক্তিপূর্ণ যুক্তি দেন।',
    'cognizant | adj | ˈkɒɡnɪzənt | ˈkɑːɡnɪzənt | সচেতন | aware, mindful | unaware, oblivious | Be cognizant of the risk. | ঝুঁকি সম্পর্কে সচেতন থাকুন।',
    'coherent | adj | kəʊˈhɪərənt | koʊˈhɪrənt | সুসংগত | logical, clear | confused, rambling | Write a coherent paragraph. | একটি সুসংগত অনুচ্ছেদ লিখুন।',
    'coincide | v | ˌkəʊɪnˈsaɪd | ˌkoʊɪnˈsaɪd | মিলে যাওয়া | match, overlap | differ, clash | The two dates coincide this year. | দুই তারিখ এ বছর মিলে যায়।',
    'collaborate | v | kəˈlæbəreɪt | kəˈlæbəˌreɪt | সহযোগিতা করা | cooperate, team | compete, oppose | Classes collaborate on the mural. | ক্লাসগুলো ম্যুরালে সহযোগিতা করে।',
    'collapse | v | kəˈlæps | kəˈlæps | ধসে পড়া | fall, crumble | stand, rise | The old shed will collapse in wind. | পুরনো শেড বাতাসে ধসে পড়বে।',
    'collate | v | kəˈleɪt | kəˈleɪt | মিলিয়ে সাজানো | compile, gather | scatter, jumble | Please collate the pages in order. | পাতাগুলো ক্রমে মিলিয়ে সাজান।',
    'colloquial | adj | kəˈləʊkwiəl | kəˈloʊkwiəl | কথ্য | informal, spoken | formal, literary | Avoid colloquial words in the paper. | পত্রে কথ্য শব্দ এড়ান।',
    'collusion | n | kəˈluːʒn | kəˈluːʒn | গোপন চক্রান্ত | conspiracy, plot | honesty, openness | The firms were accused of collusion. | প্রতিষ্ঠানগুলোকে গোপন চক্রান্তের অভিযোগ করা হয়।',
    'colossal | adj | kəˈlɒsl | kəˈlɑːsl | বিশাল | huge, enormous | tiny, minute | A colossal statue faces the river. | একটি বিশাল মূর্তি নদীর দিকে তাকায়।',
    'commemorate | v | kəˈmeməreɪt | kəˈmeməˌreɪt | স্মরণ করা | honour, remember | forget, ignore | We commemorate the fallen each year. | আমরা প্রতি বছর নিহতদের স্মরণ করি।',
    'commence | v | kəˈmens | kəˈmens | শুরু করা | begin, start | end, finish | Classes commence in July. | জুলাইয়ে ক্লাস শুরু হয়।',
    'commend | v | kəˈmend | kəˈmend | প্রশংসা করা | praise, applaud | criticise, blame | Teachers commend honest work. | শিক্ষকরা সৎ কাজের প্রশংসা করেন।',
    'commiserate | v | kəˈmɪzəreɪt | kəˈmɪzəˌreɪt | সহানুভূতি জানানো | sympathize, condole | mock, gloat | Friends commiserate after the loss. | ক্ষতির পর বন্ধুরা সহানুভূতি জানায়।',
    'commodity | n | kəˈmɒdəti | kəˈmɑːdəti | পণ্য | goods, product | service, luxury | Rice is a staple commodity here. | চাল এখানে একটি প্রধান পণ্য।',
    'commotion | n | kəˈməʊʃn | kəˈmoʊʃn | হৈচৈ | uproar, stir | calm, quiet | A commotion rose in the yard. | উঠানে হৈচৈ ওঠে।',
    'compassion | n | kəmˈpæʃn | kəmˈpæʃn | করুণা | pity, kindness | cruelty, indifference | Show compassion to the injured. | আহতদের প্রতি করুণা দেখান।',
    'compatible | adj | kəmˈpætəbl | kəmˈpætəbl | সামঞ্জস্যপূর্ণ | matching, consistent | conflicting, clashing | The two plans are compatible. | দুই পরিকল্পনা সামঞ্জস্যপূর্ণ।',
    'compel | v | kəmˈpel | kəmˈpel | বাধ্য করা | force, oblige | allow, permit | Rules compel us to wait. | নিয়ম আমাদের অপেক্ষা করতে বাধ্য করে।',
    'compensate | v | ˈkɒmpenseɪt | ˈkɑːmpənˌseɪt | ক্ষতিপূরণ দেওয়া | repay, offset | withhold, penalise | The firm will compensate the loss. | প্রতিষ্ঠান ক্ষতিপূরণ দেবে।',
    'competent | adj | ˈkɒmpɪtənt | ˈkɑːmpɪtənt | যোগ্য | capable, able | inept, unfit | A competent nurse ran the ward. | এক যোগ্য নার্স ওয়ার্ড চালান।',
    'compile | v | kəmˈpaɪl | kəmˈpaɪl | সংকলন করা | collect, assemble | scatter, destroy | Please compile the scores. | স্কোরগুলো সংকলন করুন।',
    'complacent | adj | kəmˈpleɪsnt | kəmˈpleɪsnt | আত্মতুষ্ট | smug, self-satisfied | alert, uneasy | Do not grow complacent after one win. | এক জয়ের পর আত্মতুষ্ট হবেন না।',
    'complement | n | ˈkɒmplɪmənt | ˈkɑːmplɪmənt | পরিপূরক | addition, counterpart | contrast, opposite | Rice is a complement to the curry. | ভাত তরকারির পরিপূরক।',
    'compliant | adj | kəmˈplaɪənt | kəmˈplaɪənt | বাধ্য | obedient, yielding | defiant, stubborn | A compliant student followed the rule. | এক বাধ্য শিক্ষার্থী নিয়ম মেনে চলে।',
    'composure | n | kəmˈpəʊʒə | kəmˈpoʊʒər | স্থিরতা | calm, poise | panic, agitation | She kept her composure under fire. | তিনি চাপে স্থিরতা রাখেন।',
    'comprehensive | adj | ˌkɒmprɪˈhensɪv | ˌkɑːmprɪˈhensɪv | বিস্তৃত | complete, thorough | partial, narrow | We need a comprehensive list. | আমাদের একটি বিস্তৃত তালিকা দরকার।',
    'comprise | v | kəmˈpraɪz | kəmˈpraɪz | গঠিত হওয়া | include, contain | exclude, omit | The team will comprise eleven players. | দল এগারো খেলোয়াড়ে গঠিত হবে।',
    'compromise | n | ˈkɒmprəmaɪz | ˈkɑːmprəˌmaɪz | আপস | settlement, middle | deadlock, standoff | They reached a fair compromise. | তারা একটি ন্যায্য আপসে পৌঁছায়।',
    'compulsory | adj | kəmˈpʌlsəri | kəmˈpʌlsəri | বাধ্যতামূলক | required, mandatory | optional, voluntary | Attendance is compulsory. | উপস্থিতি বাধ্যতামূলক।',
    'conceal | v | kənˈsiːl | kənˈsiːl | লুকানো | hide, cover | reveal, show | Do not conceal the truth. | সত্য লুকাবেন না।',
    'concede | v | kənˈsiːd | kənˈsiːd | স্বীকার করা | admit, grant | deny, contest | He had to concede the point. | তাকে পয়েন্টটি স্বীকার করতে হয়।',
    'conceit | n | kənˈsiːt | kənˈsiːt | অহংকার | vanity, pride | humility, modesty | Conceit lost him friends. | অহংকার তাকে বন্ধু হারায়।',
    'concise | adj | kənˈsaɪs | kənˈsaɪs | সংক্ষিপ্ত | brief, terse | wordy, lengthy | Write a concise answer. | একটি সংক্ষিপ্ত উত্তর লিখুন।',
    'concur | v | kənˈkɜː | kənˈkɜːr | একমত হওয়া | agree, assent | dissent, differ | Judges concur on the ruling. | বিচারকরা রায়ে একমত হন।',
    'condemn | v | kənˈdem | kənˈdem | নিন্দা করা | denounce, blame | praise, pardon | Leaders condemn the attack. | নেতারা হামলার নিন্দা করেন।',
    'condense | v | kənˈdens | kənˈdens | ঘনীভূত করা | compress, shorten | expand, dilute | Please condense the report. | প্রতিবেদন ঘনীভূত করুন।',
    'condone | v | kənˈdəʊn | kənˈdoʊn | উপেক্ষা করে ক্ষমা করা | excuse, overlook | punish, condemn | Do not condone cheating. | নকল উপেক্ষা করে ক্ষমা করবেন না।',
    'conducive | adj | kənˈdjuːsɪv | kənˈduːsɪv | সহায়ক | helpful, favourable | harmful, adverse | Quiet is conducive to study. | নীরবতা পড়ার সহায়ক।',
    'confer | v | kənˈfɜː | kənˈfɜːr | আলোচনা করা | consult, discuss | withhold, ignore | Teachers confer after class. | শিক্ষকরা ক্লাসের পর আলোচনা করেন।',
    'confide | v | kənˈfaɪd | kənˈfaɪd | বিশ্বাস করে বলা | trust, disclose | hide, conceal | She will confide in her sister. | তিনি বোনকে বিশ্বাস করে বলবেন।',
    'confine | v | kənˈfaɪn | kənˈfaɪn | সীমাবদ্ধ করা | restrict, limit | free, release | Illness will confine him to bed. | অসুখ তাকে বিছানায় সীমাবদ্ধ করবে।',
    'confirm | v | kənˈfɜːm | kənˈfɜːrm | নিশ্চিত করা | verify, affirm | deny, refute | Please confirm the booking. | বুকিং নিশ্চিত করুন।',
    'confiscate | v | ˈkɒnfɪskeɪt | ˈkɑːnfəˌskeɪt | বাজেয়াপ্ত করা | seize, take | return, restore | Guards confiscate phones at the gate. | প্রহরী গেটে ফোন বাজেয়াপ্ত করে।',
    'conflagration | n | ˌkɒnfləˈɡreɪʃn | ˌkɑːnfləˈɡreɪʃn | বৃহৎ অগ্নিকাণ্ড | blaze, inferno | spark, ember | A conflagration destroyed the warehouse. | একটি বৃহৎ অগ্নিকাণ্ড গুদাম ধ্বংস করে।',
    'conflate | v | kənˈfleɪt | kənˈfleɪt | গুলিয়ে ফেলা | merge, mix | distinguish, separate | Do not conflate the two issues. | দুই বিষয় গুলিয়ে ফেলবেন না।',
    'conform | v | kənˈfɔːm | kənˈfɔːrm | মানিয়ে চলা | comply, follow | rebel, deviate | Uniforms must conform to the code. | ইউনিফর্ম নিয়মে মানিয়ে চলতে হবে।',
    'confound | v | kənˈfaʊnd | kənˈfaʊnd | হতবুদ্ধি করা | confuse, baffle | clarify, explain | The result will confound the experts. | ফল বিশেষজ্ঞদের হতবুদ্ধি করবে।',
    'congenial | adj | kənˈdʒiːniəl | kənˈdʒiːniəl | মনোরম | pleasant, agreeable | hostile, unpleasant | A congenial host made us welcome. | এক মনোরম আয়োজক আমাদের স্বাগত করেন।',
    'congenital | adj | kənˈdʒenɪtl | kənˈdʒenɪtl | জন্মগত | inborn, innate | acquired, learned | The defect was congenital. | ত্রুটিটি জন্মগত ছিল।',
    'congregate | v | ˈkɒŋɡrɪɡeɪt | ˈkɑːŋɡrɪˌɡeɪt | জড়ো হওয়া | gather, assemble | disperse, scatter | Fans congregate at the gate. | ভক্তরা গেটে জড়ো হয়।',
    'conjecture | n | kənˈdʒektʃə | kənˈdʒektʃər | অনুমান | guess, speculation | fact, proof | The report is only conjecture. | প্রতিবেদন কেবল অনুমান।',
    'conjure | v | ˈkʌndʒə | ˈkʌndʒər | জাদু করে দেখানো | summon, evoke | banish, erase | Magicians conjure coins from air. | জাদুকররা বাতাস থেকে মুদ্রা জাদু করে দেখায়।',
    'conscientious | adj | ˌkɒnʃiˈenʃəs | ˌkɑːnʃiˈenʃəs | বিবেকবান | careful, diligent | careless, lazy | A conscientious student checked twice. | এক বিবেকবান শিক্ষার্থী দুবার যাচাই করেন।',
    'consecutive | adj | kənˈsekjətɪv | kənˈsekjətɪv | পরপর | successive, sequential | broken, interrupted | It rained for three consecutive days. | তিন পরপর দিন বৃষ্টি হয়।',
    'consensus | n | kənˈsensəs | kənˈsensəs | ঐক্যমত | agreement, accord | discord, split | The class reached a consensus. | ক্লাস একটি ঐক্যমতে পৌঁছায়।',
    'consequent | adj | ˈkɒnsɪkwənt | ˈkɑːnsəkwənt | পরিণামস্বরূপ | resulting, ensuing | unrelated, prior | Flooding and the consequent delay closed the road. | বন্যা ও পরিণামস্বরূপ দেরি রাস্তা বন্ধ করে।',
    'conserve | v | kənˈsɜːv | kənˈsɜːrv | সংরক্ষণ করা | save, preserve | waste, squander | We must conserve water in summer. | গ্রীষ্মে পানি সংরক্ষণ করতে হবে।',
    'considerable | adj | kənˈsɪdərəbl | kənˈsɪdərəbl | যথেষ্ট | substantial, large | slight, tiny | She spent a considerable sum. | তিনি যথেষ্ট অর্থ খরচ করেন।',
    'consign | v | kənˈsaɪn | kənˈsaɪn | পাঠিয়ে দেওয়া | send, deliver | keep, retain | They consign the goods by rail. | তারা রেলে মাল পাঠিয়ে দেয়।',
    'consistent | adj | kənˈsɪstənt | kənˈsɪstənt | সামঞ্জস্যপূর্ণ | steady, regular | erratic, uneven | Keep a consistent schedule. | একটি সামঞ্জস্যপূর্ণ সময়সূচি রাখুন।',
    'console | v | kənˈsəʊl | kənˈsoʊl | সান্ত্বনা দেওয়া | comfort, soothe | upset, distress | Friends console the family. | বন্ধুরা পরিবারকে সান্ত্বনা দেয়।',
    'consolidate | v | kənˈsɒlɪdeɪt | kənˈsɑːləˌdeɪt | মজবুত করা | strengthen, merge | weaken, split | The party will consolidate its lead. | দল তার অগ্রগতি মজবুত করবে।',
    'conspicuous | adj | kənˈspɪkjuəs | kənˈspɪkjuəs | সহজে দৃশ্যমান | obvious, noticeable | hidden, obscure | A red hat is conspicuous in a crowd. | ভিড়ে লাল টুপি সহজে দৃশ্যমান।',
    'conspire | v | kənˈspaɪə | kənˈspaɪər | ষড়যন্ত্র করা | plot, scheme | oppose, resist | They did not conspire against the club. | তারা ক্লাবের বিরুদ্ধে ষড়যন্ত্র করেনি।',
    'constrain | v | kənˈstreɪn | kənˈstreɪn | বাধা দেওয়া | restrict, limit | free, release | Rules constrain what we may say. | নিয়ম আমরা যা বলতে পারি তাতে বাধা দেয়।',
    'construe | v | kənˈstruː | kənˈstruː | ব্যাখ্যা করা | interpret, read | misread, distort | Do not construe silence as consent. | নীরবতাকে সম্মতি হিসেবে ব্যাখ্যা করবেন না।',
    'consume | v | kənˈsjuːm | kənˈsuːm | খরচ করা | use, eat | save, conserve | Cars consume too much fuel. | গাড়ি অতিরিক্ত জ্বালানি খরচ করে।',
    'contemplate | v | ˈkɒntəmpleɪt | ˈkɑːntəmˌpleɪt | গভীরভাবে ভাবা | consider, ponder | ignore, dismiss | Sit and contemplate the question. | বসে প্রশ্নটি গভীরভাবে ভাবুন।',
    'contempt | n | kənˈtempt | kənˈtempt | ঘৃণা | scorn, disdain | respect, regard | He spoke of the lie with contempt. | তিনি মিথ্যা নিয়ে ঘৃণার সঙ্গে কথা বলেন।',
    'contend | v | kənˈtend | kənˈtend | তর্ক করা | argue, compete | yield, concede | Lawyers contend over the clause. | আইনজীবীরা ধারা নিয়ে তর্ক করেন।',
    'contentious | adj | kənˈtenʃəs | kənˈtenʃəs | বিতর্কিত | disputed, quarrelsome | peaceful, agreed | Land is a contentious issue here. | জমি এখানে একটি বিতর্কিত বিষয়।',
    'contingent | adj | kənˈtɪndʒənt | kənˈtɪndʒənt | শর্তসাপেক্ষ | dependent, conditional | certain, definite | The trip is contingent on rain. | ভ্রমণ বৃষ্টির শর্তসাপেক্ষ।',
    'contrite | adj | kənˈtraɪt | kənˈtraɪt | অনুতপ্ত | sorry, remorseful | unrepentant, defiant | A contrite letter followed the error. | ভুলের পর একটি অনুতপ্ত চিঠি আসে।',
    'convene | v | kənˈviːn | kənˈviːn | আহ্বান করা | assemble, gather | adjourn, dismiss | The board will convene at noon. | বোর্ড দুপুরে আহ্বান করা হবে।',
    'conventional | adj | kənˈvenʃənl | kənˈvenʃənl | প্রচলিত | traditional, usual | unusual, radical | Wear conventional dress to the exam. | পরীক্ষায় প্রচলিত পোশাক পরুন।',
    'converge | v | kənˈvɜːdʒ | kənˈvɜːrdʒ | এক বিন্দুতে মেশা | meet, join | diverge, split | Roads converge at the square. | সড়ক চত্বরে এক বিন্দুতে মেশে।',
    'convey | v | kənˈveɪ | kənˈveɪ | পৌঁছে দেওয়া | carry, communicate | withhold, hide | Words cannot convey the scene. | শব্দ দৃশ্য পৌঁছে দিতে পারে না।',
    'conviction | n | kənˈvɪkʃn | kənˈvɪkʃn | দৃঢ় বিশ্বাস | belief, certainty | doubt, hesitation | She spoke with conviction. | তিনি দৃঢ় বিশ্বাসে কথা বলেন।',
    'convivial | adj | kənˈvɪviəl | kənˈvɪviəl | আনন্দমুখর | festive, sociable | gloomy, unsociable | A convivial dinner ended the week. | একটি আনন্দমুখর রাতের খাবার সপ্তাহ শেষ করে।',
    'convoluted | adj | ˈkɒnvəluːtɪd | ˈkɑːnvəˌluːtɪd | জটিল প্যাঁচানো | intricate, tangled | simple, plain | The plot was too convoluted. | কাহিনি খুব জটিল প্যাঁচানো ছিল।',
    'cooperate | v | kəʊˈɒpəreɪt | koʊˈɑːpəˌreɪt | সহযোগিতা করা | collaborate, help | obstruct, hinder | Classes must cooperate on the play. | ক্লাসগুলোকে নাটকে সহযোগিতা করতে হবে।',
    'copious | adj | ˈkəʊpiəs | ˈkoʊpiəs | প্রচুর | abundant, plentiful | scant, meagre | She took copious notes. | তিনি প্রচুর নোট নেন।',
    'cordial | adj | ˈkɔːdiəl | ˈkɔːrdʒəl | আন্তরিক | warm, friendly | cold, hostile | A cordial welcome met the guests. | অতিথিদের আন্তরিক স্বাগত জানানো হয়।',
    'corroborate | v | kəˈrɒbəreɪt | kəˈrɑːbəˌreɪt | সমর্থন করা | confirm, support | contradict, refute | Witnesses corroborate the story. | সাক্ষীরা গল্প সমর্থন করেন।',
    'corrupt | adj | kəˈrʌpt | kəˈrʌpt | দুর্নীতিগ্রস্ত | dishonest, crooked | honest, clean | A corrupt official took the bribe. | এক দুর্নীতিগ্রস্ত কর্মকর্তা ঘুষ নেন।',
    'cosmetic | adj | kɒzˈmetɪk | kɑːzˈmetɪk | বাহ্যিক | superficial, surface | real, substantial | The change was only cosmetic. | পরিবর্তন কেবল বাহ্যিক ছিল।',
    'cosmopolitan | adj | ˌkɒzməˈpɒlɪtən | ˌkɑːzməˈpɑːlɪtən | বিশ্বজনীন | worldly, international | provincial, local | Dhaka is a cosmopolitan city. | ঢাকা একটি বিশ্বজনীন শহর।',
    'countenance | n | ˈkaʊntənəns | ˈkaʊntənəns | মুখভঙ্গি | face, expression | - | His countenance showed relief. | তার মুখভঙ্গিতে স্বস্তি ফুটে ওঠে।',
    'counterfeit | adj | ˈkaʊntəfɪt | ˈkaʊntərfɪt | নকল | fake, forged | genuine, real | Police seized counterfeit notes. | পুলিশ নকল নোট জব্দ করে।',
    'coup | n | kuː | kuː | অভ্যুত্থান | overthrow, takeover | election, reform | The army feared a night coup. | সেনাবাহিনী রাতের অভ্যুত্থানকে ভয় পায়।',
    'covert | adj | ˈkʌvət | ˈkoʊvɜːrt | গোপন | secret, hidden | open, overt | They ran a covert investigation. | তারা একটি গোপন তদন্ত চালায়।',
    'covet | v | ˈkʌvɪt | ˈkʌvət | লোভ করা | desire, crave | spurn, reject | Do not covet another’s prize. | অন্যের পুরস্কারে লোভ করবেন না।',
    'cower | v | ˈkaʊə | ˈkaʊər | ভয়ে কুঁকড়ে থাকা | cringe, shrink | confront, stand | The dog will cower in thunder. | কুকুর বজ্রে ভয়ে কুঁকড়ে থাকবে।',
    'crave | v | kreɪv | kreɪv | তীব্রভাবে চাওয়া | desire, long | spurn, reject | Children crave praise. | শিশুরা প্রশংসা তীব্রভাবে চায়।',
    'credence | n | ˈkriːdns | ˈkriːdns | বিশ্বাস | belief, trust | doubt, disbelief | Do not give credence to rumours. | গুজবে বিশ্বাস দেবেন না।',
    'credible | adj | ˈkredəbl | ˈkredəbl | বিশ্বাসযোগ্য | believable, reliable | dubious, false | Find a credible witness. | একটি বিশ্বাসযোগ্য সাক্ষী খুঁজুন।',
    'credulous | adj | ˈkredjələs | ˈkredʒələs | সহজে বিশ্বাসী | gullible, naive | sceptical, wary | A credulous buyer paid too much. | এক সহজে বিশ্বাসী ক্রেতা বেশি দেন।',
    'crestfallen | adj | ˈkrestfɔːlən | ˈkrestˌfɔːlən | মনমরা | dejected, downcast | elated, cheerful | The team looked crestfallen after defeat. | হারের পর দল মনমরা দেখায়।',
    'criterion | n | kraɪˈtɪəriən | kraɪˈtɪriən | মানদণ্ড | standard, measure | exception, fluke | Marks are one criterion of progress. | নম্বর অগ্রগতির একটি মানদণ্ড।',
    'crucial | adj | ˈkruːʃl | ˈkruːʃl | অত্যন্ত গুরুত্বপূর্ণ | vital, critical | trivial, minor | Sleep is crucial before an exam. | পরীক্ষার আগে ঘুম অত্যন্ত গুরুত্বপূর্ণ।',
    'cryptic | adj | ˈkrɪptɪk | ˈkrɪptɪk | রহস্যময় | obscure, puzzling | clear, plain | A cryptic note lay on the desk. | ডেস্কে একটি রহস্যময় নোট পড়ে ছিল।',
    'culminate | v | ˈkʌlmɪneɪt | ˈkʌlməˌneɪt | চূড়ান্ত পর্যায়ে পৌঁছানো | peak, climax | begin, start | The festival will culminate on Friday. | উৎসব শুক্রবার চূড়ান্ত পর্যায়ে পৌঁছাবে।',
    'culpable | adj | ˈkʌlpəbl | ˈkʌlpəbl | দোষী | guilty, blameworthy | innocent, blameless | The driver was culpable for the crash. | চালক দুর্ঘটনার জন্য দোষী ছিলেন।',
    'cultivate | v | ˈkʌltɪveɪt | ˈkʌltɪˌveɪt | চাষ করা | grow, foster | neglect, abandon | Farmers cultivate rice here. | কৃষকরা এখানে ধান চাষ করেন।',
    'cumbersome | adj | ˈkʌmbəsəm | ˈkʌmbərsəm | ভারী জটিল | awkward, bulky | handy, light | The box is too cumbersome to lift. | বাক্স তোলার জন্য খুব ভারী জটিল।',
    'cunning | adj | ˈkʌnɪŋ | ˈkʌnɪŋ | চতুর | sly, crafty | naive, honest | A cunning fox stole the hen. | এক চতুর শিয়াল মুরগি চুরি করে।',
    'curtail | v | kɜːˈteɪl | kərˈteɪl | কমিয়ে দেওয়া | cut, reduce | extend, increase | We must curtail spending. | আমাদের খরচ কমিয়ে দিতে হবে।',
    'cynical | adj | ˈsɪnɪkl | ˈsɪnɪkl | বিদ্রূপাত্মক | sceptical, scornful | trusting, naive | A cynical view of politics spread. | রাজনীতি নিয়ে বিদ্রূপাত্মক দৃষ্টি ছড়ায়।',
  ],
};
