import { type IRawSaifursGroup } from './schema';

export const WORDS_E: IRawSaifursGroup = {
  letter: 'E',
  entries: [
    'earnest | adj | ˈɜːnɪst | ˈɜːrnɪst | আন্তরিক | sincere, serious | flippant, joking | An earnest student asked again. | এক আন্তরিক শিক্ষার্থী আবার জিজ্ঞাসা করেন।',
    'ebb | v | eb | eb | ভাটা পড়া | recede, fade | rise, flow | The tide will ebb at dusk. | সন্ধ্যায় জোয়ার ভাটা পড়বে।',
    'eccentric | adj | ɪkˈsentrɪk | ɪkˈsentrɪk | খেয়ালী | odd, quirky | conventional, normal | An eccentric inventor lived next door. | পাশে এক খেয়ালী উদ্ভাবক থাকতেন।',
    'eclipse | n | ɪˈklɪps | ɪˈklɪps | গ্রহণ | obscuring, overshadowing | - | A solar eclipse darkened noon. | একটি সূর্যগ্রহণ দুপুর অন্ধকার করে।',
    'ecstasy | n | ˈekstəsi | ˈekstəsi | পরমানন্দ | rapture, joy | misery, despair | Victory filled them with ecstasy. | জয় তাদের পরমানন্দে ভরে দেয়।',
    'edifice | n | ˈedɪfɪs | ˈedɪfɪs | বৃহৎ ভবন | building, structure | hut, shack | A stone edifice faces the square. | একটি পাথরের বৃহৎ ভবন চত্বরের দিকে তাকায়।',
    'edify | v | ˈedɪfaɪ | ˈedɪˌfaɪ | শিক্ষা দেওয়া | instruct, enlighten | corrupt, confuse | Good books edify the young. | ভালো বই তরুণদের শিক্ষা দেয়।',
    'eerie | adj | ˈɪəri | ˈɪri | ভয়ঙ্কর অদ্ভুত | uncanny, spooky | ordinary, comforting | An eerie silence filled the lane. | একটি ভয়ঙ্কর অদ্ভুত নীরবতা গলি ভরে দেয়।',
    'efface | v | ɪˈfeɪs | ɪˈfeɪs | মুছে ফেলা | erase, wipe | preserve, keep | Time will efface the carving. | সময় খোদাই মুছে ফেলবে।',
    'effect | n | ɪˈfekt | ɪˈfekt | প্রভাব | result, impact | cause, origin | The new rule had little effect. | নতুন নিয়মের সামান্য প্রভাব ছিল।',
    'effigy | n | ˈefɪdʒi | ˈefɪdʒi | প্রতিকৃতি | dummy, image | original, person | They burned an effigy in protest. | তারা প্রতিবাদে একটি প্রতিকৃতি পোড়ায়।',
    'effusive | adj | ɪˈfjuːsɪv | ɪˈfjuːsɪv | অতিমাত্রায় প্রশংসাপূর্ণ | gushing, lavish | reserved, cool | An effusive welcome met the team. | দলকে অতিমাত্রায় প্রশংসাপূর্ণ স্বাগত জানানো হয়।',
    'egalitarian | adj | ɪˌɡælɪˈteəriən | ɪˌɡælɪˈteriən | সমতাবাদী | equal, fair | elitist, unequal | An egalitarian rule treated all alike. | একটি সমতাবাদী নিয়ম সবাইকে সমান করে।',
    'egocentric | adj | ˌiːɡəʊˈsentrɪk | ˌiːɡoʊˈsentrɪk | আত্মকেন্দ্রিক | selfish, self-centred | altruistic, generous | An egocentric speech ignored the team. | একটি আত্মকেন্দ্রিক বক্তৃতা দল উপেক্ষা করে।',
    'egregious | adj | ɪˈɡriːdʒəs | ɪˈɡriːdʒəs | চরম খারাপ | shocking, flagrant | minor, slight | An egregious error cost the match. | একটি চরম খারাপ ভুল ম্যাচ কাড়ে।',
    'eject | v | ɪˈdʒekt | ɪˈdʒekt | বের করে দেওয়া | expel, throw out | admit, welcome | Stewards eject the noisy fan. | স্টুয়ার্ড হৈচৈ করা ভক্তকে বের করে দেয়।',
    'elated | adj | ɪˈleɪtɪd | ɪˈleɪtɪd | উল্লসিত | joyful, thrilled | dejected, sad | The class looked elated. | ক্লাস উল্লসিত দেখায়।',
    'elicit | v | ɪˈlɪsɪt | ɪˈlɪsɪt | বের করে আনা | draw out, evoke | suppress, hide | Good questions elicit honest answers. | ভালো প্রশ্ন সৎ উত্তর বের করে আনে।',
    'eligible | adj | ˈelɪdʒəbl | ˈelɪdʒəbl | যোগ্য | qualified, entitled | ineligible, unfit | Only members are eligible to vote. | কেবল সদস্যরা ভোট দিতে যোগ্য।',
    'eliminate | v | ɪˈlɪmɪneɪt | ɪˈlɪməˌneɪt | বাদ দেওয়া | remove, exclude | include, keep | The round will eliminate two teams. | রাউন্ড দুই দল বাদ দেবে।',
    'eloquent | adj | ˈeləkwənt | ˈeləkwənt | বাগ্মী | fluent, expressive | inarticulate, dull | An eloquent speech moved the hall. | একটি বাগ্মী বক্তৃতা হল নাড়ায়।',
    'elucidate | v | ɪˈluːsɪdeɪt | ɪˈluːsəˌdeɪt | স্পষ্ট করা | explain, clarify | confuse, obscure | Please elucidate the last line. | শেষ লাইনটি স্পষ্ট করুন।',
    'elude | v | ɪˈluːd | ɪˈluːd | এড়িয়ে যাওয়া | escape, evade | face, meet | The thief tried to elude the police. | চোর পুলিশ এড়িয়ে যাওয়ার চেষ্টা করে।',
    'emaciated | adj | ɪˈmeɪʃieɪtɪd | ɪˈmeɪʃiˌeɪtɪd | শীর্ণ | wasted, thin | plump, healthy | An emaciated cow stood in the field. | মাঠে একটি শীর্ণ গরু দাঁড়িয়ে ছিল।',
    'emancipate | v | ɪˈmænsɪpeɪt | ɪˈmænsəˌpeɪt | মুক্ত করা | free, liberate | enslave, bind | Laws emancipate the bonded worker. | আইন বন্ধক শ্রমিককে মুক্ত করে।',
    'embark | v | ɪmˈbɑːk | ɪmˈbɑːrk | যাত্রা শুরু করা | board, begin | disembark, end | We embark at dawn. | আমরা ভোরে যাত্রা শুরু করি।',
    'embed | v | ɪmˈbed | ɪmˈbed | পুঁতে রাখা | implant, fix | extract, remove | Journalists embed with the unit. | সাংবাদিকরা ইউনিটের সঙ্গে পুঁতে থাকেন।',
    'embellish | v | ɪmˈbelɪʃ | ɪmˈbelɪʃ | অলংকৃত করা | decorate, adorn | strip, simplify | Do not embellish the facts. | তথ্য অলংকৃত করবেন না।',
    'embezzle | v | ɪmˈbezl | ɪmˈbezl | আত্মসাৎ করা | steal, misappropriate | repay, restore | A clerk tried to embezzle the funds. | এক কেরানি তহবিল আত্মসাৎ করার চেষ্টা করে।',
    'embody | v | ɪmˈbɒdi | ɪmˈbɑːdi | মূর্ত করা | represent, personify | lack, omit | The statue will embody hope. | মূর্তি আশা মূর্ত করবে।',
    'embrace | v | ɪmˈbreɪs | ɪmˈbreɪs | আলিঙ্গন করা | hug, adopt | reject, shun | They embrace the new method. | তারা নতুন পদ্ধতি আলিঙ্গন করে।',
    'embroil | v | ɪmˈbrɔɪl | ɪmˈbrɔɪl | জড়িয়ে ফেলা | involve, entangle | extricate, free | Do not embroil the school in the feud. | স্কুলকে ঝগড়ায় জড়াবেন না।',
    'emend | v | ɪˈmend | ɪˈmend | সংশোধন করা | correct, revise | corrupt, spoil | Editors emend the text. | সম্পাদকরা পাঠ সংশোধন করেন।',
    'eminent | adj | ˈemɪnənt | ˈemɪnənt | বিশিষ্ট | distinguished, famous | obscure, unknown | An eminent poet visited the college. | এক বিশিষ্ট কবি কলেজে আসেন।',
    'emit | v | ɪˈmɪt | ɪˈmɪt | নির্গত করা | give off, discharge | absorb, take in | Factories emit smoke at night. | কারখানা রাতে ধোঁয়া নির্গত করে।',
    'empathy | n | ˈempəθi | ˈempəθi | সহানুভূতি | compassion, understanding | indifference, apathy | Teachers need empathy with fear. | শিক্ষকদের ভয়ের প্রতি সহানুভূতি দরকার।',
    'emphasize | v | ˈemfəsaɪz | ˈemfəˌsaɪz | জোর দেওয়া | stress, highlight | downplay, ignore | Please emphasize the deadline. | সময়সীমায় জোর দিন।',
    'empirical | adj | ɪmˈpɪrɪkl | ɪmˈpɪrɪkl | পরীক্ষালব্ধ | observed, experimental | theoretical, speculative | We need empirical proof. | আমাদের পরীক্ষালব্ধ প্রমাণ দরকার।',
    'empower | v | ɪmˈpaʊə | ɪmˈpaʊər | ক্ষমতা দেওয়া | enable, authorize | weaken, restrict | Training will empower the staff. | প্রশিক্ষণ কর্মীদের ক্ষমতা দেবে।',
    'emulate | v | ˈemjuleɪt | ˈemjəˌleɪt | অনুকরণ করা | imitate, follow | ignore, shun | Young players emulate the captain. | তরুণ খেলোয়াড়রা অধিনায়ককে অনুকরণ করে।',
    'enact | v | ɪˈnækt | ɪˈnækt | আইন পাশ করা | pass, legislate | repeal, revoke | Parliament will enact the bill. | সংসদ বিল আইন হিসেবে পাশ করবে।',
    'encompass | v | ɪnˈkʌmpəs | ɪnˈkʌmpəs | ঘিরে রাখা | include, surround | exclude, omit | The course will encompass four skills. | কোর্স চার দক্ষতা ঘিরে রাখবে।',
    'encounter | v | ɪnˈkaʊntə | ɪnˈkaʊntər | সম্মুখীন হওয়া | meet, face | avoid, miss | You may encounter delays. | আপনি দেরির সম্মুখীন হতে পারেন।',
    'encroach | v | ɪnˈkrəʊtʃ | ɪnˈkroʊtʃ | অনধিকার প্রবেশ করা | intrude, trespass | withdraw, recede | Do not encroach on the field. | মাঠে অনধিকার প্রবেশ করবেন না।',
    'encumber | v | ɪnˈkʌmbə | ɪnˈkʌmbər | বোঝা চাপানো | burden, hamper | free, lighten | Debt will encumber the farm. | ঋণ খামারে বোঝা চাপাবে।',
    'endemic | adj | enˈdemɪk | enˈdemɪk | স্থানীয় মহামারিসংক্রান্ত | native, local | foreign, imported | The fever is endemic here. | জ্বর এখানে স্থানীয়।',
    'endorse | v | ɪnˈdɔːs | ɪnˈdɔːrs | সমর্থন করা | support, approve | oppose, reject | Stars endorse the campaign. | তারকারা প্রচার সমর্থন করেন।',
    'endow | v | ɪnˈdaʊ | ɪnˈdaʊ | দান করা | grant, bestow | withhold, strip | Donors endow the scholarship. | দাতারা বৃত্তি দান করেন।',
    'endure | v | ɪnˈdjʊə | ɪnˈdʊr | সহ্য করা | bear, withstand | quit, collapse | Farmers endure the drought. | কৃষকরা খরা সহ্য করেন।',
    'enervate | v | ˈenəveɪt | ˈenərˌveɪt | শক্তিহীন করা | weaken, drain | energize, strengthen | Heat can enervate the workers. | গরম শ্রমিকদের শক্তিহীন করতে পারে।',
    'enfranchise | v | ɪnˈfræntʃaɪz | ɪnˈfrænˌtʃaɪz | ভোটাধিকার দেওয়া | empower, free | disenfranchise, bar | The law will enfranchise women. | আইন নারীদের ভোটাধিকার দেবে।',
    'engender | v | ɪnˈdʒendə | ɪnˈdʒendər | সৃষ্টি করা | produce, cause | prevent, halt | Trust will engender cooperation. | বিশ্বাস সহযোগিতা সৃষ্টি করবে।',
    'engross | v | ɪnˈɡrəʊs | ɪnˈɡroʊs | সম্পূর্ণ মগ্ন করা | absorb, occupy | bore, distract | The novel will engross you. | উপন্যাস আপনাকে সম্পূর্ণ মগ্ন করবে।',
    'enhance | v | ɪnˈhɑːns | ɪnˈhæns | উন্নত করা | improve, boost | diminish, spoil | Practice will enhance your score. | অনুশীলন আপনার স্কোর উন্নত করবে।',
    'enigma | n | ɪˈnɪɡmə | ɪˈnɪɡmə | রহস্য | puzzle, mystery | solution, answer | The code remains an enigma. | সংকেতটি রহস্যই থেকে যায়।',
    'enlighten | v | ɪnˈlaɪtn | ɪnˈlaɪtn | জ্ঞান দান করা | inform, instruct | confuse, mislead | Travel can enlighten a student. | ভ্রমণ শিক্ষার্থীকে জ্ঞান দান করতে পারে।',
    'enmity | n | ˈenməti | ˈenməti | শত্রুতা | hostility, hatred | friendship, amity | Old enmity split the villages. | পুরনো শত্রুতা গ্রামগুলো ভাগ করে।',
    'enormous | adj | ɪˈnɔːməs | ɪˈnɔːrməs | বিশাল | huge, vast | tiny, minute | An enormous tree shades the yard. | একটি বিশাল গাছ উঠান ছায়ায় রাখে।',
    'enquire | v | ɪnˈkwaɪə | ɪnˈkwaɪər | জিজ্ঞাসা করা | ask, query | ignore, assume | Please enquire at the desk. | ডেস্কে জিজ্ঞাসা করুন।',
    'enrich | v | ɪnˈrɪtʃ | ɪnˈrɪtʃ | সমৃদ্ধ করা | enhance, improve | impoverish, drain | Reading will enrich your English. | পড়া আপনার ইংরেজি সমৃদ্ধ করবে।',
    'enrol | v | ɪnˈrəʊl | ɪnˈroʊl | নাম লেখানো | register, join | withdraw, quit | Students enrol in June. | শিক্ষার্থীরা জুনে নাম লেখায়।',
    'ensnare | v | ɪnˈsneə | ɪnˈsner | ফাঁদে ফেলা | trap, catch | free, release | Lies ensnare the careless. | মিথ্যা অসতর্ককে ফাঁদে ফেলে।',
    'ensue | v | ɪnˈsjuː | ɪnˈsuː | অনুসরণ করা | follow, result | precede, start | Chaos will ensue if we leave. | আমরা গেলে বিশৃঙ্খলা অনুসরণ করবে।',
    'entail | v | ɪnˈteɪl | ɪnˈteɪl | অনিবার্যভাবে আনা | involve, require | exclude, omit | The job will entail night work. | কাজ রাতের শ্রম অনিবার্যভাবে আনবে।',
    'enthral | v | ɪnˈθrɔːl | ɪnˈθrɔːl | মুগ্ধ করা | captivate, fascinate | bore, repel | The play will enthral the hall. | নাটক হলকে মুগ্ধ করবে।',
    'entice | v | ɪnˈtaɪs | ɪnˈtaɪs | প্রলুব্ধ করা | lure, tempt | deter, repel | Shops entice buyers with sales. | দোকান সেল দিয়ে ক্রেতা প্রলুব্ধ করে।',
    'entreat | v | ɪnˈtriːt | ɪnˈtriːt | অনুনয় করা | beg, implore | demand, command | I entreat you to wait. | আমি আপনাকে অপেক্ষা করার অনুনয় করি।',
    'enumerate | v | ɪˈnjuːməreɪt | ɪˈnuːməˌreɪt | গণনা করে বলা | list, count | omit, skip | Please enumerate the reasons. | কারণগুলো গণনা করে বলুন।',
    'enunciate | v | ɪˈnʌnsieɪt | ɪˈnʌnsiˌeɪt | স্পষ্ট উচ্চারণ করা | pronounce, articulate | mumble, slur | Actors enunciate every word. | অভিনেতারা প্রতিটি শব্দ স্পষ্ট উচ্চারণ করেন।',
    'ephemeral | adj | ɪˈfemərəl | ɪˈfemərəl | ক্ষণস্থায়ী | fleeting, brief | lasting, enduring | Fame can be ephemeral. | খ্যাতি ক্ষণস্থায়ী হতে পারে।',
    'epic | adj | ˈepɪk | ˈepɪk | মহাকাব্যিক | grand, heroic | trivial, petty | An epic journey crossed the hills. | একটি মহাকাব্যিক যাত্রা পাহাড় পার হয়।',
    'epidemic | n | ˌepɪˈdemɪk | ˌepɪˈdemɪk | মহামারি | outbreak, plague | - | An epidemic closed the schools. | একটি মহামারি স্কুল বন্ধ করে।',
    'epilogue | n | ˈepɪlɒɡ | ˈepɪˌlɔːɡ | উপসংহার | afterword, coda | prologue, preface | The epilogue names the survivors. | উপসংহার বেঁচে যাওয়াদের নাম বলে।',
    'epitome | n | ɪˈpɪtəmi | ɪˈpɪtəmi | আদর্শ উদাহরণ | embodiment, model | opposite, contrast | She is the epitome of patience. | তিনি ধৈর্যের আদর্শ উদাহরণ।',
    'equanimity | n | ˌekwəˈnɪməti | ˌekwəˈnɪməti | মানসিক স্থিরতা | composure, calm | panic, agitation | He faced loss with equanimity. | তিনি ক্ষতিকে মানসিক স্থিরতায় মেনে নেন।',
    'equitable | adj | ˈekwɪtəbl | ˈekwɪtəbl | ন্যায্য | fair, just | unfair, biased | Seek an equitable share. | একটি ন্যায্য ভাগ চান।',
    'equivocal | adj | ɪˈkwɪvəkl | ɪˈkwɪvəkl | দ্ব্যর্থক | ambiguous, vague | clear, definite | An equivocal answer helped nobody. | একটি দ্ব্যর্থক উত্তর কাউকে সাহায্য করেনি।',
    'eradicate | v | ɪˈrædɪkeɪt | ɪˈrædəˌkeɪt | নির্মূল করা | wipe out, eliminate | plant, spread | Campaigns eradicate the fever. | প্রচার জ্বর নির্মূল করে।',
    'erratic | adj | ɪˈrætɪk | ɪˈrætɪk | অনিয়মিত | unpredictable, uneven | steady, regular | Erratic rain ruined the crop. | অনিয়মিত বৃষ্টি ফসল নষ্ট করে।',
    'erroneous | adj | ɪˈrəʊniəs | ɪˈroʊniəs | ভুল | wrong, incorrect | accurate, true | The figure was erroneous. | সংখ্যাটি ভুল ছিল।',
    'erudite | adj | ˈerudaɪt | ˈerjəˌdaɪt | পণ্ডিত | learned, scholarly | ignorant, untaught | An erudite note filled the margin. | একটি পণ্ডিত টীকা মার্জিন ভরে দেয়।',
    'escalate | v | ˈeskəleɪt | ˈeskəˌleɪt | তীব্রতর হওয়া | intensify, rise | ease, lessen | Do not escalate the quarrel. | ঝগড়া তীব্রতর করবেন না।',
    'eschew | v | ɪsˈtʃuː | ɪsˈtʃuː | পরিহার করা | avoid, shun | embrace, seek | Please eschew slang in the paper. | পত্রে অপভাষা পরিহার করুন।',
    'esoteric | adj | ˌesəˈterɪk | ˌesəˈterɪk | গূঢ় | obscure, arcane | common, popular | The rite uses esoteric signs. | অনুষ্ঠানে গূঢ় চিহ্ন ব্যবহার হয়।',
    'espouse | v | ɪˈspaʊz | ɪˈspaʊz | সমর্থন করা | adopt, support | reject, oppose | They espouse free schools. | তারা বিনামূল্যে স্কুল সমর্থন করে।',
    'essence | n | ˈesns | ˈesns | সারকথা | core, heart | surface, shell | Trust is the essence of the deal. | বিশ্বাস চুক্তির সারকথা।',
    'establish | v | ɪˈstæblɪʃ | ɪˈstæblɪʃ | প্রতিষ্ঠা করা | found, set up | abolish, close | They establish a clinic each year. | তারা প্রতি বছর একটি ক্লিনিক প্রতিষ্ঠা করে।',
    'esteem | n | ɪˈstiːm | ɪˈstiːm | সম্মান | respect, regard | contempt, scorn | She holds teachers in high esteem. | তিনি শিক্ষকদের উচ্চ সম্মানে রাখেন।',
    'estimate | v | ˈestɪmeɪt | ˈestəˌmeɪt | অনুমান করা | judge, gauge | measure exactly | Please estimate the cost. | খরচ অনুমান করুন।',
    'estrange | v | ɪˈstreɪndʒ | ɪˈstreɪndʒ | দূরে সরিয়ে দেওয়া | alienate, separate | reunite, bind | Harsh words estrange friends. | কঠোর কথা বন্ধুদের দূরে সরিয়ে দেয়।',
    'eternal | adj | ɪˈtɜːnl | ɪˈtɜːrnl | চিরন্তন | endless, lasting | brief, finite | They swore eternal friendship. | তারা চিরন্তন বন্ধুত্বের শপথ নেয়।',
    'ethereal | adj | ɪˈθɪəriəl | ɪˈθɪriəl | অপার্থিব | delicate, airy | earthly, heavy | An ethereal light filled the hall. | একটি অপার্থিব আলো হল ভরে দেয়।',
    'ethical | adj | ˈeθɪkl | ˈeθɪkl | নৈতিক | moral, principled | unethical, corrupt | An ethical choice is not always easy. | একটি নৈতিক পছন্দ সবসময় সহজ নয়।',
    'etiquette | n | ˈetɪket | ˈetɪket | শিষ্টাচার | manners, protocol | rudeness, disorder | Learn the etiquette of the exam hall. | পরীক্ষা হলের শিষ্টাচার শিখুন।',
    'eulogy | n | ˈjuːlədʒi | ˈjuːlədʒi | প্রশংসাবাক্য | tribute, praise | insult, attack | A short eulogy closed the meeting. | একটি সংক্ষিপ্ত প্রশংসাবাক্য সভা শেষ করে।',
    'euphoria | n | juːˈfɔːriə | juːˈfɔːriə | অতিআনন্দ | elation, bliss | despair, gloom | Victory brought brief euphoria. | জয় সংক্ষিপ্ত অতিআনন্দ আনে।',
    'evacuate | v | ɪˈvækjueɪt | ɪˈvækjuˌeɪt | সরিয়ে নেওয়া | empty, withdraw | occupy, fill | Police evacuate the building. | পুলিশ ভবন সরিয়ে নেয়।',
    'evade | v | ɪˈveɪd | ɪˈveɪd | এড়ানো | avoid, dodge | face, confront | Do not evade the question. | প্রশ্ন এড়াবেন না।',
    'evaluate | v | ɪˈvæljueɪt | ɪˈvæljuˌeɪt | মূল্যায়ন করা | assess, judge | ignore, guess | Teachers evaluate the essays. | শিক্ষকরা রচনা মূল্যায়ন করেন।',
    'evaporate | v | ɪˈvæpəreɪt | ɪˈvæpəˌreɪt | বাষ্পীভূত হওয়া | vanish, dry | condense, collect | Puddles evaporate in the sun. | জলা রোদে বাষ্পীভূত হয়।',
    'evasive | adj | ɪˈveɪsɪv | ɪˈveɪsɪv | এড়িয়ে যাওয়া | elusive, vague | direct, frank | An evasive answer wasted time. | একটি এড়িয়ে যাওয়া উত্তর সময় নষ্ট করে।',
    'evoke | v | ɪˈvəʊk | ɪˈvoʊk | জাগানো | summon, stir | suppress, mute | The song will evoke old days. | গান পুরনো দিন জাগাবে।',
    'exacerbate | v | ɪɡˈzæsəbeɪt | ɪɡˈzæsərˌbeɪt | আরও খারাপ করা | worsen, aggravate | ease, soothe | Heat will exacerbate the drought. | গরম খরা আরও খারাপ করবে।',
    'exact | adj | ɪɡˈzækt | ɪɡˈzækt | নির্ভুল | precise, accurate | approximate, rough | Give the exact time. | নির্ভুল সময় দিন।',
    'exaggerate | v | ɪɡˈzædʒəreɪt | ɪɡˈzædʒəˌreɪt | অতিরঞ্জিত করা | overstate, inflate | understate, minimise | Do not exaggerate the injury. | চোট অতিরঞ্জিত করবেন না।',
    'exalt | v | ɪɡˈzɔːlt | ɪɡˈzɔːlt | উচ্চ প্রশংসা করা | praise, glorify | belittle, degrade | Poems exalt the river. | কবিতা নদীর উচ্চ প্রশংসা করে।',
    'exasperate | v | ɪɡˈzæspəreɪt | ɪɡˈzæspəˌreɪt | বিরক্ত করা | irritate, infuriate | soothe, please | Delays exasperate the passengers. | দেরি যাত্রীদের বিরক্ত করে।',
    'excavate | v | ˈekskəveɪt | ˈekskəˌveɪt | খনন করা | dig, unearth | bury, fill | Teams excavate the old well. | দলগুলো পুরনো কূপ খনন করে।',
    'exceed | v | ɪkˈsiːd | ɪkˈsiːd | ছাড়িয়ে যাওয়া | surpass, outdo | fall short | Do not exceed the limit. | সীমা ছাড়িয়ে যাবেন না।',
    'excel | v | ɪkˈsel | ɪkˈsel | শ্রেষ্ঠত্ব দেখানো | shine, surpass | fail, lag | She will excel in maths. | তিনি গণিতে শ্রেষ্ঠত্ব দেখাবেন।',
    'excerpt | n | ˈeksɜːpt | ˈeksɜːrpt | উদ্ধৃতাংশ | extract, passage | whole, entirety | Read this excerpt aloud. | এই উদ্ধৃতাংশ জোরে পড়ুন।',
    'excruciating | adj | ɪkˈskruːʃieɪtɪŋ | ɪkˈskruːʃiˌeɪtɪŋ | অসহ্য যন্ত্রণাদায়ক | agonizing, intense | mild, slight | An excruciating pain woke him. | একটি অসহ্য যন্ত্রণাদায়ক ব্যথা তাকে জাগায়।',
    'exemplary | adj | ɪɡˈzempləri | ɪɡˈzempləri | আদর্শ | model, admirable | poor, shameful | Her conduct was exemplary. | তার আচরণ আদর্শ ছিল।',
    'exempt | adj | ɪɡˈzempt | ɪɡˈzempt | অব্যাহতিপ্রাপ্ত | free, excused | liable, subject | Students are exempt from the fee. | শিক্ষার্থীরা ফি থেকে অব্যাহতিপ্রাপ্ত।',
    'exert | v | ɪɡˈzɜːt | ɪɡˈzɜːrt | প্রয়োগ করা | apply, use | withhold, rest | Please exert more effort. | আরও চেষ্টা প্রয়োগ করুন।',
    'exhale | v | eksˈheɪl | eksˈheɪl | নিঃশ্বাস ছাড়া | breathe out, emit | inhale, breathe in | Slow down and exhale. | ধীরে হন এবং নিঃশ্বাস ছাড়ুন।',
    'exhaust | v | ɪɡˈzɔːst | ɪɡˈzɔːst | ক্লান্ত করা | tire, drain | refresh, restore | Heat can exhaust the runners. | গরম দৌড়বিদদের ক্লান্ত করতে পারে।',
    'exhibit | v | ɪɡˈzɪbɪt | ɪɡˈzɪbɪt | প্রদর্শন করা | display, show | hide, conceal | Artists exhibit new work. | শিল্পীরা নতুন কাজ প্রদর্শন করেন।',
    'exhilarate | v | ɪɡˈzɪləreɪt | ɪɡˈzɪləˌreɪt | উল্লসিত করা | thrill, elate | bore, depress | The win will exhilarate the fans. | জয় ভক্তদের উল্লসিত করবে।',
    'exhort | v | ɪɡˈzɔːt | ɪɡˈzɔːrt | উদ্বুদ্ধ করা | urge, encourage | deter, discourage | Coaches exhort the team to run. | কোচরা দলকে দৌড়াতে উদ্বুদ্ধ করেন।',
    'exile | n | ˈeksaɪl | ˈeksaɪl | নির্বাসন | banishment, expulsion | homecoming, return | Years of exile ended at last. | বছরের নির্বাসন শেষ হয়।',
    'exonerate | v | ɪɡˈzɒnəreɪt | ɪɡˈzɑːnəˌreɪt | নির্দোষ প্রমাণ করা | acquit, clear | convict, blame | New facts exonerate the accused. | নতুন তথ্য অভিযুক্তকে নির্দোষ প্রমাণ করে।',
    'exorbitant | adj | ɪɡˈzɔːbɪtənt | ɪɡˈzɔːrbɪtənt | অতিরিক্ত | excessive, steep | reasonable, fair | The rent is exorbitant. | ভাড়া অতিরিক্ত।',
    'exotic | adj | ɪɡˈzɒtɪk | ɪɡˈzɑːtɪk | বিদেশি অদ্ভুত | foreign, unusual | native, ordinary | An exotic bird sat on the wall. | একটি বিদেশি অদ্ভুত পাখি দেয়ালে বসে।',
    'expand | v | ɪkˈspænd | ɪkˈspænd | বিস্তৃত করা | enlarge, grow | shrink, contract | The school will expand next year. | স্কুল আগামী বছর বিস্তৃত হবে।',
    'expatriate | n | eksˈpætriət | eksˈpeɪtriət | প্রবাসী | emigrant, exile | native, resident | An expatriate opened the shop. | এক প্রবাসী দোকান খোলেন।',
    'expedient | adj | ɪkˈspiːdiənt | ɪkˈspiːdiənt | সুবিধাজনক | convenient, practical | unwise, principled | A short cut was expedient but unfair. | শর্টকাট সুবিধাজনক কিন্তু অন্যায্য ছিল।',
    'expedite | v | ˈekspədaɪt | ˈekspəˌdaɪt | ত্বরান্বিত করা | hasten, speed | delay, hinder | Please expedite the papers. | কাগজপত্র ত্বরান্বিত করুন।',
    'expel | v | ɪkˈspel | ɪkˈspel | বহিষ্কার করা | eject, oust | admit, welcome | The school may expel the cheat. | স্কুল নকলকারীকে বহিষ্কার করতে পারে।',
    'expend | v | ɪkˈspend | ɪkˈspend | খরচ করা | spend, use | save, conserve | Do not expend all your energy. | সব শক্তি খরচ করবেন না।',
    'expertise | n | ˌekspɜːˈtiːz | ˌekspərˈtiːz | বিশেষজ্ঞতা | skill, know-how | ignorance, inexperience | We need legal expertise. | আমাদের আইনি বিশেষজ্ঞতা দরকার।',
    'expire | v | ɪkˈspaɪə | ɪkˈspaɪər | মেয়াদ শেষ হওয়া | end, lapse | begin, renew | Tickets expire at midnight. | টিকিট মধ্যরাতে মেয়াদ শেষ হয়।',
    'explicit | adj | ɪkˈsplɪsɪt | ɪkˈsplɪsɪt | স্পষ্ট | clear, plain | implicit, vague | Give explicit instructions. | স্পষ্ট নির্দেশ দিন।',
    'exploit | v | ɪkˈsplɔɪt | ɪkˈsplɔɪt | শোষণ করা | misuse, use | protect, aid | Do not exploit cheap labour. | সস্তা শ্রম শোষণ করবেন না।',
    'explore | v | ɪkˈsplɔː | ɪkˈsplɔːr | অন্বেষণ করা | investigate, survey | ignore, neglect | Students explore the old fort. | শিক্ষার্থীরা পুরনো দুর্গ অন্বেষণ করে।',
    'expose | v | ɪkˈspəʊz | ɪkˈspoʊz | প্রকাশ করা | reveal, uncover | hide, conceal | Papers expose the fraud. | পত্রিকা প্রতারণা প্রকাশ করে।',
    'expound | v | ɪkˈspaʊnd | ɪkˈspaʊnd | বিস্তারিত ব্যাখ্যা করা | explain, interpret | summarize, hide | Teachers expound the poem. | শিক্ষকরা কবিতা বিস্তারিত ব্যাখ্যা করেন।',
    'exquisite | adj | ɪkˈskwɪzɪt | ɪkˈskwɪzɪt | অতিসুন্দর | delicate, fine | coarse, crude | An exquisite cloth lined the box. | একটি অতিসুন্দর কাপড় বাক্স মুড়ে।',
    'extant | adj | ekˈstænt | ˈekstənt | এখনও বিদ্যমান | surviving, remaining | extinct, lost | Few copies are still extant. | কয়েকটি কপি এখনও বিদ্যমান।',
    'extemporaneous | adj | ɪkˌstempəˈreɪniəs | ɪkˌstempəˈreɪniəs | তাৎক্ষণিক | impromptu, unprepared | rehearsed, planned | An extemporaneous speech won the prize. | একটি তাৎক্ষণিক বক্তৃতা পুরস্কার জেতে।',
    'extend | v | ɪkˈstend | ɪkˈstend | বাড়ানো | lengthen, stretch | shorten, cut | Please extend the deadline. | সময়সীমা বাড়ান।',
    'extenuate | v | ɪkˈstenjueɪt | ɪkˈstenjuˌeɪt | লঘু করা | lessen, mitigate | aggravate, worsen | Nothing can extenuate the crime. | কিছুই অপরাধ লঘু করতে পারে না।',
    'exterminate | v | ɪkˈstɜːmɪneɪt | ɪkˈstɜːrməˌneɪt | নির্মূল করা | wipe out, destroy | spare, protect | Traps exterminate the rats. | ফাঁদ ইঁদুর নির্মূল করে।',
    'extol | v | ɪkˈstəʊl | ɪkˈstoʊl | প্রশংসা করা | praise, laud | criticise, blame | Poets extol the river. | কবিরা নদীর প্রশংসা করেন।',
    'extort | v | ɪkˈstɔːt | ɪkˈstɔːrt | আদায় করা | extract, blackmail | give, offer | Thugs try to extort money. | গুণ্ডারা টাকা আদায় করার চেষ্টা করে।',
    'extract | v | ɪkˈstrækt | ɪkˈstrækt | বের করা | pull, remove | insert, add | Dentists extract the tooth. | দন্তচিকিৎসক দাঁত বের করেন।',
    'extraneous | adj | ɪkˈstreɪniəs | ɪkˈstreɪniəs | অপ্রাসঙ্গিক | irrelevant, extra | relevant, essential | Cut extraneous detail. | অপ্রাসঙ্গিক বিস্তারিত কাটুন।',
    'extravagant | adj | ɪkˈstrævəɡənt | ɪkˈstrævəɡənt | অমিতব্যয়ী | lavish, wasteful | thrifty, modest | An extravagant feast emptied the purse. | একটি অমিতব্যয়ী ভোজ থলি খালি করে।',
    'extreme | adj | ɪkˈstriːm | ɪkˈstriːm | চরম | intense, utmost | moderate, mild | Extreme heat closed the school. | চরম গরম স্কুল বন্ধ করে।',
    'extricate | v | ˈekstrɪkeɪt | ˈekstrɪˌkeɪt | মুক্ত করা | free, disentangle | ensnare, trap | Help me extricate the rope. | দড়ি মুক্ত করতে সাহায্য করুন।',
    'exuberant | adj | ɪɡˈzjuːbərənt | ɪɡˈzuːbərənt | উচ্ছ্বসিত | lively, enthusiastic | subdued, gloomy | An exuberant crowd filled the yard. | একটি উচ্ছ্বসিত ভিড় উঠান ভরে দেয়।',
    'exude | v | ɪɡˈzjuːd | ɪɡˈzuːd | নির্গত হওয়া | emit, radiate | absorb, hide | Trees exude a sweet gum. | গাছ মিষ্টি আঠা নির্গত করে।',
  ],
};
