import { type IRawSaifursGroup } from './schema';

export const WORDS_A: IRawSaifursGroup = {
  letter: 'A',
  entries: [
    'abandon | v | əˈbændən | əˈbændən | পরিত্যাগ করা | forsake, desert | keep, retain | They had to abandon the flooded village. | তাদের বন্যাগ্রস্ত গ্রামটি পরিত্যাগ করতে হয়েছিল।',
    'abate | v | əˈbeɪt | əˈbeɪt | কমে যাওয়া | lessen, subside | increase, intensify | The storm will abate by evening. | সন্ধ্যার মধ্যে ঝড় কমে যাবে।',
    'abbreviate | v | əˈbriːvieɪt | əˈbriviˌeɪt | সংক্ষেপ করা | shorten, condense | lengthen, expand | Please abbreviate the title on the form. | ফর্মে শিরোনামটি সংক্ষেপ করুন।',
    'abdicate | v | ˈæbdɪkeɪt | ˈæbdɪˌkeɪt | সিংহাসন ত্যাগ করা | resign, renounce | assume, retain | The king chose to abdicate rather than fight. | রাজা লড়াই করার বদলে সিংহাসন ত্যাগ করতে চাইলেন।',
    'abduct | v | æbˈdʌkt | æbˈdʌkt | অপহরণ করা | kidnap, seize | release, free | The report said rebels might abduct the envoy. | প্রতিবেদনে বলা হয় বিদ্রোহীরা দূতকে অপহরণ করতে পারে।',
    'abhor | v | əbˈhɔː | əbˈhɔːr | ঘৃণা করা | detest, loathe | love, admire | I abhor cruelty of any kind. | যেকোনো ধরনের নিষ্ঠুরতা আমি ঘৃণা করি।',
    'abide | v | əˈbaɪd | əˈbaɪd | মেনে চলা | obey, observe | defy, ignore | Players must abide by the referee. | খেলোয়াড়দের রেফারিকে মেনে চলতে হবে।',
    'abolish | v | əˈbɒlɪʃ | əˈbɑːlɪʃ | বিলুপ্ত করা | end, repeal | establish, retain | Parliament voted to abolish the tax. | সংসদ করটি বিলুপ্ত করার পক্ষে ভোট দেয়।',
    'abound | v | əˈbaʊnd | əˈbaʊnd | প্রচুর থাকা | teem, overflow | lack, want | Fish abound in this river. | এই নদীতে মাছ প্রচুর আছে।',
    'abridge | v | əˈbrɪdʒ | əˈbrɪdʒ | সংক্ষিপ্ত করা | condense, shorten | expand, lengthen | The editor had to abridge the novel. | সম্পাদককে উপন্যাসটি সংক্ষিপ্ত করতে হয়েছিল।',
    'abrupt | adj | əˈbrʌpt | əˈbrʌpt | হঠাৎ | sudden, unexpected | gradual, gentle | His abrupt departure surprised everyone. | তার হঠাৎ চলে যাওয়া সবাইকে অবাক করে।',
    'abscond | v | əbˈskɒnd | æbˈskɑːnd | পালিয়ে যাওয়া | flee, escape | remain, stay | The cashier tried to abscond with the cash. | ক্যাশিয়ার নগদ নিয়ে পালিয়ে যাওয়ার চেষ্টা করে।',
    'absorb | v | əbˈzɔːb | əbˈzɔːrb | শোষণ করা | soak up, take in | emit, release | The sponge will absorb the spill. | স্পঞ্জটি ছড়ানো তরল শোষণ করবে।',
    'abstain | v | əbˈsteɪn | æbˈsteɪn | বিরত থাকা | refrain, forgo | indulge, partake | Doctors asked him to abstain from sugar. | চিকিৎসকরা তাকে চিনি থেকে বিরত থাকতে বলেন।',
    'abstract | adj | ˈæbstrækt | ˈæbstrækt | বিমূর্ত | theoretical, conceptual | concrete, tangible | Justice is an abstract idea. | ন্যায় একটি বিমূর্ত ধারণা।',
    'absurd | adj | əbˈsɜːd | əbˈsɜːrd | অযৌক্তিক | ridiculous, silly | reasonable, sensible | The claim was too absurd to believe. | দাবিটি বিশ্বাস করার মতো অযৌক্তিক ছিল।',
    'abundant | adj | əˈbʌndənt | əˈbʌndənt | প্রচুর | plentiful, ample | scarce, sparse | Rain was abundant that monsoon. | সেই বর্ষায় বৃষ্টি প্রচুর হয়েছিল।',
    'abyss | n | əˈbɪs | əˈbɪs | অতল গহ্বর | gulf, chasm | peak, summit | The path ended at a dark abyss. | পথটি একটি অন্ধকার অতল গহ্বরে গিয়ে শেষ হয়।',
    'accede | v | əkˈsiːd | ækˈsiːd | সম্মত হওয়া | agree, consent | refuse, reject | The board did not accede to the demand. | বোর্ড চাহিদাটিতে সম্মত হয়নি।',
    'accelerate | v | əkˈseləreɪt | ækˈseləˌreɪt | ত্বরান্বিত করা | hasten, quicken | slow, delay | New roads will accelerate trade. | নতুন সড়ক বাণিজ্য ত্বরান্বিত করবে।',
    'accentuate | v | əkˈsentʃueɪt | ækˈsentʃuˌeɪt | জোর দেওয়া | emphasize, highlight | downplay, hide | The lighting will accentuate the painting. | আলো চিত্রকর্মটিতে জোর দেবে।',
    'acclaim | n | əˈkleɪm | əˈkleɪm | প্রশংসা | praise, applause | criticism, blame | The film won critical acclaim. | ছবিটি সমালোচকদের প্রশংসা পায়।',
    'accommodate | v | əˈkɒmədeɪt | əˈkɑːməˌdeɪt | জায়গা দেওয়া | house, lodge | refuse, turn away | The hostel can accommodate forty students. | হোস্টেলে চল্লিশজন শিক্ষার্থীকে জায়গা দেওয়া যায়।',
    'accomplish | v | əˈkʌmplɪʃ | əˈkɑːmplɪʃ | সম্পন্ন করা | achieve, complete | fail, abandon | She will accomplish the task today. | তিনি আজ কাজটি সম্পন্ন করবেন।',
    'accord | n | əˈkɔːd | əˈkɔːrd | চুক্তি | agreement, pact | conflict, clash | The two sides signed a peace accord. | দুই পক্ষ একটি শান্তি চুক্তি সই করে।',
    'accumulate | v | əˈkjuːmjəleɪt | əˈkjuːmjəˌleɪt | জমা হওয়া | gather, amass | disperse, spend | Dust will accumulate if you never clean. | না পরিষ্কার করলে ধুলো জমা হবে।',
    'accurate | adj | ˈækjərət | ˈækjərət | সঠিক | exact, precise | wrong, inaccurate | Give an accurate count of the votes. | ভোটের একটি সঠিক হিসাব দিন।',
    'accuse | v | əˈkjuːz | əˈkjuːz | অভিযোগ করা | charge, blame | defend, excuse | They accuse him of theft. | তারা তাকে চুরির অভিযোগ করে।',
    'accustom | v | əˈkʌstəm | əˈkʌstəm | অভ্যস্ত করা | familiarize, habituate | unsettle, alienate | Living abroad will accustom you to change. | বিদেশে থাকা আপনাকে পরিবর্তনে অভ্যস্ত করবে।',
    'achieve | v | əˈtʃiːv | əˈtʃiːv | অর্জন করা | attain, accomplish | fail, miss | Hard work helped her achieve the grade. | কঠোর পরিশ্রম তাকে গ্রেডটি অর্জন করতে সাহায্য করে।',
    'acknowledge | v | əkˈnɒlɪdʒ | ækˈnɑːlɪdʒ | স্বীকার করা | admit, recognize | deny, ignore | Please acknowledge the email. | অনুগ্রহ করে ইমেইলটি স্বীকার করুন।',
    'acquaint | v | əˈkweɪnt | əˈkweɪnt | পরিচিত করানো | familiarize, inform | hide, conceal | The guide will acquaint you with the city. | গাইড আপনাকে শহরের সঙ্গে পরিচিত করাবেন।',
    'acquire | v | əˈkwaɪə | əˈkwaɪər | অর্জন করা | obtain, gain | lose, forfeit | She hopes to acquire a new skill. | তিনি একটি নতুন দক্ষতা অর্জন করতে চান।',
    'acquit | v | əˈkwɪt | əˈkwɪt | খালাস দেওয়া | clear, exonerate | convict, condemn | The jury voted to acquit the accused. | জুরি অভিযুক্তকে খালাস দেওয়ার পক্ষে ভোট দেয়।',
    'acrid | adj | ˈækrɪd | ˈækrɪd | তীব্র গন্ধযুক্ত | pungent, sharp | mild, sweet | An acrid smoke filled the room. | তীব্র গন্ধযুক্ত ধোঁয়া ঘর ভরে ফেলে।',
    'acute | adj | əˈkjuːt | əˈkjuːt | তীব্র | sharp, severe | mild, dull | He felt an acute pain in the chest. | তিনি বুকে তীব্র ব্যথা অনুভব করেন।',
    'adapt | v | əˈdæpt | əˈdæpt | মানিয়ে নেওয়া | adjust, modify | resist, reject | Plants adapt to dry soil. | গাছপালা শুকনো মাটিতে মানিয়ে নেয়।',
    'adept | adj | əˈdept | əˈdept | দক্ষ | skilled, proficient | clumsy, inept | She is adept at mental arithmetic. | তিনি মানসিক গণিতে দক্ষ।',
    'adequate | adj | ˈædɪkwət | ˈædɪkwət | পর্যাপ্ত | sufficient, enough | insufficient, scant | The water supply is not adequate. | পানির সরবরাহ পর্যাপ্ত নয়।',
    'adhere | v | ədˈhɪə | ədˈhɪr | লেগে থাকা | stick, cling | detach, separate | The stamp did not adhere to the envelope. | স্ট্যাম্পটি খামে লেগে থাকেনি।',
    'adjacent | adj | əˈdʒeɪsnt | əˈdʒeɪsnt | সংলগ্ন | neighbouring, next | distant, remote | The school is adjacent to the park. | স্কুলটি পার্কের সংলগ্ন।',
    'adjoin | v | əˈdʒɔɪn | əˈdʒɔɪn | সংযুক্ত থাকা | border, abut | separate, divide | Our garden will adjoin theirs. | আমাদের বাগান তাদেরটির সঙ্গে সংযুক্ত থাকবে।',
    'adjourn | v | əˈdʒɜːn | əˈdʒɜːrn | স্থগিত করা | postpone, suspend | continue, convene | The court will adjourn until Monday. | আদালত সোমবার পর্যন্ত স্থগিত থাকবে।',
    'adjust | v | əˈdʒʌst | əˈdʒʌst | ঠিক করা | adapt, regulate | disturb, unsettle | Please adjust the volume. | অনুগ্রহ করে ভলিউম ঠিক করুন।',
    'administer | v | ədˈmɪnɪstə | ədˈmɪnɪstər | পরিচালনা করা | manage, run | neglect, mishandle | Nurses administer the medicine. | নার্সরা ওষুধ পরিচালনা করেন।',
    'admonish | v | ədˈmɒnɪʃ | ədˈmɑːnɪʃ | সতর্ক করা | warn, reprimand | praise, commend | Teachers admonish latecomers. | শিক্ষকরা দেরিতে আসা শিক্ষার্থীদের সতর্ক করেন।',
    'adolescent | n | ˌædəˈlesnt | ˌædəˈlesnt | কিশোর | teenager, youth | adult, elder | An adolescent needs patient guidance. | একজন কিশোরের ধৈর্যশীল নির্দেশনা দরকার।',
    'adopt | v | əˈdɒpt | əˈdɑːpt | গ্রহণ করা | take up, embrace | reject, abandon | The city will adopt a new plan. | শহর একটি নতুন পরিকল্পনা গ্রহণ করবে।',
    'adore | v | əˈdɔː | əˈdɔːr | অত্যন্ত ভালোবাসা | love, cherish | hate, despise | Children adore their grandmother. | শিশুরা তাদের দিদিকে অত্যন্ত ভালোবাসে।',
    'adorn | v | əˈdɔːn | əˈdɔːrn | সাজানো | decorate, embellish | strip, deface | Flowers adorn the hall. | ফুল দিয়ে হল সাজানো হয়।',
    'adroit | adj | əˈdrɔɪt | əˈdrɔɪt | নিপুণ | skilful, deft | clumsy, awkward | An adroit speaker calmed the crowd. | একজন নিপুণ বক্তা ভিড়কে শান্ত করেন।',
    'adulation | n | ˌædjuˈleɪʃn | ˌædʒəˈleɪʃn | অতিরিক্ত প্রশংসা | flattery, worship | criticism, scorn | The singer tired of constant adulation. | গায়ক অতিরিক্ত প্রশংসায় ক্লান্ত হয়ে পড়েন।',
    'advent | n | ˈædvent | ˈædvent | আগমন | arrival, coming | departure, end | The advent of printing changed Europe. | মুদ্রণের আগমন ইউরোপকে বদলে দেয়।',
    'adverse | adj | ˈædvɜːs | ædˈvɜːrs | প্রতিকূল | unfavourable, harmful | favourable, helpful | Fog is adverse to flying. | কুয়াশা উড়ানের জন্য প্রতিকূল।',
    'advocate | v | ˈædvəkeɪt | ˈædvəˌkeɪt | পক্ষ সমর্থন করা | support, recommend | oppose, condemn | Doctors advocate daily walking. | চিকিৎসকরা প্রতিদিন হাঁটার পক্ষ সমর্থন করেন।',
    'aesthetic | adj | iːsˈθetɪk | esˈθetɪk | নান্দনিক | artistic, tasteful | ugly, crude | The building has an aesthetic design. | ভবনটির নকশা নান্দনিক।',
    'affable | adj | ˈæfəbl | ˈæfəbl | সহজসরল | friendly, cordial | rude, cold | An affable host welcomed us. | একজন সহজসরল আয়োজক আমাদের স্বাগত জানান।',
    'affection | n | əˈfekʃn | əˈfekʃn | স্নেহ | fondness, love | hatred, dislike | She showed great affection for the child. | তিনি শিশুটির প্রতি গভীর স্নেহ দেখান।',
    'affiliate | v | əˈfɪlieɪt | əˈfɪliˌeɪt | সংযুক্ত হওয়া | associate, join | separate, detach | The college will affiliate with the university. | কলেজটি বিশ্ববিদ্যালয়ের সঙ্গে সংযুক্ত হবে।',
    'affinity | n | əˈfɪnəti | əˈfɪnəti | ঘনিষ্ঠতা | kinship, closeness | aversion, dislike | He felt an affinity with the sea. | তিনি সমুদ্রের সঙ্গে এক ঘনিষ্ঠতা অনুভব করেন।',
    'affirm | v | əˈfɜːm | əˈfɜːrm | নিশ্চিত করা | confirm, assert | deny, contradict | Witnesses affirm what they saw. | সাক্ষীরা যা দেখেছেন তা নিশ্চিত করেন।',
    'afflict | v | əˈflɪkt | əˈflɪkt | ভোগানো | torment, trouble | comfort, relieve | Drought will afflict the farms. | খরা খামারগুলোকে ভোগাবে।',
    'affluent | adj | ˈæfluənt | ˈæfluənt | ধনী | wealthy, rich | poor, needy | An affluent neighbourhood lined the river. | নদীর ধারে একটি ধনী পাড়া ছিল।',
    'affront | n | əˈfrʌnt | əˈfrʌnt | অপমান | insult, slight | compliment, honour | The remark was an affront to her. | মন্তব্যটি তার প্রতি অপমান ছিল।',
    'aftermath | n | ˈɑːftəmæθ | ˈæftərmæθ | পরিণতি | consequence, wake | prelude, cause | In the aftermath of the flood, roads closed. | বন্যার পরিণতিতে সড়ক বন্ধ হয়ে যায়।',
    'aggravate | v | ˈæɡrəveɪt | ˈæɡrəˌveɪt | আরও খারাপ করা | worsen, intensify | soothe, ease | Scratching will aggravate the rash. | চুলকানো ফুসকুড়ি আরও খারাপ করবে।',
    'aggregate | n | ˈæɡrɪɡət | ˈæɡrɪɡət | মোট | total, sum | part, fragment | The aggregate score decided the match. | মোট স্কোর ম্যাচটির ফয়সালা করে।',
    'aggressive | adj | əˈɡresɪv | əˈɡresɪv | আক্রমণাত্মক | hostile, forceful | gentle, passive | An aggressive tackle earned a card. | একটি আক্রমণাত্মক ট্যাকলে কার্ড হয়।',
    'aghast | adj | əˈɡɑːst | əˈɡæst | স্তম্ভিত | horrified, stunned | calm, unmoved | We stood aghast at the news. | খবরে আমরা স্তম্ভিত হয়ে দাঁড়াই।',
    'agile | adj | ˈædʒaɪl | ˈædʒl | চটপটে | nimble, quick | clumsy, slow | The cat is too agile to catch. | বিড়ালটি ধরার জন্য খুব চটপটে।',
    'agitate | v | ˈædʒɪteɪt | ˈædʒɪˌteɪt | উত্তেজিত করা | stir, upset | calm, soothe | Loud noise can agitate the animals. | জোরে শব্দ প্রাণীদের উত্তেজিত করতে পারে।',
    'agony | n | ˈæɡəni | ˈæɡəni | তীব্র যন্ত্রণা | torment, anguish | comfort, ease | He cried out in agony. | তিনি তীব্র যন্ত্রণায় চিৎকার করেন।',
    'ailment | n | ˈeɪlmənt | ˈeɪlmənt | অসুখ | illness, disorder | health, wellness | A minor ailment kept her home. | একটি ছোট অসুখ তাকে ঘরে রাখে।',
    'ajar | adj | əˈdʒɑː | əˈdʒɑːr | আধখোলা | open, unlatched | shut, closed | Leave the door ajar for air. | বাতাসের জন্য দরজা আধখোলা রাখুন।',
    'akin | adj | əˈkɪn | əˈkɪn | সদৃশ | similar, related | unlike, different | His fear is akin to panic. | তার ভয় আতঙ্কের সদৃশ।',
    'alacrity | n | əˈlækrəti | əˈlækrəti | তৎপরতা | eagerness, readiness | reluctance, delay | She accepted the offer with alacrity. | তিনি তৎপরতার সঙ্গে প্রস্তাব গ্রহণ করেন।',
    'alienate | v | ˈeɪliəneɪt | ˈeɪliəˌneɪt | দূরে সরিয়ে দেওয়া | estrange, isolate | unite, attract | Harsh words alienate friends. | কঠোর কথা বন্ধুদের দূরে সরিয়ে দেয়।',
    'allay | v | əˈleɪ | əˈleɪ | প্রশমিত করা | ease, soothe | provoke, inflame | Facts can allay public fear. | তথ্য জনগণের ভয় প্রশমিত করতে পারে।',
    'allege | v | əˈledʒ | əˈledʒ | অভিযোগ করা | claim, assert | deny, retract | Papers allege misuse of funds. | পত্রিকা তহবিলের অপব্যবহারের অভিযোগ করে।',
    'allegiance | n | əˈliːdʒəns | əˈliːdʒəns | আনুগত্য | loyalty, fidelity | treachery, revolt | Soldiers swore allegiance to the flag. | সৈন্যরা পতাকার প্রতি আনুগত্যের শপথ নেয়।',
    'alleviate | v | əˈliːvieɪt | əˈliːviˌeɪt | লাঘব করা | ease, relieve | worsen, aggravate | Rest will alleviate the pain. | বিশ্রাম ব্যথা লাঘব করবে।',
    'allocate | v | ˈæləkeɪt | ˈæləˌkeɪt | বরাদ্দ করা | assign, allot | withhold, deny | The city will allocate funds for parks. | শহর পার্কের জন্য তহবিল বরাদ্দ করবে।',
    'allude | v | əˈluːd | əˈluːd | ইঙ্গিত করা | hint, refer | state, specify | Do not allude to the secret. | গোপন বিষয়ে ইঙ্গিত করবেন না।',
    'allure | n | əˈljʊə | əˈlʊr | আকর্ষণ | charm, appeal | repulsion, ugliness | The allure of the city drew them in. | শহরের আকর্ষণ তাদের টেনে আনে।',
    'aloof | adj | əˈluːf | əˈluːf | দূরত্ব রক্ষা করা | distant, detached | friendly, warm | He remained aloof from the argument. | তিনি তর্ক থেকে দূরত্ব রক্ষা করেন।',
    'alter | v | ˈɔːltə | ˈɔːltər | পরিবর্তন করা | change, modify | keep, preserve | We must alter the plan. | আমাদের পরিকল্পনা পরিবর্তন করতে হবে।',
    'altruism | n | ˈæltruɪzəm | ˈæltruˌɪzəm | পরার্থপরতা | selflessness, generosity | selfishness, greed | True altruism asks for nothing back. | প্রকৃত পরার্থপরতা প্রতিদান চায় না।',
    'amalgamate | v | əˈmælɡəmeɪt | əˈmælɡəˌmeɪt | একত্র করা | merge, combine | separate, split | The two firms will amalgamate next year. | দুই প্রতিষ্ঠান আগামী বছর একত্র হবে।',
    'amass | v | əˈmæs | əˈmæs | জমানো | accumulate, gather | scatter, spend | He did not amass wealth overnight. | তিনি এক রাতে সম্পদ জমাননি।',
    'ambiguous | adj | æmˈbɪɡjuəs | æmˈbɪɡjuəs | দ্ব্যর্থক | unclear, vague | clear, definite | The rule is too ambiguous to apply. | নিয়মটি প্রয়োগ করার মতো দ্ব্যর্থক।',
    'ambivalent | adj | æmˈbɪvələnt | æmˈbɪvələnt | দ্বিধাগ্রস্ত | uncertain, mixed | decided, certain | She felt ambivalent about leaving. | চলে যাওয়া নিয়ে তিনি দ্বিধাগ্রস্ত ছিলেন।',
    'amble | v | ˈæmbl | ˈæmbl | ধীরে হাঁটা | stroll, saunter | rush, hurry | We amble along the river each evening. | আমরা প্রতি সন্ধ্যায় নদীর ধারে ধীরে হাঁটি।',
    'ameliorate | v | əˈmiːliəreɪt | əˈmiːliəˌreɪt | উন্নত করা | improve, better | worsen, impair | Aid can ameliorate living conditions. | সাহায্য জীবনযাত্রা উন্নত করতে পারে।',
    'amenable | adj | əˈmiːnəbl | əˈmiːnəbl | সহজে রাজি | agreeable, compliant | stubborn, resistant | He was amenable to the change. | তিনি পরিবর্তনে সহজে রাজি ছিলেন।',
    'amiable | adj | ˈeɪmiəbl | ˈeɪmiəbl | বন্ধুত্বপূর্ণ | friendly, pleasant | hostile, surly | An amiable neighbour helped us move. | একজন বন্ধুত্বপূর্ণ প্রতিবেশী আমাদের সরাতে সাহায্য করেন।',
    'amicable | adj | ˈæmɪkəbl | ˈæmɪkəbl | সৌহার্দ্যপূর্ণ | cordial, peaceful | hostile, bitter | They reached an amicable settlement. | তারা একটি সৌহার্দ্যপূর্ণ মীমাংসায় পৌঁছায়।',
    'amnesty | n | ˈæmnəsti | ˈæmnəsti | সাধারণ ক্ষমা | pardon, reprieve | punishment, penalty | The state declared an amnesty for debt. | রাষ্ট্র ঋণের জন্য সাধারণ ক্ষমা ঘোষণা করে।',
    'amorphous | adj | əˈmɔːfəs | əˈmɔːrfəs | আকারহীন | shapeless, formless | defined, distinct | An amorphous cloud covered the sun. | একটি আকারহীন মেঘ সূর্য ঢেকে দেয়।',
    'amplify | v | ˈæmplɪfaɪ | ˈæmplɪˌfaɪ | বাড়ানো | increase, boost | reduce, mute | A mic will amplify her voice. | মাইক তার কণ্ঠ বাড়াবে।',
    'analogy | n | əˈnælədʒi | əˈnælədʒi | উপমা | comparison, parallel | contrast, difference | He explained gravity by analogy. | তিনি উপমা দিয়ে মাধ্যাকর্ষণ বোঝান।',
    'anarchy | n | ˈænəki | ˈænərki | নৈরাজ্য | chaos, disorder | order, rule | Without police the town fell into anarchy. | পুলিশ ছাড়া শহর নৈরাজ্যে পড়ে।',
    'anecdote | n | ˈænɪkdəʊt | ˈænɪkˌdoʊt | ক্ষুদ্র কাহিনি | story, tale | treatise, lecture | She told a funny anecdote about school. | তিনি স্কুল নিয়ে একটি মজার ক্ষুদ্র কাহিনি বলেন।',
    'anguish | n | ˈæŋɡwɪʃ | ˈæŋɡwɪʃ | মর্মপীড়া | torment, grief | joy, relief | His face showed deep anguish. | তার মুখে গভীর মর্মপীড়া ফুটে ওঠে।',
    'animosity | n | ˌænɪˈmɒsəti | ˌænəˈmɑːsəti | শত্রুতা | hostility, hatred | friendship, goodwill | Old animosity still divides the clubs. | পুরনো শত্রুতা এখনও ক্লাবগুলোকে ভাগ করে।',
    'annex | v | əˈneks | əˈneks | দখল করা | seize, add | cede, surrender | The empire tried to annex the island. | সাম্রাজ্য দ্বীপটি দখল করার চেষ্টা করে।',
    'annihilate | v | əˈnaɪəleɪt | əˈnaɪəˌleɪt | সম্পূর্ণ ধ্বংস করা | destroy, wipe out | preserve, create | One bomb can annihilate a city. | একটি বোমা একটি শহর সম্পূর্ণ ধ্বংস করতে পারে।',
    'annotate | v | ˈænəteɪt | ˈænəˌteɪt | টীকা দেওয়া | comment, gloss | erase, omit | Please annotate the poem in the margin. | অনুগ্রহ করে কবিতায় মার্জিনে টীকা দিন।',
    'annul | v | əˈnʌl | əˈnʌl | বাতিল করা | cancel, void | confirm, ratify | The court may annul the contract. | আদালত চুক্তিটি বাতিল করতে পারে।',
    'anomalous | adj | əˈnɒmələs | əˈnɑːmələs | অস্বাভাবিক | irregular, abnormal | normal, typical | The reading was anomalous and checked again. | পাঠটি অস্বাভাবিক ছিল বলে আবার যাচাই হয়।',
    'anonymous | adj | əˈnɒnɪməs | əˈnɑːnɪməs | বেনামি | unnamed, unknown | named, identified | An anonymous donor paid the fees. | এক বেনামি দাতা ফি পরিশোধ করেন।',
    'antagonize | v | ænˈtæɡənaɪz | ænˈtæɡəˌnaɪz | শত্রু বানানো | provoke, alienate | soothe, befriend | Do not antagonize the neighbours. | প্রতিবেশীদের শত্রু বানাবেন না।',
    'anticipate | v | ænˈtɪsɪpeɪt | ænˈtɪsəˌpeɪt | আগে থেকে আশা করা | expect, foresee | doubt, miss | We anticipate a late monsoon. | আমরা দেরিতে বর্ষা আগে থেকে আশা করি।',
    'antidote | n | ˈæntidəʊt | ˈæntiˌdoʊt | প্রতিষেধক | remedy, cure | poison, toxin | There is an antidote for that bite. | সেই কামড়ের একটি প্রতিষেধক আছে।',
    'antipathy | n | ænˈtɪpəθi | ænˈtɪpəθi | বিদ্বেষ | dislike, aversion | liking, fondness | He felt a strong antipathy to lies. | তিনি মিথ্যার প্রতি তীব্র বিদ্বেষ অনুভব করেন।',
    'antiquated | adj | ˈæntɪkweɪtɪd | ˈæntɪˌkweɪtɪd | পুরনো ধাঁচের | outdated, obsolete | modern, current | The law looks antiquated now. | আইনটি এখন পুরনো ধাঁচের মনে হয়।',
    'antithesis | n | ænˈtɪθəsɪs | ænˈtɪθəsɪs | বিপরীত | opposite, contrast | copy, match | Peace is the antithesis of war. | শান্তি যুদ্ধের বিপরীত।',
    'anxiety | n | æŋˈzaɪəti | æŋˈzaɪəti | উদ্বেগ | worry, unease | calm, ease | Exam anxiety kept her awake. | পরীক্ষার উদ্বেগ তাকে জাগিয়ে রাখে।',
    'apathetic | adj | ˌæpəˈθetɪk | ˌæpəˈθetɪk | উদাসীন | indifferent, listless | eager, keen | Voters seemed apathetic this year. | এ বছর ভোটাররা উদাসীন মনে হয়েছিল।',
    'apathy | n | ˈæpəθi | ˈæpəθi | উদাসীনতা | indifference, unconcern | interest, zeal | Public apathy delayed the reform. | জনগণের উদাসীনতা সংস্কার দেরি করায়।',
    'apex | n | ˈeɪpeks | ˈeɪpeks | শীর্ষ | peak, summit | base, bottom | She reached the apex of her career. | তিনি ক্যারিয়ারের শীর্ষে পৌঁছান।',
    'aplomb | n | əˈplɒm | əˈplɑːm | আত্মবিশ্বাস | poise, composure | panic, unease | She answered with perfect aplomb. | তিনি পূর্ণ আত্মবিশ্বাসে উত্তর দেন।',
    'appal | v | əˈpɔːl | əˈpɔːl | ভয়ঙ্করভাবে নাড়ানো | shock, horrify | delight, please | The waste will appal visitors. | অপচয় দর্শকদের ভয়ঙ্করভাবে নাড়াবে।',
    'appease | v | əˈpiːz | əˈpiːz | শান্ত করা | pacify, soothe | provoke, inflame | A snack may appease the child. | একটি নাশতা শিশুকে শান্ত করতে পারে।',
    'applaud | v | əˈplɔːd | əˈplɔːd | করতালি দেওয়া | clap, praise | boo, criticise | The crowd will applaud the speech. | ভিড় বক্তৃতায় করতালি দেবে।',
    'apposite | adj | ˈæpəzɪt | ˈæpəzɪt | প্রাসঙ্গিক | apt, relevant | irrelevant, odd | That quote was apposite. | সেই উদ্ধৃতিটি প্রাসঙ্গিক ছিল।',
    'appraise | v | əˈpreɪz | əˈpreɪz | মূল্যায়ন করা | assess, value | ignore, guess | Banks appraise the house before a loan. | ঋণের আগে ব্যাংক বাড়ি মূল্যায়ন করে।',
    'appreciate | v | əˈpriːʃieɪt | əˈpriːʃiˌeɪt | কদর করা | value, treasure | scorn, ignore | I appreciate your help. | আমি আপনার সাহায্যের কদর করি।',
    'apprehend | v | ˌæprɪˈhend | ˌæprɪˈhend | গ্রেফতার করা | arrest, catch | release, free | Police hope to apprehend the thief. | পুলিশ চোরকে গ্রেফতার করতে চায়।',
    'apprentice | n | əˈprentɪs | əˈprentɪs | শিক্ষানবিশ | trainee, learner | master, expert | The apprentice watched the carpenter. | শিক্ষানবিশ ছুতারকে দেখছিলেন।',
    'appropriate | adj | əˈprəʊpriət | əˈproʊpriət | উপযুক্ত | suitable, fitting | improper, wrong | Wear appropriate clothes for the lab. | ল্যাবের জন্য উপযুক্ত পোশাক পরুন।',
    'apt | adj | æpt | æpt | উপযোগী | suitable, likely | unfit, unlikely | Rain is apt to fall in June. | জুনে বৃষ্টি পড়ার উপযোগী।',
    'aptitude | n | ˈæptɪtjuːd | ˈæptɪˌtuːd | স্বাভাবিক দক্ষতা | talent, knack | ineptitude, weakness | She has an aptitude for languages. | তার ভাষায় স্বাভাবিক দক্ষতা আছে।',
    'arbitrary | adj | ˈɑːbɪtrəri | ˈɑːrbəˌtreri | খেয়ালখুশি | random, capricious | reasoned, fair | An arbitrary rule angered staff. | একটি খেয়ালখুশির নিয়ম কর্মীদের রাগায়।',
    'arcane | adj | ɑːˈkeɪn | ɑːrˈkeɪn | গূঢ় | obscure, mysterious | plain, obvious | The rite uses arcane symbols. | অনুষ্ঠানে গূঢ় প্রতীক ব্যবহার হয়।',
    'archaic | adj | ɑːˈkeɪɪk | ɑːrˈkeɪɪk | প্রাচীন | obsolete, old | modern, current | That word is archaic in speech. | সেই শব্দ কথায় প্রাচীন।',
    'ardent | adj | ˈɑːdnt | ˈɑːrdnt | উৎসাহী | passionate, eager | cool, indifferent | He is an ardent reader of history. | তিনি ইতিহাসের একজন উৎসাহী পাঠক।',
    'arduous | adj | ˈɑːdjuəs | ˈɑːrdʒuəs | কষ্টসাধ্য | difficult, taxing | easy, light | The climb was arduous in the heat. | গরমে আরোহণ কষ্টসাধ্য ছিল।',
    'arid | adj | ˈærɪd | ˈærɪd | শুষ্ক | dry, barren | wet, fertile | Crops fail in arid land. | শুষ্ক জমিতে ফসল হয় না।',
    'aroma | n | əˈrəʊmə | əˈroʊmə | সুগন্ধ | scent, fragrance | stench, odour | Coffee filled the room with aroma. | কফি ঘর সুগন্ধে ভরে দেয়।',
    'arouse | v | əˈraʊz | əˈraʊz | জাগানো | awaken, stir | calm, lull | The speech will arouse the crowd. | বক্তৃতা ভিড়কে জাগাবে।',
    'arraign | v | əˈreɪn | əˈreɪn | আদালতে হাজির করা | charge, accuse | acquit, free | The court will arraign him tomorrow. | আদালত আগামীকাল তাকে হাজির করবে।',
    'arrogant | adj | ˈærəɡənt | ˈærəɡənt | অহংকারী | conceited, haughty | humble, modest | An arrogant reply lost the deal. | একটি অহংকারী উত্তর চুক্তি হারায়।',
    'articulate | v | ɑːˈtɪkjuleɪt | ɑːrˈtɪkjəˌleɪt | স্পষ্ট করে বলা | express, voice | mumble, hide | She can articulate the problem well. | তিনি সমস্যাটি স্পষ্ট করে বলতে পারেন।',
    'ascend | v | əˈsend | əˈsend | ওপরে ওঠা | climb, rise | descend, fall | We ascend the hill before dawn. | আমরা ভোরের আগে পাহাড়ে ওপরে উঠি।',
    'ascertain | v | ˌæsəˈteɪn | ˌæsərˈteɪn | নিশ্চিতভাবে জানা | determine, confirm | guess, assume | Please ascertain the train time. | অনুগ্রহ করে ট্রেনের সময় নিশ্চিতভাবে জানুন।',
    'ascetic | adj | əˈsetɪk | əˈsetɪk | কঠোর সংযমী | austere, spare | indulgent, luxurious | An ascetic life suited the monk. | কঠোর সংযমী জীবন সন্ন্যাসীর উপযোগী ছিল।',
    'ascribe | v | əˈskraɪb | əˈskraɪb | আরোপ করা | attribute, assign | deny, withhold | They ascribe the win to luck. | তারা জয়কে ভাগ্যের ওপর আরোপ করে।',
    'asinine | adj | ˈæsɪnaɪn | ˈæsɪˌnaɪn | নির্বোধ | foolish, stupid | wise, sensible | That was an asinine mistake. | সেটি একটি নির্বোধ ভুল ছিল।',
    'aspire | v | əˈspaɪə | əˈspaɪər | উচ্চাকাঙ্ক্ষা করা | aim, yearn | resign, settle | Many students aspire to study abroad. | অনেক শিক্ষার্থী বিদেশে পড়ার উচ্চাকাঙ্ক্ষা করে।',
    'assail | v | əˈseɪl | əˈseɪl | আক্রমণ করা | attack, assault | defend, protect | Critics assail the new policy. | সমালোচকরা নতুন নীতিকে আক্রমণ করেন।',
    'assert | v | əˈsɜːt | əˈsɜːrt | দাবি করা | declare, maintain | deny, retract | Witnesses assert they saw the car. | সাক্ষীরা গাড়ি দেখার দাবি করেন।',
    'assess | v | əˈses | əˈses | মূল্যায়ন করা | evaluate, judge | ignore, guess | Teachers assess the essays. | শিক্ষকরা রচনা মূল্যায়ন করেন।',
    'assiduous | adj | əˈsɪdjuəs | əˈsɪdʒuəs | অধ্যবসায়ী | diligent, industrious | lazy, idle | Assiduous practice improved her score. | অধ্যবসায়ী অনুশীলন তার স্কোর বাড়ায়।',
    'assimilate | v | əˈsɪməleɪt | əˈsɪməˌleɪt | মিশে যাওয়া | absorb, integrate | reject, isolate | Newcomers slowly assimilate the language. | নতুনরা ধীরে ধীরে ভাষায় মিশে যায়।',
    'assuage | v | əˈsweɪdʒ | əˈsweɪdʒ | প্রশমিত করা | ease, soothe | inflame, worsen | Kind words assuage grief. | সদয় কথা শোক প্রশমিত করে।',
    'assume | v | əˈsjuːm | əˈsuːm | অনুমান করা | suppose, presume | know, prove | Do not assume the worst. | সবচেয়ে খারাপ অনুমান করবেন না।',
    'astonish | v | əˈstɒnɪʃ | əˈstɑːnɪʃ | অবাক করা | amaze, surprise | bore, dull | The trick will astonish the children. | কৌশলটি শিশুদের অবাক করবে।',
    'astute | adj | əˈstjuːt | əˈstuːt | ধূর্ত বুদ্ধিসম্পন্ন | shrewd, clever | naive, dull | An astute buyer waited for the sale. | একজন ধূর্ত বুদ্ধিসম্পন্ন ক্রেতা সেলের অপেক্ষা করেন।',
    'asylum | n | əˈsaɪləm | əˈsaɪləm | আশ্রয় | refuge, shelter | exile, danger | They sought asylum after the war. | যুদ্ধের পর তারা আশ্রয় চায়।',
    'atone | v | əˈtəʊn | əˈtoʊn | প্রায়শ্চিত্ত করা | make amends, redeem | offend, harm | He tried to atone for the error. | তিনি ভুলের জন্য প্রায়শ্চিত্ত করার চেষ্টা করেন।',
    'atrocious | adj | əˈtrəʊʃəs | əˈtroʊʃəs | জঘন্য | dreadful, horrible | excellent, fine | The food was atrocious. | খাবারটি জঘন্য ছিল।',
    'atrocity | n | əˈtrɒsəti | əˈtrɑːsəti | নৃশংসতা | outrage, horror | kindness, mercy | The report listed every atrocity. | প্রতিবেদন প্রতিটি নৃশংসতা তালিকা করে।',
    'atrophy | v | ˈætrəfi | ˈætrəfi | ক্ষয় হওয়া | waste, wither | grow, strengthen | Unused muscles atrophy. | অব্যবহৃত পেশী ক্ষয় হয়।',
    'attain | v | əˈteɪn | əˈteɪn | অর্জন করা | reach, achieve | miss, fail | She hopes to attain a first class. | তিনি ফার্স্ট ক্লাস অর্জন করতে চান।',
    'attenuate | v | əˈtenjueɪt | əˈtenjuˌeɪt | দুর্বল করা | weaken, reduce | strengthen, intensify | Distance will attenuate the signal. | দূরত্ব সংকেত দুর্বল করবে।',
    'attest | v | əˈtest | əˈtest | সাক্ষ্য দেওয়া | confirm, certify | deny, dispute | Records attest to her work. | নথি তার কাজের সাক্ষ্য দেয়।',
    'attire | n | əˈtaɪə | əˈtaɪər | পোশাক | clothing, dress | - | Formal attire is required. | আনুষ্ঠানিক পোশাক প্রয়োজন।',
    'attribute | v | əˈtrɪbjuːt | əˈtrɪbjut | আরোপ করা | ascribe, credit | deny, withhold | They attribute the win to teamwork. | তারা জয়কে দলগত কাজের ওপর আরোপ করে।',
    'attrition | n | əˈtrɪʃn | əˈtrɪʃn | ক্ষয় | erosion, wearing | growth, increase | Staff left through slow attrition. | কর্মীরা ধীর ক্ষয়ে চলে যায়।',
    'audacious | adj | ɔːˈdeɪʃəs | ɔːˈdeɪʃəs | দুঃসাহসী | bold, daring | timid, cautious | An audacious plan won the match. | একটি দুঃসাহসী পরিকল্পনা ম্যাচ জেতে।',
    'audible | adj | ˈɔːdəbl | ˈɔːdəbl | শোনা যায় এমন | hearable, clear | silent, faint | Keep your voice audible at the back. | পেছনে যেন কণ্ঠ শোনা যায় এমন রাখুন।',
    'augment | v | ɔːɡˈment | ɔːɡˈment | বৃদ্ধি করা | increase, enlarge | reduce, decrease | Extra staff will augment the team. | অতিরিক্ত কর্মী দল বৃদ্ধি করবে।',
    'auspicious | adj | ɔːˈspɪʃəs | ɔːˈspɪʃəs | শুভ | favourable, promising | ominous, unlucky | Dawn was an auspicious start. | ভোর একটি শুভ শুরু ছিল।',
    'austere | adj | ɒˈstɪə | ɔːˈstɪr | কঠোর সরল | severe, stark | luxurious, ornate | The room was austere and bare. | ঘরটি কঠোর সরল ও খালি ছিল।',
    'authentic | adj | ɔːˈθentɪk | ɔːˈθentɪk | প্রামাণিক | genuine, real | fake, false | The museum shows authentic letters. | জাদুঘর প্রামাণিক চিঠি দেখায়।',
    'authoritative | adj | ɔːˈθɒrɪtətɪv | əˈθɔːrəˌteɪtɪv | কর্তৃত্বপূর্ণ | official, reliable | dubious, weak | Use an authoritative source. | একটি কর্তৃত্বপূর্ণ উৎস ব্যবহার করুন।',
    'autonomy | n | ɔːˈtɒnəmi | ɔːˈtɑːnəmi | স্বায়ত্তশাসন | independence, self-rule | dependence, control | The region wants more autonomy. | অঞ্চলটি আরও স্বায়ত্তশাসন চায়।',
    'avarice | n | ˈævərɪs | ˈævərɪs | লোভ | greed, cupidity | generosity, charity | Avarice ruined the trader. | লোভ ব্যবসায়ীকে ধ্বংস করে।',
    'avenge | v | əˈvendʒ | əˈvendʒ | প্রতিশোধ নেওয়া | revenge, repay | forgive, pardon | He swore to avenge the insult. | তিনি অপমানের প্রতিশোধ নেওয়ার শপথ করেন।',
    'averse | adj | əˈvɜːs | əˈvɜːrs | অনিচ্ছুক | unwilling, opposed | eager, keen | She is averse to risk. | তিনি ঝুঁকিতে অনিচ্ছুক।',
    'avert | v | əˈvɜːt | əˈvɜːrt | এড়ানো | prevent, avoid | cause, invite | Quick action can avert disaster. | দ্রুত পদক্ষেপ বিপর্যয় এড়াতে পারে।',
    'avid | adj | ˈævɪd | ˈævɪd | উদগ্র | eager, keen | indifferent, apathetic | He is an avid cricket fan. | তিনি একজন উদগ্র ক্রিকেট অনুরাগী।',
    'avow | v | əˈvaʊ | əˈvaʊ | প্রকাশ্যে স্বীকার করা | declare, admit | deny, hide | They avow their support for reform. | তারা সংস্কারের সমর্থন প্রকাশ্যে স্বীকার করে।',
    'awe | n | ɔː | ɑː | বিস্ময় | wonder, reverence | contempt, scorn | The mountain filled them with awe. | পাহাড় তাদের বিস্ময়ে ভরে দেয়।',
    'awkward | adj | ˈɔːkwəd | ˈɔːkwərd | অস্বস্তিকর | clumsy, uneasy | graceful, easy | An awkward silence followed. | একটি অস্বস্তিকর নীরবতা অনুসরণ করে।',
    'awry | adj | əˈraɪ | əˈraɪ | বিগড়ে যাওয়া | amiss, askew | right, straight | The plan went awry in the rain. | বৃষ্টিতে পরিকল্পনা বিগড়ে যায়।',
    'axiom | n | ˈæksiəm | ˈæksiəm | স্বতঃসিদ্ধ | principle, truism | paradox, doubt | It is an axiom that practice helps. | অনুশীলন সাহায্য করে এটি একটি স্বতঃসিদ্ধ।',
    'azure | adj | ˈæʒə | ˈæʒər | আকাশনীল | sky-blue, blue | - | An azure sky followed the storm. | ঝড়ের পর আকাশনীল আকাশ দেখা যায়।',
  ],
};
