import { type IRawFormalInformalGroup } from './schema';

/**
 * Further informal → formal swaps, to bring the list to a thousand.
 *
 * Same pairing as the common file: the everyday word, and the letter word.
 * Kept in its own topic so a learner can filter to "the extra bank" without
 * losing the original EngDic set.
 */
export const PAIRS_MORE: IRawFormalInformalGroup = {
  topic: 'more',
  entries: [
    'stuff | materials | stʌf | məˈtɪəriəlz | জিনিসপত্র | উপকরণ',
    'things | items | θɪŋz | ˈaɪtəmz | জিনিস | বিষয়সমূহ',
    'lots of | a great deal of | ˈlɒts ɒv | ə ɡreɪt diːl ɒv | অনেক | প্রচুর',
    'very | extremely | ˈveri | ɪkˈstriːmli | খুব | অত্যন্ত',
    'really | genuinely | ˈrɪəli | ˈdʒenjuɪnli | সত্যিই | প্রকৃতপক্ষে',
    'so much | considerably | səʊ mʌtʃ | kənˈsɪdərəbli | এতটা | উল্লেখযোগ্যভাবে',
    'too | excessively | tuː | ɪkˈsesɪvli | খুব বেশি | অতিরিক্ত',
    'nice | pleasant | naɪs | ˈpleznt | ভালো | মনোরম',
    'great | considerable | ɡreɪt | kənˈsɪdərəbl | দারুণ | উল্লেখযোগ্য',
    'huge | substantial | hjuːdʒ | səbˈstænʃl | বিশাল | যথেষ্ট পরিমাণ',
    'tiny | minute | ˈtaɪni | maɪˈnjuːt | খুব ছোট | অতি ক্ষুদ্র',
    'easy | straightforward | ˈiːzi | ˌstreɪtˈfɔːwəd | সহজ | সরল',
    'hard | arduous | hɑːd | ˈɑːdjuəs | কঠিন | দুঃসাধ্য',
    'new | novel | njuː | ˈnɒvl | নতুন | নতুনতর',
    'old fashioned | outdated | əʊld ˈfæʃnd | ˌaʊtˈdeɪtɪd | পুরনো ধরনের | সেকেলে',
    'weird | peculiar | wɪəd | pɪˈkjuːliə | অদ্ভুত | বিচিত্র',
    'crazy | absurd | ˈkreɪzi | əbˈsɜːd | পাগল | অযৌক্তিক',
    'ok | satisfactory | ˌəʊˈkeɪ | ˌsætɪsˈfæktəri | ঠিক আছে | সন্তোষজনক',
    'yes | affirmative | jes | əˈfɜːmətɪv | হ্যাঁ | সম্মতিসূচক',
    'no | negative | nəʊ | ˈneɡətɪv | না | নেতিবাচক',
    'sorry | regretful | ˈsɒri | rɪˈɡretfl | দুঃখিত | অনুতপ্ত',
    'please | kindly | pliːz | ˈkaɪndli | দয়া করে | অনুগ্রহপূর্বক',
    'thanks a lot | many thanks | θæŋks ə lɒt | ˈmeni θæŋks | অনেক ধন্যবাদ | বহু ধন্যবাদ',
    'hello | greetings | həˈləʊ | ˈɡriːtɪŋz | হ্যালো | অভিবাদন',
    'bye | farewell | baɪ | ˌfeəˈwel | বিদায় | বিদায় সম্ভাষণ',
    'guy | gentleman | ɡaɪ | ˈdʒentlmən | ছেলে | ভদ্রলোক',
    'guys | individuals | ɡaɪz | ˌɪndɪˈvɪdʒuəlz | লোকজন | ব্যক্তিবর্গ',
    'man | gentleman | mæn | ˈdʒentlmən | মানুষ | ভদ্রলোক',
    'woman | lady | ˈwʊmən | ˈleɪdi | নারী | মহিলা',
    'people | persons | ˈpiːpl | ˈpɜːsnz | মানুষ | ব্যক্তিগণ',
    'home | residence | həʊm | ˈrezɪdəns | বাড়ি | বাসস্থান',
    'house | dwelling | haʊs | ˈdwelɪŋ | বাড়ি | আবাস',
    'room | chamber | ruːm | ˈtʃeɪmbə | ঘর | কক্ষ',
    'place | location | pleɪs | ləʊˈkeɪʃn | জায়গা | অবস্থান',
    'area | vicinity | ˈeəriə | vəˈsɪnəti | এলাকা | পার্শ্ববর্তী অঞ্চল',
    'town | municipality | taʊn | mjuːˌnɪsɪˈpæləti | শহর | পৌরসভা',
    'city | metropolis | ˈsɪti | məˈtrɒpəlɪs | মহানগর | মহানগরী',
    'country | nation | ˈkʌntri | ˈneɪʃn | দেশ | রাষ্ট্র',
    'world | globe | wɜːld | ɡləʊb | পৃথিবী | বিশ্ব',
    'money | funds | ˈmʌni | fʌndz | টাকা | তহবিল',
    'cash | currency | kæʃ | ˈkʌrənsi | নগদ | মুদ্রা',
    'price | cost | praɪs | kɒst | দাম | মূল্য',
    'cheap | economical | tʃiːp | ˌiːkəˈnɒmɪkl | সস্তা | মিতব্যয়ী',
    'expensive | costly | ɪkˈspensɪv | ˈkɒstli | দামি | ব্যয়বহুল',
    'free | complimentary | friː | ˌkɒmplɪˈmentri | বিনামূল্যে | শুভেচ্ছা সূচক',
    'work | labour | wɜːk | ˈleɪbə | কাজ | শ্রম',
    'worker | employee | ˈwɜːkə | ɪmˈplɔɪiː | কর্মী | কর্মচারী',
    'shop | retail outlet | ʃɒp | ˈriːteɪl ˈaʊtlet | দোকান | খুচরা বিক্রয়কেন্দ্র',
    'store | establishment | stɔː | ɪˈstæblɪʃmənt | দোকান | প্রতিষ্ঠান',
    'buy | acquire | baɪ | əˈkwaɪə | কেনা | অর্জন করা',
    'sell | vend | sel | vend | বেচা | বিক্রয় করা',
    'pay | remunerate | peɪ | rɪˈmjuːnəreɪt | দেওয়া | পারিশ্রমিক দেওয়া',
    'cost | amount to | kɒst | əˈmaʊnt tuː | খরচ | দাঁড়ানো',
    'save | conserve | seɪv | kənˈsɜːv | বাঁচানো | সংরক্ষণ করা',
    'spend | expend | spend | ɪkˈspend | খরচ করা | ব্যয় করা',
    'waste | squander | weɪst | ˈskwɒndə | নষ্ট করা | অপচয় করা',
    'need | necessitate | niːd | nəˈsesɪteɪt | দরকার | অপরিহার্য করা',
    'want | require | wɒnt | rɪˈkwaɪə | চাওয়া | প্রয়োজন',
    'like | prefer | laɪk | prɪˈfɜː | পছন্দ | অগ্রাধিকার দেওয়া',
    'love | adore | lʌv | əˈdɔː | ভালোবাসা | শ্রদ্ধাভরে ভালোবাসা',
    'hate | detest | heɪt | dɪˈtest | ঘৃণা | অত্যন্ত অপছন্দ',
    'hope | aspire | həʊp | əˈspaɪə | আশা | উচ্চাকাঙ্ক্ষা',
    'wish | desire | wɪʃ | dɪˈzaɪə | ইচ্ছা | কামনা',
    'feel | perceive | fiːl | pəˈsiːv | অনুভব | উপলব্ধি করা',
    'think | ponder | θɪŋk | ˈpɒndə | ভাবা | গভীরভাবে ভাবা',
    'know | comprehend | nəʊ | ˌkɒmprɪˈhend | জানা | উপলব্ধি করা',
    'understand | apprehend | ˌʌndəˈstænd | ˌæprɪˈhend | বোঝা | ধারণ করা',
    'remember | recollect | rɪˈmembə | ˌrekəˈlekt | মনে রাখা | স্মরণ করা',
    'forget | omit | fəˈɡet | əˈmɪt | ভুলে যাওয়া | বাদ পড়া',
    'learn | acquire knowledge | lɜːn | əˈkwaɪə ˈnɒlɪdʒ | শেখা | জ্ঞান অর্জন',
    'teach | instruct | tiːtʃ | ɪnˈstrʌkt | শেখানো | নির্দেশ দেওয়া',
    'study | examine | ˈstʌdi | ɪɡˈzæmɪn | পড়া | পরীক্ষা করা',
    'read | peruse | riːd | pəˈruːz | পড়া | মনোযোগ দিয়ে পড়া',
    'write | author | raɪt | ˈɔːθə | লেখা | রচনা করা',
    'say | declare | seɪ | dɪˈkleə | বলা | ঘোষণা করা',
    'speak | converse | spiːk | kənˈvɜːs | কথা বলা | আলাপ করা',
    'talk | confer | tɔːk | kənˈfɜː | কথা | আলোচনা করা',
    'ask | interrogate | ɑːsk | ɪnˈterəɡeɪt | জিজ্ঞাসা | প্রশ্ন করা',
    'answer | respond | ˈɑːnsə | rɪˈspɒnd | উত্তর | জবাব দেওয়া',
    'tell | notify | tel | ˈnəʊtɪfaɪ | বলা | অবহিত করা',
    'call | summon | kɔːl | ˈsʌmən | ডাকা | তলব করা',
    'meet | encounter | miːt | ɪnˈkaʊntə | দেখা | সাক্ষাৎ',
    'see | perceive | siː | pəˈsiːv | দেখা | অনুধাবন করা',
    'look | inspect | lʊk | ɪnˈspekt | তাকানো | পরিদর্শন করা',
    'watch | monitor | wɒtʃ | ˈmɒnɪtə | দেখা | পর্যবেক্ষণ করা',
    'hear | attend | hɪə | əˈtend | শোনা | মনোযোগ দেওয়া',
    'listen | heed | ˈlɪsn | hiːd | শোনা | কর্ণপাত করা',
    'go | advance | ɡəʊ | ədˈvɑːns | যাওয়া | অগ্রসর হওয়া',
    'come | arrive | kʌm | əˈraɪv | আসা | উপস্থিত হওয়া',
    'leave | withdraw | liːv | wɪðˈdrɔː | চলে যাওয়া | প্রত্যাহার',
    'stay | remain | steɪ | rɪˈmeɪn | থাকা | অবস্থান করা',
    'sit | be seated | sɪt | bi ˈsiːtɪd | বসা | উপবিষ্ট থাকা',
    'stand | arise | stænd | əˈraɪz | দাঁড়ানো | উত্থিত হওয়া',
    'walk | proceed on foot | wɔːk | prəˈsiːd ɒn fʊt | হাঁটা | পদব্রজে যাওয়া',
    'run | sprint | rʌn | sprɪnt | দৌড় | দ্রুত ধাবিত হওয়া',
    'drive | operate a vehicle | draɪv | ˈɒpəreɪt ə ˈviːɪkl | গাড়ি চালানো | যানবাহন পরিচালনা',
    'fly | take flight | flaɪ | teɪk flaɪt | উড়া | উড্ডয়ন করা',
    'open | commence | ˈəʊpən | kəˈmens | খোলা | আরম্ভ করা',
    'close | conclude | kləʊz | kənˈkluːd | বন্ধ | সমাপ্ত করা',
    'start off | initiate | ˈstɑːt ɒf | ɪˈnɪʃieɪt | শুরু | সূচনা করা',
    'finish | complete | ˈfɪnɪʃ | kəmˈpliːt | শেষ | সম্পন্ন করা',
    'stop | discontinue | stɒp | ˌdɪskənˈtɪnjuː | থামা | বন্ধ করা',
    'keep on | persist | ˈkiːp ɒn | pəˈsɪst | চালিয়ে যাওয়া | অধ্যবসায় করা',
    'give | confer | ɡɪv | kənˈfɜː | দেওয়া | প্রদান করা',
    'take | obtain | teɪk | əbˈteɪn | নেওয়া | অর্জন করা',
    'bring | convey | brɪŋ | kənˈveɪ | আনা | বহন করে আনা',
    'send | dispatch | send | dɪˈspætʃ | পাঠানো | প্রেরণ করা',
    'put | deposit | pʊt | dɪˈpɒzɪt | রাখা | স্থাপন করা',
    'get rid of | dispose of | ˈɡet rɪd ɒv | dɪˈspəʊz ɒv | ছাড়া | নিষ্পত্তি করা',
    'throw | propel | θrəʊ | prəˈpel | ছোড়া | নিক্ষেপ করা',
    'catch | intercept | kætʃ | ˌɪntəˈsept | ধরা | আটকানো',
    'hold | retain | həʊld | rɪˈteɪn | ধরে রাখা | সংরক্ষণ করা',
    'keep | retain | kiːp | rɪˈteɪn | রাখা | ধরে রাখা',
    'lose | forfeit | luːz | ˈfɔːfɪt | হারানো | হরণ হওয়া',
    'find | locate | faɪnd | ləʊˈkeɪt | খুঁজে পাওয়া | অবস্থান নির্ণয়',
    'search | seek out | sɜːtʃ | siːk aʊt | খোঁজা | অন্বেষণ করা',
    'hide | conceal | haɪd | kənˈsiːl | লুকানো | গোপন করা',
    'show | exhibit | ʃəʊ | ɪɡˈzɪbɪt | দেখানো | প্রদর্শন করা',
    'change | modify | tʃeɪndʒ | ˈmɒdɪfaɪ | বদলানো | পরিবর্তন করা',
    'turn into | transform | ˈtɜːn ˈɪntuː | trænsˈfɔːm | হয়ে যাওয়া | রূপান্তরিত হওয়া',
    'make | manufacture | meɪk | ˌmænjuˈfæktʃə | তৈরি | উৎপাদন করা',
    'break | fracture | breɪk | ˈfræktʃə | ভাঙা | ভগ্ন করা',
    'fix | rectify | fɪks | ˈrektɪfaɪ | সারানো | সংশোধন করা',
    'cut | sever | kʌt | ˈsevə | কাটা | বিচ্ছিন্ন করা',
    'join | unite | dʒɔɪn | juˈnaɪt | যোগ | একত্রিত করা',
    'mix | blend | mɪks | blend | মেশানো | মিশ্রিত করা',
    'grow | expand | ɡrəʊ | ɪkˈspænd | বাড়া | সম্প্রসারিত হওয়া',
    'shrink | diminish | ʃrɪŋk | dɪˈmɪnɪʃ | কমে যাওয়া | ক্ষীয়মাণ হওয়া',
    'rise | escalate | raɪz | ˈeskəleɪt | ওঠা | বৃদ্ধি পাওয়া',
    'fall | decline | fɔːl | dɪˈklaɪn | পড়া | হ্রাস পাওয়া',
    'happen | occur | ˈhæpən | əˈkɜː | ঘটা | সংঘটিত হওয়া',
    'begin | originate | bɪˈɡɪn | əˈrɪdʒɪneɪt | শুরু | উৎপত্তি হওয়া',
    'die | perish | daɪ | ˈperɪʃ | মারা যাওয়া | নিহত হওয়া',
    'live on | subsist | ˈlɪv ɒn | səbˈsɪst | বেঁচে থাকা | জীবিকা নির্বাহ',
    'eat | ingest | iːt | ɪnˈdʒest | খাওয়া | গ্রহণ করা',
    'drink | imbibe | drɪŋk | ɪmˈbaɪb | পান | পান করা',
    'sleep | slumber | sliːp | ˈslʌmbə | ঘুম | নিদ্রা',
    'wake | awaken | weɪk | əˈweɪkən | জাগা | জাগ্রত হওয়া',
    'sick | unwell | sɪk | ˌʌnˈwel | অসুস্থ | অস্বস্থ',
    'well | healthy | wel | ˈhelθi | ভালো | সুস্থ',
    'hurt | injure | hɜːt | ˈɪndʒə | ব্যথা | আহত করা',
    'kill | slay | kɪl | sleɪ | মারা | হত্যা করা',
    'save someone | rescue | seɪv ˈsʌmwʌn | ˈreskjuː | বাঁচানো | উদ্ধার করা',
    'help out | succour | ˈhelp aʊt | ˈsʌkə | সাহায্য | সহায়তা করা',
    'save | salvage | seɪv | ˈsælvɪdʒ | রক্ষা | উদ্ধার করা',
    'try hard | strive | traɪ hɑːd | straɪv | চেষ্টা | প্রয়াস করা',
    'do | perform | duː | pəˈfɔːm | করা | সম্পাদন করা',
    'make sure | ensure | meɪk ʃɔː | ɪnˈʃɔː | নিশ্চিত | নিশ্চিত করা',
    'let in | admit | ˈlet ɪn | ədˈmɪt | ঢুকতে দেওয়া | প্রবেশাধিকার দেওয়া',
    'let out | emit | ˈlet aʊt | ɪˈmɪt | ছাড়া | নির্গত করা',
    'set off | depart | ˈset ɒf | dɪˈpɑːt | রওনা | প্রস্থান করা',
    'set down | record | ˈset daʊn | rɪˈkɔːd | লেখা | লিপিবদ্ধ করা',
    'turn down | decline | ˈtɜːn daʊn | dɪˈklaɪn | প্রত্যাখ্যান | অস্বীকার করা',
    'turn up | appear | ˈtɜːn ʌp | əˈpɪə | হাজির | উপস্থিত হওয়া',
    'turn off | deactivate | ˈtɜːn ɒf | ˌdiːˈæktɪveɪt | বন্ধ | নিষ্ক্রিয় করা',
    'turn on | activate | ˈtɜːn ɒn | ˈæktɪveɪt | চালু | সক্রিয় করা',
    'work out | calculate | ˈwɜːk aʊt | ˈkælkjuleɪt | হিসাব | গণনা করা',
    'figure out | ascertain | ˈfɪɡər aʊt | ˌæsəˈteɪn | বোঝা | নির্ণয় করা',
    'carry on | persist | ˈkæri ɒn | pəˈsɪst | চালিয়ে যাওয়া | অব্যাহত রাখা',
    'give in | yield | ˈɡɪv ɪn | jiːld | হার মেনে নেওয়া | নতিস্বীকার',
    'give away | donate | ˈɡɪv əˈweɪ | dəʊˈneɪt | দান | প্রদান করা',
    'take over | assume control | ˈteɪk ˈəʊvə | əˈsjuːm kənˈtrəʊl | দায়িত্ব নেওয়া | নিয়ন্ত্রণ গ্রহণ',
    'take after | resemble | ˈteɪk ˈɑːftə | rɪˈzembl | মিল | সাদৃশ্য রাখা',
    'look after | supervise | ˈlʊk ˈɑːftə | ˈsuːpəvaɪz | দেখাশোনা | তত্ত্বাবধান',
    'look forward to | anticipate | ˈlʊk ˈfɔːwəd tuː | ænˈtɪsɪpeɪt | অপেক্ষা | প্রত্যাশা করা',
    'put down | record | ˈpʊt daʊn | rɪˈkɔːd | লেখা | লিপিবদ্ধ করা',
    'put forward | propose | ˈpʊt ˈfɔːwəd | prəˈpəʊz | পেশ করা | প্রস্তাব করা',
    'put through | connect | ˈpʊt θruː | kəˈnekt | সংযোগ | যুক্ত করা',
    'come across | encounter | ˈkʌm əˈkrɒs | ɪnˈkaʊntə | পড়ে যাওয়া | সম্মুখীন হওয়া',
    'come up with | devise | ˈkʌm ʌp wɪð | dɪˈvaɪz | বের করা | উদ্ভাবন করা',
    'go along with | comply | ˈɡəʊ əˈlɒŋ wɪð | kəmˈplaɪ | রাজি | সম্মত হওয়া',
    'go over | scrutinise | ˈɡəʊ ˈəʊvə | ˈskruːtənaɪz | দেখা | সূক্ষ্ম পরীক্ষা',
    'break up | dissolve | ˈbreɪk ʌp | dɪˈzɒlv | ভাঙা | ভেঙে দেওয়া',
    'break in | interrupt | ˈbreɪk ɪn | ˌɪntəˈrʌpt | বাধা | বিঘ্ন ঘটানো',
    'bring about | occasion | ˈbrɪŋ əˈbaʊt | əˈkeɪʒn | ঘটানো | সূচিত করা',
    'bring up | raise | ˈbrɪŋ ʌp | reɪz | তোলা | উত্থাপন করা',
    'call for | necessitate | ˈkɔːl fɔː | nəˈsesɪteɪt | দাবি | অপরিহার্য করা',
    'carry out | execute | ˈkæri aʊt | ˈeksɪkjuːt | করা | কার্যকর করা',
    'cut down | reduce | ˈkʌt daʊn | rɪˈdjuːs | কমানো | হ্রাস করা',
    'cut off | isolate | ˈkʌt ɒf | ˈaɪsəleɪt | বিচ্ছিন্ন | পৃথক করা',
    'do away with | abolish | ˈduː əˈweɪ wɪð | əˈbɒlɪʃ | তুলে দেওয়া | রদ করা',
    'draw up | draft | ˈdrɔː ʌp | drɑːft | তৈরি | খসড়া করা',
    'drop in | visit briefly | ˈdrɒp ɪn | ˈvɪzɪt ˈbriːfli | উঁকি | সংক্ষিপ্ত সাক্ষাৎ',
    'fall back on | resort to | ˈfɔːl bæk ɒn | rɪˈzɔːt tuː | ভরসা | আশ্রয় নেওয়া',
    'get across | communicate | ˈɡet əˈkrɒs | kəˈmjuːnɪkeɪt | বোঝানো | জানানো',
    'get along | be compatible | ˈɡet əˈlɒŋ | bi kəmˈpætəbl | মিলিয়ে চলা | সামঞ্জস্যপূর্ণ',
    'get over | recover | ˈɡet ˈəʊvə | rɪˈkʌvə | সেরে ওঠা | আরোগ্য লাভ',
    'give off | emit | ˈɡɪv ɒf | ɪˈmɪt | ছড়ানো | নির্গত করা',
    'go back on | renege | ˈɡəʊ bæk ɒn | rɪˈniːɡ | কথা না রাখা | অঙ্গীকার ভঙ্গ',
    'hold on | persist | ˈhəʊld ɒn | pəˈsɪst | ধরে থাকা | অধ্যবসায়',
    'keep up | maintain | ˈkiːp ʌp | meɪnˈteɪn | ধরে রাখা | বজায় রাখা',
    'lay off | dismiss | ˈleɪ ɒf | dɪsˈmɪs | ছাঁটাই | বরখাস্ত',
    'let down | disappoint | ˈlet daʊn | ˌdɪsəˈpɔɪnt | হতাশ | নিরাশ করা',
    'make up for | compensate | ˈmeɪk ʌp fɔː | ˈkɒmpenseɪt | পুষিয়ে দেওয়া | ক্ষতিপূরণ',
    'pass away | decease | ˈpɑːs əˈweɪ | dɪˈsiːs | মারা যাওয়া | মৃত্যুবরণ',
    'pass out | faint | ˈpɑːs aʊt | feɪnt | অজ্ঞান | মূর্ছা যাওয়া',
    'pick out | distinguish | ˈpɪk aʊt | dɪˈstɪŋɡwɪʃ | বেছে নেওয়া | পার্থক্য করা',
    'put aside | reserve | ˈpʊt əˈsaɪd | rɪˈzɜːv | সরিয়ে রাখা | সংরক্ষণ',
    'put together | assemble | ˈpʊt təˈɡeðə | əˈsembl | জোড়া | একত্রিত করা',
    'run into | encounter | ˈrʌn ˈɪntuː | ɪnˈkaʊntə | দেখা হয়ে যাওয়া | সম্মুখীন',
    'run out of | exhaust | ˈrʌn aʊt ɒv | ɪɡˈzɔːst | ফুরিয়ে যাওয়া | নিঃশেষ',
    'see to | attend to | ˈsiː tuː | əˈtend tuː | দেখা | তত্ত্বাবধান',
    'set aside | allocate | ˈset əˈsaɪd | ˈæləkeɪt | আলাদা | বরাদ্দ করা',
    'sort out | resolve | ˈsɔːt aʊt | rɪˈzɒlv | মিটানো | নিষ্পত্তি',
    'stand for | represent | ˈstænd fɔː | ˌreprɪˈzent | মানে | প্রতিনিধিত্ব',
    'take in | comprehend | ˈteɪk ɪn | ˌkɒmprɪˈhend | বোঝা | উপলব্ধি',
    'take up | occupy | ˈteɪk ʌp | ˈɒkjupaɪ | নেওয়া | অধিকার করা',
    'think over | contemplate | ˈθɪŋk ˈəʊvə | ˈkɒntəmpleɪt | ভেবে দেখা | চিন্তা করা',
    'turn out | transpire | ˈtɜːn aʊt | trænˈspaɪə | প্রমাণিত | প্রকাশিত হওয়া',
    'wipe out | eradicate | ˈwaɪp aʊt | ɪˈrædɪkeɪt | মুছে ফেলা | নির্মূল',
    'about | approximately | əˈbaʊt | əˈprɒksɪmətli | প্রায় | আনুমানিক',
    'around | in the vicinity of | əˈraʊnd | ɪn ðə vəˈsɪnəti ɒv | আশেপাশে | নিকটবর্তী',
    'almost | nearly | ˈɔːlməʊst | ˈnɪəli | প্রায় | প্রায় সম্পূর্ণ',
    'always | invariably | ˈɔːlweɪz | ɪnˈveəriəbli | সবসময় | নির্বিশেষে',
    'never | under no circumstances | ˈnevə | ˈʌndə nəʊ ˈsɜːkəmstænsɪz | কখনো না | কোনো অবস্থাতেই না',
    'often | frequently | ˈɒfn | ˈfriːkwəntli | প্রায়ই | ঘন ঘন',
    'sometimes | occasionally | ˈsʌmtaɪmz | əˈkeɪʒnəli | মাঝে মাঝে | কদাচিৎ',
    'soon | shortly | suːn | ˈʃɔːtli | শিগগির | অচিরেই',
    'now | currently | naʊ | ˈkʌrəntli | এখন | বর্তমানে',
    'then | subsequently | ðen | ˈsʌbsɪkwəntli | তারপর | পরবর্তীতে',
    'later | thereafter | ˈleɪtə | ˌðeərˈɑːftə | পরে | তৎপরবর্তী',
    'before | prior to | bɪˈfɔː | ˈpraɪə tuː | আগে | পূর্বে',
    'after | following | ˈɑːftə | ˈfɒləʊɪŋ | পরে | অনুসরণে',
    'because | owing to | bɪˈkɒz | ˈəʊɪŋ tuː | কারণ | কারণে',
    'so that | in order that | səʊ ðæt | ɪn ˈɔːdə ðæt | যাতে | এই উদ্দেশ্যে',
    'if | provided that | ɪf | prəˈvaɪdɪd ðæt | যদি | শর্তে',
    'unless | except when | ʌnˈles | ɪkˈsept wen | যদি না | ব্যতিরেকে',
    'but | whereas | bət | weərˈæz | কিন্তু | অপরপক্ষে',
    'or | alternatively | ɔː | ɔːlˈtɜːnətɪvli | অথবা | বিকল্পভাবে',
    'and | in conjunction with | ənd | ɪn kənˈdʒʌŋkʃn wɪð | এবং | সহযোগে',
    'also | furthermore | ˈɔːlsəʊ | ˌfɜːðəˈmɔː | এছাড়া | তদুপরি',
    'too | in addition | tuː | ɪn əˈdɪʃn |ও | অতিরিক্তভাবে',
    'only | solely | ˈəʊnli | ˈsəʊlli | শুধু | কেবলমাত্র',
    'just | merely | dʒʌst | ˈmɪəli | শুধু | মাত্র',
    'even | indeed | ˈiːvn | ɪnˈdiːd | এমনকি | প্রকৃতপক্ষে',
    'still | nonetheless | stɪl | ˌnʌnðəˈles | তবু | তথাপি',
    'yet | nevertheless | jet | ˌnevəðəˈles | তবু | তথাপি',
    'already | previously | ɔːlˈredi | ˈpriːviəsli | ইতিমধ্যে | পূর্বেই',
    'still not | not as yet | stɪl nɒt | nɒt æz jet | এখনো না | এখনো পর্যন্ত নয়',
    'again | once more | əˈɡen | wʌns mɔː | আবার | পুনরায়',
    'more | additional | mɔː | əˈdɪʃənl | আরও | অতিরিক্ত',
    'less | fewer | les | ˈfjuːə | কম | অল্পতর',
    'most | the majority of | məʊst | ðə məˈdʒɒrəti ɒv | বেশিরভাগ | অধিকাংশ',
    'all | the entirety of | ɔːl | ði ɪnˈtaɪərəti ɒv | সব | সম্পূর্ণতা',
    'some | a number of | sʌm | ə ˈnʌmbər ɒv | কিছু | কতিপয়',
    'any | whatsoever | ˈeni | ˌwɒtsəʊˈevə | কোনো | যাই হোক',
    'each | every | iːtʃ | ˈevri | প্রতিটি | প্রত্যেক',
    'both | the two | bəʊθ | ðə tuː | দুটোই | উভয়',
    'another | an additional | əˈnʌðə | ən əˈdɪʃənl | আরেকটি | অতিরিক্ত একটি',
    'other | remaining | ˈʌðə | rɪˈmeɪnɪŋ | অন্য | অবশিষ্ট',
    'same | identical | seɪm | aɪˈdentɪkl | একই | অভিন্ন',
    'different | distinct | ˈdɪfrənt | dɪˈstɪŋkt | আলাদা | পৃথক',
    'first | primary | fɜːst | ˈpraɪməri | প্রথম | প্রাথমিক',
    'last | final | lɑːst | ˈfaɪnl | শেষ | চূড়ান্ত',
    'next one | subsequent | nekst wʌn | ˈsʌbsɪkwənt | পরেরটি | পরবর্তী',
    'best | optimal | best | ˈɒptɪml | সেরা | সর্বোত্তম',
    'worst | least favourable | wɜːst | liːst ˈfeɪvərəbl | খারাপতম | ন্যূনতম অনুকূল',
    'better off | in a superior position | ˈbetər ɒf | ɪn ə suːˈpɪəriə pəˈzɪʃn | ভালো অবস্থা | উন্নত অবস্থান',
    'worse off | in an inferior position | ˈwɜːs ɒf | ɪn ən ɪnˈfɪəriə pəˈzɪʃn | খারাপ অবস্থা | নিম্নতর অবস্থান',
    'kind of | somewhat | kaɪnd ɒv | ˈsʌmwɒt | একরকম | কিছুটা',
    'sort of | relatively | sɔːt ɒv | ˈrelətɪvli | মোটামুটি | তুলনামূলকভাবে',
    'a couple of | several | ə ˈkʌpl ɒv | ˈsevrəl | কয়েকটি | কতিপয়',
    'loads of | an abundance of | ləʊdz ɒv | ən əˈbʌndəns ɒv | অনেক | প্রাচুর্য',
    'tons of | a multitude of | tʌnz ɒv | ə ˈmʌltɪtjuːd ɒv | অঢেল | বিপুল সংখ্যক',
    'pretty | rather | ˈprɪti | ˈrɑːðə | মোটামুটি | বরং',
    'quite | fairly | kwaɪt | ˈfeəli | বেশ | যথেষ্ট',
    'totally | entirely | ˈtəʊtəli | ɪnˈtaɪəli | পুরোপুরি | সম্পূর্ণভাবে',
    'completely | utterly | kəmˈpliːtli | ˈʌtəli | সম্পূর্ণ | নিশ্ছিদ্রভাবে',
    'basically | essentially | ˈbeɪsɪkli | ɪˈsenʃəli | মূলত | সার্বিকভাবে',
    'actually | in fact | ˈæktʃuəli | ɪn fækt | আসলে | প্রকৃতপক্ষে',
    'obviously | evidently | ˈɒbviəsli | ˈevɪdəntli | স্পষ্টত | প্রতীয়মানভাবে',
    'probably | presumably | ˈprɒbəbli | prɪˈzjuːməbli | সম্ভবত | অনুমানক্রমে',
    'maybe not | conceivably not | ˈmeɪbi nɒt | kənˈsiːvəbli nɒt | হয়তো না | সম্ভাব্য নয়',
    'of course | certainly | əv kɔːs | ˈsɜːtnli | অবশ্যই | নিশ্চিতভাবে',
    'sure | assuredly | ʃɔː | əˈʃʊədli | নিশ্চিত | নিঃসন্দেহে',
    'no way | by no means | nəʊ weɪ | baɪ nəʊ miːnz | কোনোভাবেই না | মোটেই নয়',
    'for sure | without doubt | fɔː ʃɔː | wɪˈðaʊt daʊt | নিশ্চিত | সন্দেহাতীত',
    'kind | benevolent | kaɪnd | bəˈnevələnt | দয়ালু | পরোপকারী',
    'mean | miserly | miːn | ˈmaɪzəli | কৃপণ | ব্যয়কুণ্ঠ',
    'funny | comical | ˈfʌni | ˈkɒmɪkl | মজার | হাস্যকর',
    'serious | grave | ˈsɪəriəs | ɡreɪv | গম্ভীর | গুরুতর',
    'happy | delighted | ˈhæpi | dɪˈlaɪtɪd | খুশি | আনন্দিত',
    'sad | melancholy | sæd | ˈmelənkəli | দুঃখিত | বিষণ্ণ',
    'angry | irate | ˈæŋɡri | aɪˈreɪt | রাগান্বিত | ক্রুদ্ধ',
    'scared | apprehensive | skeəd | ˌæprɪˈhensɪv | ভীত | শঙ্কিত',
    'bored | uninterested | bɔːd | ʌnˈɪntrəstɪd | বিরক্ত | অনাগ্রহী',
    'excited | enthusiastic | ɪkˈsaɪtɪd | ɪnˌθjuːziˈæstɪk | উত্তেজিত | উৎসাহী',
    'tired out | weary | ˈtaɪəd aʊt | ˈwɪəri | ক্লান্ত | অবসন্ন',
    'busy | occupied | ˈbɪzi | ˈɒkjupaɪd | ব্যস্ত | কর্মরত',
    'lazy | indolent | ˈleɪzi | ˈɪndələnt | অলস | কর্মবিমুখ',
    'clever | astute | ˈklevə | əˈstjuːt | চালাক | বিচক্ষণ',
    'stupid | foolish | ˈstjuːpɪd | ˈfuːlɪʃ | বোকা | নির্বোধ',
    'careful | cautious | ˈkeəfl | ˈkɔːʃəs | সাবধান | সতর্ক',
    'careless | negligent | ˈkeələs | ˈneɡlɪdʒənt | অসাবধান | অবহেলাকারী',
    'strong | robust | strɒŋ | rəʊˈbʌst | শক্তিশালী | দৃঢ়',
    'weak | feeble | wiːk | ˈfiːbl | দুর্বল | ক্ষীণ',
    'heavy | ponderous | ˈhevi | ˈpɒndərəs | ভারী | গুরুভার',
    'light | lightweight | laɪt | ˈlaɪtweɪt | হালকা | লঘু',
    'full | replete | fʊl | rɪˈpliːt | ভরা | পরিপূর্ণ',
    'loud | sonorous | laʊd | ˈsɒnərəs | জোরে | গম্ভীরধ্বনি',
    'quiet | tranquil | ˈkwaɪət | ˈtræŋkwɪl | শান্ত | নিরিবিলি',
    'hot weather | torrid | hɒt ˈweðə | ˈtɒrɪd | গরম | উষ্ণ',
    'cold | frigid | kəʊld | ˈfrɪdʒɪd | ঠান্ডা | শীতল',
    'wet | saturated | wet | ˈsætʃəreɪtɪd | ভেজা | সিক্ত',
    'dry | arid | draɪ | ˈærɪd | শুকনো | শুষ্ক',
    'clean | immaculate | kliːn | ɪˈmækjələt | পরিষ্কার | নিখুঁত পরিচ্ছন্ন',
    'messy | disordered | ˈmesi | dɪsˈɔːdəd | এলোমেলো | বিশৃঙ্খল',
    'safe | secure | seɪf | sɪˈkjʊə | নিরাপদ | সুরক্ষিত',
    'dangerous | hazardous | ˈdeɪndʒərəs | ˈhæzədəs | বিপজ্জনক | ঝুঁকিপূর্ণ',
    'true | accurate | truː | ˈækjərət | সত্য | নির্ভুল',
    'false | erroneous | fɔːls | ɪˈrəʊniəs | মিথ্যা | ভ্রান্ত',
    'real | authentic | rɪəl | ɔːˈθentɪk | আসল | প্রামাণিক',
    'fake | counterfeit | feɪk | ˈkaʊntəfɪt | নকল | জাল',
    'possible | feasible | ˈpɒsəbl | ˈfiːzəbl | সম্ভব | বাস্তবসম্মত',
    'impossible | unattainable | ɪmˈpɒsəbl | ˌʌnəˈteɪnəbl | অসম্ভব | অপ্রাপ্য',
    'important | significant | ɪmˈpɔːtnt | sɪɡˈnɪfɪkənt | গুরুত্বপূর্ণ | তাৎপর্যপূর্ণ',
    'useful | advantageous | ˈjuːsfl | ˌædvənˈteɪdʒəs | দরকারি | সুবিধাজনক',
    'useless | ineffectual | ˈjuːsləs | ˌɪnɪˈfektʃuəl | অকেজো | নিষ্ফল',
    'ready | prepared | ˈredi | prɪˈpeəd | প্রস্তুত | সজ্জিত',
    'late | tardy | leɪt | ˈtɑːdi | দেরি | বিলম্বিত',
    'early | premature | ˈɜːli | ˈpremətʃə | তাড়াতাড়ি | অকাল',
    'long | lengthy | lɒŋ | ˈleŋθi | লম্বা | দীর্ঘ',
    'short | brief | ʃɔːt | briːf | ছোট | সংক্ষিপ্ত',
    'wide | extensive | waɪd | ɪkˈstensɪv | চওড়া | বিস্তৃত',
    'narrow | restricted | ˈnærəʊ | rɪˈstrɪktɪd | সরু | সীমিত',
    'deep | profound | diːp | prəˈfaʊnd | গভীর | গভীরতর',
    'high | elevated | haɪ | ˈelɪveɪtɪd | উঁচু | উন্নত',
    'low | modest | ləʊ | ˈmɒdɪst | নিচু | নম্র',
    'near | adjacent | nɪə | əˈdʒeɪsnt | কাছে | সংলগ্ন',
    'far | remote | fɑː | rɪˈməʊt | দূরে | দূরবর্তী',
    'inside | interior | ɪnˈsaɪd | ɪnˈtɪəriə | ভিতরে | অভ্যন্তর',
    'outside | exterior | ˌaʊtˈsaɪd | ɪkˈstɪəriə | বাইরে | বহির্ভাগ',
    'top | summit | tɒp | ˈsʌmɪt | উপরে | শীর্ষ',
    'bottom | base | ˈbɒtəm | beɪs | নিচে | ভিত্তি',
    'front | anterior | frʌnt | ænˈtɪəriə | সামনে | অগ্রভাগ',
    'back | posterior | bæk | pɒˈstɪəriə | পেছনে | পশ্চাদভাগ',
    'middle | intermediate | ˈmɪdl | ˌɪntəˈmiːdiət | মাঝে | মধ্যবর্তী',
    'side | flank | saɪd | flæŋk | পাশে | পার্শ্ব',
    'part | component | pɑːt | kəmˈpəʊnənt | অংশ | উপাদান',
    'piece | fragment | piːs | ˈfræɡmənt | টুকরো | খণ্ড',
    'bit | portion | bɪt | ˈpɔːʃn | একটু | অংশবিশেষ',
    'rest | remainder | rest | rɪˈmeɪndə | বাকি | অবশিষ্টাংশ',
    'half | fifty percent | hɑːf | ˈfɪfti pəˈsent | অর্ধেক | শতকরা পঞ্চাশ',
    'number | quantity | ˈnʌmbə | ˈkwɒntəti | সংখ্যা | পরিমাণ',
    'amount | volume | əˈmaʊnt | ˈvɒljuːm | পরিমাণ | আয়তন',
    'size | magnitude | saɪz | ˈmæɡnɪtjuːd | আকার | বিশালতা',
    'level | degree | ˈlevl | dɪˈɡriː | স্তর | মাত্রা',
    'way | manner | weɪ | ˈmænə | উপায় | পদ্ধতি',
    'kind | category | kaɪnd | ˈkætəɡəri | ধরন | শ্রেণি',
    'type | classification | taɪp | ˌklæsɪfɪˈkeɪʃn | প্রকার | শ্রেণিবিন্যাস',
    'example | illustration | ɪɡˈzɑːmpl | ˌɪləˈstreɪʃn | উদাহরণ | দৃষ্টান্ত',
    'reason | rationale | ˈriːzn | ˌræʃəˈnɑːl | কারণ | যৌক্তিকতা',
    'result | outcome | rɪˈzʌlt | ˈaʊtkʌm | ফল | পরিণাম',
    'problem | predicament | ˈprɒbləm | prɪˈdɪkəmənt | সমস্যা | সংকট',
    'question | enquiry | ˈkwestʃən | ɪnˈkwaɪəri | প্রশ্ন | অনুসন্ধান',
    'answer | solution | ˈɑːnsə | səˈluːʃn | উত্তর | সমাধান',
    'story | narrative | ˈstɔːri | ˈnærətɪv | গল্প | বৃত্তান্ত',
    'news | intelligence | njuːz | ɪnˈtelɪdʒəns | খবর | সংবাদ',
    'letter | correspondence | ˈletə | ˌkɒrəˈspɒndəns | চিঠি | পত্রালাপ',
    'book | volume | bʊk | ˈvɒljuːm | বই | গ্রন্থ',
    'paper | document | ˈpeɪpə | ˈdɒkjəmənt | কাগজ | দলিল',
    'note | memorandum | nəʊt | ˌmeməˈrændəm | নোট | স্মারকলিপি',
    'list | inventory | lɪst | ˈɪnvəntri | তালিকা | তালিকাপত্র',
    'plan | strategy | plæn | ˈstrætədʒi | পরিকল্পনা | কৌশল',
    'idea | concept | aɪˈdɪə | ˈkɒnsept | ধারণা | প্রত্যয়',
    'way of thinking | perspective | weɪ əv ˈθɪŋkɪŋ | pəˈspektɪv | চিন্তাধারা | দৃষ্টিভঙ্গি',
    'view | standpoint | vjuː | ˈstændpɔɪnt | মত | অবস্থান',
    'feeling | sentiment | ˈfiːlɪŋ | ˈsentɪmənt | অনুভূতি | মনোভাব',
    'mind | intellect | maɪnd | ˈɪntəlekt | মন | বুদ্ধিবৃত্তি',
    'heart | core | hɑːt | kɔː | হৃদয় | অন্তঃস্থল',
    'life | existence | laɪf | ɪɡˈzɪstəns | জীবন | অস্তিত্ব',
    'time | duration | taɪm | djuˈreɪʃn | সময় | স্থিতিকাল',
    'day | diurnal period | deɪ | daɪˈɜːnl ˈpɪəriəd | দিন | দিবাসময়',
    'year | annum | jɪə | ˈænəm | বছর | অব্দ',
    'age | era | eɪdʒ | ˈɪərə | যুগ | কাল',
    'future | forthcoming period | ˈfjuːtʃə | ˌfɔːθˈkʌmɪŋ ˈpɪəriəd | ভবিষ্যৎ | আগামী কাল',
    'past | former times | pɑːst | ˈfɔːmə taɪmz | অতীত | পূর্বকাল',
    'present | contemporary moment | ˈpreznt | kənˈtemprəri ˈməʊmənt | বর্তমান | সমকাল',
    'weather | climatic conditions | ˈweðə | klaɪˈmætɪk kənˈdɪʃnz | আবহাওয়া | জলবায়ুগত অবস্থা',
    'rain | precipitation | reɪn | prɪˌsɪpɪˈteɪʃn | বৃষ্টি | বর্ষণ',
    'sun | solar disc | sʌn | ˈsəʊlə dɪsk | সূর্য | সৌরবিম্ব',
    'air | atmosphere | eə | ˈætməsfɪə | বাতাস | বায়ুমণ্ডল',
    'water | aqueous liquid | ˈwɔːtə | ˈeɪkwiəs ˈlɪkwɪd | পানি | জলীয় তরল',
    'fire | combustion | ˈfaɪə | kəmˈbʌstʃən | আগুন | দহন',
    'earth | terrestrial surface | ɜːθ | təˈrestriəl ˈsɜːfɪs | পৃথিবী | স্থলপৃষ্ঠ',
    'food | nourishment | fuːd | ˈnʌrɪʃmənt | খাবার | পুষ্টি',
    'meal | repast | miːl | rɪˈpɑːst | খাবার | আহার',
    'bread | loaf | bred | ləʊf | রুটি | পাউরুটি',
    'rice | grain | raɪs | ɡreɪn | ভাত | শস্য',
    'meat | flesh | miːt | fleʃ | মাংস | মাংসপেশি',
    'fish | seafood | fɪʃ | ˈsiːfuːd | মাছ | সামুদ্রিক খাদ্য',
    'fruit | produce | fruːt | ˈprɒdjuːs | ফল | উৎপাদিত ফল',
    'milk | dairy liquid | mɪlk | ˈdeəri ˈlɪkwɪd | দুধ | দুগ্ধজাত তরল',
    'tea | infusion | tiː | ɪnˈfjuːʒn | চা | নির্যাস',
    'coffee | beverage | ˈkɒfi | ˈbevərɪdʒ | কফি | পানীয়',
    'car | motor vehicle | kɑː | ˈməʊtə ˈviːɪkl | গাড়ি | মোটরযান',
    'bus | public coach | bʌs | ˈpʌblɪk kəʊtʃ | বাস | গণপরিবহন',
    'train | locomotive service | treɪn | ˌləʊkəˈməʊtɪv ˈsɜːvɪs | ট্রেন | রেলসেবা',
    'plane | aircraft | pleɪn | ˈeəkrɑːft | প্লেন | বিমান',
    'boat | vessel | bəʊt | ˈvesl | নৌকা | জলযান',
    'road | thoroughfare | rəʊd | ˈθʌrəfeə | রাস্তা | সড়কপথ',
    'street | public way | striːt | ˈpʌblɪk weɪ | রাস্তা | জনপথ',
    'bridge | viaduct | brɪdʒ | ˈvaɪədʌkt | সেতু | সেতুপথ',
    'door | portal | dɔː | ˈpɔːtl | দরজা | প্রবেশদ্বার',
    'window | aperture | ˈwɪndəʊ | ˈæpətʃə | জানালা | ছিদ্রপথ',
    'table | dining surface | ˈteɪbl | ˈdaɪnɪŋ ˈsɜːfɪs | টেবিল | ভোজনতল',
    'chair | seat | tʃeə | siːt | চেয়ার | আসন',
    'bed | sleeping couch | bed | ˈsliːpɪŋ kaʊtʃ | বিছানা | শয়নকক্ষের আসন',
    'clothes | attire | kləʊðz | əˈtaɪə | পোশাক | পরিচ্ছদ',
    'shirt | garment | ʃɜːt | ˈɡɑːmənt | শার্ট | পরিধেয়',
    'bag | receptacle | bæɡ | rɪˈseptəkl | ব্যাগ | ধারক',
    'phone call | telephone conversation | fəʊn kɔːl | ˈtelɪfəʊn ˌkɒnvəˈseɪʃn | ফোন | দূরালাপ',
    'computer | processor | kəmˈpjuːtə | ˈprəʊsesə | কম্পিউটার | প্রক্রিয়াকারী যন্ত্র',
    'internet | worldwide network | ˈɪntənet | ˌwɜːldˈwaɪd ˈnetwɜːk | ইন্টারনেট | বিশ্বব্যাপী নেটওয়ার্ক',
    'email | electronic mail | ˈiːmeɪl | ɪlekˈtrɒnɪk meɪl | ইমেইল | বৈদ্যুতিন চিঠি',
    'photo | photograph | ˈfəʊtəʊ | ˈfəʊtəɡrɑːf | ছবি | আলোকচিত্র',
    'film | motion picture | fɪlm | ˈməʊʃn ˈpɪktʃə | সিনেমা | চলচ্চিত্র',
    'song | vocal composition | sɒŋ | ˈvəʊkl ˌkɒmpəˈzɪʃn | গান | কণ্ঠসঙ্গীত',
    'game | contest | ɡeɪm | ˈkɒntest | খেলা | প্রতিযোগিতা',
    'sport | athletic pursuit | spɔːt | æθˈletɪk pəˈsjuːt | খেলা | ক্রীড়া',
    'team | ensemble | tiːm | ɒnˈsɒmbl | দল | সমষ্টি',
    'win | prevail | wɪn | prɪˈveɪl | জেতা | জয়লাভ',
    'lose a game | be defeated | luːz ə ɡeɪm | bi dɪˈfiːtɪd | হারা | পরাজিত হওয়া',
    'play a game | participate | pleɪ ə ɡeɪm | pɑːˈtɪsɪpeɪt | খেলা | অংশগ্রহণ',
    'friend | companion | frend | kəmˈpæniən | বন্ধু | সঙ্গী',
    'enemy | adversary | ˈenəmi | ˈædvəsəri | শত্রু | প্রতিপক্ষ',
    'family | household | ˈfæməli | ˈhaʊshəʊld | পরিবার | গৃহস্থালি',
    'parents | guardians | ˈpeərənts | ˈɡɑːdiənz | বাবা-মা | অভিভাবক',
    'child | offspring | tʃaɪld | ˈɒfsprɪŋ | সন্তান | সন্তানসন্ততি',
    'baby | infant | ˈbeɪbi | ˈɪnfənt | শিশু | নবজাতক',
    'boy | male child | bɔɪ | meɪl tʃaɪld | ছেলে | পুত্রসন্তান',
    'girl | female child | ɡɜːl | ˈfiːmeɪl tʃaɪld | মেয়ে | কন্যাসন্তান',
    'husband | spouse | ˈhʌzbənd | spaʊs | স্বামী | সহধর্মী',
    'wife | spouse | waɪf | spaʊs | স্ত্রী | সহধর্মিণী',
    'name | designation | neɪm | ˌdezɪɡˈneɪʃn | নাম | অভিধা',
    'word | lexical item | wɜːd | ˈleksɪkl ˈaɪtəm | শব্দ | শব্দাংশ',
    'sentence | utterance | ˈsentəns | ˈʌtərəns | বাক্য | উক্তি',
    'language | tongue | ˈlæŋɡwɪdʒ | tʌŋ | ভাষা | জিহ্বা',
    'voice | vocalisation | vɔɪs | ˌvəʊkəlaɪˈzeɪʃn | কণ্ঠ | কণ্ঠস্বর',
    'sound | acoustic signal | saʊnd | əˈkuːstɪk ˈsɪɡnl | শব্দ | ধ্বনিসংকেত',
    'colour | hue | ˈkʌlə | hjuː | রং | বর্ণ',
    'shape | form | ʃeɪp | fɔːm | আকৃতি | রূপ',
    'line | linear mark | laɪn | ˈlɪniə mɑːk | রেখা | সরলচিহ্ন',
    'picture | depiction | ˈpɪktʃə | dɪˈpɪkʃn | ছবি | চিত্রণ',
    'map | cartographic chart | mæp | ˌkɑːtəˈɡræfɪk tʃɑːt | মানচিত্র | মানচিত্রপট',
    'law | statute | lɔː | ˈstætʃuːt | আইন | বিধি',
    'rule | ordinance | ruːl | ˈɔːdɪnəns | নিয়ম | বিধান',
    'right | entitlement | raɪt | ɪnˈtaɪtlmənt | অধিকার | প্রাপ্যতা',
    'duty | obligation | ˈdjuːti | ˌɒblɪˈɡeɪʃn | কর্তব্য | বাধ্যবাধকতা',
    'power | authority | ˈpaʊə | ɔːˈθɒrəti | ক্ষমতা | কর্তৃত্ব',
    'government | administration | ˈɡʌvənmənt | ədˌmɪnɪˈstreɪʃn | সরকার | প্রশাসন',
    'leader | principal | ˈliːdə | ˈprɪnsəpl | নেতা | প্রধান',
    'member | constituent | ˈmembə | kənˈstɪtjuənt | সদস্য | অংশবিশেষ',
    'group of people | assemblage | ɡruːp əv ˈpiːpl | əˈsemblɪdʒ | দল | সমবেশ',
    'crowd | multitude | kraʊd | ˈmʌltɪtjuːd | ভিড় | জনসমুদ্র',
    'war | armed conflict | wɔː | ɑːmd ˈkɒnflɪkt | যুদ্ধ | সশস্ত্র সংঘাত',
    'peace | concord | piːs | ˈkɒŋkɔːd | শান্তি | সমঝোতা',
    'army | military force | ˈɑːmi | ˈmɪlətri fɔːs | সেনা | সামরিক বাহিনী',
    'police | constabulary | pəˈliːs | kənˈstæbjələri | পুলিশ | আইনশৃঙ্খলা বাহিনী',
    'crime | offence | kraɪm | əˈfens | অপরাধ | অপকর্ম',
    'thief | perpetrator | θiːf | ˈpɜːpətreɪtə | চোর | অপরাধী',
    'judge | magistrate | dʒʌdʒ | ˈmædʒɪstreɪt | বিচারক | ম্যাজিস্ট্রেট',
    'court | tribunal | kɔːt | traɪˈbjuːnl | আদালত | বিচারসভা',
    'prison | penitentiary | ˈprɪzn | ˌpenɪˈtenʃəri | কারাগার | কারাগার',
    'doctor | physician | ˈdɒktə | fɪˈzɪʃn | ডাক্তার | চিকিৎসক',
    'hospital | infirmary | ˈhɒspɪtl | ɪnˈfɜːməri | হাসপাতাল | চিকিৎসালয়',
    'medicine | pharmaceutical | ˈmedsn | ˌfɑːməˈsuːtɪkl | ওষুধ | ঔষধ',
    'pain | discomfort | peɪn | dɪsˈkʌmfət | ব্যথা | অস্বস্তি',
    'health | wellbeing | helθ | ˌwelˈbiːɪŋ | স্বাস্থ্য | কুশল',
    'school | academy | skuːl | əˈkædəmi | স্কুল | শিক্ষায়তন',
    'university | tertiary institution | ˌjuːnɪˈvɜːsəti | ˈtɜːʃəri ˌɪnstɪˈtjuːʃn | বিশ্ববিদ্যালয় | উচ্চশিক্ষা প্রতিষ্ঠান',
    'student | undergraduate | ˈstjuːdnt | ˌʌndəˈɡrædʒuət | ছাত্র | স্নাতক শিক্ষার্থী',
    'lesson | tutorial | ˈlesn | tjuːˈtɔːriəl | পাঠ | শিক্ষাপর্ব',
    'exam paper | assessment | ɪɡˈzæm ˈpeɪpə | əˈsesmənt | পরীক্ষা | মূল্যায়ন',
    'mark | grade | mɑːk | ɡreɪd | নম্বর | গ্রেড',
    'degree | academic award | dɪˈɡriː | ˌækəˈdemɪk əˈwɔːd | ডিগ্রি | একাডেমিক সম্মান',
    'job interview | selection meeting | dʒɒb ˈɪntəvjuː | sɪˈlekʃn ˈmiːtɪŋ | সাক্ষাৎকার | নির্বাচনী বৈঠক',
    'salary | remuneration | ˈsæləri | rɪˌmjuːnəˈreɪʃn | বেতন | পারিশ্রমিক',
    'boss at work | superior | bɒs ət wɜːk | suːˈpɪəriə | বস | ঊর্ধ্বতন',
    'company | corporation | ˈkʌmpəni | ˌkɔːpəˈreɪʃn | কোম্পানি | নিগম',
    'factory | manufacturing plant | ˈfæktri | ˌmænjuˈfæktʃərɪŋ plɑːnt | কারখানা | উৎপাদন কেন্দ্র',
    'farm | agricultural holding | fɑːm | ˌæɡrɪˈkʌltʃərəl ˈhəʊldɪŋ | খামার | কৃষিজমি',
    'field | cultivated land | fiːld | ˈkʌltɪveɪtɪd lænd | মাঠ | চাষের জমি',
    'tree | woody plant | triː | ˈwʊdi plɑːnt | গাছ | কাষ্ঠল উদ্ভিদ',
    'flower | blossom | ˈflaʊə | ˈblɒsəm | ফুল | পুষ্প',
    'animal | creature | ˈænɪml | ˈkriːtʃə | প্রাণী | জীব',
    'bird | avian | bɜːd | ˈeɪviən | পাখি | পক্ষী',
    'dog | canine | dɒɡ | ˈkeɪnaɪn | কুকুর | কুকুরজাতীয়',
    'cat | feline | kæt | ˈfiːlaɪn | বিড়াল | বিড়ালজাতীয়',
    'god | deity | ɡɒd | ˈdeɪəti | ঈশ্বর | দেবতা',
    'religion | faith | rɪˈlɪdʒən | feɪθ | ধর্ম | বিশ্বাস',
    'church | place of worship | tʃɜːtʃ | pleɪs əv ˈwɜːʃɪp | গির্জা | উপাসনালয়',
    'prayer | supplication | preə | ˌsʌplɪˈkeɪʃn | প্রার্থনা | মিনতি',
    'art | creative work | ɑːt | kriˈeɪtɪv wɜːk | শিল্প | সৃজনশীল কাজ',
    'music | auditory art | ˈmjuːzɪk | ˈɔːdɪtri ɑːt | সঙ্গীত | শ্রবণশিল্প',
    'dance | choreography | dɑːns | ˌkɒriˈɒɡrəfi | নাচ | নৃত্যপরিকল্পনা',
    'theatre | dramatic venue | ˈθɪətə | drəˈmætɪk ˈvenjuː | থিয়েটার | নাট্যমঞ্চ',
    'museum | repository | mjuˈziːəm | rɪˈpɒzɪtri | জাদুঘর | সংগ্রহশালা',
    'library | archive | ˈlaɪbrəri | ˈɑːkaɪv | গ্রন্থাগার | নথিভান্ডার',
    'holiday | vacation | ˈhɒlədeɪ | vəˈkeɪʃn | ছুটি | অবকাশ',
    'trip | excursion | trɪp | ɪkˈskɜːʃn | ভ্রমণ | পর্যটন',
    'hotel | lodging | həʊˈtel | ˈlɒdʒɪŋ | হোটেল | আবাসন',
    'ticket | voucher | ˈtɪkɪt | ˈvaʊtʃə | টিকিট | ভাউচার',
    'passport | travel document | ˈpɑːspɔːt | ˈtrævl ˈdɒkjəmənt | পাসপোর্ট | ভ্রমণদলিল',
    'border | frontier | ˈbɔːdə | ˈfrʌntɪə | সীমান্ত | সীমানা',
    'island | isle | ˈaɪlənd | aɪl | দ্বীপ | দ্বীপভূমি',
    'mountain | peak | ˈmaʊntɪn | piːk | পাহাড় | শৃঙ্গ',
    'river | watercourse | ˈrɪvə | ˈwɔːtəkɔːs | নদী | জলধারা',
    'sea | ocean | siː | ˈəʊʃn | সমুদ্র | মহাসাগর',
    'sky | firmament | skaɪ | ˈfɜːməmənt | আকাশ | নভোমণ্ডল',
    'star | celestial body | stɑː | səˈlestiəl ˈbɒdi | তারা | জ্যোতিষ্ক',
    'night | nocturnal hours | naɪt | nɒkˈtɜːnl ˈaʊəz | রাত | নিশাসময়',
    'morning | forenoon | ˈmɔːnɪŋ | ˈfɔːnuːn | সকাল | পূর্বাহ্ন',
    'evening | dusk | ˈiːvnɪŋ | dʌsk | সন্ধ্যা | গোধূলি',
    'today | the present day | təˈdeɪ | ðə ˈpreznt deɪ | আজ | অদ্য',
    'tomorrow | the following day | təˈmɒrəʊ | ðə ˈfɒləʊɪŋ deɪ | আগামীকাল | পরদিন',
    'yesterday | the preceding day | ˈjestədeɪ | ðə prɪˈsiːdɪŋ deɪ | গতকাল | পূর্বদিন',
    'week | seven day period | wiːk | ˈsevn deɪ ˈpɪəriəd | সপ্তাহ | সাতদিন',
    'month | calendar month | mʌnθ | ˈkælɪndə mʌnθ | মাস | পঞ্জিকা মাস',
    'hour | sixty minutes | ˈaʊə | ˈsɪksti ˈmɪnɪts | ঘণ্টা | ষাট মিনিট',
    'minute | sixty seconds | ˈmɪnɪt | ˈsɪksti ˈsekəndz | মিনিট | ষাট সেকেন্ড',
    'second | instant | ˈsekənd | ˈɪnstənt | সেকেন্ড | মুহূর্ত',
    'clock | timepiece | klɒk | ˈtaɪmpiːs | ঘড়ি | সময়যন্ত্র',
    'watch | timepiece | wɒtʃ | ˈtaɪmpiːs | হাতঘড়ি | সময়যন্ত্র',
    'key | implement | kiː | ˈɪmplɪmənt | চাবি | সরঞ্জাম',
    'lock | fastening | lɒk | ˈfɑːsnɪŋ | তালা | বন্ধনী',
    'box | container | bɒks | kənˈteɪnə | বাক্স | পাত্র',
    'bottle | flask | ˈbɒtl | flɑːsk | বোতল | ফ্লাস্ক',
    'cup | vessel | kʌp | ˈvesl | কাপ | পাত্র',
    'plate | dish | pleɪt | dɪʃ | থালা | পাত্র',
    'knife | blade | naɪf | bleɪd | ছুরি | ফলা',
    'spoon | utensil | spuːn | juːˈtensl | চামচ | বাসন',
    'fork | utensil | fɔːk | juːˈtensl | কাঁটাচামচ | বাসন',
    'glass | drinking vessel | ɡlɑːs | ˈdrɪŋkɪŋ ˈvesl | গ্লাস | পানপাত্র',
    'paper money | banknote | ˈpeɪpə ˈmʌni | ˈbæŋknəʊt | নোট | ব্যাংকনোট',
    'coin | specie | kɔɪn | ˈspiːʃiː | মুদ্রা | ধাতব মুদ্রা',
    'bank | financial institution | bæŋk | faɪˈnænʃl ˌɪnstɪˈtjuːʃn | ব্যাংক | আর্থিক প্রতিষ্ঠান',
    'account | ledger | əˈkaʊnt | ˈledʒə | হিসাব | খতিয়ান',
    'bill | invoice | bɪl | ˈɪnvɔɪs | বিল | চালান',
    'tax | levy | tæks | ˈlevi | কর | শুল্ক',
    'rent | tenancy fee | rent | ˈtenənsi fiː | ভাড়া | ভাড়াচুক্তির ফি',
    'house rent | accommodation charge | haʊs rent | əˌkɒməˈdeɪʃn tʃɑːdʒ | বাড়িভাড়া | আবাসন খরচ',
    'gift wrap | wrapping | ɡɪft ræp | ˈræpɪŋ | মোড়ক | আচ্ছাদন',
    'party time | festivity | ˈpɑːti taɪm | feˈstɪvəti | আনন্দ | উৎসব',
    'wedding | nuptials | ˈwedɪŋ | ˈnʌpʃlz | বিয়ে | শুভপরিণয়',
    'birthday | anniversary of birth | ˈbɜːθdeɪ | ˌænɪˈvɜːsəri əv bɜːθ | জন্মদিন | জন্মবার্ষিকী',
    'death | passing | deθ | ˈpɑːsɪŋ | মৃত্যু | তিরোধান',
    'grave | tomb | ɡreɪv | tuːm | কবর | সমাধি',
    'god bless | benediction | ɡɒd bles | ˌbenɪˈdɪkʃn | আশীর্বাদ | মঙ্গলকামনা',
    'raincoat | waterproof | ˈreɪnkəʊt | ˈwɔːtəpruːf | রেইনকোট | জলনিরোধক পোশাক',
    'umbrella | parasol | ʌmˈbrelə | ˈpærəsɒl | ছাতা | সূর্যছায়া',
    'jumper | pullover | ˈdʒʌmpə | ˈpʊləʊvə | জাম্পার | পুলওভার',
    'vest | waistcoat | vest | ˈweskɪt | ভেস্ট | ওয়েস্টকোট',
    'tie | necktie | taɪ | ˈnektaɪ | টাই | গলবন্ধনী',
    'belt | waistband | belt | ˈweɪstbænd | বেল্ট | কটিবন্ধ',
    'socks | hosiery | sɒks | ˈhəʊzəri | মোজা | পায়ে পরিধেয়',
    'gloves | gauntlets | ɡlʌvz | ˈɡɔːntlɪts | দস্তানা | হাতমোজা',
    'hat | headwear | hæt | ˈhedweə | টুপি | মস্তকাবরণ',
    'cap | head covering | kæp | hed ˈkʌvərɪŋ | ক্যাপ | মাথার আবরণ',
    'scarf | muffler | skɑːf | ˈmʌflə | স্কার্ফ | গলরুমাল',
    'glasses | spectacles | ˈɡlɑːsɪz | ˈspektəklz | চশমা | দৃষ্টি কাচ',
    'suitcase | valise | ˈsuːtkeɪs | vəˈliːz | স্যুটকেস | ভ্রমণপেটিকা',
    'backpack | rucksack | ˈbækpæk | ˈrʌksæk | ব্যাকপ্যাক | পিঠের থলে',
    'wallet | billfold | ˈwɒlɪt | ˈbɪlfəʊld | মানিব্যাগ | নোটধারক',
    'purse | handbag | pɜːs | ˈhændbæɡ | পার্স | হাতব্যাগ',
    'mirror | looking glass | ˈmɪrə | ˈlʊkɪŋ ɡlɑːs | আয়না | দর্পণ',
    'towel | drying cloth | ˈtaʊəl | ˈdraɪɪŋ klɒθ | তোয়ালে | শুষ্কক বস্ত্র',
    'pillow | cushion | ˈpɪləʊ | ˈkʊʃn | বালিশ | উপধান',
    'blanket | coverlet | ˈblæŋkɪt | ˈkʌvəlɪt | কম্বল | আচ্ছাদনী',
    'mattress | pallet | ˈmætrɪs | ˈpælɪt | গদি | শয়নতল',
    'curtain | drape | ˈkɜːtn | dreɪp | পর্দা | অবগুণ্ঠন',
    'carpet | flooring | ˈkɑːpɪt | ˈflɔːrɪŋ | গালিচা | মেঝে আচ্ছাদন',
    'rug | floor covering | rʌɡ | flɔː ˈkʌvərɪŋ | রাগ | মেঝের আবরণ',
    'sofa | settee | ˈsəʊfə | seˈtiː | সোফা | আসনপীঠ',
    'armchair | easy chair | ˈɑːmtʃeə | ˈiːzi tʃeə | আরামকেদারা | সুখাসন',
    'stool | footrest | stuːl | ˈfʊtrest | টুল | পা রাখার আসন',
    'lamp | light fitting | læmp | laɪt ˈfɪtɪŋ | বাতি | আলোকসজ্জা',
    'bulb | electric lamp | bʌlb | ɪˈlektrɪk læmp | বাল্ব | বিদ্যুৎ প্রদীপ',
    'plug | connector | plʌɡ | kəˈnektə | প্লাগ | সংযোগক',
    'battery | cell | ˈbætəri | sel | ব্যাটারি | কোষ',
    'switch | actuator | swɪtʃ | ˈæktʃʊeɪtə | সুইচ | সঞ্চালক',
    'wire | conductor | ˈwaɪə | kənˈdʌktə | তার | পরিবাহী',
    'soap | cleansing agent | səʊp | ˈklenzɪŋ ˈeɪdʒənt | সাবান | পরিষ্কারক',
    'brush | applicator | brʌʃ | ˈæplɪkeɪtə | ব্রাশ | প্রলেপক',
    'comb | hairdressing tool | kəʊm | ˈheədresɪŋ tuːl | চিরুনি | কেশসজ্জা যন্ত্র',
    'needle | stitching implement | ˈniːdl | ˈstɪtʃɪŋ ˈɪmplɪmənt | সুই | সেলাই সরঞ্জাম',
    'thread | filament | θred | ˈfɪləmənt | সুতা | তন্তু',
    'button | fastener | ˈbʌtn | ˈfɑːsnə | বোতাম | সংযোজক',
    'zip | zipper | zɪp | ˈzɪpə | জিপ | চেইনবন্ধনী',
  ],
};
