import { type IRawFormalInformalGroup } from './schema';

/**
 * Everyday informal → formal swaps.
 *
 * The long list a learner meets first: the words they already say, and the
 * words a letter, an exam or a stranger is waiting for. Slash and comma
 * alternatives on the source page were folded to the first formal, so each
 * row teaches one swap rather than a menu.
 */
export const PAIRS_COMMON: IRawFormalInformalGroup = {
  topic: 'common',
  entries: [
    'a bit | a little | ə ˈbɪt | ə ˈlɪtl | একটু | সামান্য',
    'a lot of | numerous | ə ˈlɒt əv | ˈnjuːmərəs | অনেক | অসংখ্য',
    'afraid | fearful | əˈfreɪd | ˈfɪəfl | ভীত | আতঙ্কিত',
    'again and again | repeatedly | əˈɡen ənd əˈɡen | rɪˈpiːtɪdli | বারবার | পুনঃপুনঃ',
    'also | in addition | ˈɔːlsəʊ | ɪn əˈdɪʃn | এছাড়াও | তদুপরি',
    'anyway | nevertheless | ˈeniweɪ | ˌnevəðəˈles | যাই হোক | তথাপি',
    'ask | enquire | ɑːsk | ɪnˈkwaɪə | জিজ্ঞাসা করা | অনুসন্ধান করা',
    'ask for | request | ˈɑːsk fɔː | rɪˈkwest | চাওয়া | অনুরোধ করা',
    'ask out | invite | ˈɑːsk aʊt | ɪnˈvaɪt | ডেকে নিয়ে যাওয়া | আমন্ত্রণ জানানো',
    'at first | initially | ət ˈfɜːst | ɪˈnɪʃəli | প্রথমে | প্রাথমিকভাবে',
    'at once | immediately | ət ˈwʌns | ɪˈmiːdiətli | তখনই | অবিলম্বে',
    'avoid | evade | əˈvɔɪd | ɪˈveɪd | এড়ানো | পরিহার করা',
    'away | absent | əˈweɪ | ˈæbsənt | দূরে | অনুপস্থিত',
    'bad | negative | bæd | ˈneɡətɪv | খারাপ | নেতিবাচক',
    'beat up | assault | ˈbiːt ʌp | əˈsɔːlt | মারধর করা | আক্রমণ করা',
    'better | improved | ˈbetə | ɪmˈpruːvd | আরও ভালো | উন্নত',
    'big | enormous | bɪɡ | ɪˈnɔːməs | বড় | বিশাল',
    'block | undermine | blɒk | ˌʌndəˈmaɪn | বাধা দেওয়া | দুর্বল করা',
    'blow up | explode | ˈbləʊ ʌp | ɪkˈspləʊd | ফাটিয়ে দেওয়া | বিস্ফোরিত হওয়া',
    'book | reserve | bʊk | rɪˈzɜːv | বুক করা | সংরক্ষণ করা',
    'boss | employer | bɒs | ɪmˈplɔɪə | বস | নিয়োগকর্তা',
    'brave | courageous | breɪv | kəˈreɪdʒəs | সাহসী | বীরত্বপূর্ণ',
    'break down | fail | ˈbreɪk daʊn | feɪl | নষ্ট হয়ে যাওয়া | ব্যর্থ হওয়া',
    'break off | suspend | ˈbreɪk ɒf | səˈspend | ভেঙে দেওয়া | স্থগিত করা',
    'break out | erupt | ˈbreɪk aʊt | ɪˈrʌpt | ছড়িয়ে পড়া | প্রকোপ বাড়া',
    'bright | intelligent | braɪt | ɪnˈtelɪdʒənt | চালাক | বুদ্ধিমান',
    'bring in | introduce | ˈbrɪŋ ɪn | ˌɪntrəˈdjuːs | নিয়ে আসা | প্রবর্তন করা',
    'build | construct | bɪld | kənˈstrʌkt | তৈরি করা | নির্মাণ করা',
    'but | however | bət | haʊˈevə | কিন্তু | তবে',
    'buy | purchase | baɪ | ˈpɜːtʃəs | কেনা | ক্রয় করা',
    'by | by means of | baɪ | baɪ ˈmiːnz ɒv | দ্বারা | মাধ্যমে',
    'call off | cancel | ˈkɔːl ɒf | ˈkænsl | বাতিল করা | রদ করা',
    'call on | visit | ˈkɔːl ɒn | ˈvɪzɪt | দেখা করতে যাওয়া | সাক্ষাৎ করা',
    'can | is capable of | kæn | ɪz ˈkeɪpəbl ɒv | পারা | সক্ষম হওয়া',
    'catch up | understand | ˈkætʃ ʌp | ˌʌndəˈstænd | ধরে ফেলা | বুঝতে পারা',
    'chance | opportunity | tʃɑːns | ˌɒpəˈtjuːnəti | সুযোগ | সুযোগসন্ধান',
    'cheap | inexpensive | tʃiːp | ˌɪnɪkˈspensɪv | সস্তা | সাশ্রয়ী',
    'check | verify | tʃek | ˈverɪfaɪ | দেখা | যাচাই করা',
    'childish | infantile | ˈtʃaɪldɪʃ | ˈɪnfəntaɪl | শিশুসুলভ | শিশুবৎ',
    'choose | select | tʃuːz | sɪˈlekt | বেছে নেওয়া | নির্বাচন করা',
    'clear | transparent | klɪə | trænˈspærənt | পরিষ্কার | স্বচ্ছ',
    'climb | ascend | klaɪm | əˈsend | ওঠা | আরোহণ করা',
    'clothes | garment | kləʊðz | ˈɡɑːmənt | জামাকাপড় | পরিধেয়',
    'come after | follow | ˈkʌm ˈɑːftə | ˈfɒləʊ | পেছনে আসা | অনুসরণ করা',
    'come in | enter | ˈkʌm ɪn | ˈentə | ভিতরে আসা | প্রবেশ করা',
    'come up to | reach | ˈkʌm ʌp tuː | riːtʃ | পৌঁছানো | অধিগত করা',
    'complex | convoluted | ˈkɒmpleks | ˈkɒnvəluːtɪd | জটিল | দুর্বোধ্য',
    'dad | father | dæd | ˈfɑːðə | বাবা | পিতা',
    'danger | peril | ˈdeɪndʒə | ˈperəl | বিপদ | সংকট',
    'dare | challenge | deə | ˈtʃælɪndʒ | সাহস করা | চ্যালেঞ্জ করা',
    'deal with | handle | ˈdiːl wɪð | ˈhændl | মোকাবিলা করা | নিষ্পত্তি করা',
    'death | demise | deθ | dɪˈmaɪz | মৃত্যু | তিরোধান',
    'describe | depict | dɪˈskraɪb | dɪˈpɪkt | বর্ণনা করা | চিত্রিত করা',
    'dim | indistinct | dɪm | ˌɪndɪˈstɪŋkt | ম্লান | অস্পষ্ট',
    'dirty | contaminated | ˈdɜːti | kənˈtæmɪneɪtɪd | নোংরা | দূষিত',
    'drop out of | withdraw | ˈdrɒp aʊt ɒv | wɪðˈdrɔː | ছেড়ে দেওয়া | প্রত্যাহার করা',
    'eager | avid | ˈiːɡə | ˈævɪd | আগ্রহী | উদগ্রীব',
    'ease | facilitate | iːz | fəˈsɪlɪteɪt | সহজ করা | সহায়ক করা',
    'empty | vacant | ˈempti | ˈveɪkənt | খালি | শূন্য',
    'end | terminate | end | ˈtɜːmɪneɪt | শেষ করা | সমাপ্ত করা',
    'enjoyment | gratification | ɪnˈdʒɔɪmənt | ˌɡrætɪfɪˈkeɪʃn | আনন্দ | পরিতৃপ্তি',
    'enough | sufficient | ɪˈnʌf | səˈfɪʃnt | যথেষ্ট | পর্যাপ্ত',
    'expect | anticipate | ɪkˈspekt | ænˈtɪsɪpeɪt | আশা করা | প্রত্যাশা করা',
    'explain | disclose | ɪkˈspleɪn | dɪsˈkləʊz | ব্যাখ্যা করা | প্রকাশ করা',
    'fall out | quarrel | ˈfɔːl aʊt | ˈkwɒrəl | ঝগড়া করা | বিবাদ করা',
    'fight | combat | faɪt | ˈkɒmbæt | লড়াই | সংগ্রাম',
    'find out | discover | ˈfaɪnd aʊt | dɪˈskʌvə | খুঁজে বের করা | আবিষ্কার করা',
    'fork out | pay | ˈfɔːk aʊt | peɪ | টাকা খরচ করা | পরিশোধ করা',
    'free | release | friː | rɪˈliːs | মুক্ত করা | অব্যাহতি দেওয়া',
    'friendly | amiable | ˈfrendli | ˈeɪmiəbl | বন্ধুসুলভ | স্নেহশীল',
    'funny | humorous | ˈfʌni | ˈhjuːmərəs | মজার | রসাত্মক',
    'get | receive | ɡet | rɪˈsiːv | পাওয়া | গ্রহণ করা',
    'get away | elude | ˈɡet əˈweɪ | ɪˈluːd | পালিয়ে যাওয়া | এড়িয়ে যাওয়া',
    'get by | survive | ˈɡet baɪ | səˈvaɪv | কোনোভাবে চলা | টিকে থাকা',
    'get out | escape | ˈɡet aʊt | ɪˈskeɪp | বেরিয়ে যাওয়া | পলায়ন করা',
    'give | provide | ɡɪv | prəˈvaɪd | দেওয়া | সরবরাহ করা',
    'give out | distribute | ˈɡɪv aʊt | dɪˈstrɪbjuːt | ভাগ করে দেওয়া | বিতরণ করা',
    'give up | quit | ˈɡɪv ʌp | kwɪt | ছেড়ে দেওয়া | ত্যাগ করা',
    'go | depart | ɡəʊ | dɪˈpɑːt | যাওয়া | প্রস্থান করা',
    'go after | pursue | ˈɡəʊ ˈɑːftə | pəˈsjuː | পেছনে যাওয়া | অনুসরণ করা',
    'go against | oppose | ˈɡəʊ əˈɡenst | əˈpəʊz | বিরুদ্ধে যাওয়া | প্রতিবাদ করা',
    'go ahead | proceed | ˈɡəʊ əˈhed | prəˈsiːd | এগিয়ে যাওয়া | অগ্রসর হওয়া',
    'go away | leave | ˈɡəʊ əˈweɪ | liːv | চলে যাওয়া | প্রস্থান করা',
    'go before | precede | ˈɡəʊ bɪˈfɔː | prɪˈsiːd | আগে যাওয়া | পূর্বগামী হওয়া',
    'go down | decrease | ˈɡəʊ daʊn | dɪˈkriːs | কমে যাওয়া | হ্রাস পাওয়া',
    'go on | continue | ˈɡəʊ ɒn | kənˈtɪnjuː | চালিয়ে যাওয়া | অব্যাহত রাখা',
    'go out of | exit | ˈɡəʊ aʊt ɒv | ˈeksɪt | বেরিয়ে যাওয়া | নির্গমন করা',
    'go through | examine | ˈɡəʊ θruː | ɪɡˈzæmɪn | খুঁটিয়ে দেখা | পরীক্ষা করা',
    'go up | increase | ˈɡəʊ ʌp | ˈɪnkriːs | বেড়ে যাওয়া | বৃদ্ধি পাওয়া',
    'good | positive | ɡʊd | ˈpɒzətɪv | ভালো | ইতিবাচক',
    'good for | beneficial | ˈɡʊd fɔː | ˌbenɪˈfɪʃl | উপকারী | কল্যাণকর',
    'good looking | attractive | ˈɡʊd ˈlʊkɪŋ | əˈtræktɪv | সুন্দর | আকর্ষণীয়',
    'happy | pleased | ˈhæpi | pliːzd | খুশি | সন্তুষ্ট',
    'help | aid | help | eɪd | সাহায্য | সহায়তা',
    'here | present | hɪə | ˈpreznt | এখানে | উপস্থিত',
    'hit out at | criticise | ˈhɪt aʊt ət | ˈkrɪtɪsaɪz | আক্রমণ করা | সমালোচনা করা',
    'hopeless | futile | ˈhəʊpləs | ˈfjuːtaɪl | আশাহীন | নিষ্ফল',
    'hungry | famished | ˈhʌŋɡri | ˈfæmɪʃt | ক্ষুধার্ত | অভুক্ত',
    'hurry | haste | ˈhʌri | heɪst | তাড়া | ত্বরতা',
    'hurt | damage | hɜːt | ˈdæmɪdʒ | আঘাত | ক্ষতি',
    'idea | notion | aɪˈdɪə | ˈnəʊʃn | ধারণা | মতবাদ',
    'imagine | envisage | ɪˈmædʒɪn | ɪnˈvɪzɪdʒ | কল্পনা করা | অনুমান করা',
    'in charge of | responsible | ɪn ˈtʃɑːdʒ ɒv | rɪˈspɒnsəbl | দায়িত্বে | দায়িত্বশীল',
    'in the end | finally | ɪn ði ˈend | ˈfaɪnəli | শেষে | অবশেষে',
    'iron out | solve | ˈaɪən aʊt | sɒlv | মিটিয়ে ফেলা | সমাধান করা',
    'job | occupation | dʒɒb | ˌɒkjuˈpeɪʃn | চাকরি | পেশা',
    'keep | preserve | kiːp | prɪˈzɜːv | রাখা | সংরক্ষণ করা',
    'kidding | jesting | ˈkɪdɪŋ | ˈdʒestɪŋ | মজা করা | পরিহাস করা',
    'kids | children | kɪdz | ˈtʃɪldrən | বাচ্চারা | শিশুরা',
    'lack | deficiency | læk | dɪˈfɪʃnsi | অভাব | ঘাটতি',
    'laid back | relaxed | ˈleɪd bæk | rɪˈlækst | চিন্তামুক্ত | স্বচ্ছন্দ',
    'lead to | cause | ˈliːd tuː | kɔːz | ঘটানো | কারণ হওয়া',
    'leave out | omit | ˈliːv aʊt | əˈmɪt | বাদ দেওয়া | পরিহার করা',
    'let | allow | let | əˈlaʊ | দিতে দেওয়া | অনুমতি দেওয়া',
    'link up | connect | ˈlɪŋk ʌp | kəˈnekt | যুক্ত করা | সংযোগ করা',
    'live | reside | lɪv | rɪˈzaɪd | থাকা | বসবাস করা',
    'lively | energetic | ˈlaɪvli | ˌenəˈdʒetɪk | প্রাণবন্ত | কর্মঠ',
    'look at | regard | ˈlʊk ət | rɪˈɡɑːd | দেখা | বিবেচনা করা',
    'look for | seek | ˈlʊk fɔː | siːk | খোঁজা | অন্বেষণ করা',
    'look into | investigate | ˈlʊk ˈɪntuː | ɪnˈvestɪɡeɪt | খতিয়ে দেখা | তদন্ত করা',
    'look like | resemble | ˈlʊk laɪk | rɪˈzembl | মনে হওয়া | সাদৃশ্য রাখা',
    'look up to | respect | ˈlʊk ʌp tuː | rɪˈspekt | শ্রদ্ধা করা | সম্মান করা',
    'lucky | fortunate | ˈlʌki | ˈfɔːtʃənət | ভাগ্যবান | সৌভাগ্যবান',
    'mad | insane | mæd | ɪnˈseɪn | পাগল | উন্মাদ',
    'mainly | principally | ˈmeɪnli | ˈprɪnsəpəli | প্রধানত | মূলত',
    'make out | discern | ˈmeɪk aʊt | dɪˈsɜːn | বুঝতে পারা | উপলব্ধি করা',
    'make up | invent | ˈmeɪk ʌp | ɪnˈvent | বানিয়ে বলা | উদ্ভাবন করা',
    'marvelous | exceptional | ˈmɑːvələs | ɪkˈsepʃənl | চমৎকার | অসাধারণ',
    'maybe | perhaps | ˈmeɪbi | pəˈhæps | হয়তো | সম্ভবত',
    'mend | repair | mend | rɪˈpeə | সারানো | মেরামত করা',
    'naked | nude | ˈneɪkɪd | njuːd | উলঙ্গ | নগ্ন',
    'need | require | niːd | rɪˈkwaɪə | দরকার | প্রয়োজন',
    'next | subsequently | nekst | ˈsʌbsɪkwəntli | পরে | পরবর্তীকালে',
    'okay | acceptable | ˌəʊˈkeɪ | əkˈseptəbl | ঠিক আছে | গ্রহণযোগ্য',
    'old | elderly | əʊld | ˈeldəli | বয়স্ক | প্রবীণ',
    'older | senior | ˈəʊldə | ˈsiːniə | বড় | জ্যেষ্ঠ',
    'over | at an end | ˈəʊvə | ət ən ˈend | শেষ | সমাপ্ত',
    'pay back | repay | ˈpeɪ bæk | rɪˈpeɪ | ফেরত দেওয়া | পরিশোধ করা',
    'pick up | collect | ˈpɪk ʌp | kəˈlekt | তুলে নেওয়া | সংগ্রহ করা',
    'pin down | determine | ˈpɪn daʊn | dɪˈtɜːmɪn | নিশ্চিত করা | নির্ধারণ করা',
    'point out | indicate | ˈpɔɪnt aʊt | ˈɪndɪkeɪt | দেখিয়ে দেওয়া | নির্দেশ করা',
    'put in | insert | ˈpʊt ɪn | ɪnˈsɜːt | ঢোকানো | সন্নিবেশ করা',
    'put off | postpone | ˈpʊt ɒf | pəˈspəʊn | পেছানো | স্থগিত করা',
    'put up with | tolerate | ˈpʊt ʌp wɪð | ˈtɒləreɪt | সহ্য করা | সহ্য করা',
    'rack up | accumulate | ˈræk ʌp | əˈkjuːmjəleɪt | জমানো | সঞ্চয় করা',
    'really big | considerable | ˈrɪəli bɪɡ | kənˈsɪdərəbl | খুব বড় | উল্লেখযোগ্য',
    'refer to | consult | rɪˈfɜː tuː | kənˈsʌlt | দেখা | পরামর্শ নেওয়া',
    'remove | eliminate | rɪˈmuːv | ɪˈlɪmɪneɪt | সরানো | অপসারণ করা',
    'rich | wealthy | rɪtʃ | ˈwelθi | ধনী | সম্পদশালী',
    'right | correct | raɪt | kəˈrekt | ঠিক | সঠিক',
    'round | circular | raʊnd | ˈsɜːkjələ | গোল | বৃত্তাকার',
    'say | express | seɪ | ɪkˈspres | বলা | প্রকাশ করা',
    'say no | reject | ˈseɪ nəʊ | rɪˈdʒekt | না বলা | প্রত্যাখ্যান করা',
    'say sorry | apologise | ˈseɪ ˈsɒri | əˈpɒlədʒaɪz | দুঃখ প্রকাশ | ক্ষমা চাওয়া',
    'see | observe | siː | əbˈzɜːv | দেখা | পর্যবেক্ষণ করা',
    'seem | appear | siːm | əˈpɪə | মনে হওয়া | প্রতীয়মান হওয়া',
    'set out | display | ˈset aʊt | dɪˈspleɪ | সাজিয়ে রাখা | প্রদর্শন করা',
    'set up | establish | ˈset ʌp | ɪˈstæblɪʃ | গড়ে তোলা | প্রতিষ্ঠা করা',
    'settle for | choose | ˈsetl fɔː | tʃuːz | মেনে নেওয়া | নির্বাচন করা',
    'shorten | decrease | ˈʃɔːtn | dɪˈkriːs | ছোট করা | হ্রাস করা',
    'show | demonstrate | ʃəʊ | ˈdemənstreɪt | দেখানো | প্রদর্শন করা',
    'sick | ill | sɪk | ɪl | অসুস্থ | রুগ্ন',
    'sight | vision | saɪt | ˈvɪʒn | দৃষ্টি | দর্শন',
    'small | diminutive | smɔːl | dɪˈmɪnjətɪv | ছোট | ক্ষুদ্র',
    'so | therefore | səʊ | ˈðeəfɔː | তাই | অতএব',
    'speed up | accelerate | ˈspiːd ʌp | əkˈseləreɪt | তাড়াতাড়ি করা | ত্বরান্বিত করা',
    'start | commence | stɑːt | kəˈmens | শুরু করা | আরম্ভ করা',
    'stop | cease | stɒp | siːs | থামা | নিবৃত্ত হওয়া',
    'stubborn | obstinate | ˈstʌbən | ˈɒbstɪnət | একগুঁয়ে | জেদি',
    'sweat | perspiration | swet | ˌpɜːspəˈreɪʃn | ঘাম | স্বেদ',
    'take out | extract | ˈteɪk aʊt | ɪkˈstrækt | বের করা | নিষ্কাশন করা',
    'talk about | discuss | ˈtɔːk əˈbaʊt | dɪˈskʌs | কথা বলা | আলোচনা করা',
    'talk into | persuade | ˈtɔːk ˈɪntuː | pəˈsweɪd | রাজি করানো | প্ররোচিত করা',
    'tell | inform | tel | ɪnˈfɔːm | বলা | অবহিত করা',
    'test | experiment | test | ɪkˈsperɪmənt | পরীক্ষা | পরীক্ষণ',
    'thanks | gratitude | θæŋks | ˈɡrætɪtjuːd | ধন্যবাদ | কৃতজ্ঞতা',
    'think about | consider | ˈθɪŋk əˈbaʊt | kənˈsɪdə | ভাবা | বিবেচনা করা',
    'think of | conceive | ˈθɪŋk ɒv | kənˈsiːv | মনে করা | কল্পনা করা',
    'throw away | discard | ˈθrəʊ əˈweɪ | dɪˈskɑːd | ফেলে দেওয়া | পরিত্যাগ করা',
    'throw out | eject | ˈθrəʊ aʊt | ɪˈdʒekt | বের করে দেওয়া | বহিষ্কার করা',
    'tired | exhausted | ˈtaɪəd | ɪɡˈzɔːstɪd | ক্লান্ত | অবসন্ন',
    'tough | difficult | tʌf | ˈdɪfɪkəlt | কঠিন | দুরূহ',
    'try | endeavour | traɪ | ɪnˈdevə | চেষ্টা করা | প্রচেষ্টা করা',
    'try out | test | ˈtraɪ aʊt | test | পরখ করা | পরীক্ষা করা',
    'use | utilise | juːz | ˈjuːtɪlaɪz | ব্যবহার করা | প্রয়োগ করা',
    'use | consume | juːz | kənˈsjuːm | খাওয়া | ভোগ করা',
    'wait for | await | ˈweɪt fɔː | əˈweɪt | অপেক্ষা করা | প্রতীক্ষা করা',
    'whole | entire | həʊl | ɪnˈtaɪə | পুরো | সম্পূর্ণ',
    'wood | timber | wʊd | ˈtɪmbə | কাঠ | কাষ্ঠ',
    'worse | inferior | wɜːs | ɪnˈfɪəriə | আরও খারাপ | নিম্নতর',
    'wrong | incorrect | rɒŋ | ˌɪnkəˈrekt | ভুল | অশুদ্ধ',
    'young | youthful | jʌŋ | ˈjuːθfl | তরুণ | যুবকসুলভ',
  ],
};
